### ISSUE TITLE
Upgrade test failed due to Cannot write event

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#10416]
### Description

Test result link

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnect/20231211-063743-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-ND-DisAftPrepare-RecAftUpgrade-1.5k-25m/

Looks like intermittent error, happened 30% to upgrade tests.

```
2023-12-11 09:10:50.706 77       ERROR EXCEPTION        <<preconsensus: event-writer>> AbstractThreadConfiguration: exception on thread <preconsensus: event-writer>
java.lang.IllegalStateException: Cannot write event 12d4d4e599bce93258b95f3b01e0e0ef32a367e3a9f84a60ee517d36fb11efa45cb0adfc9433aad862a26b3dbe10a490 with generation 5270 to file 2023-12-11T09+10+50.702771722Z_seq8_ming5317_maxg5859_orgn0.pces
	at com.swirlds.platform.event.preconsensus.PreconsensusEventMutableFile.writeEvent(PreconsensusEventMutableFile.java:99) ~[swirlds-platform-core-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.writeEvent(SyncPreconsensusEventWriter.java:188) ~[swirlds-platform-core-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.AsyncPreconsensusEventWriter.addEventHandler(AsyncPreconsensusEventWriter.java:268) ~[swirlds-platform-core-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.MultiQueueThreadImpl.handle(MultiQueueThreadImpl.java:99) ~[swirlds-common-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.45.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.45.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to reproduce

Nightly test panel `GCP-Daily-Update-Reconnect-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Other incident of the same error

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnect/20231209-063647-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-ND-DisAftUpdate-RecAftFreeze-1.5k-25m/

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnect/20231210-063644-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-ND-DisAftUpdate-RecAftPrepare-1.5k-25m/

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnect/20231210-063644-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-ND-DisAftUpdate-RecPrePrepare-1.5k-25m/

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnectAbortDisPreUpdate/20231210-063640-GCP-UpdateRecAbort-PreUpdate-4N-2C/Crypto-Update-ND-DisPreUpdate-RecAftFreezeAbort-1.5k-35m/

http://35.247.76.217:8095/swirlds-automation/develop/4N_2C/UpdateReconnectAbortDisPreUpdate/20231210-063640-GCP-UpdateRecAbort-PreUpdate-4N-2C/Crypto-Update-ND-DisPreUpdate-RecAftPrepareAbort-1.5k-35m/

**Comment by cody-littley** [comment]
@alittley merged a PR that should have fixed this issue. Closing for now, we should file a new ticket if the issue still arises.
