### ISSUE TITLE
Test MixedOps-Global-ND-3NReconnect-6k-35m failed due to StoppableThreadImpl

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#10434]
### Description

Result link :

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/Global3NReconnect/20231211-080940-GCP-Daily-Global-Reconnect-15N-4C/MixedOps-Global-ND-3NReconnect-6k-35m/

```
2023-12-11 09:12:35.729 13809    ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: pausing thread thread-cons is taking longer than PT5S
2023-12-11 09:12:35.731 13810    ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: stack trace of thread-cons:
jdk.internal.misc.Unsafe.park(Unsafe.java:-2)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
	at com.swirlds.common.threading.CountUpLatch.await(CountUpLatch.java:140)
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.waitUntilDurable(SyncPreconsensusEventWriter.java:261)
	at com.swirlds.platform.event.preconsensus.AsyncPreconsensusEventWriter.waitUntilDurable(AsyncPreconsensusEventWriter.java:234)
	at com.swirlds.platform.SwirldsPlatform$$Lambda$1316/0x0000000801283680.accept(null:-1)
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:364)
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler$$Lambda$1318/0x0000000801283ae0.accept(null:-1)
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253)
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl$$Lambda$874/0x00000008010c67a0.run(null:-1)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl$$Lambda$666/0x0000000801014fc8.run(null:-1)
	at java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

Nightly test panel `GCP-Daily-Global-Reconnect-15N-4C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
No longer appearing
