### ISSUE TITLE
Can not run unit tests that use the constructable registry

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#10689]
When I attempt to run unit tests in intellij that do things like `ConstructableRegistry.getInstance().registerConstructables("")`, I get the following error. These tests seem to be passing in CI.

```
java.lang.IllegalArgumentException: The constructor return type must extend RuntimeConstructable
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.<init>(GenericConstructorRegistry.java:73)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.getOrCreate(DefaultConstructableRegistry.java:85)
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructables(DefaultConstructableRegistry.java:61)
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructables(DefaultConstructableRegistry.java:68)
	at com.swirlds.platform.SignedStateFileManagerTests.beforeAll(SignedStateFileManagerTests.java:105)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	...
```

Steps to reproduce:

1) go to `SignedStateFileManagerTests.java`
2) press the green play button and run all tests in class
3) tests will fail with exception above

**Comment by lpetrovic05** [comment]
Does not seem to be failing on my machine....

**Comment by lpetrovic05** [comment]
@cody-littley can we close this?

**Comment by cody-littley** [comment]
Required me to reinstall java.
