### ISSUE TITLE
nmt v1.2.4-alpha.0/develop deployment fails to retrieve Service version while loading a known state

### ISSUE THREAD

**Issue by tomzhenghedera** [hashgraph/hedera-services#10784]
### Description

On one of the perf env with recent develop build(8aeb2d68), while restarting with a known state, the application failed to start with an `EXCEPTION`
```
2024-01-04 18:49:04.427 68       ERROR EXCEPTION        <main> Browser: Unable t
o start Browser
java.lang.IllegalStateException: The current software version `Services @ 0.0.0
| HAPI @ 0.0.0` is prior to the software version `Services @ 0.45.2 | HAPI @ 0.4
5.0` that created the state that was loaded from disk.
        at com.swirlds.platform.util.BootstrapUtils.detectSoftwareUpgrade(Bootst
rapUtils.java:277) ~[swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:237)
~[swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.launchUnhandled(Browser.java:185) ~[swir
lds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.launch(Browser.java:129) [swirlds-platfo
rm-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.ja
va:103) [swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.main(Browser.java:92) [swirlds-platform-
core-0.47.0-develop.x8aeb2d6.jar:?]
2024-01-04 18:49:04.427 70       ERROR EXCEPTION        <main> Log4jSetup: excep
tion on thread main
java.lang.RuntimeException: Unable to start Browser
        at com.swirlds.platform.Browser.launch(Browser.java:132) ~[swirlds-platf
orm-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.ja
va:103) ~[swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.main(Browser.java:92) ~[swirlds-platform
-core-0.47.0-develop.x8aeb2d6.jar:?]
Caused by: java.lang.IllegalStateException: The current software version `Servic
es @ 0.0.0 | HAPI @ 0.0.0` is prior to the software version `Services @ 0.45.2 |
 HAPI @ 0.45.0` that created the state that was loaded from disk.
        at com.swirlds.platform.util.BootstrapUtils.detectSoftwareUpgrade(Bootst
rapUtils.java:277) ~[swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:237)
~[swirlds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.launchUnhandled(Browser.java:185) ~[swir
lds-platform-core-0.47.0-develop.x8aeb2d6.jar:?]
        at com.swirlds.platform.Browser.launch(Browser.java:129) ~[swirlds-platf
orm-core-0.47.0-develop.x8aeb2d6.jar:?]
        ... 2 more
```

### Steps to reproduce

1. deploy any latest develop build with nmt `v1.2.4-alpha.0`(the genesis start up should be successful)
2. hard restart with a known state

### Hedera network

other

### Version

build-develop-8aeb2d68

### Operating system

Linux

**Comment by tomzhenghedera** [comment]
Two updates:

A fresh reset of the network w/ nmt v1.2.4-alpha.0 seems to insert empty variables

**Comment by tinker-michaelj** [comment]
Obsolete.
