### ISSUE TITLE
Figure out how to completely remove null routes in state

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#10949]
In context of the migration from mono state format to the modular state format, we need to remove the old mono routes from state after populating the state with all new data. 

Note: the "old" and "new" states are actually the same object, a "hybrid state" of sorts, while the migration is taking place. After the migration finishes, this state will have all mono _and_ all modular data. The mono data is what needs to be removed.

**Comment by mhess-swl** [comment]
This was the original strategy:

* Copy all mono ServicesState children into static fields
* Call `MerkleHederaState.addDeserializedChildren(List.of(), 0L)` to clear the list of internal children (immediately after saving the mono children into static fields)
* Do the schema migrations, copying all data from the mono children static fields into the new state format

Unfortunately we ran into an issue with VirtualMap. If we clear the file service's virtual map via `MerkleHederaState::addDeserializedChildren`, the virtual map data is erased before the file service has a chance to migrate the old data over. The current code uses a `Supplier` for the file service virtual map, but even changing this to a virtual map instance didn't work. We get this error:
```
2024-01-12 16:33:45.152 20       ERROR EXCEPTION        <<virtual-map-migration: reader-1>> AbstractThreadConfiguration: exception on thread <virtual-map-migration: reader-1>
java.lang.NullPointerException: Cannot invoke "com.swirlds.virtualmap.datasource.VirtualLeafRecord.getKey()" because "leafRecord" is null
	at com.swirlds.virtualmap.VirtualMapMigration.lambda$extractVirtualMapData$0(VirtualMapMigration.java:92) ~[swirlds-virtualmap-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.AbstractThreadConfiguration.lambda$setInterruptableRunnable$2(AbstractThreadConfiguration.java:622) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by mhess-swl** [comment]
I found a way that seems to work. By using the `copy()` functionality on the new nodes in state, it seems we can call `addDeserializedChildren` successfully:

```
            final List<MerkleNode> children = new ArrayList<>();
            for (int i = PAYER_RECORDS_OR_CONSOLIDATED_FCQ + 1; i < state.getNumberOfChildren(); i++) {
                // For each modular child node, copy it the data isn't erased
                final var modularChild = state.getChild(i);
                children.add(modularChild.copy());
            }

            // Now clear out state entirely, then re-add the copies of the new modular children nodes
            state.addDeserializedChildren(children, 0);
```

**Comment by mhess-swl** [comment]
The solution that finally worked best was to call `copy()` on each of the virtual maps, store the mutable copy, and then call `addDeserializedChildren(List.of(), 0)` so the original virtual maps would get released. See commit 9c353b6229358037580e15a5943a2c95c7159f2a in PR #11003
