### ISSUE TITLE
VMerkleDual-NDReconnect-500-60m thread pause timeout triggered

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#11018]
[Test data link](http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240117-053548-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m)

After restarting, a node replays a lot of events from the PCES. After this, it starts syncing and realizes its behind. To prepare for a reconnect, it clears out its queues. The clearing of the consensus queue seems to take 13 seconds in this example. Based on the metrics, I do not understand why this is taking so long.
The clearing should be as follows:
- clear out any data from the queue to remove the backlog
- wait for the current operation to finish, which in this case is handling the transactions of a single round (should be way less than 13s)

A possible cause might be that we are adding more rounds to be handled after clearing the queue.

Relevant stack trace:
```
2024-01-17 06:14:20.417 183      INFO  STARTUP          <<platform: status-state-machine>> PlatformTestingToolMain: Platform Status Change REPLAYING_EVENTS 
2024-01-17 06:14:20.430 184      INFO  STARTUP          <ForkJoinPool.commonPool-worker-39> ConsensusImpl: Found init judge (3,14,312b2685), num remaining: 3
2024-01-17 06:14:20.431 185      INFO  STARTUP          <ForkJoinPool.commonPool-worker-40> ConsensusImpl: Found init judge (2,14,2415cdbf), num remaining: 2
2024-01-17 06:14:20.432 186      INFO  STARTUP          <ForkJoinPool.commonPool-worker-39> ConsensusImpl: Found init judge (1,14,46896224), num remaining: 1
2024-01-17 06:14:20.433 187      INFO  STARTUP          <ForkJoinPool.commonPool-worker-40> ConsensusImpl: Found init judge (0,14,ab43c783), num remaining: 0
2024-01-17 06:14:20.475 188      WARN  DEMO_INFO        <<platform-core: thread-cons 3>> VirtualMerkleTransactionHandler: Value for key SmartContractByteCodeMapKey{contractId=45000} was not found inside smart contract bytecode map.
2024-01-17 06:14:20.481 192      WARN  DEMO_INFO        <<platform-core: thread-cons 3>> VirtualMerkleTransactionHandler: Value for key SmartContractByteCodeMapKey{contractId=15000} was not found inside smart contract bytecode map.
2024-01-17 06:14:23.338 381      INFO  STARTUP          <<platform-core: MetricsThread #0>> LegacyCsvWriter: CsvWriter: Initializing statistics output in CSV format [ csvOutputFolder = '/opt/hgcapp/services-hedera/HapiApp2.0/data/stats', csvFileName = 'PlatformTesting3.csv' ]
2024-01-17 06:14:23.343 382      DEBUG STARTUP          <<platform-core: MetricsThread #0>> LegacyCsvWriter: CsvWriter: Using the existing metrics folder [ folder = '/opt/hgcapp/services-hedera/HapiApp2.0/data/stats' ]
2024-01-17 06:16:34.902 7793     INFO  STARTUP          <<start-node-3>> PcesReplayer: Replayed 10,360 preconsensus events. These events contained 122,869 transactions. 523 rounds reached consensus spanning 5.9 minutes of consensus time. The latest round to reach consensus is round 527. Replay took 2.2 minutes.
2024-01-17 06:16:34.907 7794     INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 2.2 m in REPLAYING_EVENTS. Now in OBSERVING {"oldStatus":"REPLAYING_EVENTS","newStatus":"OBSERVING"} [com.swirlds.logging.legacy.payload.PlatformStatusPayload]
2024-01-17 06:16:34.908 7795     INFO  STARTUP          <<platform: status-state-machine>> PlatformTestingToolMain: Platform Status Change OBSERVING 
2024-01-17 06:16:34.909 7796     INFO  DEMO_INFO        <<app: appMain 3>> PlatformTestingToolMain: Node 3 starts transactions ........
2024-01-17 06:16:36.005 7861     INFO  RECONNECT        <<platform-core: SyncProtocolWith1 3 to 1>> ReconnectController: Starting ReconnectController
2024-01-17 06:16:36.006 7862     INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 1.1 s in OBSERVING. Now in BEHIND {"oldStatus":"OBSERVING","newStatus":"BEHIND"} [com.swirlds.logging.legacy.payload.PlatformStatusPayload]
2024-01-17 06:16:36.006 7863     INFO  STARTUP          <<platform: status-state-machine>> PlatformTestingToolMain: Platform Status Change BEHIND 
2024-01-17 06:16:36.006 7864     INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectHelper: Preparing for reconnect, stopping gossip
2024-01-17 06:16:36.009 7865     INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectHelper: Preparing for reconnect, start clearing queues
2024-01-17 06:16:36.009 7866     INFO  RECONNECT        <<reconnect: reconnect-controller>> LoggingClearables: about to clear intakeQueue
2024-01-17 06:16:36.015 7867     INFO  RECONNECT        <<reconnect: reconnect-controller>> LoggingClearables: about to clear platformWiring
2024-01-17 06:16:36.017 7868     INFO  RECONNECT        <<reconnect: reconnect-controller>> LoggingClearables: about to clear shadowGraph
2024-01-17 06:16:36.018 7869     INFO  RECONNECT        <<reconnect: reconnect-controller>> LoggingClearables: about to clear consensusRoundHandler
2024-01-17 06:16:36.018 7870     INFO  RECONNECT        <<reconnect: reconnect-controller>> ConsensusRoundHandler: consensus handler: clearing queue thread
2024-01-17 06:16:41.020 8096     ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: pausing thread thread-cons is taking longer than PT5S
2024-01-17 06:16:41.022 8097     ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: stack trace of thread-cons:
java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1955)
	at com.swirlds.virtualmap.internal.cache.VirtualNodeCache.updatePaths(VirtualNodeCache.java:1170)
	at com.swirlds.virtualmap.internal.cache.VirtualNodeCache.putLeaf(VirtualNodeCache.java:556)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.add(VirtualRootNode.java:1621)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.put(VirtualRootNode.java:847)
	at com.swirlds.virtualmap.VirtualMap.put(VirtualMap.java:463)
	at com.swirlds.demo.virtualmerkle.transaction.handler.VirtualMerkleTransactionHandler.handleMethodExecutionTransaction(VirtualMerkleTransactionHandler.java:214)
	at com.swirlds.demo.virtualmerkle.transaction.handler.VirtualMerkleTransactionHandler.handle(VirtualMerkleTransactionHandler.java:123)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleVirtualMerkleTransaction(PlatformTestingToolState.java:779)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleTransaction(PlatformTestingToolState.java:1220)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleConsensusTransaction(PlatformTestingToolState.java:1096)
	at com.swirlds.demo.platform.PlatformTestingToolState.lambda$handleConsensusRound$8(PlatformTestingToolState.java:1068)
	at com.swirlds.platform.system.Round.forEachEventTransaction(Round.java:105)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleConsensusRound(PlatformTestingToolState.java:1067)
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84)
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169)
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:376)
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:260)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215)
	at java.lang.Thread.run(Thread.java:1583)

2024-01-17 06:16:46.022 8470     ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: pausing thread thread-cons is taking longer than PT5S
2024-01-17 06:16:46.022 8471     ERROR EXCEPTION        <<reconnect: reconnect-controller>> StoppableThreadImpl: stack trace of thread-cons:
com.swirlds.merkledb.files.hashmap.Bucket.readFrom(Bucket.java:305)
	at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:142)
	at com.swirlds.merkledb.files.hashmap.BucketSerializer.deserialize(BucketSerializer.java:35)
	at com.swirlds.merkledb.files.DataFileCollection.readDataItem(DataFileCollection.java:529)
	at com.swirlds.merkledb.files.DataFileCollection.retryReadUsingIndex(DataFileCollection.java:553)
	at com.swirlds.merkledb.files.DataFileCollection.readDataItemUsingIndex(DataFileCollection.java:639)
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.get(HalfDiskHashMap.java:473)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:614)
	at com.swirlds.virtualmap.internal.merkle.RecordAccessorImpl.findLeafRecord(RecordAccessorImpl.java:135)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.get(VirtualRootNode.java:820)
	at com.swirlds.virtualmap.VirtualMap.get(VirtualMap.java:449)
	at com.swirlds.demo.virtualmerkle.transaction.handler.VirtualMerkleTransactionHandler.handleMethodExecutionTransaction(VirtualMerkleTransactionHandler.java:184)
	at com.swirlds.demo.virtualmerkle.transaction.handler.VirtualMerkleTransactionHandler.handle(VirtualMerkleTransactionHandler.java:123)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleVirtualMerkleTransaction(PlatformTestingToolState.java:779)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleTransaction(PlatformTestingToolState.java:1220)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleConsensusTransaction(PlatformTestingToolState.java:1096)
	at com.swirlds.demo.platform.PlatformTestingToolState.lambda$handleConsensusRound$8(PlatformTestingToolState.java:1068)
	at com.swirlds.platform.system.Round.forEachEventTransaction(Round.java:105)
	at com.swirlds.demo.platform.PlatformTestingToolState.handleConsensusRound(PlatformTestingToolState.java:1067)
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84)
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169)
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.applyConsensusRoundToState(ConsensusRoundHandler.java:376)
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:260)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215)
	at java.lang.Thread.run(Thread.java:1583)
```

**Comment by alittley** [comment]
Fixed via https://github.com/hashgraph/hedera-services/pull/11000
