### ISSUE TITLE
MerkleSynchronizationException deserializing class ID 8989011001974646263

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#11116]
http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20240122-063817-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/

(Node 7) 

MixedOps-Interrupted-2NReconnect-1k-41m had the following exception: 

```
com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Synchronization failed with exceptions
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.sendTree(TeachingSynchronizer.java:195) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.synchronize(TeachingSynchronizer.java:135) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.reconnect(ReconnectTeacher.java:233) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.execute(ReconnectTeacher.java:168) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.teacher(ReconnectProtocol.java:297) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.runProtocol(ReconnectProtocol.java:259) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.states.ProtocolNegotiated.transition(ProtocolNegotiated.java:62) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.Negotiator.execute(Negotiator.java:94) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:74) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

and 

```
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:154) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:147) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:156) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.sendTree(TeachingSynchronizer.java:192) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.synchronize(TeachingSynchronizer.java:135) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.reconnect(ReconnectTeacher.java:233) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.execute(ReconnectTeacher.java:168) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.teacher(ReconnectProtocol.java:297) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.runProtocol(ReconnectProtocol.java:259) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.states.ProtocolNegotiated.transition(ProtocolNegotiated.java:62) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.Negotiator.execute(Negotiator.java:94) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:74) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:157) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:142) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	```

**Comment by edward-swirldslabs** [comment]
this is standard interrupted network connection caused exceptions.
