### ISSUE TITLE
Add an upgrade JRS test that removes node

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#11227]
After this https://github.com/hashgraph/hedera-services/issues/11225 is done, add an upgrade test that removes a node during upgrade similar to the platform test `AddressBook-restart-upgrade-remove-node-1k-4m`

**Comment by Neeharika-Sompalli** [comment]
The upgrade test actually completes. But NMT restarts the node that is not in config.txt. 
So the platform `swirlds.log` fails with this message

```
2024-03-19 20:06:41.319 1        ERROR EXCEPTION        <main> BootstrapUtils: No AddressBook entry found for the available machine IP addresses {"internalIpAddress":"172.17.0.1","externalIpAddress":""} [com.swirlds.logging.legacy.payload.NodeAddressMismatchPayload]
2024-03-19 20:06:41.363 2        INFO  STARTUP          <main> SystemExitUtils: System exit requested (NODE_ADDRESS_MISMATCH)
thread requesting exit: main
com.swirlds.platform.system.SystemExitUtils.exitSystem(SystemExitUtils.java:51)
	at com.swirlds.platform.system.SystemExitUtils.exitSystem(SystemExitUtils.java:87)
	at com.swirlds.platform.util.BootstrapUtils.checkNodesToRun(BootstrapUtils.java:416)
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:157)
	at com.swirlds.platform.Browser.launch(Browser.java:128)
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:103)
	at com.swirlds.platform.Browser.main(Browser.java:92)

2024-03-19 20:06:41.365 3        ERROR EXCEPTION        <main> SystemExitUtils: Exiting system {"reason":"NODE_ADDRESS_MISMATCH","code":205} [com.swirlds.logging.legacy.payload.SystemExitPayload]
2024-03-19 20:06:41.366 4        INFO  STARTUP          <<browser: shutdown-hook>> Log4jSetup: JVM is shutting down.
```

Informed @mattp-swirldslabs  regarding this and will be a NMT feature to look at `config.txt` and start only those nodes . That will be implemented in the future.
