### ISSUE TITLE
VirtualMapReconnectTest fails intermittently with path not in range log message

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#11298]
Exception:

```
org.opentest4j.AssertionFailedError: Should not throw a Exception ==> Unexpected exception thrown: org.opentest4j.AssertionFailedError: We did not expect an exception on this reconnect attempt! java.lang.IllegalArgumentException: path (8) is not valid; must be in range (-1,-1) ==> expected: <true> but was: <false>	
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)	
•••
at com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTest.fullTeacherEmptyLearner(VirtualMapReconnectTest.java:103)	
•••
Caused by: org.opentest4j.AssertionFailedError: We did not expect an exception on this reconnect attempt! java.lang.IllegalArgumentException: path (8) is not valid; must be in range (-1,-1) ==> expected: <true> but was: <false>	
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)	
•••
at com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTestBase.reconnectMultipleTimes(VirtualMapReconnectTestBase.java:228)	
at com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTestBase.reconnectMultipleTimes(VirtualMapReconnectTestBase.java:174)	
at com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTestBase.reconnect(VirtualMapReconnectTestBase.java:170)	
•••
at com.swirlds.virtual.merkle.reconnect.VirtualMapReconnectTest.fullTeacherEmptyLearner(VirtualMapReconnectTest.java:103)	
•••
```

**Comment by poulok** [comment]
We are waiting for a reproduction so that we have more information for debugging.

**Comment by artemananiev** [comment]
May be related: #6991

**Comment by artemananiev** [comment]
PR to print the full stack trace, if an unexpected exception is observed in reconnect tests: https://github.com/hashgraph/hedera-services/pull/11370. It doesn't fix the problem, but will help debug this issue in the future.

**Comment by artemananiev** [comment]
Another PR for this ticket: https://github.com/hashgraph/hedera-services/pull/11435 It propagates reconnect exceptions from the work group to the caller.

**Comment by poulok** [comment]
https://github.com/hashgraph/hedera-services/issues/11750 merged which may fix this issue. Reevaluate on March 18th.

**Comment by poulok** [comment]
No failures in the last several weeks. We suspect it has been fixed already with previous changes.
