### ISSUE TITLE
Log4JSetup NullPointerException on staging-lg

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#11291]
[Found while examining the logs of the staging-lg network](https://preproduction.grafana.hedera-ops.com/explore?schemaVersion=1&panes=%7B%225m3%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Benvironment%3D%5C%22staging-lg%5C%22,%20log_name%3D%5C%22swirlds%5C%22%7D%20%21%3D%20%60socket%60%20%21%3D%20%60reconnect%60%20%7C%3D%20%60ERROR%60%20%21%3D%20%60Configuration%60%20%21%3D%20%60old%20signed%20state%60%20%7C%20json%20%7C%20line_format%20%60%7B%7B.body%7D%7D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:2000%7D%5D,%22range%22:%7B%22from%22:%221706637453434%22,%22to%22:%221706652619392%22%7D%7D%7D&orgId=1): 

```
2024-01-30 13:33:19.480 | 2024-01-30 19:33:18.719 1341     ERROR EXCEPTION        <pool-4-thread-15> Log4jSetup: exception on thread pool-4-thread-15 java.lang.NullPointerException: null 	
at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?] 	
at com.hedera.node.app.service.mono.context.MutableStateChildren.accounts(MutableStateChildren.java:82) ~[app-service-mono-0.46.2.jar:?] 	
at com.hedera.node.app.service.mono.cache.EntityMapWarmer.lambda$warmAccount$6(EntityMapWarmer.java:202) ~[app-service-mono-0.46.2.jar:?] 	
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] 	
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] 	
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

```

**Comment by edward-swirldslabs** [comment]
This exception was also found in the [logs of testnet](https://production.grafana.hedera-ops.com/explore?schemaVersion=1&panes=%7B%225m3%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Benvironment%3D%5C%22testnet%5C%22,%20log_name%3D%5C%22swirlds%5C%22%7D%20%21%3D%20%60socket%60%20%21%3D%20%60reconnect%60%20%7C%3D%20%60ERROR%60%20%21%3D%20%60Configuration%60%20%21%3D%20%60old%20signed%20state%60%20%7C%20json%20%7C%20line_format%20%60%7B%7B.body%7D%7D%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22builder%22,%22maxLines%22:2000%7D%5D,%22range%22:%7B%22from%22:%221706548417941%22,%22to%22:%221706578577515%22%7D%7D%7D&orgId=1).

**Comment by akugal** [comment]
Looks like this ticket could be closed since `MutableStateChildren` doesn't exist anymore

**Comment by edward-swirldslabs** [comment]
closing per recommendation.
