### ISSUE TITLE
SignedStateFIleManagerTests.sequenceOfStatesTest flake

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#11445]
https://scans.gradle.com/s/zdqlhyuqfc4l4/tests/overview?outcome=FAILED

```
com.swirlds.common.exceptions.ReferenceCountException: can not reserve node that has already been destroyed	

at com.swirlds.common.utility.AbstractReservable.lambda$static$0(AbstractReservable.java:37)	
	at java.util.concurrent.atomic.AtomicInteger.updateAndGet(AtomicInteger.java:281)	
	at com.swirlds.common.utility.AbstractReservable.reserve(AbstractReservable.java:73)	
	at com.swirlds.platform.state.signed.SignedState.incrementReservationCount(SignedState.java:311)	
	at com.swirlds.platform.state.signed.ReservedSignedState.createAndReserve(ReservedSignedState.java:97)	
	at com.swirlds.platform.state.signed.SignedState.reserve(SignedState.java:301)	
	at com.swirlds.platform.SignedStateFileManagerTests.sequenceOfStatesTest(SignedStateFileManagerTests.java:328)
```

**Comment by lpetrovic05** [comment]
this wasn't a flake, the test was broken but wasn't running at all
