### ISSUE TITLE
ReconnectException: SignedStateInvalidException: Received signed state is for a round smaller

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#11477]
http://35.247.76.217:8095/poulok/reenable_timing_sensitive_tests/4N/Abbrev/20240209-133341-GCP-PRCheck-Abbrev-4N/Consistency-NDReconnect-10m/

```
node2 | 1m 29.667s | ERROR | ReconnectLearnerThrottle: | Error while receiving a signed state! {"causeOfFailure":"ERROR"} [com.swirlds.logging.legacy.payload.ReconnectFailurePayload]
  |   | com.swirlds.platform.reconnect.ReconnectException: com.swirlds.platform.state.signed.SignedStateInvalidException: Received signed state is for a round smaller than or a consensus earlier than what we started with. Original round 101, received round 100. Original timestamp 2024-02-09T13:58:01.690231Z, received timestamp 2024-02-09T13:58:01.150780Z. 	
at com.swirlds.platform.reconnect.ReconnectLearner.execute(ReconnectLearner.java:161) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.reconnect.ReconnectHelper.reconnectLearner(ReconnectHelper.java:133) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.reconnect.ReconnectHelper.receiveSignedState(ReconnectHelper.java:111) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.reconnect.ReconnectController.executeReconnect(ReconnectController.java:114) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.reconnect.ReconnectController.run(ReconnectController.java:95) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: com.swirlds.platform.state.signed.SignedStateInvalidException: Received signed state is for a round smaller than or a consensus earlier than what we started with. Original round 101, received round 100. Original timestamp 2024-02-09T13:58:01.690231Z, received timestamp 2024-02-09T13:58:01.150780Z. 	
at com.swirlds.platform.reconnect.DefaultSignedStateValidator.throwIfOld(DefaultSignedStateValidator.java:88) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.platform.reconnect.DefaultSignedStateValidator.validate(DefaultSignedStateValidator.java:52) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]

**Comment by edward-swirldslabs** [comment]
May be related to this issue:  https://github.com/hashgraph/hedera-services/issues/11471

**Comment by edward-swirldslabs** [comment]
Funky Hashstream Log: 

```
2024-02-09 13:58:01.930 232      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: State Info, round = 99:
Round:                  99
Timestamp:              2024-02-09T13:58:00.580907Z
Next consensus number:  1809
Running event hash:     949115b9e9ae50aca23a2f0b24a2546715c81c9d90f40239b5ace795c82bf0326f289f28f8fb9c7a71674bec3beed688
Running event mnemonic: hospital-rescue-ski-better
Rounds non-ancient:     26
Creation version:       1
Epoch mnemonic:         null
Epoch hash:             null
Min gen hash code:      444559905
Root hash:              c3135b8903480afba0cfe39bdf004ec4b41409fa4fbb95d829a2f3beedd9843805ab70741e42a4245a9b7160d424534e

(root) State                            /     oval-illness-harbor-garage
   0 ConsistencyTestingToolState        /0    treat-globe-grape-piece
   1 PlatformState                      /1    pen-combine-winner-glory

2024-02-09 13:58:02.568 240      INFO  STATE_HASH       <ForkJoinPool-2-worker-20> IssDetector: Nodes holding 50000000000/50000000000 (100.0%) of total weight have reported a hash for round 74.
Consensus mnemonic: second-ranch-garlic-lottery
Consensus hash: 4e13ba7412febbe08f740f796e7711b3e8c90055f04284e2dc1d4f4e5497c218ab0a2259922feb13ec8f3d7288f7a541
- nodes 0, 1, 2, 3
  partition weight: 50000000000 (100.0% of total weight)
  partition mnemonic: second-ranch-garlic-lottery
  partition hash: 4e13ba7412febbe08f740f796e7711b3e8c90055f04284e2dc1d4f4e5497c218ab0a2259922feb13ec8f3d7288f7a541

2024-02-09 13:58:02.568 241      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: State Info, round = 100:
Round:                  100
Timestamp:              2024-02-09T13:58:01.150780Z
Next consensus number:  1827
Running event hash:     56e3845e7932b3eb3fb1117453eed7385631aafc2ebfaea3a3727ba8698f894f2349466f780655ec7b3b16469a0bd934
Running event mnemonic: symbol-inmate-chaos-live
Rounds non-ancient:     26
Creation version:       1
Epoch mnemonic:         null
Epoch hash:             null
Min gen hash code:      -20198184
Root hash:              795e230c7b05f1a11565b3a2696382469790bcfeda65920ff5e53e44b285498d21c70c5eab9cf79849ce83b21cc3a5f3

(root) State                            /     cloth-ghost-gaze-slogan
   0 ConsistencyTestingToolState        /0    gesture-wide-shoe-day
   1 PlatformState                      /1    frown-corn-scrub-leader

2024-02-09 13:58:03.347 242      INFO  STATE_HASH       <ForkJoinPool-2-worker-9> IssDetector: Nodes holding 50000000000/50000000000 (100.0%) of total weight have reported a hash for round 75.
Consensus mnemonic: element-group-three-evoke
Consensus hash: 1a3dfcc95708ed9012e278fd427befa46df817c80c2ee541df8034942639e2b17f12d6c37dc86b800f0b7489f8cd0a0f
- nodes 0, 1, 2, 3
  partition weight: 50000000000 (100.0% of total weight)
  partition mnemonic: element-group-three-evoke
  partition hash: 1a3dfcc95708ed9012e278fd427befa46df817c80c2ee541df8034942639e2b17f12d6c37dc86b800f0b7489f8cd0a0f

2024-02-09 13:58:03.348 243      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: State Info, round = 101:
Round:                  101
Timestamp:              2024-02-09T13:58:01.690231Z
Next consensus number:  1842
Running event hash:     73b44704109d96cfef1c2a6ca802fbe53dbee6dd3f8a3105be5f11aa8f3346e4279bcbf7ca805449604af34b0b9c2305
Running event mnemonic: isolate-they-beauty-change
Rounds non-ancient:     26
Creation version:       1
Epoch mnemonic:         null
Epoch hash:             null
Min gen hash code:      1532190016
Root hash:              8478cb6a1b503888b5444c52aa11d306f9f278b73874fe8cace370ce2df1b98ea0922bfc8011c46b78da1f9037d2287b

(root) State                            /     illegal-name-head-baby
   0 ConsistencyTestingToolState        /0    poem-sadness-unusual-minor
   1 PlatformState                      /1    solar-category-party-core

2024-02-09 14:08:04.516 298      INFO  STATE_HASH       <<reconnect: reconnect-controller>> SwirldsPlatform: RECONNECT: loadReconnectState: reloading state
2024-02-09 14:08:04.537 306      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: *** Several rounds skipped. Round received 570. Previously received 101.
2024-02-09 14:08:04.537 307      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: State Info, round = 570:
Round:                  570
Timestamp:              2024-02-09T14:08:01.095375Z
Next consensus number:  7249
Running event hash:     9f466e8aab44e928bd9eab6c0ac0dad77daeccf1775439b55b05a079a11d819d532ae6627af0952130aef2bcaa0d891d
Running event mnemonic: blanket-spend-nurse-swallow
Rounds non-ancient:     26
Creation version:       1
Epoch mnemonic:         null
Epoch hash:             null
Min gen hash code:      -939987217
Root hash:              ec219c4568886bfa2f7c1d00009f5fadaf60c0da245157acd271e0e8f8a47aeffc7446f428d4c0ebd9bb7b7ee606abd2

(root) State                            /     know-jazz-baby-leg
   0 ConsistencyTestingToolState        /0    fade-purpose-few-fury
   1 PlatformState                      /1    agent-vicious-setup-gadget

2024-02-09 14:08:05.372 324      INFO  STATE_HASH       <<logging: log-hashstream>> HashLogger: State Info, round = 571:
Round:                  571
Timestamp:              2024-02-09T14:08:02.055683621Z
Next consensus number:  7261
Running event hash:     766bc64f03991cf78630d3347822b07fba92ab0d83c079b97271e72390e05da18a8f74366ffa9cad49db51d1bc112cdc
Running event mnemonic: sniff-curtain-industry-page
Rounds non-ancient:     26
Creation version:       1
Epoch mnemonic:         null
Epoch hash:             null
Min gen hash code:      -1089039054
Root hash:              671657b430a80c8bf0e0f74136d430a23ddf0775834f91aec9bcf251ed71baef102b51a8ecc8fbc0f2cc550aa1797553
```
