### ISSUE TITLE
ISS detector uncaught exception: round handled twice

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11471]
- observed in [this JRS run](http://35.247.76.217:8095/alittley/11446-use-ordered-solder/4N/Abbrev/20240208-202853-GCP-PRCheck-Abbrev-4N/Consistency-NDReconnect-10m/swirlds-logs.html)
    - this is on a non-develop branch, but I don't think the changes there are the cause of this error

```
2024-02-08 21:01:17.602 371      ERROR EXCEPTION        <ForkJoinPool-2-worker-18> TaskSchedulerBuilder: Uncaught exception in scheduler issDetector
java.lang.IllegalArgumentException: previous round was 521, can't decrease round to 521
	at com.swirlds.platform.state.iss.IssDetector.roundCompleted(IssDetector.java:175) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.iss.IssDetector.overridingState(IssDetector.java:362) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:93) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialTask.exec(SequentialTask.java:92) [swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
```

**Comment by edward-swirldslabs** [comment]
Additional Occurrence: http://35.247.76.217:8095/edward-swirldslabs/10837-address-stores-x509Certificate/4N/Abbrev/20240209-151821-GCP-PRCheck-Abbrev-4N/Consistency-NDReconnect-10m/
