### ISSUE TITLE
File name too long for JRS runners: `ReverterConstructorCallWithValueToHederaPrecompile.json`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#11495]
- Caused by https://github.com/hashgraph/hedera-services/pull/11045
- Causes runners JRS runners [to fail](https://github.com/hashgraph/hedera-services/actions/runs/7868121736/job/21464822711)

```
2024-02-12 06:39:57.715 888    ERROR PROVISIONING     <main> Regression: Unhandled Exception During Experiment Configuration
 java.lang.IllegalArgumentException: file name 'resource/contract/contracts/ReverterConstructorCallWithValueToHederaPrecompile/ReverterConstructorCallWithValueToHederaPrecompile.json' is too long ( > 100 bytes)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.handleLongName(TarArchiveOutputStream.java:702) ~[commons-compress-1.21.jar:1.21]
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.putArchiveEntry(TarArchiveOutputStream.java:366) ~[commons-compress-1.21.jar:1.21]
	at com.swirlds.fsts.bundler.TarBundler.packInto(TarBundler.java:133) ~[regression.jar:?]
	at com.swirlds.fsts.bundler.TarBundler.packInto(TarBundler.java:160) ~[regression.jar:?]
	at com.swirlds.fsts.bundler.TarBundler.packInto(TarBundler.java:157) ~[regression.jar:?]
	at com.swirlds.fsts.bundler.TarBundler.pack(TarBundler.java:76) ~[regression.jar:?]
	at com.swirlds.fsts.workflow.DockerRemoteRegression.buildServicesDataArchive(DockerRemoteRegression.java:588) ~[regression.jar:?]
	at com.swirlds.fsts.workflow.DockerRemoteRegression.configureClientNodes(DockerRemoteRegression.java:496) ~[regression.jar:?]
	at com.swirlds.fsts.workflow.DockerRemoteRegression.experimentConfiguration(DockerRemoteRegression.java:387) ~[regression.jar:?]
	at com.swirlds.fsts.workflow.Regression.execute(Regression.java:237) [regression.jar:?]
	at com.swirlds.fsts.cli.MainCommand.executeRegressionFlow(MainCommand.java:297) [regression.jar:?]
	at com.swirlds.fsts.cli.MainCommand.call(MainCommand.java:285) [regression.jar:?]
	at com.swirlds.fsts.cli.MainCommand.call(MainCommand.java:60) [regression.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine.access$1300(CommandLine.java:145) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) [picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine.execute(CommandLine.java:2078) [picocli-4.6.3.jar:4.6.3]
	at com.swirlds.fsts.Main.main(Main.java:31) [regression.jar:?]
```

**Comment by alittley** [comment]
Fixed via https://github.com/hashgraph/hedera-services/pull/11491
