### ISSUE TITLE
Investigate possibly catastrophic exceptions and ISS on reconnecting nodes in JRS test `MixedOps-Interrupted-2NReconnect-1k-41m/`

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#11551]
During [one of the JRS runs](https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1708895678599649), we saw a lot of log messages with "Possibly CATASTROPHIC failure." This is also very likely the cause of the ISS on the involved nodes. The log messages keep repeating. Below is an excerpt. While it looks like a duplication, there are subtle differences between the two parts.

Here is what I think is happening:

1. There is some kind of due diligence failure.
2. We want to charge the account of the creator node (0.0.4), but it does not exist.
3. This throws an IllegalStateException (first IllegalStateException below)
4. This is caught by the catch-all block in `HandleWorkflow.handleUserTransaction()`
5. We try to charge the payer (as we do for all unexpected `Exceptions`)
6. The payer cannot be found, which results in the second `IllegalStateException`
7. The second `IllegalStateException` is caught by the catch-all block in `HandleWorkflow.handleRound()`

This raises several of questions:

- Why are the accounts not present? In particular, the account of the creator node should always be present. (Is this related to #11549?)
- Why is this happening only on some of the nodes and not on all?
- Is throwing an `IllegalStateException` in `TokenServicepImpl.lookupAccount()` (and not catching it) the right approach here?

```
2024-02-15 00:37:55.563 FATAL 462  TokenServiceApiImpl - Payer account AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=4]] does not exist
2024-02-15 00:37:55.563 ERROR 560  HandleWorkflow - Possibly CATASTROPHIC failure while handling a user transaction
java.lang.IllegalStateException: Payer account does not exist
	at com.hedera.node.app.service.token.impl.api.TokenServiceApiImpl.lookupAccount(TokenServiceApiImpl.java:463) ~[app-service-token-impl-0.47.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.service.token.impl.api.TokenServiceApiImpl.chargeNetworkFee(TokenServiceApiImpl.java:326) ~[app-service-token-impl-0.47.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.fees.FeeAccumulatorImpl.chargeNetworkFee(FeeAccumulatorImpl.java:52) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleUserTransaction(HandleWorkflow.java:441) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handlePlatformTransaction(HandleWorkflow.java:282) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleRound(HandleWorkflow.java:251) ~[?:?]
	at com.hedera.node.app.Hedera.onHandleConsensusRound(Hedera.java:932) ~[?:?]
	at com.hedera.node.app.state.HederaLifecyclesImpl.onHandleConsensusRound(HederaLifecyclesImpl.java:63) ~[?:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.handleConsensusRound(MerkleHederaState.java:313) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.handleConsensusRound(ConsensusRoundHandler.java:226) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:77) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:191) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2024-02-15 00:37:55.564 FATAL 462  TokenServiceApiImpl - Payer account AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=15680]] does not exist
2024-02-15 00:37:55.564 FATAL 254  HandleWorkflow - Possibly CATASTROPHIC failure while running the handle workflow. While this node may not die right away, it is in a bad way, most likely fatally.
java.lang.IllegalStateException: Payer account does not exist
	at com.hedera.node.app.service.token.impl.api.TokenServiceApiImpl.lookupAccount(TokenServiceApiImpl.java:463) ~[app-service-token-impl-0.47.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.service.token.impl.api.TokenServiceApiImpl.chargeFees(TokenServiceApiImpl.java:349) ~[app-service-token-impl-0.47.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.fees.FeeAccumulatorImpl.chargeFees(FeeAccumulatorImpl.java:63) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleUserTransaction(HandleWorkflow.java:565) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handlePlatformTransaction(HandleWorkflow.java:282) ~[?:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleRound(HandleWorkflow.java:251) ~[?:?]
	at com.hedera.node.app.Hedera.onHandleConsensusRound(Hedera.java:932) ~[?:?]
	at com.hedera.node.app.state.HederaLifecyclesImpl.onHandleConsensusRound(HederaLifecyclesImpl.java:63) ~[?:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.handleConsensusRound(MerkleHederaState.java:313) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.handleConsensusRound(ConsensusRoundHandler.java:226) ~[swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:77) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:191) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```

**Comment by Neeharika-Sompalli** [comment]
Latest [run](https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1708709590801989) doesnt show `CATSTROPHIC FAILURE` anymore

**Comment by Neeharika-Sompalli** [comment]
At the end of this run there is ISS on the reconnecting nodes. This ISS doesn't happen on all the reconnects that happens in this test. But only on the final reconnect.

**Comment by Neeharika-Sompalli** [comment]
Logs for the run are here http://35.247.76.217:8095/netopyr/11225-D-enable-workflow-modrun/15N_4C/3NReconnect/20240214-072753-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/
