### ISSUE TITLE
(mod) skip re-creating extant record and signature files when `REPLAYING_EVENTS` 

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#11614]
### Problem

During `REPLAYING_EVENTS` mod-service is throwing exceptions like,
```
2024-02-15 16:23:06.890 ERROR 111  SignatureWriterV6 - Fail to generate signature file for hedera-node/data/recordStreams/record0.0.5/2024-02-15T16_00_02.024802686Z.rcd.gz
java.nio.file.FileAlreadyExistsException: hedera-node/data/recordStreams/record0.0.5/2024-02-15T16_00_02.024802686Z.rcd_sig
...
	at com.hedera.node.app.records.impl.producers.formats.v6.BlockRecordWriterV6.close(BlockRecordWriterV6.java:286) ~[HederaNode.jar:?]
	at com.hedera.node.app.records.impl.producers.StreamFileProducerConcurrent.closeWriter(StreamFileProducerConcurrent.java:310) ~[HederaNode.jar:?]
	at com.hedera.node.app.records.impl.producers.StreamFileProducerConcurrent.lambda$switchBlocks$1(StreamFileProducerConcurrent.java:180) ~[HederaNode.jar:?]
```
which at minimum is unnecessary log spam (as record files will often already exist when `REPLAYING_EVENTS`), and seems it might somehow be causing an ISS after reconnect?

### Solution

Gracefully work around existing record stream files.

**Comment by tomzhenghedera** [comment]
New test data from the latest
