### ISSUE TITLE
2024-02-20 - VirtualHasher:	Failed to wait for all hashing tasks

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#11629]
http://35.247.76.217:8095/swirlds-automation/release/0.47/4N/Reconnect/20240220-094051-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/
```

node3 | 27m 17.520s | ERROR | VirtualHasher: | Failed to wait for all hashing tasks
 java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: hash 	
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] 	
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653) ~[?:?] 	
at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:479) ~[swirlds-virtualmap-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.lambda$prepareReconnectHashing$4(VirtualRootNode.java:1483) ~[swirlds-virtualmap-0.47.0-SNAPSHOT.jar:?] 	
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] 

Caused by: java.lang.IllegalArgumentException: hash 	
at com.swirlds.common.crypto.HashBuilder.update(HashBuilder.java:169) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.hash(VirtualHasher.java:258) ~[swirlds-virtualmap-0.47.0-SNAPSHOT.jar:?] 	
at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.exec(VirtualHasher.java:231) ~[swirlds-virtualmap-0.47.0-SNAPSHOT.jar:?] 	
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] 	
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]


```

**Comment by imalygin** [comment]
It looks like this issue has the same root cause as https://github.com/hashgraph/hedera-services/issues/11304
