### ISSUE TITLE
2024-02-20 - TaskSchedulerBuilder: Uncaught Exception in scheduler linkedEventIntake

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#11633]
http://35.247.76.217:8095/swirlds-automation/release/0.47/4N_2C/CentOS7_Update/20240217-110814-GCP-Daily-Update-CentOS7-4N-2C/Crypto-Update-Jar-1.5k-25m/

I've pasted swirlds.log up until the exception starts occurring at the bottom. 

```
---- ErrorValidator FAILED validation ----
(Node 0) Marker EXCEPTION appeared 135155 times.
(Node 0) Exception java.lang.IllegalStateException appeared 135152 times.
(Node 1) Marker EXCEPTION appeared 135159 times.
(Node 1) Exception java.lang.IllegalStateException appeared 135156 times.
(Node 2) Marker EXCEPTION appeared 135159 times.
(Node 2) Exception java.lang.IllegalStateException appeared 135156 times.
(Node 3) Marker EXCEPTION appeared 135157 times.
(Node 3) Exception java.lang.IllegalStateException appeared 135154 times.
```

All nodes failed to come up on this run, logs filled with the following exception.  

```
2024-02-17 11:23:46.103 80       ERROR EXCEPTION        <<scheduler linkedEventIntake>> TaskSchedulerBuilder: Uncaught exception in scheduler linkedEventIntake
java.lang.IllegalStateException: Cannot provide the minimum generation until all judges are found
	at com.swirlds.platform.consensus.RoundElections.getMinGeneration(RoundElections.java:115) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.consensus.RoundElections.creatMinGenInfo(RoundElections.java:124) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.consensus.ConsensusRounds.currentElectionDecided(ConsensusRounds.java:132) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.roundDecided(ConsensusImpl.java:639) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.calculateAndVote(ConsensusImpl.java:370) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.recalculateAndVote(ConsensusImpl.java:322) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.ConsensusImpl.addEvent(ConsensusImpl.java:280) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.components.LinkedEventIntake.addEvent(LinkedEventIntake.java:127) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:74) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:193) ~[swirlds-common-0.80.0.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```
[node-0-swirlds.log](https://github.com/hashgraph/hedera-services/files/14351052/node-0-swirlds.log)

**Comment by lpetrovic05** [comment]
The plan for this is to enable JRS to download states and PCES to debug this issue
