### ISSUE TITLE
Fix failing upgrade JRS tests running against mod service

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#11737]
Failing tests results https://swirldslabs.slack.com/archives/C03ELH5MUHK/p1708711884816649

- [x] Crypto-Update-Jar-1.5k-25m - `execute_immediate.mf` marker is not being detected by NMT 1.2.4
- [x] Crypto-Update-Setting-1.5k-15m - `execute_immediate.mf` marker is not being detected by NMT 1.2.4
- [x] Crypto-Update-Setting-Config-1.5k-25m - The correct `settings.txt` is not getting updated and stops at `Waiting for upgrade to finish to load new settings.txt`

**Comment by Neeharika-Sompalli** [comment]
Now hitting deserialization failure
```
2024-02-29 20:35:43.566 17       ERROR EXCEPTION        <main> StreamDebugUtils: Deserialization failure. Will re-attempt deserialization with extra debug information.
com.swirlds.common.io.exceptions.ClassNotFoundException: No class with id=-7039950634678584517(0x9E4D12326FB27B3B) found
	at com.swirlds.common.io.streams.SerializableDataInputStream.registryConstructor(SerializableDataInputStream.java:453) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:163) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.merkledb.MerkleDbTableConfig.deserialize(MerkleDbTableConfig.java:464) ~[swirlds-merkledb-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:108) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSourceBuilder.deserialize(MerkleDbDataSourceBuilder.java:194) ~[swirlds-merkledb-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.deserialize(VirtualRootNode.java:1210) ~[swirlds-virtualmap-0.80.0.jar:?]
	at com.swirlds.virtualmap.VirtualMap.lambda$loadFromFile$1(VirtualMap.java:367) ~[swirlds-virtualmap-0.80.0.jar:?]
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.virtualmap.VirtualMap.loadFromFile(VirtualMap.java:362) ~[swirlds-virtualmap-0.80.0.jar:?]
	at com.swirlds.virtualmap.VirtualMap.deserialize(VirtualMap.java:343) ~[swirlds-virtualmap-0.80.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingInternal(MerkleDataInputStream.java:113) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:170) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230) ~[swirlds-common-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileReader.lambda$readStateFile$1(SignedStateFileReader.java:94) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82) [swirlds-common-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileReader.readStateFile(SignedStateFileReader.java:87) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:504) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadLatestState(StartupStateUtils.java:473) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:223) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.getInitialState(StartupStateUtils.java:150) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:235) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:189) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:128) [swirlds-platform-core-0.80.0.jar:?]
```
