### ISSUE TITLE
Hashes RAM to disk threshold is incorrect for legacy MerkleDb tables, fileStore and smartContractIterableKvStore

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#11964]
While testing migration from 0.46 to 0.47, an issue was found with several `staging-lg` nodes. Migration is completed fine, then a node is restarted, and right on startup the following exception is thrown:

```
2024-03-06 18:35:04.545 58       ERROR EXCEPTION        <<adv crypto: merkle hash #6>> VirtualHasher: Failed to wait for all hashing tasks
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: hash
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:540) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:567) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:653) ~[?:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:479) ~[swirlds-virtualmap-0.47.1.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.computeHash(VirtualRootNode.java:1293) ~[swirlds-virtualmap-0.47.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashCopy(VirtualPipeline.java:388) ~[swirlds-virtualmap-0.47.1.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.getHash(VirtualRootNode.java:1233) ~[swirlds-virtualmap-0.47.1.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:206) ~[swirlds-common-0.47.1.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173) ~[swirlds-common-0.47.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalArgumentException: hash
	at com.swirlds.common.crypto.HashBuilder.update(HashBuilder.java:169) ~[swirlds-common-0.47.1.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.hash(VirtualHasher.java:257) ~[swirlds-virtualmap-0.47.1.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher$ChunkHashTask.exec(VirtualHasher.java:231) ~[swirlds-virtualmap-0.47.1.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

Further investigation showed that it happens only on certain nodes, and only for one of two virtual maps: file store and smart contracts store. These were the first two maps migrated from MerkleMap to VirtualMap long time ago.

What happens behind the scenes:
* When a snapshot is created, MerkleDb stores its table configs in `database_metadata.jdb/pbj` file
* Among others, table configs have `hashesRamToDiskThreshold` fields, which indicate the size of hashes store in RAM
* On some nodes, the value is 0, while other nodes have value 8388608, which is the default in `MerkleDbConfig`
* When a node with value 0 is migrated to 0.47, MerkleDb doesn't store this value in `database_metadata.pbj`, as default values aren't written to protobuf
* When such a node is restarted, it uses a default threshold value, which in `MerkleDbConfig` is 8388608
* When a hash is loaded from the data source, the path is below the threshold, so the data source tries to get the hash from RAM. However, there are no hashes in RAM, as they were all stored (previously in 0.46) on disk
* Since the hash is not found, virtual hasher fails with the exception above

**Comment by artemananiev** [comment]
The fix is merged to `release/0.47`
