### ISSUE TITLE
Daily Misc-Basic-1-20m JRS regression failed with StatsValidator

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1198]
**Summary of the defect**
Recently, this test's StatsValidator failed with NPE consistently.

**How to reproduce (if possible)**

Slack failure report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1616478757058600

**Service logs (if applicable)**
```
---- StatsValidator failed with an exception:
java.lang.NullPointerException
    at com.swirlds.regression.validators.StatsValidator.validate(StatsValidator.java:61)
    at com.swirlds.regression.Experiment.doValidation(Experiment.java:766)
    at com.swirlds.regression.Experiment.validateTest(Experiment.java:691)
    at com.swirlds.regression.Experiment.runRemoteExperiment(Experiment.java:1190)
    at com.swirlds.regression.RegressionMain.runExperiments(RegressionMain.java:271)
    at com.swirlds.regression.RegressionMain.RunCloudExperiment(RegressionMain.java:145)
    at com.swirlds.regression.RegressionMain.RunRegression(RegressionMain.java:117)
    at com.swirlds.regression.RegressionMain.main(RegressionMain.java:538)
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
The issue is repeated today https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1617255814152400. But the name of the test is `Misc-Basic-1-10m`

**Comment by ljianghedera** [comment]
Yeah. I have found the cause and fix for this issue. Now testing it now.

For the naming of `Misc-Basic-1-10m`, there is some complexity here. There are several JRS tests using this experiment, including the 15N-1C NetDelay. Somehow, that experiment didn't finish even in 15m (sometimes) with 15N-1C NetDelay env,
even though 10m seems to be sufficient for other test environments (4N, 6N). 
 
I am a little hesitant to create two files for the same content, so I put it back to 20m.
