### ISSUE TITLE
Teacher times out waiting for responses, while learner is still processing the previous reconnect root

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#12046]
The test `VMerkleDual-NDReconnect-500-60m` had two failures recently where the cause seem to be a timeout.
- [develop failure](http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20240309-053532-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/)
- [0.47 failure](http://35.247.76.217:8095/swirlds-automation/release/0.47/4N/Reconnect/20240310-091009-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/)

Example stack trace:
```
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:154) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:147) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:156) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.sendTree(TeachingSynchronizer.java:195) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.synchronize(TeachingSynchronizer.java:136) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.reconnect(ReconnectTeacher.java:233) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.execute(ReconnectTeacher.java:168) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.teacher(ReconnectProtocol.java:297) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.runProtocol(ReconnectProtocol.java:259) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.states.ProtocolNegotiated.transition(ProtocolNegotiated.java:62) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.Negotiator.execute(Negotiator.java:94) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:74) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:157) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:142) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:278) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:304) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346) ~[?:?]
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796) ~[?:?]
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:489) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:483) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1461) ~[?:?]
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1066) ~[?:?]
	at com.swirlds.common.io.extendable.extensions.AbstractStreamExtension.read(AbstractStreamExtension.java:88) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.extendable.ExtendableInputStream.read(ExtendableInputStream.java:78) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291) ~[?:?]
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:325) ~[?:?]
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:312) ~[?:?]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:71) ~[?:?]
	at com.swirlds.common.io.streams.AugmentedDataInputStream.read(AugmentedDataInputStream.java:71) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
	at java.base/java.io.DataInputStream.readBoolean(DataInputStream.java:255) ~[?:?]
	at com.swirlds.common.io.streams.AugmentedDataInputStream.readBoolean(AugmentedDataInputStream.java:139) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.QueryResponse.deserialize(QueryResponse.java:71) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:148) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:142) ~[swirlds-common-0.49.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	... 1 more
```

**Comment by artemananiev** [comment]
I think I know what went wrong here:

1. On the teacher side:

```
2024-03-09 06:20:28.123 20724    INFO  RECONNECT        <<platform-core: SyncProtocolWith3 0 to 3>> TeachingSynchronizer: finished sending tree
2024-03-09 06:20:28.299 20733    INFO  RECONNECT        <<platform-core: SyncProtocolWith3 0 to 3>> TeachingSynchronizer: sending tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
```

That is, the teacher finished sending a virtual map at route [0 -> 8 -> 1] at 06:20:28 and started sending the next virtual map at route [0 -> 9 -> 1] right after

2. On the learner side:

```
2024-03-09 06:17:13.430 6944     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 8 -> 1]
2024-03-09 06:25:28.187 7028     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 9 -> 1]
```

Note the timestamps here. The first virtual map is processed from 06:17:13 to 06:25:28

3. It means, the teacher started sending the next virtual map 5 minutes before the learner finished processing the previous virtual map. Async stream timeout is 5 minutes by default, so the teacher timed out waiting for a response from the learner for the second map

**Comment by anthony-swirldslabs** [comment]
The current implementation is unable to start sending the next virtual map because a call to `sendTree()` is blocking at

https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java#L195

until the current map is fully synchronized. This is implemented in the TeacherReceivingThread by continuing to run the `while` loop as long as `view.isResponseExpected()` is true:

https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherReceivingThread.java#L89

and the latter would keep being true until the queue of expected responses is empty:

https://github.com/hashgraph/hedera-services/blob/develop/platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTeacherTreeView.java#L179

The queue is getting cleared when responses from the learner are received.

Until the learner reports the status of the very last node at the last level that has been sent to it, the `TeacherReceivingThread` will keep running and keeping the `workGroup` alive, hence delaying the processing of the next subtree (e.g. the next VirtualMap) until the current one is processed.

So, while the evaluation above is correct stating that the learner took 5 seconds before it started processing the next VirtualMap, this doesn't necessarily indicate that it was busy processing the previous one, because if it was, it wouldn't send a response to the teacher about the last node being processed, and hence the teacher wouldn't have started sending the next VirtualMap.

It seems that the problem here is either on the learner side (it took too long to start processing the next virtual map once it received the first node of this next map), or between the teacher and the learner (e.g. a network latency delayed the network packet to the learner for 5 seconds after the teacher has sent it.)

**Comment by anthony-swirldslabs** [comment]
Upon further inspection, it looks like the `TeacherSendingThread` would send a `LeafDataLesson` for leaves, thus bypassing a call to `prepareForQueryResponse`, and therefore not adding any entries to the expected responses queue.

This means that the teacher has no way of knowing when the learner would possibly finish processing all the leaf nodes of the last level.

**Comment by anthony-swirldslabs** [comment]
I hope to get more insights with more logs introduced at https://github.com/hashgraph/hedera-services/pull/12284 once the test fails again.

**Comment by artemananiev** [comment]
A recent failure because of this problem: http://35.247.76.217:8095/thenswan/develop/4N/Reconnect/20241003-105334-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m

According to additional logs (from #12284), the learner spends 5+ minutes in hashing code. Data transfers for the current subtree is complete by this time, so the teacher started sending the next subtree and then times out waiting for the first response from the learner (who is hashing the previous subtree).

**Comment by lpetrovic05** [comment]
Can the learner send periodical messages indicating that its busy hashing or something?

**Comment by akugal** [comment]
This issue is old and related to code that doesn't exist anymore
