### ISSUE TITLE
20N_20C MixedOps-Restart-Performance-10k-31m fails with error 

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1206]
**Summary of the defect**
`MixedOps-Restart-Performance-10k-31m` failed with the following error in `swirlds.log`. This resulted in platform not turning ACTIVE and the test did not run 

```
2021-03-24 02:31:12.102 13       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:465) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:699) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:942) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.0.jar:?]
Caused by: java.lang.NullPointerException
	at com.google.protobuf.ByteString.copyFrom(ByteString.java:363) ~[protobuf-java-3.8.0.jar:?]
	at com.hedera.services.state.merkle.MerkleSchedule.witnessValidEd25519Signature(MerkleSchedule.java:105) ~[?:?]
	at com.hedera.services.state.merkle.MerkleSchedule.deserialize(MerkleSchedule.java:207) ~[?:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.finishReadingLeaf(MerkleDataInputStream.java:97) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:148) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:202) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.platform.SignedStateFileManager.readSavedState(SignedStateFileManager.java:300) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:432) ~[swirlds-platform-core-0.9.0.jar:?]
	... 3 more
2021-03-24 02:31:12.109 14       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting
2021-03-24 02:31:12.110 15       DEBUG STARTUP          <main> BinaryObjectStore: Recovering Objects [ objectCount = 3, uniqueObjectCount = 3 ]
2021-03-24 02:31:12.135 16       ERROR EXCEPTION        <main> Browser: 
com.swirlds.blob.BinaryObjectException: Failed to retrieve Id for Hash of BinaryObject
	at com.swirlds.blob.BinaryObjectStore.recover(BinaryObjectStore.java:238) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.blob.BinaryObjectStore.stopInit(BinaryObjectStore.java:170) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.stopInit(Browser.java:1036) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:945) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.0.jar:?]
2021-03-24 02:31:12.139 17       DEBUG STARTUP          <main> Browser: main() finished
``` 

**How to reproduce (if possible)**
https://app.circleci.com/pipelines/github/hashgraph/hedera-services/12366/workflows/39c29f24-7f49-4bef-b9eb-e28c1acdec91/jobs/60023/artifacts

**Comment by Neeharika-Sompalli** [comment]
Need to generate a new state to run this test that has all entities in it with new services code base.
