### ISSUE TITLE
Deserialization bug during reconnect

### ISSUE THREAD

**Issue by cody-l** [hashgraph/hedera-services#1223]
# Summary
I suspect that a merkle node in the state may be throwing an exception during deserialization during reconnect.

There is a bug in the platform as of at least platform version 0.9.0 where certain types of exceptions thrown during deserialization during reconnect could cause the sync thread to permanently deadlock. Unfortunately this deadlock also prevents the original error from being logged. 

The exception thrown is guaranteed to not be an IO exception or an interrupted exception (these types do not cause deadlock).

We have observed deadlock in this location for some reconnect tests. Once the deadlock bug is patched on platform, we should attempt to provoke this reconnect failure so that we can find (and fix) the triggering exception.

# Related issues:

https://github.com/swirlds/swirlds-platform/issues/3135
swirlds/swirlds-platform-regression#709
hashgraph/hedera-services#709
hashgraph/hedera-services#1042

**Comment by Neeharika-Sompalli** [comment]
I could reproduce the issue once with 0.9.0 sdk by running `ValidationScenarios` and manually killing java process on node 5 while that suite in client is running. 

Attached are the logs 
[logs-0.9.0-error-produced.zip](https://github.com/hashgraph/hedera-services/files/6260974/logs-0.9.0-error-produced.zip)

**Comment by Neeharika-Sompalli** [comment]
As @tinker-michaelj  observed the issue is triggered on existing Reconnect tests. [Logs](https://app.circleci.com/pipelines/github/hashgraph/hedera-services/12748/workflows/bfaeaab0-ef2c-400c-892f-e71213800cd6/jobs/61297/steps) are available. The exception looks similar to [original error](https://github.com/hashgraph/hedera-services/issues/1042#issuecomment-772848105).



```
2021-04-06 09:01:58.795 54       INFO  RECONNECT        <<    syncListener  0  3>> SyncListener: 0 got commStateRequest from 3
2021-04-06 09:01:58.799 55       INFO  RECONNECT        <<    syncListener  0  3>> SyncListener: Starting reconnect in the role of the sender {"receiving":false,"nodeId":0,"otherNodeId":3,"round":10814} [com.swirlds.logging.payloads.ReconnectStartPayload]
2021-04-06 09:01:58.800 56       DEBUG RECONNECT        <<    syncListener  0  3>> ReconnectSender: Got commStateRequest from 3, preparing for synchronization.
2021-04-06 09:01:58.801 57       INFO  RECONNECT        <<    syncListener  0  3>> ReconnectSender: Starting synchronization in the role of the sender.
2021-04-06 09:01:59.296 59       ERROR SOCKET_EXCEPTIONS <sync_server_3> SyncServer: 0 got new connection from 3, disconnecting old one
2021-04-06 09:01:59.295 58       ERROR RECONNECT        <<    syncListener  0  3>> ReconnectSender: Work Group Exception [ groupName = sending-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:156) ~[swirlds-common-0.9.0.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:149) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:118) [swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.merkle.synchronization.SendingSynchronizer.synchronize(SendingSynchronizer.java:137) [swirlds-common-0.9.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.reconnect(ReconnectSender.java:117) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:85) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:310) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:152) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:104) [swirlds-platform-core-0.9.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:128) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:100) ~[swirlds-common-0.9.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readBoolean(DataInputStream.java:249) ~[?:?]
	at com.swirlds.common.merkle.synchronization.AckMessage.deserialize(AckMessage.java:59) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:119) ~[swirlds-common-0.9.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:100) ~[swirlds-common-0.9.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
2021-04-06 09:01:59.302 60       ERROR EXCEPTION        <<    syncListener  0  3>> SyncListener: ! SyncListener.sync Exception (so incrementing interruptedRecSyncsPerSecond) while 0 listening for 3:
java.lang.NullPointerException: null
	at com.swirlds.platform.reconnect.ReconnectSender.resetSocketTimeout(ReconnectSender.java:72) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:93) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:310) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:152) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:104) [swirlds-platform-core-0.9.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

**Comment by nathanklick** [comment]
@Neeharika-Sompalli The logs above are more of a symptom of the problem. It looks like a socket bind error may be closer to the root cause: 

```
2021-04-05 21:03:47.171 47       ERROR EXCEPTION        <<      syncServer  5   >> SyncServer: SyncServer.run error
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:386) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:340) ~[?:?]
	at com.swirlds.platform.Crypto.newServerSocketConnect(Crypto.java:381) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncServer.run(SyncServer.java:190) [swirlds-platform-core-0.9.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```
