### ISSUE TITLE
All service regression tests failed due to exception from BootstrapUtils

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#12335]
### Description

All nodes failed to start with following errors from swirlds.log

```
2024-03-25 06:43:13.549 1        INFO  STARTUP          <main> BootstrapUtils: there are 1 nodes with local IP addresses
2024-03-25 06:43:13.622 2        DEBUG STARTUP          <main> BootstrapUtils: Scanning the classpath for RuntimeConstructable classes
2024-03-25 06:43:14.670 4        DEBUG STARTUP          <main> BootstrapUtils: Done with registerConstructables, time taken 1047ms
2024-03-25 06:43:14.702 5        ERROR EXCEPTION        <main> BootstrapUtils: Problems with class com.hedera.node.app.ServicesMain
com.swirlds.platform.swirldapp.AppLoaderException: ERROR: Couldn't instantiate the class com.hedera.node.app.ServicesMain
	at com.swirlds.platform.swirldapp.SwirldAppLoader.instantiateSwirldMain(SwirldAppLoader.java:58) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.util.BootstrapUtils.buildAppMain(BootstrapUtils.java:284) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.util.BootstrapUtils.loadSwirldMains(BootstrapUtils.java:401) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:169) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:137) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:112) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:101) [swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at com.swirlds.platform.swirldapp.SwirldAppLoader.instantiateSwirldMain(SwirldAppLoader.java:56) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	... 6 more
Caused by: java.lang.IllegalArgumentException: No config data record available of type 'class com.hedera.node.config.data.HederaConfig'
	at com.swirlds.config.impl.internal.ConfigDataService.getConfigData(ConfigDataService.java:111) ~[swirlds-config-impl-0.49.0-SNAPSHOT.jar:?]
	at com.swirlds.config.impl.internal.ConfigurationImpl.getConfigData(ConfigurationImpl.java:204) ~[swirlds-config-impl-0.49.0-SNAPSHOT.jar:?]
	at com.hedera.node.config.VersionedConfigImpl.getConfigData(VersionedConfigImpl.java:106) ~[config-0.49.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.ServicesMain.<init>(ServicesMain.java:72) ~[?:?]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at com.swirlds.platform.swirldapp.SwirldAppLoader.instantiateSwirldMain(SwirldAppLoader.java:56) ~[swirlds-platform-core-0.49.0-SNAPSHOT.jar:?]
	... 6 more
2024-03-25 06:43:14.713 6        ERROR EXCEPTION        <main> Browser: Unable to start Browser
```

### Steps to reproduce

Any nightly regression test pnael

### Hedera network

other

### Version

latest

### Operating system

Linux

**Comment by JeffreyDallas** [comment]
Fixed by cody
