### ISSUE TITLE
ConsensusTests.partitionTests() fails on seed Running seed: 903918710117390630L

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#12380]
The unit test passes several times without setting the seed to a specific value. 

903918710117390630 fails with the following result: 

```
Running seed: 903918710117390630
WARNING: A Java agent has been loaded dynamically (/Users/user/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.14.10/90ed94ac044ea8953b224304c762316e91fd6b31/byte-buddy-agent-1.14.10.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
15:25:46.684   7738 Test worker No cyclical back pressure detected in wiring model.
15:25:46.686   7740 Test worker No illegal direct scheduler use detected in the wiring model.
15:25:46.687   7741 Test worker All input wires have been bound.
15:25:46.689   7743 Test worker No cyclical back pressure detected in wiring model.
15:25:46.689   7743 Test worker No illegal direct scheduler use detected in the wiring model.
15:25:46.689   7743 Test worker All input wires have been bound.
Partitioned nodes: [0, 1, 2, 3, 4]

Partition has 15 (33.33333333333333%) of 45 total stake.
```

```
org.opentest4j.AssertionFailedError: Consensus ratio 2.001764705882353 is more than the expected maximum 2.0 ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
	at com.swirlds.platform.test.consensus.framework.validation.EventRatioValidation.validate(EventRatioValidation.java:119)
	at com.swirlds.platform.test.consensus.framework.ConsensusTestOrchestrator.validate(ConsensusTestOrchestrator.java:122)
	at com.swirlds.platform.test.consensus.framework.ConsensusTestOrchestrator.validateAndClear(ConsensusTestOrchestrator.java:108)
	at com.swirlds.platform.test.consensus.ConsensusTestDefinitions.partitionTests(ConsensusTestDefinitions.java:208)
```

**Comment by edward-swirldslabs** [comment]
test passes on the given seed.
