### ISSUE TITLE
NPE on startup after 0.47 -> 0.48 migration

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#12466]
### Description

The following exception happens on startup after 0.47 -> 0.48 migration

```
2024-03-30 02:53:14.569 16881    ERROR EXCEPTION        <<virtual-pipeline: lifecycle
 #0>> VirtualRootNode: Could not close the dataSource after all copies were destroyed
java.lang.NullPointerException: Cannot invoke "com.swirlds.merkledb.MerkleDb$TableMet
adata.pbjSizeInBytes()" because "metadata" is null
        at com.swirlds.merkledb.MerkleDb.storeMetadata(MerkleDb.java:637) ~[swirlds-m
erkledb-0.48.0-alpha.6.jar:?]
        at com.swirlds.merkledb.MerkleDb.storeMetadata(MerkleDb.java:612) ~[swirlds-m
erkledb-0.48.0-alpha.6.jar:?]
        at com.swirlds.merkledb.MerkleDb.closeDataSource(MerkleDb.java:506) ~[swirlds
-merkledb-0.48.0-alpha.6.jar:?]
        at com.swirlds.merkledb.MerkleDbDataSource.close(MerkleDbDataSource.java:789)
 ~[swirlds-merkledb-0.48.0-alpha.6.jar:?]
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.closeDataSource(Vir
tualRootNode.java:994) ~[swirlds-virtualmap-0.48.0-alpha.6.jar:?]
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.onShutdown(VirtualR
ootNode.java:986) ~[swirlds-virtualmap-0.48.0-alpha.6.jar:?]
        at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.fireOnShutdown(Vi
rtualPipeline.java:675) ~[swirlds-virtualmap-0.48.0-alpha.6.jar:?]
        at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.lambda$shutdown$3
(VirtualPipeline.java:611) ~[swirlds-virtualmap-0.48.0-alpha.6.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.ja
va:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExec
utor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExe
cutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

```

### Steps to reproduce

1. Run 0.47-> 0.48 migration of a node with populated `VirtualMap`-s 
2. Observe exceptions

### Hedera network

previewnet

### Version

v0.48

### Operating system

None

**Comment by imalygin** [comment]
We have an array `MerkleDb#tableConfigs` which stores `TableMetadata` objects. This arrays is index by table IDs. During the migration we move data from one set of tables to the other set of tables, and then we discard the old tables, and we discard metadata for these tables as well. After that we have 5 null elements, as there were 5 objects corresponding to the old VirtualMap-s. 

This part of `MerkleDb#storeMetadata`  fails:

```
                for (final TableMetadata metadata : tables) {
                    final int len = metadata.pbjSizeInBytes();
                    ProtoWriterTools.writeDelimited(out, FIELD_DBMETADATA_TABLEMETADATA, len, metadata::writeTo);
                }
```
Here is now it gets a collection of tables:

```
    private void storeMetadata() {
        storeMetadata(storageDir, getPrimaryTables());
    }
```

Here is `MerkleDb#getPrimaryTables`

```
    private Set<TableMetadata> getPrimaryTables() {
        final Set<TableMetadata> tables = new HashSet<>();
        for (int i = 0; i < tableConfigs.length(); i++) {
            final TableMetadata tableMetadata = tableConfigs.get(i);
            if ((tableMetadata != null) && primaryTables.contains(i)) {
                tables.add(tableConfigs.get(i));
            }
        }
        // If this method is ever used outside this class, change it to return an
        // unmodifiable set instead
        return tables;
    }
```

The issue with this code is that there may be a data race. At first we check that `tableMetadata` is not null but then we don't use local variable that we just checked, we take again from `tableConfigs` array which could've been modified in parallel. To avoid NPE, we should use the value we got prior to the null check.
