### ISSUE TITLE
TopicMessageSubmit without topicID throws unexpected NPE

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12567]
Discovered during Java SDK integration testing:

TopicMessageSubmitIntegrationTest > Cannot submit message when topic ID is not set
[Link to the test](https://github.com/hashgraph/hedera-sdk-java/blob/df866e90bb796a23678aa6ea85227bf4e52b905b/sdk/src/integrationTest/java/TopicMessageSubmitIntegrationTest.java#L122)

SDK Logs:
    java.lang.AssertionError:
    Expecting code not to raise a throwable but caught
      "java.lang.AssertionError:
    Expecting actual throwable to be an instance of:
      com.hedera.hashgraph.sdk.ReceiptStatusException
    but was:
      com.hedera.hashgraph.sdk.MaxAttemptsExceededException: exceeded maximum attempts for request with last exception being
      Last exception was this -> Hedera transaction `0.0.1022@1712066727.248000000` failed pre-check with the status `OK`
      
hedera-services Logs:
2024-04-04 13:13:23.789 ERROR 151  PreHandleWorkflowImpl - Possibly CATASTROPHIC failure while running the pre-handle workflow
java.lang.NullPointerException: null
        at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at com.hedera.node.app.service.consensus.impl.ReadableTopicStoreImpl.getTopic(ReadableTopicStoreImpl.java:61) ~[app-service-consensus-impl-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.service.consensus.impl.handlers.ConsensusSubmitMessageHandler.preHandle(ConsensusSubmitMessageHandler.java:85) ~[app-service-consensus-impl-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchPreHandle(TransactionDispatcher.java:91) ~[?:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.expandAndVerifySignatures(PreHandleWorkflowImpl.java:298) ~[?:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.preHandleTransaction(PreHandleWorkflowImpl.java:241) ~[?:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflow.preHandleTransaction(PreHandleWorkflow.java:59) ~[?:?]
        at com.hedera.node.app.workflows.prehandle.PreHandleWorkflowImpl.lambda$preHandle$0(PreHandleWorkflowImpl.java:146) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:?]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) [?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:?]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) [?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

**Comment by iwsimon** [comment]
PR merged and fixed the issue.
