### ISSUE TITLE
ContractDelete without contractID throws unexpected NPE

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12565]
Discovered during Java SDK integration testing: 

ContractDeleteIntegrationTest > Cannot delete contract when contract ID is not set
[Link to the test](https://github.com/hashgraph/hedera-sdk-java/blob/df866e90bb796a23678aa6ea85227bf4e52b905b/sdk/src/integrationTest/java/ContractDeleteIntegrationTest.java#L117)

SDK Logs:
java.lang.AssertionError:
Expecting throwable message:
 "Hedera transaction `0.0.1022@1712216222.748000000` failed pre-check with the status `FAIL_INVALID`"
to contain:
 "INVALID_CONTRACT_ID"
but did not.
   
hedera-services Logs:
ERROR 106  IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field contractID is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.hedera.hapi.node.contract.ContractDeleteTransactionBody.contractIDOrThrow(ContractDeleteTransactionBody.java:153) ~[hapi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.authorization.PrivilegesVerifier.hasPrivileges(PrivilegesVerifier.java:114) ~[?:?]
        at com.hedera.node.app.authorization.AuthorizerImpl.hasPrivilegedAuthorization(AuthorizerImpl.java:82) ~[?:?]
        at com.hedera.node.app.spi.authorization.Authorizer.hasWaivedFees(Authorizer.java:76) ~[app-spi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.workflows.SolvencyPreCheck.checkSolvency(SolvencyPreCheck.java:140) ~[?:?]
        at com.hedera.node.app.workflows.SolvencyPreCheck.checkSolvency(SolvencyPreCheck.java:126) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:243) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:92) ~[?:?]
        ...

**Comment by netopyr** [comment]
Another example:

ContractUpdateIntegrationTest > Cannot update contract when contract ID is not set
[Link to the test](https://github.com/hashgraph/hedera-sdk-java/blob/df866e90bb796a23678aa6ea85227bf4e52b905b/sdk/src/integrationTest/java/ContractUpdateIntegrationTest.java#L91)

SDK Logs:
java.lang.AssertionError:
Expecting throwable message:
 "Hedera transaction `0.0.1022@1712216288.089000000` failed pre-check with the status `FAIL_INVALID`"
to contain:
 "INVALID_CONTRACT_ID"
but did not.

hedera-services Logs:
ERROR 106  IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field contractID is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.hedera.hapi.node.contract.ContractUpdateTransactionBody.contractIDOrThrow(ContractUpdateTransactionBody.java:274) ~[hapi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.authorization.PrivilegesVerifier.hasPrivileges(PrivilegesVerifier.java:90) ~[?:?]
        at com.hedera.node.app.authorization.AuthorizerImpl.hasPrivilegedAuthorization(AuthorizerImpl.java:82) ~[?:?]
        at com.hedera.node.app.spi.authorization.Authorizer.hasWaivedFees(Authorizer.java:76) ~[app-spi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.workflows.SolvencyPreCheck.checkSolvency(SolvencyPreCheck.java:140) ~[?:?]
        at com.hedera.node.app.workflows.SolvencyPreCheck.checkSolvency(SolvencyPreCheck.java:126) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:243) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:92) ~[?:?]
        ...
