### ISSUE TITLE
TokenAssociate without accountID throws unexpected NPE

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12566]
Discovered during Java SDK integration testing:

TokenAssociateIntegrationTest > Cannot associate account with tokens when account ID
[Link to the test](https://github.com/hashgraph/hedera-sdk-java/blob/df866e90bb796a23678aa6ea85227bf4e52b905b/sdk/src/integrationTest/java/TokenAssociateIntegrationTest.java#L89)

SDK Logs:
is not set FAILED
  java.lang.AssertionError:
  Expecting throwable message:
    "Hedera transaction `0.0.1183@1712216328.038000000` failed pre-check with the status `FAIL_INVALID`"
  to contain:
    "INVALID_ACCOUNT_ID"
  but did not.
  
hedera-services Logs:
ERROR 106  IngestWorkflowImpl - Possibly CATASTROPHIC failure while running the ingest workflow
java.lang.NullPointerException: Field account is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.hedera.hapi.node.token.TokenAssociateTransactionBody.accountOrThrow(TokenAssociateTransactionBody.java:145) ~[hapi-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.service.token.impl.handlers.TokenAssociateToAccountHandler.calculateFees(TokenAssociateToAccountHandler.java:188) ~[app-service-token-impl-0.48.0-alpha.8.jar:?]
        at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchComputeFees(TransactionDispatcher.java:128) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestChecker.runAllChecks(IngestChecker.java:242) ~[?:?]
        at com.hedera.node.app.workflows.ingest.IngestWorkflowImpl.submitTransaction(IngestWorkflowImpl.java:92) ~[?:?]
        at com.hedera.node.app.grpc.impl.TransactionMethod.handle(TransactionMethod.java:56) ~[?:?]
        at com.hedera.node.app.grpc.impl.MethodBase.invoke(MethodBase.java:131) ~[?:?]
        at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:252) ~[?:?]
        at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:220) ~[?:?]
        ...

**Comment by netopyr** [comment]
This one surprises me. It should be checked in `TokenAssociateToAccountHandler.pureChecks()`

**Comment by kimbor** [comment]
Fix for this has been merged to release/0.48. Will close this issue when cherry-picked to develop.
