### ISSUE TITLE
NPE in HandleWorkflow.handleUserTransaction()

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#12594]
The log from PreviewNet shows this error which needs to be fixed:

```
2024-04-05 04:42:28.700 FATAL 273  HandleWorkflow - Possibly CATASTROPHIC failure while running the handle workflow. While this node may not die right away, it is in a bad way, most likely fatally.
java.lang.NullPointerException: Cannot invoke "com.hedera.node.app.workflows.TransactionInfo.functionality()" because "transactionInfo" is null
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleUserTransaction(HandleWorkflow.java:603) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handlePlatformTransaction(HandleWorkflow.java:304) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleRound(HandleWorkflow.java:270) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.onHandleConsensusRound(Hedera.java:957) ~[HederaNode.jar:?]
	at com.hedera.node.app.state.HederaLifecyclesImpl.onHandleConsensusRound(HederaLifecyclesImpl.java:63) ~[HederaNode.jar:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.handleConsensusRound(MerkleHederaState.java:328) ~[HederaNode.jar:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.48.0-alpha.8.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169) ~[swirlds-platform-core-0.48.0-alpha.8.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.handleConsensusRound(ConsensusRoundHandler.java:226) ~[swirlds-platform-core-0.48.0-alpha.8.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:77) ~[swirlds-common-0.48.0-alpha.8.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.48.0-alpha.8.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:191) ~[swirlds-common-0.48.0-alpha.8.jar:?]
```

**Comment by netopyr** [comment]
Here is what I think happened:

If we have an unexpected Exception in `HandleWorkflow.getCurrentPreHandleResult()`, we enter the catch-all Exception handling mechanism before `transactionInfo` is initialized.

But the code directly following the Exception handler relies on `transactionInfo` being set. Unfortunately, I do not know enough about throttling and record creation to understand what should happen when an unexpected Exception occurs. Somebody with more insight into this functionality needs to fix this.

Below is the problematic code that relies on `transactionInfo`. Other local variables (e.g. `payer`) may not be initialized, too.

```
        // After a contract operation was handled (i.e., not throttled), update the
        // gas throttle by leaking any unused gas
        if (isGasThrottled(transactionInfo.functionality())
                && recordBuilder.status() != CONSENSUS_GAS_EXHAUSTED
                && recordBuilder.hasContractResult()) {
            final var gasUsed = recordBuilder.getGasUsedForContractTxn();
            handleWorkflowMetrics.addGasUsed(gasUsed);
            final var contractsConfig = configuration.getConfigData(ContractsConfig.class);
            if (contractsConfig.throttleThrottleByGas()) {
                final var gasLimitForContractTx =
                        getGasLimitForContractTx(transactionInfo.txBody(), transactionInfo.functionality());
                final var excessAmount = gasLimitForContractTx - gasUsed;
                networkUtilizationManager.leakUnusedGasPreviouslyReserved(transactionInfo, excessAmount);
            }
        }

        throttleServiceManager.saveThrottleSnapshotsAndCongestionLevelStartsTo(stack);
        final var function = transactionInfo.functionality();
        transactionFinalizer.finalizeParentRecord(
                payer,
                tokenServiceContext,
                function,
                extraRewardReceivers(transactionInfo, recordBuilder),
                prePaidRewards);

        // Commit all state changes
        stack.commitFullStack();

        // store all records at once, build() records end of transaction to log
        final var recordListResult = recordListBuilder.build();
        recordCache.add(creator.nodeId(), payer, recordListResult.records());
```
