### ISSUE TITLE
Crypto-Restart-Performance-Random-10k-61m fails with NPE in swirlds.log

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1266]
**Summary of the defect**
Crypto-Restart-Performance-Random-10k-61m fails with the following error in swirlds log

```
021-04-14 05:03:11.662 56       ERROR EXCEPTION        <<      threadCurr  4   >> EventFlow: error while calculating parameters to send the app's SwirldState.handleTransaction or while calling it with event (3,356404)
java.lang.NullPointerException: null
	at com.swirlds.platform.EventFlow.handleTransaction(EventFlow.java:707) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.EventFlow.takeHandlePut(EventFlow.java:1259) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.EventFlow.doCurr(EventFlow.java:773) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.common.threading.StoppableThread.run(StoppableThread.java:248) ~[swirlds-common-0.9.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

Slack Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618379341287300
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618385943023700

**Comment by ljianghedera** [comment]
Hasn't observed the behavior for more than one month recently. It's either a one-time glitch, or fixed by other fixes or enhancement.
