### ISSUE TITLE
Crypto-Migration-Testnet-100-5m : Platform Not Active

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1274]
**Summary of the defect**
`Crypto-Migration-Testnet-100-5m` migration test : Nodes never become `ACTIVE` after successfully loading the saved state.

Slack Link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618466268298200
Summary Link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618468182024700

**Comment by anighanta** [comment]
NO longer observed. Closing this for now. Will ReOpen if necessary.

**Comment by abhishek-hedera** [comment]
Reopening the issue as it occurred in the run of 5/1/2021.

Slack Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619848528136500
Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619850444055800

```
---- StatsValidator failed with an exception:
java.io.FileNotFoundException: results/5N_1C/Migration/20210501-054714-GCP-Daily-Crypto-Migration-5N-1C/Crypto-Migration-Testnet-100-5m/node0003/ServicesStats3.csv (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
    at com.swirlds.regression.loaders.ResultFileLoader.getFileStream(ResultFileLoader.java:98)
    at com.swirlds.regression.loaders.ResultFileLoader.getCsvReader(ResultFileLoader.java:128)
    at com.swirlds.regression.validators.StatsValidator.validate(StatsValidator.java:59)
    at com.swirlds.regression.Experiment.doValidation(Experiment.java:692)
    at com.swirlds.regression.Experiment.validateTest(Experiment.java:617)
    at com.swirlds.regression.Experiment.runRemoteExperiment(Experiment.java:1118)
    at com.swirlds.regression.RegressionMain.runExperiments(RegressionMain.java:271)
    at com.swirlds.regression.RegressionMain.RunCloudExperiment(RegressionMain.java:145)
    at com.swirlds.regression.RegressionMain.RunRegression(RegressionMain.java:117)
    at com.swirlds.regression.RegressionMain.main(RegressionMain.java:538)

---- HAPIClientValidator FAILED validation ----
2021-05-01 05:50:22.233 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
2021-05-01 05:50:24.384 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
ClientNode - Suite                    Result   Failures
Node 0 - CryptoCreateForSuiteRunner   FAILED   CreatePayerAccountForEachClient
Exceptions:2
Node 0 - CryptoTransferLoadTest       FAILED   RunCryptoTransfers
Exceptions:2

---- HGCAAQueryValidator FAILED validation ----
Node 3 has 1 errors
Node 4 has 1 errors

---- HederaMigrationValidator FAILED validation ----
Node 0 didn't change status to ACTIVE
Node 1 didn't change status to ACTIVE
Node 2 didn't change status to ACTIVE
Node 3 didn't change status to ACTIVE
Node 3 didn't start platforms
Node 4 didn't change status to ACTIVE

---- HederaNodeValidator FAILED validation ----
Node 3 has exception:- Fatal precondition violated in HederaNode#3!

---- StreamSimpleValidator FAILED validation ----
No sha1sum found for server 0, and no records were recorded!
No sha1sum found for server 1, and no records were recorded!
No sha1sum found for server 2, and no records were recorded!
No sha1sum found for server 3, and no records were recorded!
```

**Comment by Neeharika-Sompalli** [comment]
Platform did not turn ACTIVE because node 3 has this error related to Binding. This is not a real test error,  but is caused because the network is not setup correctly.
```
2021-05-01 05:49:28.386 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#3!
java.lang.IllegalStateException: java.io.IOException: Failed to bind
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:72) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:703) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:949) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.2.jar:?]
Caused by: java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:264) ~[grpc-netty-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[grpc-core-1.33.0.jar:1.33.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.33.0.jar:1.33.0]
	at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:83) ~[HederaNode.jar:?]
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:65) ~[HederaNode.jar:?]
	... 6 more
Caused by: io.net
```
