### ISSUE TITLE
Fix NPE when treasury is not associated in `TokenCreateHandler`

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#12776]
When treasury is not associated with token in TokenCreateHandler , we should not throw an NPE instead return appropriate response code

```
2024-04-12 16:21:35.363 ERROR 584  HandleWorkflow - Possibly CATASTROPHIC failure while handling a user transaction
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at com.hedera.node.app.service.token.impl.handlers.TokenCreateHandler.handle(TokenCreateHandler.java:158) ~[app-service-token-impl-0.48.0-alpha.12.jar:?]
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:146) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleUserTransaction(HandleWorkflow.java:539) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handlePlatformTransaction(HandleWorkflow.java:306) ~[HederaNode.jar:?]
	at com.hedera.node.app.workflows.handle.HandleWorkflow.handleRound(HandleWorkflow.java:272) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.onHandleConsensusRound(Hedera.java:957) ~[HederaNode.jar:?]
	at com.hedera.node.app.state.HederaLifecyclesImpl.onHandleConsensusRound(HederaLifecyclesImpl.java:63) ~[HederaNode.jar:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.handleConsensusRound(MerkleHederaState.java:328) ~[HederaNode.jar:?]
	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:84) ~[swirlds-platform-core-0.48.0-alpha.12.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:169) ~[swirlds-platform-core-0.48.0-alpha.12.jar:?]
	at com.swirlds.platform.eventhandling.ConsensusRoundHandler.handleConsensusRound(ConsensusRoundHandler.java:226) ~[swirlds-platform-core-0.48.0-alpha.12.jar:?]
	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$0(BindableInputWire.java:77) ~[swirlds-common-0.48.0-alpha.12.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) ~[swirlds-common-0.48.0-alpha.12.jar:?]
	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:191) ~[swirlds-common-0.48.0-alpha.12.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Neeharika-Sompalli** [comment]
The transaction failed when alias is being used as treasury. It will be fixed by this PR https://github.com/hashgraph/hedera-services/pull/12754
