### ISSUE TITLE
Backups of round `168343348` don't pass validation

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#12824]
### Description

Today (04/15) at 10:41 AM the validation tool reported a validation failure on all the nodes. Here is [the example of a such report](example of a such report).

Here is the relevant stacktrace:
```
Caused by: java.io.IOException: The input stream provided a length of 73 for the list/array which exceeds the maxLength of 25
	at com.swirlds.common.io.streams.AugmentedDataInputStream.checkLengthLimit(AugmentedDataInputStream.java:542)
	at com.swirlds.common.io.streams.AugmentedDataInputStream.readLongArray(AugmentedDataInputStream.java:305)
	at com.hedera.node.app.service.mono.state.submerkle.CurrencyAdjustments.deserialize(CurrencyAdjustments.java:78)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88)
	at com.hedera.node.app.service.mono.state.serdes.IoUtils.readNullableSerializable(IoUtils.java:74)
	at com.hedera.node.app.service.mono.state.submerkle.ExpirableTxnRecord.deserialize(ExpirableTxnRecord.java:373)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readNextSerializableIteration(SerializableDataInputStream.java:285)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializableIterableWithSizeInternal(SerializableDataInputStream.java:252)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializableIterableWithSize(SerializableDataInputStream.java:186)
	at com.swirlds.fcqueue.FCQueue.deserializeV3(FCQueue.java:791)
	at com.swirlds.fcqueue.FCQueue.deserialize(FCQueue.java:772)
	at com.swirlds.common.merkle.MerkleLeaf.deserialize(MerkleLeaf.java:53)
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingLeaf(MerkleDataInputStream.java:95)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:168)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230)
	at com.swirlds.platform.state.signed.SignedStateFileReader.lambda$readStateFile$1(SignedStateFileReader.java:94)
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82)
	at com.swirlds.platform.state.signed.SignedStateFileReader.readStateFile(SignedStateFileReader.java:87)
``` 

### Steps to reproduce

1. Open [`Validate States of Mainnet` page](https://github.com/hashgraph/hedera-state-validator/actions/workflows/flow-validate-states-mainnet.yaml)
2. Click `Run workflow` menu
3. Enter `168343348` in the `Round to validate` text field.
4. Push `Run workflow` button

### Hedera network

mainnet

### Version

v0.47

### Operating system

None

**Comment by imalygin** [comment]
Upon the investigation with @tinker-michaelj, we concluded that this is an issue in the Hedera Services code base. There is nothing to fix in the validator, it found an actual bug. So, I close this ticket.
