### ISSUE TITLE
MerkleUtils Async tree hashing failed

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#12827]
JRS Test failed, node 1 has NPE
**data directory:**  http://35.247.76.217:8095/swirlds-automation/release/0.48/5N/SimilarStake/20240415-091225-GCP-RestartWithNewNodes-SimilarStake-5N/NFT-Restart-Stake-2.5k-10m/
test: NFT-Restart-Stake-2.5k-10m

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read the array length because "input" is null
	at com.swirlds.common.merkle.hash.FutureMerkleHash.rethrowException(FutureMerkleHash.java:83) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:93) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:30) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.utility.MerkleUtils.rehashTree(MerkleUtils.java:67) [swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:520) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadLatestState(StartupStateUtils.java:473) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:223) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.getInitialState(StartupStateUtils.java:150) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:235) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:189) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:128) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:103) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:92) [swirlds-platform-core-0.47.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because "input" is null
	at java.base/java.security.MessageDigest.update(MessageDigest.java:357) ~[?:?]
	at com.swirlds.common.crypto.HashBuilder.update(HashBuilder.java:172) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.crypto.internal.MerkleInternalDigestProvider.handleItem(MerkleInternalDigestProvider.java:79) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.crypto.internal.MerkleInternalDigestProvider.compute(MerkleInternalDigestProvider.java:91) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.crypto.internal.MerkleCryptoEngine.digestSync(MerkleCryptoEngine.java:92) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.crypto.internal.MerkleCryptoEngine.digestSync(MerkleCryptoEngine.java:116) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.crypto.MerkleCryptography.digestSync(MerkleCryptography.java:55) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:213) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173) ~[swirlds-common-0.47.0-SNAPSHOT.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by poulok** [comment]
Old issue, closing
