### ISSUE TITLE
Crypto-Restart-RecordStreamV5-1.5k-10m BindException for SyncServer in swirlds.log

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1286]
**Summary of the defect**
Lots of address bind exception in node0:

```
2021-04-20 06:30:43.594 28       INFO  PLATFORM_STATUS  << pollIntakeQueue  0   >> SwirldsPlatform: Platform status changed to: ACTIVE
2021-04-20 06:30:43.619 29       ERROR EXCEPTION        <<      syncServer  0   >> SyncServer: SyncServer.run error
java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:386) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:340) ~[?:?]
	at com.swirlds.platform.Crypto.newServerSocketConnect(Crypto.java:381) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.SyncServer.run(SyncServer.java:190) [swirlds-platform-core-0.9.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-04-20 06:30:43.720 30       ERROR EXCEPTION        <<      syncServer  0   >> SyncServer: SyncServer.run error

```

Slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618901021355600
Summary link:  https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618901874030500

The same errors happened to Crypto-Migration-Testnet-100-5m test as well: 
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618899062353200

I thought there is an issue opened for this one already, but couldn't find it. So opened it again here.

**How to reproduce (if possible)**

Slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618901021355600

**Service logs (if applicable)**
```
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Not observing the same failure in past days and not able to reproduce in local run, I am closing this issue for now.
