### ISSUE TITLE
Upgrade test failed due to ClassCastException

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#12927]
### Description

Upgrade process finished but after restart platform reported error

```
java.lang.ClassCastException: class com.hedera.node.app.state.merkle.queue.QueueNode cannot be cast to class com.swirlds.merkle.map.MerkleMap (com.hedera.node.app.state.merkle.queue.QueueNode is in unnamed module of loader com.swirlds.common.constructable.URLClassLoaderWithLookup @20c0a64d; com.swirlds.merkle.map.MerkleMap is in unnamed module of loader 'app')
	at com.hedera.node.app.state.HederaLifecyclesImpl.onUpdateWeight(HederaLifecyclesImpl.java:150) ~[?:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.updateWeight(MerkleHederaState.java:219) ~[?:?]
	at com.swirlds.platform.state.address.AddressBookInitializer.initialize(AddressBookInitializer.java:231) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.address.AddressBookInitializer.<init>(AddressBookInitializer.java:148) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:254) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:189) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:128) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:103) [swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:92) [swirlds-platform-core-0.80.0.jar:?]
2024-04-22 11:33:27.869 108      ERROR EXCEPTION        <main> Log4jSetup: exception on thread main
java.lang.RuntimeException: Unable to start Browser
	at com.swirlds.platform.Browser.launch(Browser.java:131) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:103) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:92) ~[swirlds-platform-core-0.80.0.jar:?]
Caused by: java.lang.ClassCastException: class com.hedera.node.app.state.merkle.queue.QueueNode cannot be cast to class com.swirlds.merkle.map.MerkleMap (com.hedera.node.app.state.merkle.queue.QueueNode is in unnamed module of loader com.swirlds.common.constructable.URLClassLoaderWithLookup @20c0a64d; com.swirlds.merkle.map.MerkleMap is in unnamed module of loader 'app')
	at com.hedera.node.app.state.HederaLifecyclesImpl.onUpdateWeight(HederaLifecyclesImpl.java:150) ~[?:?]
	at com.hedera.node.app.state.merkle.MerkleHederaState.updateWeight(MerkleHederaState.java:219) ~[?:?]
	at com.swirlds.platform.state.address.AddressBookInitializer.initialize(AddressBookInitializer.java:231) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.state.address.AddressBookInitializer.<init>(AddressBookInitializer.java:148) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.PlatformBuilder.build(PlatformBuilder.java:254) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:189) ~[swirlds-platform-core-0.80.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:128) ~[swirlds-platform-core-0.80.0.jar:?]
```

The last good commit is `d0733c60b9`

### Steps to reproduce

Nightly regression test panel 

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by Neeharika-Sompalli** [comment]
@JeffreyDallas  This should be fixed by this PR https://github.com/hashgraph/hedera-services/pull/12941
