### ISSUE TITLE
MixedOps-NDReconnect-1.5k-12m (release/0.13) failed due to ErrorValidator failure

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1293]
**Summary of the defect**

This error only happened to release/0.13. Node 3's swirlds.log has exception when loading saved state. See the error message below.

**How to reproduce (if possible)**
Refer to these slack reports:
slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618996097388600
Summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618996139032900

**Service logs (if applicable)**

In node3's swirlds.log:

```
...
2021-04-21 08:54:36.278 24       INFO  SNAPSHOT_MANAGER << SnapshotManager >> SnapshotManager: SnapshotManager: Completed task [taskType='RESTORE', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=3, roundNumber=706, snapshotId=restore, timeStarted=2021-04-21T08:54:36.266080Z, timeCompleted=2021-04-21T08:54:36.278842Z, complete=true, error=true ]
2021-04-21 08:54:36.279 25       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Failed to restore postgres sql snapshot: /home/services_nightly_regression/remoteExperiment/data/saved/com.hedera.services.ServicesMain/3/123/706/SignedState.swh
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:472) ~[swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:699) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:942) [swirlds-platform-core-0.9.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.0.jar:?]
2021-04-21 08:54:36.286 26       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by anighanta** [comment]
During a Reconnect Test, the reconnecting Node is occasionally failing to start from the saved state.
Happened again on May 7th but not since/in-between. 
Slack Summary of failure : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1620385050068800

**Comment by anighanta** [comment]
Test runs with `reconnectStartDelay` set to `120 sec` look consistent and stable. Node 5 successfully loaded the state back when the service stars back. 

Slack Links: [Will keep updating this list]
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1620766887190800



Creating a new issue to let devops know about this possible scenario of a node that might crash/stop working when it is in the middle of writing a saved state to disk will run into this issue.
