### ISSUE TITLE
HTS-Restart-AccountBalances-1k-26m: failed for StatsValidator, AccountBalancesValidator, and other validators

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1294]
**Summary of the defect**
The root cause could be the account balances csv files were not generated.

**How to reproduce (if possible)**
Slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1618990083379800
Summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1618991510032600

**Service logs (if applicable)**
```
...

---- StatsValidator failed with an exception:
java.io.FileNotFoundException: results/6N_1C/Basic/20210421-063934-GCP-Daily-Comp-BalancesValidate-6N-1C/HTS-Restart-AccountBalances-1k-26m/node0005/ServicesStats5.csv (No such file or directory)
    at java.base/java.io.FileInputStream.open0(Native Method)
    at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
Show more
---- AccountBalancesValidator FAILED validation ----
<<ERROR>>
Server node0: there is no account balances file
Server node 0 doesn't have account balances file created
There is no account balances file generated
Server node0: there is no account balances signature file
<<WARNING>>
No account balances file found
<<INFO>>
Do not validate client account balances
Show less
---- HAPIClientValidator FAILED validation ----
2021-04-21 07:03:26.017 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
2021-04-21 07:06:34.726 ERROR  242  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Closed by platform regression PR: https://github.com/swirlds/swirlds-platform-regression/pull/1005
