### ISSUE TITLE
Total Supply validation failed on a couple of rounds

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#13468]
### Description

There were two round for which `TotalHbarSupplyIs_50B` validation has failed: 

[171851062](https://github.com/hashgraph/hedera-state-validator/actions/runs/9196598201/job/25295133654#logs) and [171851985](https://github.com/hashgraph/hedera-state-validator/actions/runs/9196130047/job/25293574210#logs). For the subsequent rounds the issue automagically went away. 

The issue is deterministic and consistently reproducible on these rounds.

We need to understand why exactly this has happened. 

### Steps to reproduce

Run the state validation tool for one of the abovementioned rounds. 

### Hedera network

mainnet

### Version

v0.49

### Operating system

None

**Comment by imalygin** [comment]
Initially I had two assumptions about the following code: 
```
        AtomicLong totalBalance = new AtomicLong(0L);
        processRange(firstLeafPath, lastLeafPath + 1, i -> {
            try {
                VirtualLeafRecord<EntityNumVirtualKey, OnDiskValue<Account>> record = dataSource.loadLeafRecord(i);
                Account value = record.getValue().getValue();
                totalBalance.addAndGet(value.tinybarBalance());
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }).join();
````
1. Something is wrong with the range - `firstLeafPath` or `lastLeafPath`. That is, if some path that is associated with an account is excluded from the range, the total balance will be incorrect. It turned out not to be the case - I tried `firstLeafPath - 1` and `lastLeafPath + 2`. In both cases it ended with exception like
```
Caused by: java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: path (11219999) is not valid; must be in range (5609999,11219998)
```
as it should be for the path that is not in the range. 
2. Something is wrong with the parallel iterator, so I replaced it with the sequential processing:
```
 AtomicLong totalBalance = new AtomicLong(0L);
        LongStream.range(firstLeafPath, lastLeafPath + 1).forEach(i -> {
            try {
                VirtualLeafRecord<EntityNumVirtualKey, OnDiskValue<Account>> record = dataSource.loadLeafRecord(i);
                Account value = record.getValue().getValue();
                totalBalance.addAndGet(value.tinybarBalance());
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
```
I got exactly the same failure as with the parallel iterator:
```
TotalHbarSupplyIs_50B.validate,validate(DeserializedSignedState, Report) - FAILED
C:\Users\user\IdeaProjects\hedera-state-validator\report.json
org.opentest4j.AssertionFailedError: expected: <5000000000000000000> but was: <4989712725246492199>
```

**Comment by imalygin** [comment]
Interestingly enough, this code return correct results:
```
        MerkleIterator<MerkleNode> merkleNodeMerkleIterator = accountVm.treeIterator();
        while (merkleNodeMerkleIterator.hasNext()) {
            MerkleNode next = merkleNodeMerkleIterator.next();
            if(next instanceof VirtualLeafNode<?, ?> leafNode) {
                VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>> accountLeafNode  =
                        (VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>>) leafNode;
                totalBalance.addAndGet(accountLeafNode.getValue().getValue().tinybarBalance());
            }
        }
```

**Comment by imalygin** [comment]
The following code

```
        MerkleIterator<MerkleNode> merkleNodeMerkleIterator = accountVm.treeIterator();
        while (merkleNodeMerkleIterator.hasNext()) {
            MerkleNode next = merkleNodeMerkleIterator.next();
            if(next instanceof VirtualLeafNode<?, ?> leafNode) {
                VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>> accountLeafNode  =
                        (VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>>) leafNode;
                paths.add(accountLeafNode.getPath());
            }
        }

        for (Long path : paths) {
            VirtualLeafRecord<EntityNumVirtualKey, OnDiskValue<Account>> record = dataSource.loadLeafRecord(path);
            Account value = record.getValue().getValue();
            totalBalance.addAndGet(value.tinybarBalance());
        }
```        
It fails like this:
```
java.lang.IllegalArgumentException: path (11219999) is not valid; must be in range (5609999,11219998)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:639)
	at com.hedera.statevalidation.validators.servicesstate.TotalHbarSupplyIs_50B.validate(TotalHbarSupplyIs_50B.java:96)
```
on this line
```
Account value = record.getValue().getValue();
```

It means that from the perspective of Merkle tree path `11219999` is still valid, and from the data source perspective it is not




[5:46](https://swirldslabs.slack.com/archives/D04M71E9YT1/p1716587199704119)
so, from the perspective of Merkle tree a node with 11219999 is still valid, but from the data source perspective it is not

**Comment by imalygin** [comment]
The investigation is complete
