### ISSUE TITLE
Remove MerkleOptionalBlob and use BinaryObject to de-risk blob state mgmt during reconnect

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#1347]
**Summary of the defect**
The `MerkleOptionalBlob` class flouts the intended use of `BinaryObject`, ignoring all its new features such as `.update()` and `.append()`, and likely making unnecessary calls to `onRelease()`.

**Comment by Neeharika-Sompalli** [comment]
The following issue caused in [MixedOps-NI-3NReconnect-1.5k-29m](https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619772978128500)  might be resolved after the clean up of this [LOGS](https://app.circleci.com/pipelines/github/hashgraph/hedera-services/13974/workflows/7c287acd-7792-459d-8c3c-d6922ab3d54d/jobs/64296/artifacts)

```
2021-04-30 08:29:53.793 62       INFO  PLATFORM_STATUS  <<       heartbeat 12 14>> SwirldsPlatform: Platform status changed. {"oldStatus":"ACTIVE","newStatus":"DISCONNECTED"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2021-04-30 08:29:53.793 63       INFO  PLATFORM_STATUS  <<       heartbeat 12 14>> SwirldsPlatform: Platform status changed to: DISCONNECTED
2021-04-30 08:30:18.554 64       ERROR EXCEPTION        <<signedStateGarbageCollector 12   >> SignedState: Exception while deleting saved state:
com.swirlds.blob.BinaryObjectException: Failed to delete BinaryObject
	at com.swirlds.blob.BinaryObjectStore.delete(BinaryObjectStore.java:466) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.BinaryObject.onRelease(BinaryObject.java:287) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleLeaf.release(AbstractMerkleLeaf.java:39) ~[swirlds-common-0.9.2.jar:?]
	at com.hedera.services.state.merkle.MerkleOptionalBlob.onRelease(MerkleOptionalBlob.java:197) ~[?:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleLeaf.release(AbstractMerkleLeaf.java:39) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleNode.decrementReferenceCount(AbstractMerkleNode.java:70) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.release(AbstractMerkleInternal.java:165) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.platform.state.SignedState.tryDelete(SignedState.java:407) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.state.SignedStateGarbageCollector.run(SignedStateGarbageCollector.java:92) [swirlds-platform-core-0.9.2.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]

Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30023ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:697) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:196) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.3.1.jar:?]
	at com.swirlds.blob.internal.Utilities.pooledConnection(Utilities.java:260) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.internal.db.DbManager.acquire(DbManager.java:127) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.internal.db.DbManager.blob(DbManager.java:155) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.BinaryObjectStore.delete(BinaryObjectStore.java:459) ~[swirlds-platform-core-0.9.2.jar:?]
	... 39 more
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:885) ~[postgresql-42.2.16.jar:42.2.16]
	at org.postgresql.jdbc.PgConnection.setNetworkTimeout(PgConnection.java:1610) ~[postgresql-42.2.16.jar:42.2.16]
	at com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:552) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:168) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:185) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:161) ~[HikariCP-3.3.1.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100) ~[HikariCP-3.3.1.jar:?]
	at com.swirlds.blob.internal.Utilities.pooledConnection(Utilities.java:260) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.internal.db.DbManager.acquire(DbManager.java:127) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.internal.db.DbManager.blob(DbManager.java:155) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.blob.BinaryObjectStore.delete(BinaryObjectStore.java:459) ~[swirlds-platform-core-0.9.2.jar:?]
```

**Comment by Neeharika-Sompalli** [comment]
Other experiments that can be done to debug the issue, before refactor:
1. Create a test `MixedOps-NI-3NReconnect-1.5k-29m` in which only blob operations are done.
2. This issue always occurs in `MixedOps-NI-3NReconnect-1.5k-29m` immediately after node is `DISCONNECTED`. Check if the `KillNetwork` command is shutting down the postgres database. Run a test with Blobs and manually kill the node.

**Comment by tinker-michaelj** [comment]
Obsolete.
