### ISSUE TITLE
Discrepancy between iteration results using `treeIterator` and valid path range

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#13525]
### Description

This is a follow-up ticket for https://github.com/hashgraph/hedera-services/issues/13468

`Total Supply` validation demonstrated that the result of total supply calculation was incorrect for a couple of rounds. 

### Steps to reproduce

1. Download `171851062` or `171851985` round for any node. 
2. Download [`validator-0.49.jar`](https://console.cloud.google.com/storage/browser/_details/hedera-ci-ephemeral-artifacts/hedera/hedera-state-validator/validator-0.49.jar;tab=live_object)
3. Run `java -jar validator-0.49.jar /path/to/round/171851985 totalSupply`

It will fail with 
```
TotalHbarSupplyIs_50B.validate,validate(DeserializedSignedState, Report) - FAILED
C:\Users\user\IdeaProjects\hedera-state-validator\report.json
org.opentest4j.AssertionFailedError: expected: <5000000000000000000> but was: <4989712725246492199>
```

Now, if you change validator code like this:
```
        AtomicLong totalBalance = new AtomicLong(0L);

        List<Long> paths = new ArrayList<>();

        MerkleIterator<MerkleNode> merkleNodeMerkleIterator = accountVm.treeIterator();
                while (merkleNodeMerkleIterator.hasNext()) {
            MerkleNode next = merkleNodeMerkleIterator.next();
            if(next instanceof VirtualLeafNode<?, ?> leafNode) {
                VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>> accountLeafNode  =
                        (VirtualLeafNode<EntityNumVirtualKey, OnDiskValue<Account>>) leafNode;
                paths.add(accountLeafNode.getPath());
            }
        }

        for (Long path : paths) {
            VirtualLeafRecord<EntityNumVirtualKey, OnDiskValue<Account>> record = dataSource.loadLeafRecord(path);
            Account value = record.getValue().getValue();
            totalBalance.addAndGet(value.tinybarBalance());
        }
```

It will fail with the following exception: 
```
java.lang.IllegalArgumentException: path (11219999) is not valid; must be in range (5609999,11219998)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:639)
	at com.hedera.statevalidation.validators.servicesstate.TotalHbarSupplyIs_50B.validate(TotalHbarSupplyIs_50B.java:96)
```

The size of the valid range is `5609999` and the size of the list with collected paths is `5646753`

### Hedera network

mainnet

### Version

v0.49

### Operating system

None

**Comment by imalygin** [comment]
@artemananiev  clarified that it's incorrect to assume that `dataSource` has all the latest data, and it was sheer luck that we didn't see this issue before. So, we should consider `treeIterator()` as the right way of accessing all the valid entries in `VirtualMap`
