### ISSUE TITLE
NPE and INVALID_EVENT_ERROR in MixedOps-Global-NI-3NReconnect-1.5k-30m

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1356]
**Summary of the defect**
`MixedOps-Global-NI-3NReconnect-1.5k-30m` failed because of an NPE in swirlds.log. Need to look further for root cause

```
021-05-02 07:48:01.121 429      ERROR EXCEPTION        << pollIntakeQueue 14   >> Hashgraph: Error while processing intake event
java.lang.NullPointerException: null
	at com.swirlds.platform.Hashgraph.processIntakeEvent(Hashgraph.java:1048) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.Hashgraph.intakeQueueHandler(Hashgraph.java:1377) ~[swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.common.threading.StoppableThread.run(StoppableThread.java:248) ~[swirlds-common-0.9.2.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

Also there are many `INVALID_EVENT_ERROR` in swirlds.log 

**How to reproduce (if possible)**
slack link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1619942288174200
slack summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1619944421058300

**Comment by Neeharika-Sompalli** [comment]
Related the issue in platform : https://github.com/swirlds/swirlds-platform/issues/3304

**Comment by Neeharika-Sompalli** [comment]
Closed as there is an issue created in platform
