### ISSUE TITLE
MixedOps-NDReconnect-1.5k-25m failure due to corrupt fee schedules in saved state

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1361]
**Summary of the defect**
Randomly few tests fail with corrupt fee schedules like #1357. In `MixedOps-NDReconnect-1.5k-25m` test , only one node failed with the following error while loading saved state, while other nodes did not have this error.

Need to investigate further why this issue happens randomly.

```
2021-05-04 08:32:36.219 ERROR 204  HfsSystemFilesManager - Corrupt fee schedules in saved state, unable to continue!
2021-05-04 08:32:36.219 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#5!
java.lang.IllegalStateException: Could not initialize system files!
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:192) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:150) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:703) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:949) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:343) [swirlds-platform-core-0.9.2.jar:?]
Caused by: java.lang.IllegalStateException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:205) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadProtoWithSupplierFallback(HfsSystemFilesManager.java:244) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFeeSchedules(HfsSystemFilesManager.java:144) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.SystemFilesManager.loadObservableSystemFiles(SystemFilesManager.java:50) ~[HederaNode.jar:?]
	at com.hedera.services.state.logic.NetworkCtxManager.loadObservableSysFilesIfNeeded(NetworkCtxManager.java:85) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:190) ~[HederaNode.jar:?]
	... 5 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1187) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:884) ~[protobuf-java-3.8.0.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.<init>(CurrentAndNextFeeSchedule.java:73) ~[hedera-protobuf-java-api-0.14.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.<init>(CurrentAndNextFeeSchedule.java:13) ~[hedera-protobuf-java-api-0.14.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule$1.parsePartialFrom(CurrentAndNextFeeSchedule.java:866) ~[hedera-protobuf-java-api-0.14.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule$1.parsePartialFrom(CurrentAndNextFeeSchedule.java:860) ~[hedera-protobuf-java-api-0.14.0-SNAPSHOT.jar:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.8.0.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.8.0.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.parseFrom(CurrentAndNextFeeSchedule.java:289) ~[hedera-protobuf-java-api-0.14.0-SNAPSHOT.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:202) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadProtoWithSupplierFallback(HfsSystemFilesManager.java:244) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFeeSchedules(HfsSystemFilesManager.java:144) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.SystemFilesManager.loadObservableSystemFiles(SystemFilesManager.java:50) ~[HederaNode.jar:?]
	at com.hedera.services.state.logic.NetworkCtxManager.loadObservableSysFilesIfNeeded(NetworkCtxManager.java:85) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:190) ~[HederaNode.jar:?]
	... 5 more
```

**How to reproduce (if possible)**
Slack link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620117618225600
Slack summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1620122716062300

Total logs from circleCI : https://app.circleci.com/pipelines/github/hashgraph/hedera-services/14140/workflows/39eaf4d7-f3ee-44ed-9c89-9ae5c487b850/jobs/64782

**Comment by ljianghedera** [comment]
I may find fix for this issue too and testing it.
