### ISSUE TITLE
MixedOps-NI-MultiReconnect-1.5k-39m: reconnect failure when TPS is high 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1367]
**Summary of the defect**
When TPS is high ( > 6K TPS) for this reconnect test,  an error message listed below was observed. Per discussion, this means some severe issue with reconnect feature.

For more details, please look into nodes (2,3,4,5)'s swirlds.log in this results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/01334-D-increase-reconnect-tests-TPS/20210505-175154-GCP-Daily-Comp-Reconnect-6N-1C/MixedOps-NI-MultiReconnect-1.5k-39m?project=hedera-regression&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Also, the slack links may provide some information as well:

slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1620239603256000
summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1620239646064700 

**Service logs (if applicable)**
```

2021-05-05 18:19:34.754 1928     ERROR RECONNECT        <<    syncCaller-0  5   >> ReconnectReceiver: Work Group Exception [ groupName = receiving-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID -7441057967105127907(0x98BC0D340D9BCA1D) (class com.swirlds.common.merkle.synchronization.NodeDataMessage)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:156) ~[swirlds-common-0.9.2.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:149) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:118) [swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.synchronize(ReceivingSynchronizer.java:164) [swirlds-common-0.9.2.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.reconnect(ReconnectReceiver.java:161) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.execute(ReconnectReceiver.java:107) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.SyncCaller.receiveStateFromNeighbor(SyncCaller.java:474) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.SyncCaller.doReconnect(SyncCaller.java:414) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.SyncCaller.callRequestSync(SyncCaller.java:151) [swirlds-platform-core-0.9.2.jar:?]
	at com.swirlds.platform.SyncCaller.run(SyncCaller.java:104) [swirlds-platform-core-0.9.2.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID -7441057967105127907(0x98BC0D340D9BCA1D) (class com.swirlds.common.merkle.synchronization.NodeDataMessage)
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:127) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:100) ~[swirlds-common-0.9.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.io.IOException: Error while reading child hashes for node with class ID 1953444780092841751(0x1B1C07AD7DC65F17), class name 'com.swirlds.fcmap.internal.FCMInternalNode'
	at com.swirlds.common.merkle.synchronization.NodeDataMessage.deserialize(NodeDataMessage.java:133) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:120) ~[swirlds-common-0.9.2.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:100) ~[swirlds-common-0.9.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more

...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
From the repeating running results of yesterday afternoon to now, we don't observe any single occurance of disconnected node didn't reconnect after the settings change. `reconnect.asyncInputStreamTimeoutMilliseconds, 60000`.

We were using test `MixedOps-NIReconnect-1.5k-25m` which also was failed before after increasing the TPS to 6K.

And here are the stats for these repeat run results:
1. It takes 15~20 seconds to finish the reconnect completely (The sender and receiver both from reconnect start to reconnect finish);

2. For these test, we have done roughly the following during while one node is down, which is approximately 18 minutes before it's reconnected:
   - created total of 80000 crypto accounts;
   - created total 80,000 topics;
   - created max of 4,000 files;
   - created max of 80000 scheduled transfers;

**Comment by ljianghedera** [comment]
Per Nosh's request, also repeated the same test with `MixedOps-NI-MultiReconnect-6k-39m` test. The differences of this test configuration from `MixedOps-NIReconnect-1.5k-25m` are:
1. It started from a state with the following entities:
    - 1M crypto accounts;
    - 1.1 M topics;
    - 1.2 M token associations; 
    - 103 tokens;
    - 1000 scheduled jobs;
2. It reconnect twice;

So far we have three runs and the disconnected node always get reconnected and become `ACTIVE`.

And here are the stats for these test results:
1. It takes ~33 seconds to finish first reconnect and it takes ~8 seconds to finish second reconnect;
2. The disconnected node was down for ~22 minutes:
   - created total of 80,000 crypto accounts;
   - created total 80,000 topics;
   - created max of 4,000 files;
   - created max of 80,000 scheduled transfers;
   - ~6M transfer and submit message transactions;
