### ISSUE TITLE
Create data migration prototype

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#14504]
There are several possible approaches to the data migration from multiple VMs into a single Virtual Mega Map. This can be as simple as migrating all the data on upgrade. Alternatively, we can migrate the biggest VMs (token relations, accounts, smart contracts) separately—one per release. Or there are more complex approaches that take care of migration while the node is running.

These approaches have pros and cons. Ideally, we want to go with the simplest one, but first, we need to make sure that the data migration doesn't take too much time. Otherwise, it's not going to be feasible. To make a choice, we need a better understanding of how much time exactly it's going to take.

To gather this information, we should have a tool that simulates the migration. That is, it should create a map that stores byte arrays as keys and values, and then traverse all existing maps, put all the key-value pairs in this one big map, and measure the time this operation takes.

For these purposes we can use infrastructure that the state validation tool provides. This data migration prototype can be implemented as yet another validation.

**Comment by jasperpotts** [comment]
Crazy idea but if most of the data is in virtual maps already. Can we just collect the superset of all data files that exist and build new indexes pointing to existing data. I guess issue is keys will be different. Food for thought.

**Comment by artemananiev** [comment]
Data migration prototype from branch `14504-create-data-migration-prototype-0.54` fails against the latest mainnet state with the following error:

```
DataMigration.validate,validate(DeserializedSignedState) - FAILED, time taken - 5 sec 
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [com.swirlds.platform.state.snapshot.DeserializedSignedState arg0] in method [void com.hedera.statevalidation.validators.merkledb.DataMigration.validate(com.swirlds.platform.state.snapshot.DeserializedSignedState) throws java.io.IOException]: Failed to read snapshot file /home/alex.kuzmin/workspaces/hedera-state-validator/188451903/SignedState.swh
	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameter(ParameterResolutionUtils.java:159)
        ...
Caused by: com.swirlds.common.io.exceptions.ClassNotFoundException: No class with id=-167811826542867083(0xFDABD00869CD8D75) found
	at com.swirlds.common.io.streams.SerializableDataInputStream.registryConstructor(SerializableDataInputStream.java:569)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:198)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:102)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.deserialize(VirtualRootNode.java:1284)
	at com.swirlds.virtualmap.VirtualMap.lambda$loadFromFile$1(VirtualMap.java:375)
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82)
	at com.swirlds.virtualmap.VirtualMap.loadFromFile(VirtualMap.java:370)
	at com.swirlds.virtualmap.VirtualMap.deserialize(VirtualMap.java:351)
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingInternal(MerkleDataInputStream.java:113)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:170)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230)
	at com.swirlds.platform.state.snapshot.SignedStateFileUtils.readState(SignedStateFileUtils.java:64)
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.lambda$readStateFile$1(SignedStateFileReader.java:101)
	... 65 more
```

**Comment by thenswan** [comment]
**Results**
`mainnet` round: 188451903
Migration time: 205557 ms
