### ISSUE TITLE
File-Recovery-EvSave15s-5-21m  and Crypto-Recovery-EvSave15s-300-21m failed with 0.15.0-alpha.1 sdk

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#1510]
`File-Recovery-EvSave15s-5-21m` and `Crypto-Recovery-EvSave15s-300-21m ` failed with `SleepCheckException` and `Exception java.util.NoSuchElementException appeared 2 times.` in `ErrorValidator`

Slack Link : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622536123159000 , https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622534822157800
Slack Summary link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1622538366033700

**Comment by abhishek-hedera** [comment]
Error messages for `File-Recovery-EvSave15s-5-21m` on `master-plus-sdk-0.15.0-alpha.1`

```
com.swirlds.regression.testcontrol.SleepCheckException: Sleep check failed: CountMessages
    at com.swirlds.regression.testcontrol.SleepCheck.sleepEnds(SleepCheck.java:102)
    at com.swirlds.regression.testcontrol.ControlCenter.sleep(ControlCenter.java:181)
    at com.swirlds.regression.testRunners.RecoverStateRun.sleepAndSearch(RecoverStateRun.java:258)
    at com.swirlds.regression.testRunners.RecoverStateRun.resumeStepRun(RecoverStateRun.java:246)
    at com.swirlds.regression.testRunners.RecoverStateRun.runTest(RecoverStateRun.java:100)
    at com.swirlds.regression.testRunners.ServiceRecoverStateRun.runTest(ServiceRecoverStateRun.java:36)
    at com.swirlds.regression.Experiment.runRemoteExperiment(Experiment.java:1066)
    at com.swirlds.regression.RegressionMain.runExperiments(RegressionMain.java:274)
    at com.swirlds.regression.RegressionMain.RunCloudExperiment(RegressionMain.java:148)
    at com.swirlds.regression.RegressionMain.RunRegression(RegressionMain.java:120)
    at com.swirlds.regression.RegressionMain.main(RegressionMain.java:537)

---- ErrorValidator FAILED validation ----
(Node 0) Marker EXCEPTION appeared 17 times.
(Node 0) Exception java.util.NoSuchElementException appeared 2 times.
(Node 1) Marker EXCEPTION appeared 17 times.
(Node 1) Exception java.util.NoSuchElementException appeared 2 times.
(Node 2) Marker EXCEPTION appeared 17 times.
(Node 2) Exception java.util.NoSuchElementException appeared 2 times.
(Node 3) Marker EXCEPTION appeared 17 times.
(Node 3) Exception java.util.NoSuchElementException appeared 2 times.

---- ServiceRecoverStateValidator FAILED validation ----
<<ERROR>>
(node 0) unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state SECOND_RUN_STARTED
(node 1) unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state SECOND_RUN_STARTED
(node 2) unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state SECOND_RUN_STARTED
(node 3) unexpected payload com.swirlds.logging.payloads.NodeStartPayload encountered while in state SECOND_RUN_STARTED
<<INFO>>
Node 0 message encountered in logs are:
Node 0 com.swirlds.logging.payloads.NodeStartPayload
Node 0 com.swirlds.logging.payloads.PlatformStatusPayload
Node 0 com.swirlds.logging.payloads.PlatformStatusPayload
Node 0 com.swirlds.logging.payloads.PlatformStatusPayload
Node 0 com.swirlds.logging.payloads.NodeStartPayload
Node 0 com.swirlds.logging.payloads.NodeStartPayload
Node 1 message encountered in logs are:
Node 1 com.swirlds.logging.payloads.NodeStartPayload
Node 1 com.swirlds.logging.payloads.PlatformStatusPayload
Node 1 com.swirlds.logging.payloads.PlatformStatusPayload
Node 1 com.swirlds.logging.payloads.PlatformStatusPayload
Node 1 com.swirlds.logging.payloads.NodeStartPayload
Node 1 com.swirlds.logging.payloads.NodeStartPayload
Node 2 message encountered in logs are:
Node 2 com.swirlds.logging.payloads.NodeStartPayload
Node 2 com.swirlds.logging.payloads.PlatformStatusPayload
Node 2 com.swirlds.logging.payloads.PlatformStatusPayload
Node 2 com.swirlds.logging.payloads.PlatformStatusPayload
Node 2 com.swirlds.logging.payloads.NodeStartPayload
Node 2 com.swirlds.logging.payloads.NodeStartPayload
Node 3 message encountered in logs are:
Node 3 com.swirlds.logging.payloads.NodeStartPayload
Node 3 com.swirlds.logging.payloads.PlatformStatusPayload
Node 3 com.swirlds.logging.payloads.PlatformStatusPayload
Node 3 com.swirlds.logging.payloads.PlatformStatusPayload
Node 3 com.swirlds.logging.payloads.NodeStartPayload
Node 3 com.swirlds.logging.payloads.NodeStartPayload

---- StreamSimpleValidator FAILED validation ----
No sha1sum found for server 0, and no records were recorded!
No sha1sum found for server 1, and no records were recorded!
No sha1sum found for server 2, and no records were recorded!
No sha1sum found for server 3, and no records were recorded!
```

**Comment by abhishek-hedera** [comment]
Closing this as running tests on [master-plus-sdk-0.15.0](https://github.com/hashgraph/hedera-services/tree/master-plus-sdk-0.15.0) doesn't cause any failures.

Passing Tests:
File-Recovery-EvSave15s-5-21m
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1623089689387400
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622967930352700

Crypto-Recovery-EvSave15s-300-21m
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1623091049387800
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1622966814351100
