### ISSUE TITLE
add retries of port bind for GRPC ports

### ISSUE THREAD

**Issue by tannerjfco** [hashgraph/hedera-services#1523]
**Summary of the defect**
GRPC ports configured for 50211 Non-TLS and 50212 TLS sporadically fail to bind on application start, resulting in the application terminating. These ports are likely failing to bind because they are in the ephemeral port range. However, it appears that the port binds for GRPC may not include any logic to retry, as they appear to attempt to bind and fail almost immediately

Note that the gossip port is also configured to use a port in the ephemeral range at 50111, however platform includes logic to retry the port bind until it is successful. As a result, we do not see these issues on binding the gossip port

Long-term a solution could be to use ports outside the ephemeral range, however this would be a change that requires lots of coordination and implications to many parties. If such a change is possible it will be a long time before it can be made

In the more immediate term, it would be best to retry binding the GRPC ports until they are able to successfully bind

**How to reproduce (if possible)**
Issue exhibits sporadically when services is started. On a network of just about any size it often exhibits with just one or two nodes out of the network failing to bind the GRPC ports

**Service logs (if applicable)**
```
2021-06-02 22:31:34.306 INFO  151  ServicesMain - System files rationalized.
2021-06-02 22:31:34.314 INFO  105  BackedSystemAccountsCreator - Ledger float is 5000000000000000000 tinyBars in 228 accounts.
2021-06-02 22:31:34.314 INFO  153  ServicesMain - System accounts initialized.
2021-06-02 22:31:34.314 INFO  155  ServicesMain - Migrations complete.
2021-06-02 22:31:34.357 INFO  157  ServicesMain - Ledger state ok.
2021-06-02 22:31:34.357 INFO  159  ServicesMain - Platform is configured.
2021-06-02 22:31:34.362 INFO  161  ServicesMain - Platform callbacks registered.
2021-06-02 22:31:34.364 INFO  163  ServicesMain - ReconnectCompleteListener registered.
2021-06-02 22:31:34.364 INFO  165  ServicesMain - Accounts exported.
2021-06-02 22:31:34.380 INFO  167  ServicesMain - Stats initialized.
2021-06-02 22:31:34.380 INFO  209  ServicesMain - TLS is turned on by default on node 4
2021-06-02 22:31:34.380 INFO  211  ServicesMain - Active profile: PROD
2021-06-02 22:31:34.522 INFO  260  ServicesMain - Starting Netty on port 50211...
2021-06-02 22:31:34.522 INFO  65   ConfigDrivenNettyFactory - Configuring a Netty server on port 50211 (TLS OFF) for TEST environment
2021-06-02 22:31:34.806 INFO  260  ServicesMain - ...done starting Netty on port 50211.
2021-06-02 22:31:34.807 INFO  260  ServicesMain - Starting Netty with TLS support on port 50212...
2021-06-02 22:31:34.807 INFO  65   ConfigDrivenNettyFactory - Configuring a Netty server on port 50212 (TLS ON) for TEST environment
2021-06-02 22:31:35.079 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#4!
java.lang.IllegalStateException: java.io.IOException: Failed to bind
        at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:72) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HGCApp.jar:?]
        at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HGCApp.jar:?]
        at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:867) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
        at com.swirlds.platform.Browser.startPlatforms(Browser.java:978) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
        at com.swirlds.platform.Browser.main(Browser.java:360) [swirlds-platform-core-0.15.0-alpha.1.jar:?]
Caused by: java.io.IOException: Failed to bind
        at io.grpc.netty.NettyServer.start(NettyServer.java:264) ~[grpc-netty-1.33.0.jar:1.33.0]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:183) ~[grpc-core-1.33.0.jar:1.33.0]
        at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.33.0.jar:1.33.0]
        at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:83) ~[HGCApp.jar:?]
        at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:65) ~[HGCApp.jar:?]
        ... 6 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2021-06-02 22:31:35.085 INFO  260  ServicesMain - Terminating Netty on port 50211...
```

**Environment:**
- OS: Exhibited on any Linux OS hedera-services has been run on 
- Java: OpenJDK 12.0.1
- Hedera Services Version: current stable v0.14.0, current bleeding edge builds, indefinite previous releases

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by steven-sheehy** [comment]
Wouldn't the easy solution be to just use different ports outside the range for the Java process but keep the existing 50211 port for the proxy? No one should be able to go direct to the java process these days.

**Comment by jsindy** [comment]
This has been a thorn in our side for a very long time. Retry logic would be very much appreciated.

**Comment by tannerjfco** [comment]
> Wouldn't the easy solution be to just use different ports outside the range for the Java process but keep the existing 50211 port for the proxy? No one should be able to go direct to the java process these days.

This would certainly be a good solution but not necessarily the easiest and definitely not the most expedient. Any change to our network port requirements for node operators would require amendment of the agreement and likely approval of that amendment. After that, we would need a coordinated process to get all node operators to open the new ports, switch to those ports on a release window once everyone has the new ports open, and then coordinate to close the old ports. That doesn't mean this isn't worth exploring, I think it is and intend to, but retry logic for the port binding on grpc similar to what is done with gossip would be a useful improvement to make either way and resolve the pain point a lot sooner than changing ports

**Comment by tinker-michaelj** [comment]
@tannerjfco @jsindy @nathanklick 

Opened https://github.com/hashgraph/hedera-services/pull/1531; what do you think of the defaults to,
- Retry starting Netty once per second; and,
- Up to 30 times?

Note that these retries will block `SwirldMain.init()`.

**Comment by nathanklick** [comment]
@tinker-michaelj I would maybe suggest changing the wait time to support milliseconds so that devops has more flexibility it tuning the values.

**Comment by tinker-michaelj** [comment]
> @tinker-michaelj I would maybe suggest changing the wait time to support milliseconds so that devops has more flexibility in tuning the values.

@nathanklick Makes sense, updated to `netty.startRetryIntervalMs=1000`. 👍
