### ISSUE TITLE
Unable to get `PlatformStateAccessor` due to race condition

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#15385]
### Description

In some cases `MerkleStateRoot.getPlatformState` fails with the following exception

```
node0	14m 50.100s	ERROR	AbstractTaskSchedulerBuilder:	Uncaught exception in scheduler ConsensusEventStream
com.swirlds.base.state.MutabilityException: This operation is not permitted on an immutable object.
	at com.swirlds.base.state.Mutable.throwIfImmutable(Mutable.java:55) ~[swirlds-base-0.54.0.jar:?]
	at com.swirlds.base.state.Mutable.throwIfImmutable(Mutable.java:46) ~[swirlds-base-0.54.0.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.getWritableStates(MerkleStateRoot.java:354) ~[swirlds-platform-core-0.54.0.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.writablePlatformStateStore(MerkleStateRoot.java:1034) ~[swirlds-platform-core-0.54.0.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.getPlatformState(MerkleStateRoot.java:1004) ~[swirlds-platform-core-0.54.0.jar:?]
	at com.swirlds.platform.state.SwirldStateManager.isInFreezePeriod(SwirldStateManager.java:216) ~[swirlds-platform-core-0.54.0.jar:?]
	at com.swirlds.platform.builder.PlatformComponentBuilder.lambda$buildConsensusEventStream$2(PlatformComponentBuilder.java:591) ~[swirlds-platform-core-0.54.0.jar:?]
	at com.swirlds.platform.event.stream.DefaultConsensusEventStream.lambda$addEvents$0(DefaultConsensusEventStream.java:225) ~[swirlds-platform-core-0.54.0.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
```

This happens despite the fact that `getPlatformState` is implemented as follows:
```
    @Override
    public PlatformStateAccessor getPlatformState() {
        return !isImmutable() ? writablePlatformStateStore() : readablePlatformStateStore();
    }
```

This exception suggests that the state was updated to be immutable by some other state. In this particular case, it doesn't even have to be writable because ultimately, we only need to read two parameters: `platformState.getFreezeTime()` and `platformState.getLastFrozenTime()`.

To fix this, we need to use the read-only State API where possible instead of accessing it via the ambiguous `PlatformStateAccessor`.

### Steps to reproduce

This test can be reproduced with `Crypto-Update-Jar-1.5k-25m`.

### Hedera network

other

### Version

v0.54

### Operating system

None

**Comment by poulok** [comment]
I believe I found the root cause of this exception.

`SwirldStateManager.isInFreezePeriod()` calls `getPlatformState()` which returns a writable version if an immutability check indicates the state is mutable:

```
    @Override
    public PlatformStateAccessor getPlatformState() {
        return !isImmutable() ? writablePlatformStateStore() : readablePlatformStateStore();
    }
```

However, this method is not thread safe. The check to `isImmutable()` could return `false`, and before the call to `writablePlatformStateStore()` the can be copied and become immutable. The two threads involved that cause this to happen are the handle thread which creates the fast copy of the state causing it to go from mutable to immutable, and the consensus event stream thread. `DefaultConsensusEventStream.addEvent()` contains a lamba reference to `SwirldStateManager.isInFreezePeriod()` via `isLastEventInFreezeCheck`. The handle thread creates a copy at the same time the consensus event stream thread is trying to get a copy to check the freeze time. This is the race condition.

@imalygin's [PR](https://github.com/hashgraph/hedera-services/pull/15389) solves the race condition by changing the access to the state in `SwirldStateManager.isInFreezePeriod()` to always use the readable platform state.
