### ISSUE TITLE
Investigate the occasional NPE error for reconnect JRS 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1559]
**Summary of the defect**

In this JRS reconnect test, the reconnecting node has the error while doing periodic balance exporting:

```
2021-06-08 09:50:41.668 133   ERROR EXCEPTION    <<platform-core: newSignedState 5 #0>> NewSignedStateRunnable: Exception in NewSignedStateRunnable
java.lang.NullPointerException: null
    at com.hedera.services.ServicesState.getNodeAccountId(ServicesState.java:325) ~[?:?]
    at com.hedera.services.state.exports.SignedStateBalancesExporter.exportBalancesFrom(SignedStateBalancesExporter.java:132) ~[?:?]
    at com.hedera.services.ServicesMain.newSignedState(ServicesMain.java:131) ~[?:?]
    at com.swirlds.platform.state.NewSignedStateRunnable.run(NewSignedStateRunnable.java:46) [swirlds-platform-core-0.15.0-alpha.2.jar:?]
    at java.lang.Thread.run(Thread.java:835) [?:?]
```

Right now this is presumably caused by race condition. We should likely try making both ServicesState#init() and ServicesState#getNodeAccountId() methods synchronized.

**How to reproduce (if possible)**

The failure slack link https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1623146316415700 

And the results URL: https://console.cloud.google.com/storage/browser/_details/hedera-services-jrs-test-results/hedera-services-automation/master-plus-sdk-0.15.0/20210608-073255-GCP-Daily-Reconnect-Correctness-6N-1C/ScheduleExpiry-NIReconnect-1-16m/node0005/swirlds.log?authuser=3

**Service logs (if applicable)**
In node 5 (the reconnecting node)'s swirlds.log:

```
...
2021-06-08 09:50:28.736 127      DEBUG RECONNECT        <<platform-core: syncCaller-0 5 #0>> SyncCaller: locked platform[5].syncServer.lockCallListen[0]
2021-06-08 09:50:28.737 128      DEBUG RECONNECT        <<node-sync: node-sync ? #10>> NodeSynchronizerImpl: 5 -> 0: `receiveSyncRequestResponse`: received COMM_SYNC_ACK
2021-06-08 09:50:28.737 129      DEBUG RECONNECT        <<node-sync: node-sync ? #10>> NodeSynchronizerImpl: 5 -> 0: `receiveSyncRequestResponse`: request accepted
2021-06-08 09:50:28.745 130      DEBUG RECONNECT        <<platform-core: syncCaller-0 5 #0>> SyncCaller: `callRequestSync` : 5 synced with 0 ? true
2021-06-08 09:50:28.745 131      DEBUG RECONNECT        <<platform-core: syncCaller-0 5 #0>> SyncCaller: SyncCaller unlocked platform[5].syncServer.lockCallHeartbeat[0]
2021-06-08 09:50:28.745 132      DEBUG RECONNECT        <<platform-core: syncCaller-0 5 #0>> SyncCaller: SyncCaller unlocked platform[5].syncServer.lockCallListen[0]
2021-06-08 09:50:41.668 133      ERROR EXCEPTION        <<platform-core: newSignedState 5 #0>> NewSignedStateRunnable: Exception in NewSignedStateRunnable
java.lang.NullPointerException: null
	at com.hedera.services.ServicesState.getNodeAccountId(ServicesState.java:325) ~[?:?]
	at com.hedera.services.state.exports.SignedStateBalancesExporter.exportBalancesFrom(SignedStateBalancesExporter.java:132) ~[?:?]
	at com.hedera.services.ServicesMain.newSignedState(ServicesMain.java:131) ~[?:?]
	at com.swirlds.platform.state.NewSignedStateRunnable.run(NewSignedStateRunnable.java:46) [swirlds-platform-core-0.15.0-alpha.2.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-06-08 09:51:40.366 134      INFO  STATE_TO_DISK    <<platform-core: objectFileManager 5 #0>> SignedStateFileManager: Started writing 'Signed state for round 3207' to disk
2021-06-08 09:51:40.367 135      DEBUG SNAPSHOT_MANAGER <<platform-core: objectFileManager 5 #0>> SnapshotManager: SnapshotManager: Successfully queued snapshot request [taskType='BACKUP', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=5, roundNumber=3207, snapshotId=00000003-000000CE-1, timeStarted=2021-06-08T09:51:40.366810Z, timeCompleted=null, complete=false, error=false ]
...

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Some other place with this exception:

```
2021-06-05 07:07:01.262 62       ERROR EXCEPTION        <<platform-core: newSignedState 5 #0>> NewSignedStateRunnable: Exception in NewSignedStateRunnable
java.lang.NullPointerException: null
	at com.hedera.services.state.exports.SignedStateBalancesExporter.addTokenBalances(SignedStateBalancesExporter.java:310) ~[?:?]
	at com.hedera.services.state.exports.SignedStateBalancesExporter.summarized(SignedStateBalancesExporter.java:289) ~[?:?]
	at com.hedera.services.state.exports.SignedStateBalancesExporter.exportBalancesFrom(SignedStateBalancesExporter.java:136) ~[?:?]
	at com.hedera.services.ServicesMain.newSignedState(ServicesMain.java:131) ~[?:?]
	at com.swirlds.platform.state.NewSignedStateRunnable.run(NewSignedStateRunnable.java:46) [swirlds-platform-core-0.15.0-alpha.2.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-06-05 07:08:01.448 63       ERROR EXCEPTION        <<platform-core: newSignedState 5 #0>> NewSignedStateRunnable: Exception in NewSignedStateRunnable
java.lang.NullPointerException: null

```

**Comment by ljianghedera** [comment]
This not specific to 0.15.0 branch. It also has happened to master and other branches occasionally as well. As we're not clear what's the root causes and can't reproduce it easily, I will move it to 0.16.0 to continue investigating it without blocking 0.15.0 release.
