### ISSUE TITLE
Migration script perf test

### ISSUE THREAD

**Issue by alex-kuzmin-hg** [hashgraph/hedera-services#16097]
Per Artem's and Nikita's (nikita.lebedev@limechain.tech) request
To add details...

**Comment by alex-kuzmin-hg** [comment]
Reported blocking issue:
```
Caused by: java.io.IOException: Failed to read snapshot file /home/alex.kuzmin/workspaces/hedera-state-validator/188451903/SignedState.swh
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.lambda$readStateFile$1(SignedStateFileReader.java:106)
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82)
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.readStateFile(SignedStateFileReader.java:93)
	at com.hedera.statevalidation.parameterresolver.StateResolver.readState(StateResolver.java:94)
	at com.hedera.statevalidation.parameterresolver.StateResolver.resolveParameter(StateResolver.java:88)
	at com.hedera.statevalidation.parameterresolver.StateResolver.resolveParameter(StateResolver.java:69)
	at org.junit.jupiter.engine.execution.ParameterResolutionUtils.resolveParameter(ParameterResolutionUtils.java:136)
	... 59 more
Caused by: com.swirlds.common.io.exceptions.ClassNotFoundException: No class with id=-167811826542867083(0xFDABD00869CD8D75) found
	at com.swirlds.common.io.streams.SerializableDataInputStream.registryConstructor(SerializableDataInputStream.java:569)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:198)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:102)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.deserialize(VirtualRootNode.java:1284)
	at com.swirlds.virtualmap.VirtualMap.lambda$loadFromFile$1(VirtualMap.java:375)
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82)
	at com.swirlds.virtualmap.VirtualMap.loadFromFile(VirtualMap.java:370)
	at com.swirlds.virtualmap.VirtualMap.deserialize(VirtualMap.java:351)
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingInternal(MerkleDataInputStream.java:113)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:170)
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230)
	at com.swirlds.platform.state.snapshot.SignedStateFileUtils.readState(SignedStateFileUtils.java:64)
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.lambda$readStateFile$1(SignedStateFileReader.java:101)
	... 65 more
/home/alex.kuzmin/workspaces/hedera-state-validator/validator/build/libs/report.json
```

Per Artem, waiting for fix to restart testing

**Comment by alex-kuzmin-hg** [comment]
Bug : https://github.com/hashgraph/hedera-services/issues/14504

**Comment by alex-kuzmin-hg** [comment]
unblocked developers:

added ssh access to user nikita.lebedev
as user nikita.lebedev:
```
cd ~/workspaces/hedera-state-validator.fromAlex/validator/build/libs
sh ../../runHDHM.sh
```


I'll re-run final perf numbers/functionality as soon as bugs fixed in that branch

**Comment by alex-kuzmin-hg** [comment]
Per Nikita, Done. My pleasure.
Parent tasks:
https://github.com/hashgraph/hedera-services/issues/14504
