### ISSUE TITLE
Master branch's File-Recovery-EvSave15sTrunc-5-21m failed due to server node can't restart from recovering: missing generation for round -23

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1634]
**Summary of the defect**
Need to investigate why server node 0 missed generation of certain round during recovering.

**How to reproduce (if possible)**
Master branch's slack report: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624265984401700
results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210621-070255-GCP-Daily-Recovery-4N-1C/File-Recovery-EvSave15sTrunc-5-21m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**

Client node 0's hapi-client-combined.log indicates that server node 0 couldn't be reached after some normal run:
```
...
2021-06-21 08:53:19.171 INFO   143  HapiApiClients - Constructed 18 new stubs building clients for HapiApiClients{node0=NodeConnectInfo{host=35.230.42.34, port=50211, tlsPort=50212, account=0.0.3}, default=0.0.3}
2021-06-21 08:53:19.454 ERROR  253  HapiApiSpec - Fees failed to initialize! Please check if server is down...
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[SuiteRunner.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[SuiteRunner.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[SuiteRunner.jar:?]
	at com.hederahashgraph.service.proto.java.FileServiceGrpc$FileServiceBlockingStub.getFileContent(FileServiceGrpc.java:647) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:176) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.lookupDownloadFee(FeesAndRatesProvider.java:160) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:134) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:94) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.tryReinitializingFees(HapiApiSpec.java:247) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:270) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:219) [SuiteRunner.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1799) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /35.230.42.34:50211
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[SuiteRunner.jar:?]
...

```

And this is caused by server node 0's swirld.log shows it's missing generation for round-23:
```
2021-06-21 08:47:37.797 27       DEBUG STARTUP          <main> SwirldsPlatform: Platform has loaded a saved state {"round":2,"consensusTimestamp":{"nano":368395000,"epochSecond":1624264912},"willFreezeUntil":{"nano":785643000,"epochSecond":1624265267}} [com.swirlds.logging.payloads.SavedStateLoadedPayload]
2021-06-21 08:47:37.802 28       ERROR EXCEPTION        <main> Browser: 
java.util.NoSuchElementException: Missing generation for round -23
	at com.swirlds.platform.eventhandling.MinGenQueue.getRoundGeneration(MinGenQueue.java:92) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.EventFlow.loadDataFromSignedState(EventFlow.java:529) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.buildEventFlow(SwirldsPlatform.java:907) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:777) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.15.1.jar:?]
2021-06-21 08:47:37.809 29       DEBUG STARTUP          <main> Browser: main() finished
2021-06-21 08:51:45.878 1        DEBUG STARTUP          <main> Browser: main() started {} [com.swirlds.logging.payloads.NodeStartPayload]
2021-06-21 08:51:45.938 2        DEBUG STARTUP          <main> Browser: About to run startPlatforms()

...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Tested and likely be fixed by `regression` PR: https://github.com/swirlds/swirlds-platform-regression/pull/1278.
