### ISSUE TITLE
0.15 branch's File-Recovery-EvSave15sTrunc-5-21m failed probably due to timing issue.

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1636]
**Summary of the defect**
This seems to be a timing issue. While server node is already in `MAINTENANCE` state, but client still tries to send request to it, hence it gets `PLATFORM_NOT_ACIVE` error. Please refer to the log messages below.

Need to investigate why this is happening.

**How to reproduce (if possible)**

Slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624265355399200

Test results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/release/0.15/20210621-065724-GCP-Daily-Recovery-4N-1C/File-Recovery-EvSave15sTrunc-5-21m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**

Server node 0's swirld.log says it's already in `MAINTENANCE` state at `2021-06-21 08:46:37.091 53`.

```
021-06-21 08:46:37.091 51       INFO  FREEZE           <<platform-core: event-intake 0 #0>> FreezeManager: Event creation frozen in platform 0
2021-06-21 08:46:37.091 52       INFO  PLATFORM_STATUS  <<platform-core: event-intake 0 #0>> SwirldsPlatform: Platform status changed. {"oldStatus":"ACTIVE","newStatus":"MAINTENANCE"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2021-06-21 08:46:37.091 53       INFO  PLATFORM_STATUS  <<platform-core: event-intake 0 #0>> SwirldsPlatform: Platform status changed to: MAINTENANCE
2021-06-21 08:46:37.100 54       INFO  FREEZE           <<platform-core: event-intake 0 #0>> TimestampStreamFileWriter: TimestampStreamFileWriter finished writing the last object, is stopped
2021-06-21 08:46:37.117 55       INFO  STATE_TO_DISK    <<platform-core: objectFileManager 0 #0>> SignedStateFileManager: Done writing saved state with HashEventsCons 985e5c506b07a7cf06f7727e4433bf846b852edfaf626e26fde852f553683426d4a261d82e4041338b0c1a9db8ddcc5e, starting with local events
2021-06-21 08:46:37.119 56       INFO  STATE_TO_DISK    <<platform-core: objectFileManager 0 #0>> SignedStateFileManager: 'Signed state for round 1841' waiting for snapshotTask
2021-06-21 08:46:37.272 57       DEBUG SNAPSHOT_MANAGER << SnapshotManager >> SnapshotManager: SnapshotManager: Process successfully executed for snapshot task [taskType='BACKUP', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=0, roundNumber=1841, snapshotId=00000003-000010A7-1, timeStarted=2021-06-21T08:46:37.084615Z, timeCompleted=null, complete=false, error=false ] 
2021-06-21 08:46:37.273 58       INFO  SNAPSHOT_MANAGER << SnapshotManager >> SnapshotManager: SnapshotManager: Completed task [taskType='BACKUP', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=0, roundNumber=1841, snapshotId=00000003-000010A7-1, timeStarted=2021-06-21T08:46:37.084615Z, timeCompleted=2021-06-21T08:46:37.273081Z, complete=true, error=false ]
2021-06-21 08:46:37.274 59       INFO  STATE_TO_DISK    <<platform-core: objectFileManager 0 #0>> SignedStateFileManager: Finished writing 'Signed state for round 1841' to disk

...
```

Client node 0 still sends cryptoTransfer request to server node 0:

```
"\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\021\005*\261\303\367\0220h\232&\231\217\001\235(\237W\246?\226\273\362\v\3348pc\021\213\a\327Z\244\362IR/|`\313hG\377\246`\353\374&6\330\'{0\023\373C;\240\372\247\201_\004" } got status PLATFORM_NOT_ACTIVE, retrying...
2021-06-21 08:48:00.956 ERROR  253  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status PLATFORM_NOT_ACTIVE
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:189) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:135) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:94) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.tryReinitializingFees(HapiApiSpec.java:247) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:270) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:219) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:255) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:146) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:139) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:596) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:597) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:571) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:571) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:539) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:460) [SuiteRunner.jar:?]
2021-06-21 08:48:00.957 INFO   174  FileUpdateLoadTest - -------------- RESULTS OF FileUpdateLoadTest SUITE --------------
2021-06-21 08:48:00.957 INFO   176  FileUpdateLoadTest - Spec{name=RunFileUpdates, status=ERROR}


```

**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
After further testing, the reason the server node stays in `MAINTENANCE` status is that the saved state file has too few rounds before restart, which triggers the error `missing generation for round -nnn`.

Tested and likely be fixed by `regression` PR: https://github.com/swirlds/swirlds-platform-regression/pull/1278
