### ISSUE TITLE
Crypto-Restart-RecordStreamV5-1.5k-10m failed due to NPE in SystemTransactionHandler

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1638]
**Summary of the defect**
Platform get NPE exception while processing transaction: `SYS_TRANS_STATE_SIG_FREEZE`.

This happens to both 0.15 and master branch.

**How to reproduce (if possible)**

0.15 branch slack report: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624258734388400

Master branch slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624258474388000

master branch results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210621-062319-GCP-Daily-Crypto-Restart-4N-1C/Crypto-Restart-RecordStreamV5-1.5k-10m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**
The following error occurred to all 4 server node's swirld.log:

```
...
2021-06-21 06:42:59.028 33       INFO  FREEZE           <<platform-core: event-intake 3 #0>> TimestampStreamFileWriter: TimestampStreamFileWriter finished writing the last object, is stopped
2021-06-21 06:42:59.048 34       ERROR EXCEPTION        <<platform-core: event-intake 3 #0>> SystemTransactionHandler: Error while handling transaction: kind SYS_TRANS_STATE_SIG_FREEZE id 1 isConsensus false transaction com.swirlds.common.transaction.internal.StateSignatureTransaction@12ebf0c3 error
java.lang.NullPointerException: null
	at com.swirlds.platform.state.SignedStateManager.addSigInfo(SignedStateManager.java:755) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.state.SignedStateManager.recordStateSig(SignedStateManager.java:672) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.components.SystemTransactionHandler.handleSystemTransaction(SystemTransactionHandler.java:101) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.components.SystemTransactionHandler.preConsensusEvent(SystemTransactionHandler.java:139) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.observers.EventObserverDispatcher.preConsensusEvent(EventObserverDispatcher.java:119) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.components.EventIntake.addEvent(EventIntake.java:109) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.EventValidator.validateEvent(EventValidator.java:255) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.components.EventTaskDispatcher.validateEvent(EventTaskDispatcher.java:99) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.components.EventTaskDispatcher.dispatchTask(EventTaskDispatcher.java:77) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.common.threading.QueueThread.waitForWork(QueueThread.java:204) ~[swirlds-common-0.15.1.jar:?]
	at com.swirlds.common.threading.QueueThread.doWork(QueueThread.java:184) ~[swirlds-common-0.15.1.jar:?]
	at com.swirlds.common.threading.StoppableThread.doWork(StoppableThread.java:255) ~[swirlds-common-0.15.1.jar:?]
	at com.swirlds.common.threading.StoppableThread.run(StoppableThread.java:112) ~[swirlds-common-0.15.1.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]


```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Closed by PR: https://github.com/hashgraph/hedera-services/pull/1644
