### ISSUE TITLE
MixedOps-NIReconnect-1.5k-25m failed for INVALID_ACCOUNT_ID in MixedValidationsAfterReconnect suite

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1646]
**Summary of the defect**
As title.

It's a pure test client issue. Need to revisit the test design to make sure it's legit.

This happens only to master branch. But that doesn't mean branch 0.15 is ok. It's probably because this error is hidden by the INSUFFICIENT_TX_FEE error for now.

**How to reproduce (if possible)**

Master branch's slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624348494432200
and its results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210622-072507-GCP-Daily-Comp-Reconnect-6N-1C/MixedOps-NIReconnect-1.5k-25m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**
```
...

2021-06-22 07:44:19.056 INFO   174  SubmitMessagesForReconnect - -------------- RESULTS OF SubmitMessagesForReconnect SUITE --------------
2021-06-22 07:44:19.056 INFO   176  SubmitMessagesForReconnect - Spec{name=RunSubmitMessages, status=PASSED}
2021-06-22 07:44:19.057 INFO   143  MixedValidationsAfterReconnect - -------------- STARTING MixedValidationsAfterReconnect SUITE --------------
2021-06-22 07:44:19.060 INFO   57   MapPropertySource - Initializing a MapPropertySource from {nodes=34.75.39.212:0.0.3:50211,34.74.153.41:0.0.4:50211,104.196.23.51:0.0.5:50211,35.185.22.168:0.0.6:50211,34.75.85.174:0.0.7:50211,35.227.120.223:0.0.8:50211, totalClients=6, default.node=0.0.3, tls=off, txn=ALTERNATE, node.selector=fixed, default.payer=0.0.1001, ci.properties.map=tps=50,mins=3,threads=30}
2021-06-22 07:44:19.080 INFO   143  HapiApiClients - Constructed 96 new stubs building clients for HapiApiClients{node0=NodeConnectInfo{host=34.75.39.212, port=50211, tlsPort=50212, account=0.0.3}, node1=NodeConnectInfo{host=34.74.153.41, port=50211, tlsPort=50212, account=0.0.4}, node2=NodeConnectInfo{host=104.196.23.51, port=50211, tlsPort=50212, account=0.0.5}, node3=NodeConnectInfo{host=35.185.22.168, port=50211, tlsPort=50212, account=0.0.6}, node4=NodeConnectInfo{host=34.75.85.174, port=50211, tlsPort=50212, account=0.0.7}, node5=NodeConnectInfo{host=35.227.120.223, port=50211, tlsPort=50212, account=0.0.8}, default=0.0.3}
2021-06-22 07:44:19.083 INFO   57   MapPropertySource - Initializing a MapPropertySource from {nodes=34.75.39.212:0.0.3:50211,34.74.153.41:0.0.4:50211,104.196.23.51:0.0.5:50211,35.185.22.168:0.0.6:50211,34.75.85.174:0.0.7:50211,35.227.120.223:0.0.8:50211, totalClients=6, default.node=0.0.3, tls=off, txn=ALTERNATE, node.selector=fixed, default.payer=0.0.1001, ci.properties.map=tps=50,mins=3,threads=30}
2021-06-22 07:44:19.086 INFO   57   MapPropertySource - Initializing a MapPropertySource from {nodes=34.75.39.212:0.0.3:50211,34.74.153.41:0.0.4:50211,104.196.23.51:0.0.5:50211,35.185.22.168:0.0.6:50211,34.75.85.174:0.0.7:50211,35.227.120.223:0.0.8:50211, totalClients=6, default.node=0.0.3, tls=off, txn=ALTERNATE, node.selector=fixed, default.payer=0.0.1001, ci.properties.map=tps=50,mins=3,threads=30}
2021-06-22 07:44:19.088 INFO   57   MapPropertySource - Initializing a MapPropertySource from {mins=3, tps=50, threads=30}
2021-06-22 07:44:19.108 INFO   138  FeesAndRatesProvider - The exchange rates are :: [Current hbar/cent equiv 1 <-> 12 expiry @ 4102444800, Next hbar/cent equiv 1 <-> 15 expiry @ 4102444800]
2021-06-22 07:44:19.118 INFO   156  FeesAndRatesProvider - The fee schedule covers 56 ops.
2021-06-22 07:44:19.137 INFO   212  HapiGetAccountBalance - 'GetAccountBalanceFromAllNodes' - balance for '0.0.1002': 0 tinyBars (0ħ)
2021-06-22 07:44:19.142 INFO   137  HapiGetAccountBalance - Explicit token balances: []
2021-06-22 07:44:19.143 INFO   322  HapiApiSpec - 'GetAccountBalanceFromAllNodes' finished initial execution of BalanceSnapshot{snapshot=senderBalance, account=0.0.1002}
2021-06-22 07:44:19.145 INFO   212  HapiGetAccountBalance - 'GetAccountBalanceFromAllNodes' - balance for '0.0.1003': 1 tinyBars (0ħ)
2021-06-22 07:44:19.146 INFO   137  HapiGetAccountBalance - Explicit token balances: []
2021-06-22 07:44:19.146 INFO   322  HapiApiSpec - 'GetAccountBalanceFromAllNodes' finished initial execution of BalanceSnapshot{snapshot=receiverBalance, account=0.0.1003}
2021-06-22 07:44:19.147 INFO   212  HapiGetAccountBalance - 'GetAccountBalanceFromAllNodes' - balance for '0.0.21003': 0 tinyBars (0ħ)
2021-06-22 07:44:19.148 ERROR  184  HapiQueryOp - Bad answerOnlyPrecheck! expected OK, actual INVALID_ACCOUNT_ID
2021-06-22 07:44:19.150 WARN   214  HapiSpecOperation - 'GetAccountBalanceFromAllNodes' - HapiGetAccountBalance{node=0.0.3, account=0.0.21003} failed - {}
com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Bad answerOnlyPrecheck! expected OK, actual INVALID_ACCOUNT_ID
	at com.hedera.services.bdd.spec.queries.HapiQueryOp.submitOp(HapiQueryOp.java:186) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.BalanceSnapshot.submitOp(BalanceSnapshot.java:61) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:317) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:227) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:255) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:146) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:139) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:598) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:599) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:573) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:573) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:541) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:462) [SuiteRunner.jar:?]
2021-06-22 07:44:19.154 ERROR  63   BalanceSnapshot - Failed to take balance snapshot for '0.0.21003'!


```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Should be fixed by `regression` PR: https://github.com/swirlds/swirlds-platform-regression/pull/1271
