### ISSUE TITLE
MixedOps-NI-3NReconnect-6k-24m HAPIClientValidator failed for duplicate transaction

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1647]
**Summary of the defect**
This is a random failure due to the payment transaction of `HapiGetVersionInfo` issues from multiple clients. 

Probably change the `HapiGetVersionInfo` to other operation to avoid the potential race condition.

This is observed in master branch for now, but 0.15 branch should have same issue as well.

**How to reproduce (if possible)**

Master branch slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624356386447800
Its results URL: https://console.cloud.google.com/storage/browser/_details/hedera-services-jrs-test-results/hedera-services-automation/master/20210622-093926-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-NI-3NReconnect-6k-24m/node0001-TestClient/hapi-client-combined.log?authuser=3

**Service logs (if applicable)**
```
...
2021-06-22 09:47:40.910 ERROR  38   CustomSpecAssert - Operation 'HapiGetVersionInfo{}' :: Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
Exception in thread "thread0" java.lang.IllegalStateException: com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:39)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:45)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.testRun(RunLoadTest.java:247)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.lambda$threadMode$22(RunLoadTest.java:215)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
	at com.hedera.services.bdd.spec.queries.HapiQueryOp.submitOp(HapiQueryOp.java:186)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:36)
	... 4 more
2021-06-22 09:47:40.912 INFO   229  RunLoadTest - Total Ops submitted 0, actual TPS 0.0


```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
@ljianghedera  This might be fixed with https://github.com/hashgraph/hedera-services/pull/1707 ?
