### ISSUE TITLE
AddressBook Tests Fail for the same reason

### ISSUE THREAD

**Issue by mxtartaglia-sl** [hashgraph/hedera-services#16531]
All nodes throw:
```
The address books are not equal as config text. com.swirlds.demo.addressbook.AddressBookTestingToolState.equalsAsConfigText(AddressBookTestingToolState.java:598)
--
  |   | at com.swirlds.demo.addressbook.AddressBookTestingToolState.softwareUpgradeAddNodeWeightingBehavior1(AddressBookTestingToolState.java:410) 	at com.swirlds.demo.addressbook.AddressBookTestingToolState.validateTestScenario(AddressBookTestingToolState.java:352) 	at com.swirlds.demo.addressbook.AddressBookTestingToolState.handleConsensusRound(AddressBookTestingToolState.java:211) 	at com.swirlds.platform.state.TransactionHandler.handleRound(TransactionHandler.java:59) 	at com.swirlds.platform.state.SwirldStateManager.handleConsensusRound(SwirldStateManager.java:129) 	at com.swirlds.platform.eventhandling.DefaultTransactionHandler.handleConsensusRound(DefaultTransactionHandler.java:201) 	at com.swirlds.common.wiring.component.ComponentWiring.lambda$bind$7(ComponentWiring.java:725) 	at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:111) 	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTask.handle(SequentialThreadTask.java:34) 	at com.swirlds.common.wiring.schedulers.internal.SequentialThreadTaskScheduler.run(SequentialThreadTaskScheduler.java:207) 	at java.lang.Thread.run(Thread.java:1583)
```

**Comment by mxtartaglia-sl** [comment]
[jtr-develop-MondayNovember11.txt](https://github.com/user-attachments/files/17707568/jtr-develop-MondayNovember11.txt)

**Comment by mxtartaglia-sl** [comment]
<google-sheets-html-origin><style type="text/css"></style>
AddressBook | AddressBook-genesis-force-use-config-addressbook-1k-1m | platform | 12.5h | FAIL | FFPPPP
-- | -- | -- | -- | -- | --
AddressBook | AddressBook-genesis-normal-1k-1m | platform | 12.5h | FAIL | FFPPP
AddressBook | AddressBook-restart-force-use-config-addressbook-1k-4m | platform | 12.5h | FAIL | FFPPP
AddressBook | AddressBook-restart-saved-state-same-version-1k-4m | platform | 12.5h | FAIL | FFPPP
AddressBook | AddressBook-restart-upgrade-add-node-1k-4m | platform | 11.3h | FAIL | FFPPPP
AddressBook | AddressBook-restart-upgrade-force-use-config-addressbook-1k-4m | platform | 12.5h | FAIL | FFPPP
AddressBook | AddressBook-restart-upgrade-remove-node-1k-4m | platform | 11.3h | FAIL | FFPPPP
AddressBook | AddressBook-restart-upgrade-weight-behavior2-1k-4m | platform | 12.5h | FAIL | FFPPP

AddressBook	AddressBook-genesis-force-use-config-addressbook-1k-1m	platform	12.5h	FAIL	FFPPPP
AddressBook	AddressBook-genesis-normal-1k-1m	platform	12.5h	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241110-063058-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)AIL	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241109-062947-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)F[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241108-063256-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241107-063132-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241106-063146-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)
AddressBook	AddressBook-restart-force-use-config-addressbook-1k-4m	platform	12.5h	FAIL	FF[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241105-063109-GCP-Daily-AddressBook-4N/AddressBook-genesis-force-use-config-addressbook-1k-1m/)PP
AddressBook	AddressBook-restart-saved-state-same-version-1k-4m	platform	12.5h	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241110-063058-GCP-Daily-AddressBook-4N/AddressBook-genesis-normal-1k-1m/)AIL	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241109-062947-GCP-Daily-AddressBook-4N/AddressBook-genesis-normal-1k-1m/)F[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241108-063256-GCP-Daily-AddressBook-4N/AddressBook-genesis-normal-1k-1m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241106-063146-GCP-Daily-AddressBook-4N/AddressBook-genesis-normal-1k-1m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241105-063109-GCP-Daily-AddressBook-4N/AddressBook-genesis-normal-1k-1m/)
AddressBook	AddressBook-restart-upgrade-add-node-1k-4m	platform	11.3h	FAIL	FFPPPP
AddressBook	AddressBook-restart-upgrade-force-use-config-addressbook-1k-4m	platform	12.5h	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241110-063058-GCP-Daily-AddressBook-4N/AddressBook-restart-force-use-config-addressbook-1k-4m/)AIL	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241109-062947-GCP-Daily-AddressBook-4N/AddressBook-restart-force-use-config-addressbook-1k-4m/)F[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241108-063256-GCP-Daily-AddressBook-4N/AddressBook-restart-force-use-config-addressbook-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241106-063146-GCP-Daily-AddressBook-4N/AddressBook-restart-force-use-config-addressbook-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241105-063109-GCP-Daily-AddressBook-4N/AddressBook-restart-force-use-config-addressbook-1k-4m/)
AddressBook	AddressBook-restart-upgrade-remove-node-1k-4m	platform	11.3h	FAIL	[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241110-063058-GCP-Daily-AddressBook-4N/AddressBook-restart-saved-state-same-version-1k-4m/)[F](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241109-062947-GCP-Daily-AddressBook-4N/AddressBook-restart-saved-state-same-version-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241108-063256-GCP-Daily-AddressBook-4N/AddressBook-restart-saved-state-same-version-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241106-063146-GCP-Daily-AddressBook-4N/AddressBook-restart-saved-state-same-version-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/4N/AddressBook/20241105-063109-GCP-Daily-AddressBook-4N/AddressBook-restart-saved-state-same-version-1k-4m/)P
AddressBook	AddressBook-restart-upgrade-weight-behavior2-1k-4m	platform	12.5h	[F](http://35.247.76.217:8095/swirlds-automation/develop/5N/AddressBook/20241110-073724-GCP-Daily-AddressBook-5N/AddressBook-restart-upgrade-add-node-1k-4m/)AIL	[F](http://35.247.76.217:8095/swirlds-automation/develop/5N/AddressBook/20241109-073641-GCP-Daily-AddressBook-5N/AddressBook-restart-upgrade-add-node-1k-4m/)F[P](http://35.247.76.217:8095/swirlds-automation/develop/5N/AddressBook/20241108-074033-GCP-Daily-AddressBook-5N/AddressBook-restart-upgrade-add-node-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/5N/AddressBook/20241107-064819-GCP-Daily-AddressBook-5N/AddressBook-restart-upgrade-add-node-1k-4m/)[P](http://35.247.76.217:8095/swirlds-automation/develop/5N/AddressBook/20241106-073850-GCP-Daily-AddressBook-5N/AddressBook-restart-upgrade-add-node-1k-4m/)

**Comment by mxtartaglia-sl** [comment]
fixed by anthony
