### ISSUE TITLE
Tom's test reports java.lang.IllegalStateException: Genesis network info is not found

### ISSUE THREAD

**Issue by iwsimon** [hashgraph/hedera-services#16583]
Tom's test:
v0.56.2 failed to load av0.55.2 saved state, resulting in a FATAL error on perf1,
develop build (beca90f9) also failed to load the v0.54.1 saved state.
In hgacc/swirlds.logs:
2024-11-13 03:34:50.706 INFO  217  MerkleSchemaRegistry - Applying 2 schemas for service AddressBookService with state version v0.55.2+0, software version v0.56.2+0, and latest service schema version v0.56.0
2024-11-13 03:34:50.706 INFO  228  MerkleSchemaRegistry - Applying AddressBookService schema SemanticVersion[major=0, minor=53, patch=0, pre=, build=] ([STATE_DEFINITIONS])
2024-11-13 03:34:50.707 INFO  300  MerkleSchemaRegistry -   Ensuring AddressBookService has state NODES
2024-11-13 03:34:50.708 INFO  368  MerkleSchemaRegistry -   Removing states [] from service AddressBookService
2024-11-13 03:34:50.708 INFO  228  MerkleSchemaRegistry - Applying AddressBookService schema SemanticVersion[major=0, minor=56, patch=0, pre=, build=] ([MIGRATION, RESTART])
2024-11-13 03:34:50.708 FATAL 558  Hedera - Critical failure during initialization
java.lang.IllegalStateException: Genesis network info is not found
	at com.hedera.node.app.service.addressbook.impl.schemas.V056AddressBookSchema.migrate(V056AddressBookSchema.java:78) ~[app-service-addressbook-impl-0.56.2.jar:?]
	at com.hedera.node.app.state.merkle.MerkleSchemaRegistry.migrate(MerkleSchemaRegistry.java:268) ~[HederaNode.jar:?]
	at com.hedera.node.app.services.OrderedServiceMigrator.lambda$doMigrations$2(OrderedServiceMigrator.java:133) ~[HederaNode.jar:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.base/java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:3099) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.hedera.node.app.services.OrderedServiceMigrator.doMigrations(OrderedServiceMigrator.java:126) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.onMigrate(Hedera.java:614) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.migrateAndInitialize(Hedera.java:911) ~[HederaNode.jar:?]
	at com.hedera.node.app.Hedera.onStateInitialized(Hedera.java:556) [HederaNode.jar:?]
	at com.hedera.node.app.state.MerkleStateLifecyclesImpl.onStateInitialized(MerkleStateLifecyclesImpl.java:122) [HederaNode.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.init(MerkleStateRoot.java:264) [swirlds-platform-core-0.56.2.jar:?]
	at com.swirlds.platform.StateInitializer.initializeState(StateInitializer.java:84) [swirlds-platform-core-0.56.2.jar:?]
	at com.swirlds.platform.SwirldsPlatform.<init>(SwirldsPlatform.java:249) [swirlds-platform-core-0.56.2.jar:?]
	at com.swirlds.platform.builder.PlatformComponentBuilder.build(PlatformComponentBuilder.java:218) [swirlds-platform-core-0.56.2.jar:?]
	at com.swirlds.platform.builder.PlatformBuilder.build(PlatformBuilder.java:484) [swirlds-platform-core-0.56.2.jar:?]
	at com.hedera.node.app.ServicesMain.main(ServicesMain.java:284) [HederaNode.jar:?]

**Comment by iwsimon** [comment]
This fix went in release/0.56 branch with PR https://github.com/hashgraph/hedera-services/pull/16588 and https://github.com/hashgraph/hedera-services/pull/16609. @tinker-michaelj will cherry-pick the changes to develop with issue https://github.com/hashgraph/hedera-services/issues/16321.
