### ISSUE TITLE
HTS-Restart-AccountBalances-2k-20m balances file export was not scheduled at appropriate time

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1659]
**Summary of the defect**
Account balances file export is missed.

**How to reproduce (if possible)**

Branch 0.15's slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624346799430200
Its results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/release/0.15/20210622-065741-GCP-Daily-Comp-BalancesValidate-6N-1C/HTS-Restart-AccountBalances-2k-20m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**
```
...
Account balances should be scheduled to be exported at time 2021-06-22T07:16:00.423Z
<<INFO>>
Do not validate client account balances
All server nodes have same account balances file names
Server node 1 account balances file content is same as that of node0's
Server node 2 account balances file content is same as that of node0's
Server node 3 account balances file content is same as that of node0's
Server node 4 account balances file content is same as that of node0's
Server node 5 account balances file content is same as that of node0's
Csv file account balances match proto file account balances

```

In server node 0's swirld.log:

```
2021-06-22 07:22:28.810 44       ERROR EXCEPTION        <<event-flow: state-hash 0 #0>> ThreadConfiguration: exception on thread <event-flow: state-hash 0 #0>
java.lang.NullPointerException: null
	at com.swirlds.platform.state.SignedStateManager.addSigInfo(SignedStateManager.java:755) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.state.SignedStateManager.recordStateSig(SignedStateManager.java:656) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.state.SignedStateManager.newSelfSigned(SignedStateManager.java:613) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.platform.EventFlow.stateHashSign(EventFlow.java:1044) ~[swirlds-platform-core-0.15.1.jar:?]
	at com.swirlds.common.threading.StoppableThread.doWork(StoppableThread.java:255) ~[swirlds-common-0.15.1.jar:?]
	at com.swirlds.common.threading.StoppableThread.run(StoppableThread.java:112) ~[swirlds-common-0.15.1.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]

```

**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
This also fixed by PR #1644.
