### ISSUE TITLE
JTR failure: FCM-Migration-NewNodesFromSavedState-2.5k-10m

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#16744]
### Description

`FCM-Migration-NewNodesFromSavedState-2.5k-10m` fails with the following error: 

```
Caused by: com.swirlds.common.merkle.exceptions.IllegalChildIndexException: Child Index range supported: [0, 2]. Requested: 3
	at com.swirlds.common.merkle.impl.PartialNaryMerkleInternal.checkChildIndexIsValid(PartialNaryMerkleInternal.java:150) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:98) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.merkle.interfaces.MerkleParent.setChild(MerkleParent.java:108) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:491) ~[swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:415) ~[swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.lambda$initPlatformState$4(FakeMerkleStateLifecycles.java:84) 
```

### Steps to reproduce

Run `FCM-Migration-NewNodesFromSavedState-2.5k-10m` 

### Additional context

Caused by https://github.com/hashgraph/hedera-services/pull/16352 

### Version

v0.57

### Operating system

None

**Comment by imalygin** [comment]
I resolved the issues that caused the original failure. Now the tests fails because of the following exception:
```
2024-11-23 04:03:44.773 33       ERROR EXCEPTION        <main> StreamDebugUtils: Deserialization re-attempt also encountered a failure.
java.io.IOException: Failed to read snapshot file /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.swirlds.demo.migration.MigrationTestingToolMain/0/123/9523/SignedState.swh
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.readStateFileDataV1(MerkleTreeSnapshotReader.java:108) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.lambda$readStateFileData$1(MerkleTreeSnapshotReader.java:85) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:93) [swirlds-common-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.readStateFileData(MerkleTreeSnapshotReader.java:78) [swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.readStateFile(SignedStateFileReader.java:87) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:249) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadLatestState(StartupStateUtils.java:220) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:151) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.getInitialState(StartupStateUtils.java:94) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:278) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:161) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:136) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:125) [swirlds-platform-core-0.57.0.jar:?]
Caused by: com.swirlds.common.io.exceptions.ClassNotFoundException: No class with id=2986366740991591426(0x2971B4BA7DD84402) found
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:154) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.io.streams.DebuggableMerkleDataInputStream.readNextNode(DebuggableMerkleDataInputStream.java:627) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.io.streams.DebuggableMerkleDataInputStream.readMerkleTree(DebuggableMerkleDataInputStream.java:612) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.readStateFileDataV1(MerkleTreeSnapshotReader.java:103) ~[swirlds-state-impl-0.57.0.jar:?]
```

This classId - `id=2986366740991591426(0x2971B4BA7DD84402)` - is nowhere to be found in the codebase because it belongs to deleted `com.swirlds.platform.state.State` class. 

To address the issue I'll try to register `MerkleStateRoot` using this class id.
