### ISSUE TITLE
Crypto-Recovery-300-21m failed for Corrupt fee schedule in saved state

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1675]
**Summary of the defect**

The node validator's Node 0 has exception:- Corrupt fee schedules in saved state...

This only happens to master branch, so it should be introduced recently.

**How to reproduce (if possible)**

Master branch slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624605681044200
Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210625-070424-GCP-Daily-Recovery-4N-1C/Crypto-Recovery-300-21m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

**Service logs (if applicable)**

In output.log of all server nodes, we see the following errors:

```
...
2021-06-25 07:14:22.452 ERROR 206  HfsSystemFilesManager - Corrupt fee schedules in saved state (\n\2167\n\232\001\b\033\022\225\001\n-\020\200\200\232\246\352\257\343\001\030\303\205\360\340\020 \371\364\266\003(\360\220\304\374B0\272%8\350\002@\305\366\002P\371\364\266\003X\303\374\n\0221\020\200\200\232\246\352\257\343\001\030\263\330\200\216\214\002 \225\317\3566(\207\216\302\310\257\b0\242\327\0048\371,@\321\350.P\225\317\3566X\261\310\257\001\0321\020\200\200\232\246\352\257\343\001\030\263\330\200\216\214\002 \225\317\3566(\207\216\302\310\257\b0\242\327\0048\371,@\321\350.P\225\317\3566X\261\310\257\001\n\201\001\b!\022}\n%\020\200\200\232\246\352\257\343\001\030\216\270\314\034 \206\355\005(\211\356\245r0@8\005@\377\004P\206\355\005X\335\022\022)\020\200\200\232\246\352\257\343\001\030\331\201\307\311\003 \344\320](\217\341\335\244\0160\377\a8M@\363OP\344\320]X\317\253\002\032)\020\200\200\232\246\352\257\343\001\030\331\201\307\311\003 \344\320](\217\341\335\244\0160\377\a8M@\363OP\344\320]X\317\253\002\n\177\b\002\022{\n%\020\200\200\232\246\352\257\343\001\030\370\250\257\t \266\365\001(\373\260\271%0\0258\002@\321\001P\266\365\001X\221\006\022(\020\200\200\232\246\352\257\343\001\030\202\217\365\225\001 \337\326\036(\266\217\226\327\0040\317\0028\031@\227\032P\337\326\036X\226b\032(\020\200\200\232\246\352\257\343\001\030\202\217\365\225\001 \337\326\036(\266\217\226\327\0040\317\0028\031@\227\032P\337\326\036X\226b\nk\b\001\022g\n\035\020\300\273\001\030\347\217\275\004 \244u(\356\320\362\0210\n8\001@dP\244uX\367\002\022\"\020\240\231\002\030\357\374\321G \276\324\016(\336\215\252\236\0020\240\0018\f@\301\fP\276\324\016X\365.\032\"\020\240\231\002\030\357\374\321G \276\324\016(\336\215\252\236\0020\240\0018\f@\301\fP\276\324\016X\365.\n\216\001\b\003\022\211\001\n)\020\200\200\232\246\352\257\343\001\030\343\326\345\340\001 \210\200.(\245\234\271\202\a0\366\0038&@\240\'P\210\200.X\232\223\001\022-\020\200\200\232\246\352\257\343\001\030\255\354\332\214\034 \200\201\340\005(\316\304\223\247p0\347>8\333\004@\210\364\004P\200\201\340\005X\235\263\022\032-\020\200\200\232\246\352\257\343\001\030\255\354\332\214\034 \200\201\340\005(\316\304\223\247p0\347>8\333\004@\210\364\004P\200\201\340\005X\235\263\022\n\232\001\b\004\022\225\001\n-\020\200\200\232\246\352\257\343\001\030\252\340\202\334\024 \327\330\236\004(\272\206\274\347R0\250.8\275\003@\215\317\003P\327\330\236\004X\317\310\r\0221\020\200\200\232\246\352\257\343\001\030\237\205\254\300\313\002 \363\212\353C(\233\347\300\367\254\n0\372\344\0058\3117@\310\3619P\363\212\353CX\360\211\331\001\0321\020\200\200\232\246\352\257\343\001\030\237\205\254\300\313\002 \363\212\353C(\233\347\300\367\254\n0\372\344\0058\3117@\310\3619P\363\212\353CX\360\211\331\001\n\216\001\b\005\022\211\001\n)\020\200\200\232\246\352\257\343\001\030\334\346\265\337\001 \211\334-(\233\245\372\374\0060\363\0038%@\202\'P\211\334-X\247\222\001\022-\020\200\200\232\246\352\257\343\001\030\271\353\334\366\033 \224\301\333\005(\251\323\244\317o0\266>8\327\004@\234\360\004P\224\301\333\005X\352\244\022\032-\020\200\200\232\246\352\257\343\001\030\271\353\334\366\033 \224\301\333\005(\251\323\244\317o0\266>8\327\004@\234\360\004P\224\301\333\005X\352\244\022\n_\b\025\022[\n\031\020\200\200\232\246\352\257\343\001\030\256\314\003 ^(\372\257\016@\001P^X\002\022\036\020\200\200\232\246\352\257\343\001\030\346\3059 \343\v(\240\377\345\0010\001@\nP\343\vX&\032\036\020\200\200\232\246\352\257\343\001\030\346\3059 \343\v(\240\377\345\0010\001@\nP\343\vX&\nW\b\016\022S\n\027\020\200\200\232\246\352\257\343\001\030\234\254\001 #(\251\260\005P#X\001\022\033\020\200\200\232\246\352\257\343\001\030\304\303\025 \264\004(\230\205V@\004P\264\004X\016\032\033\020\200\200\232\246\352\257\343\001\030\304\303\025 

...

2021-06-25 07:14:22.237 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#3!
java.lang.IllegalStateException: Could not initialize system files!
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:192) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:150) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:878) [swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0-alpha.1.jar:?]
Caused by: java.lang.IllegalStateException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:207) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadProtoWithSupplierFallback(HfsSystemFilesManager.java:246) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFeeSchedules(HfsSystemFilesManager.java:145) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.SystemFilesManager.loadObservableSystemFiles(SystemFilesManager.java:50) ~[HederaNode.jar:?]
	at com.hedera.services.state.logic.NetworkCtxManager.loadObservableSysFilesIfNeeded(NetworkCtxManager.java:94) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:190) ~[HederaNode.jar:?]
	... 5 more


```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by tinker-michaelj** [comment]
Likely can be resolved by removing the `adjustFeeSchedules` client.

**Comment by ljianghedera** [comment]
Fixed by `regression` PR: https://github.com/swirlds/swirlds-platform-regression/pull/1278

**Comment by ljianghedera** [comment]
By
