### ISSUE TITLE
PTT certificate unit test fail

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#16829]
Roger Barker reported this failing unit test:

```
> Task :PlatformTestingTool:timingSensitive
  com.swirlds.demo.merkle.map.MapValueFCQTests ✘ initializationError

    java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.crypto.SerializableX509Certificate.getCertificate()" because "this.sigCert" is null
        at com.swirlds.demo.merkle.map.MapValueFCQTests.setUp(MapValueFCQTests.java:84)
```

**Comment by lpetrovic05** [comment]
I fixed one failure in the branch: `16829-D-PTT-certificate-unit-test-fail`
But now a different exception is thrown:
```
Invalid class ID 253095242501945279(0x3832CC837AB77BF) at index 2 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
com.swirlds.common.merkle.exceptions.IllegalChildTypeException: Invalid class ID 253095242501945279(0x3832CC837AB77BF) at index 2 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.throwIfInvalidChild(AbstractMerkleInternal.java:157)
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:100)
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:96)
	at com.swirlds.common.merkle.interfaces.MerkleParent.setChild(MerkleParent.java:108)
	at com.swirlds.state.merkle.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:394)
	at com.swirlds.state.merkle.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:338)
	at com.swirlds.state.merkle.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:318)
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.lambda$initPlatformState$4(FakeMerkleStateLifecycles.java:85)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.initPlatformState(FakeMerkleStateLifecycles.java:82)
	at com.swirlds.demo.platform.PlatformTestingToolState.init(PlatformTestingToolState.java:1303)
	at com.swirlds.demo.platform.PlatformTestingToolState.init(PlatformTestingToolState.java:1265)
	at com.swirlds.demo.merkle.map.MapValueFCQTests.setUp(MapValueFCQTests.java:90)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

@imalygin do you have any idea what the source of this failure is?

**Comment by lpetrovic05** [comment]
should be fixed by https://github.com/hashgraph/hedera-services/pull/16864
