### ISSUE TITLE
JTR failure: `FCM-VM-DynamicFreeze-2.5k-40m` fails

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#16971]
### Description

Test `FCM-VM-DynamicFreeze-2.5k-40m` fails with the following error:

```
java.lang.ExceptionInInitializerError: null
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at com.swirlds.platform.swirldapp.SwirldAppLoader.loadSwirldApp(SwirldAppLoader.java:81) ~[swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.util.BootstrapUtils.loadSwirldMains(BootstrapUtils.java:377) ~[swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:194) ~[swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:162) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:137) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:126) [swirlds-platform-core-0.57.0.jar:?]
Caused by: com.swirlds.common.merkle.exceptions.IllegalChildTypeException: Invalid class ID -5151568835156514733(0xB881F3704885E853) at index 1 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.throwIfInvalidChild(AbstractMerkleInternal.java:157) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:100) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.merkle.interfaces.MerkleParent.setChild(MerkleParent.java:108) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:394) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleStateRoot.putServiceStateIfAbsent(MerkleStateRoot.java:318) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.lambda$initRosterState$10(FakeMerkleStateLifecycles.java:173) ~[swirlds-platform-core-0.57.0-test-fixtures.jar:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.initRosterState(FakeMerkleStateLifecycles.java:161) ~[swirlds-platform-core-0.57.0-test-fixtures.jar:?]
	at com.swirlds.platform.test.fixtures.state.FakeMerkleStateLifecycles.initStates(FakeMerkleStateLifecycles.java:120) ~[swirlds-platform-core-0.57.0-test-fixtures.jar:?]
	at com.swirlds.demo.platform.PlatformTestingToolMain.lambda$static$0(PlatformTestingToolMain.java:153) ~[?:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.getClassId(GenericConstructorRegistry.java:135) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.registerConstructable(GenericConstructorRegistry.java:119) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructable(DefaultConstructableRegistry.java:74) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.demo.platform.PlatformTestingToolMain.<clinit>(PlatformTestingToolMain.java:151) ~[?:?]
```

### Steps to reproduce

Run `FCM-VM-DynamicFreeze-2.5k-40m` 

### Hedera network

other

### Version

v0.58

### Operating system

None

**Comment by imalygin** [comment]
Fixed by a combination of https://github.com/hashgraph/hedera-services/pull/17006 and https://github.com/hashgraph/hedera-services/pull/17005
