### ISSUE TITLE
JRS failure: `ISS-catastrophic-1k-5m` fails with "`ROSTER_STATE` for service `RosterService` is missing" error

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#16981]
### Description

The following tests:

`ISS-catastrophic-1k-5m`
`ISS-recoverable-1k-5m`

are failing with the following error:
```
java.lang.IllegalStateException: State 'ROSTER_STATE' for service 'RosterService' is missing from the merkle tree!
    at com.swirlds.state.merkle.MerkleStateRoot$MerkleStates.findNode(MerkleStateRoot.java:641) ~[swirlds-state-impl-0.57.0.jar:?]
    at com.swirlds.state.merkle.MerkleStateRoot$MerkleStates.getSingleton(MerkleStateRoot.java:566) ~[swirlds-state-impl-0.57.0.jar:?]
    at com.swirlds.state.merkle.MerkleStateRoot$MerkleReadableStates.getSingleton(MerkleStateRoot.java:652) ~[swirlds-state-impl-0.57.0.jar:?]
    at com.swirlds.platform.roster.RosterRetriever.getActiveRosterHash(RosterRetriever.java:145) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.platform.roster.RosterRetriever.retrieveActive(RosterRetriever.java:120) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.platform.roster.RosterRetriever.retrieveActiveOrGenesisRoster(RosterRetriever.java:70) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.platform.state.signed.SignedState.getAddressBook(SignedState.java:265) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.platform.state.signed.SignedState.pruneInvalidSignatures(SignedState.java:672) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.platform.state.signed.DefaultStateSignatureCollector.addReservedState(DefaultStateSignatureCollector.java:102) ~[swirlds-platform-core-0.57.0.jar:?]
    at com.swirlds.common.wiring.component.ComponentWiring.lambda$bind$7(ComponentWiring.java:725) ~[swirlds-common-0.57.0.jar:?]
    at com.swirlds.common.wiring.wires.input.BindableInputWire.lambda$bind$1(BindableInputWire.java:111) ~[swirlds-common-0.57.0.jar:?]
    at com.swirlds.common.wiring.schedulers.internal.SequentialTask.exec(SequentialTask.java:92) [swirlds-common-0.57.0.jar:?]
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]

```

### Steps to reproduce

Run either `ISS-catastrophic-1k-5m` or `ISS-recoverable-1k-5m`

### Hedera network

other

### Version

v0.57

### Operating system

None

**Comment by anthony-swirldslabs** [comment]
This may have been fixed with https://github.com/hashgraph/hedera-services/pull/17006 . We'll learn more tomorrow after the next JTR run.

**Comment by artemananiev** [comment]
@anthony-swirldslabs Could you check that the fix for #17006 also addressed this issue, please?

**Comment by anthony-swirldslabs** [comment]
@artemananiev : Yes, it fixed the issue. Also, there were a couple more PRs (from @imalygin , I believe) that renumbered other children in other demo states as well (I don't have the links handy now.)

All the JTR tests pass now, which indicates that the issue is resolved and this ticket can be closed.
