### ISSUE TITLE
GetReceipt after CryptoAddClaim leaves errors in services-hedera console

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#170]
git commit: `18bdf41`

Sending

```
transactionID {
  transactionValidStart {
    seconds: 1563281639
    nanos: 798600000
  }
  accountID {
    accountNum: 2
  }
}
nodeAccountID {
  accountNum: 3
}
transactionFee: 10000000
transactionValidDuration {
  seconds: 120
}
memo: "Demo memo"
cryptoAddClaim {
  claim {
    accountID {
      accountNum: 1012
    }
    hash: "012345678901234567890123456789012345678901234567"
    keys {
      keys {
        ed25519: "s?i\227\261e\252\340\256>\315\021Xt\375\315m\277b\306\3330?\004\215\207\337\037\313\223_<"
      }
    }
    claimDuration {
      seconds: 1594817649
    }
  }
}
```

followed by getting a receipt

```
transactionGetReceipt {
  header {
  }
  transactionID {
    transactionValidStart {
      seconds: 1563281639
      nanos: 798600000
    }
    accountID {
      accountNum: 2
    }
  }
}
```

leaves the following in the services-hedera console

```
2019-07-16 14:54:30.336 ERROR 223  JTransactionRecord - JTransactionRecord to TransactionRecord Proto Failed..
java.lang.NullPointerException: null
	at com.opencrowd.core.jproto.JTransactionID.convert(JTransactionID.java:181) ~[classes/:?]
	at com.opencrowd.core.jproto.JTransactionRecord.convert(JTransactionRecord.java:185) [classes/:?]
	at com.opencrowd.handler.DeDupMap.getRecord(DeDupMap.java:68) [classes/:?]
	at com.opencrowd.handler.TransactionHandler.getTransactionRecordFromCache(TransactionHandler.java:262) [classes/:?]
	at com.opencrowd.service.CryptoServiceImpl.getTransactionReceipts(CryptoServiceImpl.java:552) [classes/:?]
	at com.hederahashgraph.service.proto.java.CryptoServiceGrpc$MethodHandlers.invoke(CryptoServiceGrpc.java:1272) [classes/:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171) [grpc-stub-1.13.1.jar:1.13.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283) [grpc-core-1.13.1.jar:1.13.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:707) [grpc-core-1.13.1.jar:1.13.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.13.1.jar:1.13.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.13.1.jar:1.13.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by tinker-michaelj** [comment]
Obsolete.
