### ISSUE TITLE
Drop support of `INIT_STATE_FILE_VERSION` 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#17023]
### Problem

Currently we have two implementations for a method reading state file data: `readStateFileDataV1` and `readStateFileDataV2`. 
`readStateFileDataV1` assumes that a signature set is a part of the state file. `readStateFileDataV2` assumes that the signature set is stored separately. 

The only reason why `MerkleTreeSnapshotReader` is aware of the signatures is `readStateFileDataV1`. 

### Solution

Starting from release 0.58 we don't have to support `readStateFileDataV1`. 
Things to do: 
- remove `INIT_STATE_FILE_VERSION` from the set of supported versions
- remove usages of `readStateFileDataV1`
- simplify `StateFileData` by dropping `sigSet` field
- move `SigSet` class back to `platform-core`

Be aware, that it may break tests using `MigrationTestingTool`, as the state it uses has version 0.53

**Comment by anthony-swirldslabs** [comment]
The JTR test `FCM-Migration-NewNodesFromSavedState-2.5k-10m` fails with:

```
ERROR	StreamDebugUtils:	Deserialization failure. Will re-attempt deserialization with extra debug information.
com.swirlds.common.merkle.exceptions.IllegalChildCountException: Node with class ID 1877348786352289444(0x1A0DAEC64A09F6A4) at version 4 requires at least 5 children and no more than 5 children, but 3 children were provided.
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingInternal(MerkleDataInputStream.java:123) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:170) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:230) ~[swirlds-common-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.readStateFileDataV1(MerkleTreeSnapshotReader.java:105) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.lambda$readStateFileData$1(MerkleTreeSnapshotReader.java:87) ~[swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82) [swirlds-common-0.57.0.jar:?]
	at com.swirlds.state.merkle.MerkleTreeSnapshotReader.readStateFileData(MerkleTreeSnapshotReader.java:80) [swirlds-state-impl-0.57.0.jar:?]
	at com.swirlds.platform.state.snapshot.SignedStateFileReader.readStateFile(SignedStateFileReader.java:97) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:249) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadLatestState(StartupStateUtils.java:220) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.loadStateFile(StartupStateUtils.java:151) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.state.signed.StartupStateUtils.getInitialState(StartupStateUtils.java:94) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:279) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:162) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:137) [swirlds-platform-core-0.57.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:126) [swirlds-platform-core-0.57.0.jar:?]
```

because the saved state for the `MigrationTestingTool` is unaware of rosters. Apart from deprecating the old state version, this is another reason why that saved state needs to be re-generated to be 0.57-compatible.

**Comment by imalygin** [comment]
PR is updated with the fix for the test @anthony-swirldslabs mentioned above.
