### ISSUE TITLE
Investigate why UNKNOWN status code show up in low TPS JRS tests

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1706]
**Summary of the defect**
One example is the FileOps-NIReconnect-12-21m test, the TPS is rather low, but the client gets UNKNOWN response code, while corresponding serve node's log files doesn't show any noticeable error messages.

**How to reproduce (if possible)**

One example slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624957759222300
and results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210629-072311-GCP-Daily-Comp-Reconnect-6N-1C/FileOps-NIReconnect-12-21m;tab=objects?prefix=&forceOnObjectsSortingFiltering=false&authuser=3

**Service logs (if applicable)**
```
...
021-06-29 09:01:03.180 WARN   216  HapiSpecOperation - 'runMixedFileOps' - HapiFileCreate{sigs=4, node=0.0.3, created=0} failed Wrong status! Expected SUCCESS, was UNKNOWN!
2021-06-29 09:01:03.181 ERROR  38   CustomSpecAssert - Operation 'HapiFileCreate{sigs=4, node=0.0.3, created=0}' :: Wrong status! Expected SUCCESS, was UNKNOWN
Exception in thread "thread2" java.lang.IllegalStateException: com.hedera.services.bdd.spec.exceptions.HapiTxnCheckStateException: Wrong status! Expected SUCCESS, was UNKNOWN
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:39)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:45)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.testRun(RunLoadTest.java:247)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.lambda$threadMode$22(RunLoadTest.java:215)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: com.hedera.services.bdd.spec.exceptions.HapiTxnCheckStateException: Wrong status! Expected SUCCESS, was UNKNOWN
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.resolveStatus(HapiTxnOp.java:271)
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:223)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:36)
	... 4 more
2021-06-29 09:01:03.351 INFO   269  HapiTxnOp - 'runMixedFileOps' -  HapiFileCreate{sigs=4, node=0.0.3, created=0} Wrong actual status UNKNOWN, expected SUCCESS
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
