### ISSUE TITLE
Crypto-Recovery-EvSave15sTrunc-300-21m fails with NoSuchElementException: Missing generation

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1710]
**Summary of the defect**
`Crypto-Recovery-EvSave15sTrunc-300-21m` on `master` fails with `NoSuchElementException: Missing generation` while recovering. Need platform's input on this error.

**Service logs (if applicable)**
```
2021-06-29 08:38:36.248 22       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting
2021-06-29 08:38:36.249 23       DEBUG STARTUP          <main> BinaryObjectStore: Recovering Objects [ objectCount = 15, uniqueObjectCount = 7 ]
2021-06-29 08:38:36.278 24       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Finished
2021-06-29 08:38:36.279 25       INFO  STARTUP          <main> SwirldsPlatform: startUpEventFrozenEndTime: 2021-06-29T08:38:46.279375Z
2021-06-29 08:38:36.280 26       INFO  STARTUP          <main> SwirldsPlatform: initialize eventStreamManager
2021-06-29 08:38:36.293 27       DEBUG STARTUP          <main> SwirldsPlatform: Platform has loaded a saved state {"round":2,"consensusTimestamp":{"nano":47173000,"epochSecond":1624955259},"willFreezeUntil":{"nano":279375000,"epochSecond":1624955926}} [com.swirlds.logging.payloads.SavedStateLoadedPayload]
2021-06-29 08:38:36.299 28       ERROR EXCEPTION        <main> Browser: 
java.util.NoSuchElementException: Missing generation for round -23
	at com.swirlds.platform.eventhandling.MinGenQueue.getRoundGeneration(MinGenQueue.java:92) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.EventFlow.loadDataFromSignedState(EventFlow.java:529) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.buildEventFlow(SwirldsPlatform.java:907) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:777) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) ~[swirlds-platform-core-0.16.0-alpha.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0-alpha.1.jar:?]
```

**Additional Context**
[slack link](https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1624956389218300)
[summary link](https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1624957731119000)

**Comment by Neeharika-Sompalli** [comment]
This is caused when we try to load with a state that is less than round 25. Increasing the test timing to recover from state > 25 will solve the issue
