### ISSUE TITLE
MixedOps-NIReconnect-6k-28m : Reconnect fails with MutabilityException

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1731]
### Description

Reconnect fails with `MutabilityException` during sycronization.

and nodes keeps sending `ReconnectReceiver: Node 4 is unwilling to help this node to reconnect. {"causeOfFailure":"REJECTION"} [com.swirlds.logging.payloads.ReconnectFailurePayload]` to the reconnecting node, hence making it impossible to reconnect.

```
2021-07-02 06:03:29.840 129      ERROR RECONNECT        <<platform-core: syncCaller-0 5 #0>> ReconnectReceiver: Work Group Exception [ groupName = receiving-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.MutabilityException: Immutable child can not be added to parent. parent = (com.hedera.services.ServicesState: route = [0], released = false, ref count = 1, immutable = false, child count = 8), child = (com.swirlds.fcmap.FCMap: route = [0 -> 8], released = false, ref count = 2, immutable = true, child count = 2)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:156) ~[swirlds-common-0.16.0.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:149) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:115) [swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.synchronize(ReceivingSynchronizer.java:169) [swirlds-common-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.reconnect(ReconnectReceiver.java:220) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.execute(ReconnectReceiver.java:147) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.receiveStateFromNeighbor(SyncCaller.java:554) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.doReconnect(SyncCaller.java:474) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.callRequestSync(SyncCaller.java:161) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.run(SyncCaller.java:113) [swirlds-platform-core-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.MutabilityException: Immutable child can not be added to parent. parent = (com.hedera.services.ServicesState: route = [0], released = false, ref count = 1, immutable = false, child count = 8), child = (com.swirlds.fcmap.FCMap: route = [0 -> 8], released = false, ref count = 2, immutable = true, child count = 2)
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:128) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.utility.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:104) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.addToParent(ReceivingSynchronizer.java:374) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.handleData(ReceivingSynchronizer.java:305) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.execute(ReceivingSynchronizer.java:325) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.lambda$synchronize$1(ReceivingSynchronizer.java:167) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:97) ~[swirlds-common-0.16.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
2021-07-02 06:03:29.841 130      ERROR EXCEPTION        <<platform-core: syncCaller-0 5 #0>> SyncCaller: Error while receiving a signed state! {"causeOfFailure":"ERROR"} [com.swirlds.logging.payloads.ReconnectFailurePayload]
com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Synchronization failed with exceptions
	at com.swirlds.common.merkle.synchronization.ReceivingSynchronizer.synchronize(ReceivingSynchronizer.java:174) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.reconnect(ReconnectReceiver.java:220) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.execute(ReconnectReceiver.java:147) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.receiveStateFromNeighbor(SyncCaller.java:554) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.doReconnect(SyncCaller.java:474) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.callRequestSync(SyncCaller.java:161) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.run(SyncCaller.java:113) [swirlds-platform-core-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]

```

### Steps to reproduce

Run test `MixedOps-NIReconnect-6k-28m`

### Hedera network

other

### Version

master, v0.16.0

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
Was closed by https://github.com/hashgraph/hedera-services/pull/1738
