### ISSUE TITLE
All except one of master GCP-Daily-Comp-Reconnect-6N-1C panel failed for MerkleSynchronizationException

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1733]
**Summary of the defect**

Same issue happened to all GCP-Daily-Reconnect-Correctness-6N-1C tests as well.

**How to reproduce (if possible)**

Slack report summary link https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625216929127300: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625216929127300

Slack report summary link for GCP-Daily-Reconnect-Correctness-6N-1C test panel:
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625225020128000

**Service logs (if applicable)**
```
...
2021-07-02 07:42:10.533 67       INFO  RECONNECT        <<platform-core: syncListener-5 1 #0>> ReconnectSender: Starting synchronization in the role of the sender.
2021-07-02 07:42:10.589 68       ERROR RECONNECT        <<platform-core: syncListener-5 1 #0>> ReconnectSender: Work Group Exception [ groupName = sending-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:156) ~[swirlds-common-0.16.0.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:149) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:115) [swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.SendingSynchronizer.synchronize(SendingSynchronizer.java:143) [swirlds-common-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.reconnect(ReconnectSender.java:213) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:138) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:333) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:174) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:126) [swirlds-platform-core-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:127) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:97) ~[swirlds-common-0.16.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readBoolean(DataInputStream.java:249) ~[?:?]
	at com.swirlds.common.merkle.synchronization.AckMessage.deserialize(AckMessage.java:59) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:120) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:97) ~[swirlds-common-0.16.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
2021-07-02 07:42:10.597 69       ERROR EXCEPTION        <<platform-core: syncListener-5 1 #0>> SyncListener: ! SyncListener.sync Exception (so incrementing interruptedRecSyncsPerSecond) while 1 listening for 5:
com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Synchronization failed with exceptions
	at com.swirlds.common.merkle.synchronization.SendingSynchronizer.synchronize(SendingSynchronizer.java:147) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.reconnect(ReconnectSender.java:213) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:138) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:333) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:174) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:126) [swirlds-platform-core-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2021-07-02 07:42:10.690 70       ERROR SOCKET_EXCEPTIONS <sync_server_3> SyncServer: 1 got new connection from 5, disconnecting old one
2021-07-02 07:42:10.707 71       INFO  RECONNECT        <<platform-core: syncListener-5 1 #0>> SyncListener: 1 got COMM_STATE_REQUEST from 5


```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
My branch's run with latest changes still has one failure of the same error: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625283393128300

Nightly regression run of last night : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625303995130300
doesn't have the same error.

**Comment by ljianghedera** [comment]
Last night's regression are all good. This error didn't show up. 

GCP-Daily-Comp-Reconnect-6N-1C slack summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625390362133400

GCP-Daily-Reconnect-Correctness-6N-1C slack summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1625404998134400
