### ISSUE TITLE
CongestionPricing-NDReconnect-1-16m HapiClientValidator failed for update throttle definition file

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1743]
### Description

In master branch, the test failed for SUCCESS_BUT_MISSING_EXPECTED_OPERATION  when updating throttle definition file. 

Prior to that, there is an error messaging saying the server node 0 refused connection. Could be related.

We didn't see this error before.

### Steps to reproduce

Slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1625346010398000

Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210703-194741-GCP-Daily-Reconnect-Correctness-6N-1C/CongestionPricing-NDReconnect-1-16m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In hapi-client-combined.log

```
...
2021-07-03 20:50:37.097 INFO   269  HapiTxnOp - 'ValidateCongestionPricing' -  HapiFileUpdate{sigs=1, payer=EXCHANGE_RATES_CONTROL, node=0.0.3, fileName=THROTTLE_DEFINITIONS} Wrong actual status SUCCESS_BUT_MISSING_EXPECTED_OPERATION, expected SUCCESS
com.hedera.services.bdd.spec.exceptions.HapiTxnCheckStateException: Wrong status! Expected SUCCESS, was SUCCESS_BUT_MISSING_EXPECTED_OPERATION
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.resolveStatus(HapiTxnOp.java:271)
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:223)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194)
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:317)
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:227)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:255)
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:146)
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:139)
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:600)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:601)
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:575)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:575)
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:543)
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:464)
2021-07-03 20:50:37.100 WARN   217  HapiSpecOperation - 'ValidateCongestionPricing' - HapiFileUpdate{sigs=1, payer=EXCHANGE_RATES_CONTROL, node=0.0.3, fileName=THROTTLE_DEFINITIONS} failed Wrong status! Expected SUCCESS, was SUCCESS_BUT_MISSING_EXPECTED_OPERATION!
2021-07-03 20:50:37.453 INFO   341  HapiApiSpec - 'ValidateCongestionPricing' - final status: FAILED!


```

### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
Closed by #1748
