### ISSUE TITLE
TransactionHistory-NDReconnect-1-16m failed for not able to load saved state

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1744]
### Description

The ErrorValidator reported an exception on node 5:

(Node 5) Exception com.swirlds.platform.internal.SignedStateLoadingException appeared 1 times.

From the output.log, it says the file db backup doesn't exist:
```
2021-07-03 20:13:58.953 INFO  268  ServicesState -   --> Context initialized accordingly on Services node 5
cp: cannot stat '/home/services_nightly_regression/remoteExperiment/data/saved/com.hedera.services.ServicesMain/5/123/2237/PostgresBackup.tar.gz': No such file or directory
cp exited with error code: 1

```

### Steps to reproduce

The slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1625343818397200

Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210703-194741-GCP-Daily-Reconnect-Correctness-6N-1C/TransactionHistory-NDReconnect-1-16m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In swirlds.log:

```
...
2021-07-03 20:13:58.973 23       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Failed to restore postgres sql snapshot: /home/services_nightly_regression/remoteExperiment/data/saved/com.hedera.services.ServicesMain/5/123/2237/SignedState.swh
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:536) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:722) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:974) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0.jar:?]
2021-07-03 20:13:58.979 24       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting
...

```

### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
Not seeing this in last night's regression.
