### ISSUE TITLE
MixedOps-NI-MultiReconnect-6k-39m : ReconnectValidator FAILED NPE

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1793]
### Description

`MixedOps-NI-MultiReconnect-6k-39m` test suit failed with reconnect workflow happening only `once` when it is expected to happen `twice`. 

This happened because the testClients crashed with NPE.

### Steps to reproduce

Run test `MixedOps-NI-MultiReconnect-6k-39m` against `master` of services

### Additional context

```
2021-07-13 16:28:11.505 INFO   229  RunLoadTest - Total Ops submitted 450665, actual TPS 2503.6943
2021-07-13 16:28:11.506 INFO   324  HapiApiSpec - 'RunCryptoTransfers' finished initial execution of RunLoadTest{}
2021-07-13 16:28:11.531 INFO   212  HapiGetAccountBalance - 'RunCryptoTransfers' - balance for 'sender': 62236791496 tinyBars (622ħ)
2021-07-13 16:28:11.534 INFO   137  HapiGetAccountBalance - Explicit token balances: []
2021-07-13 16:28:11.537 INFO   324  HapiApiSpec - 'RunCryptoTransfers' finished initial execution of HapiGetAccountBalance{sigs=0, node=0.0.6, account=sender}
2021-07-13 16:28:11.541 INFO   393  HapiApiSpec - 'RunCryptoTransfers' - executed 450673 ledger ops.
2021-07-13 16:28:11.541 INFO   394  HapiApiSpec - 'RunCryptoTransfers' - now finalizing 2103 more pending ops...
2021-07-13 16:28:12.104 INFO   343  HapiApiSpec - 'RunCryptoTransfers' - final status: PASSED!
2021-07-13 16:28:12.104 INFO   174  CryptoTransferLoadTest - -------------- RESULTS OF CryptoTransferLoadTest SUITE --------------
2021-07-13 16:28:12.104 INFO   176  CryptoTransferLoadTest - Spec{name=RunCryptoTransfers, status=PASSED}
Exception in thread "main" java.lang.NullPointerException
	at com.hedera.services.bdd.suites.HapiApiSuite.lambda$reportStats$7(HapiApiSuite.java:189)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.HapiApiSuite.reportStats(HapiApiSuite.java:190)
	at com.hedera.services.bdd.suites.HapiApiSuite.summarizeResults(HapiApiSuite.java:179)
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:148)
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:139)
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:602)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:603)
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:577)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:577)
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:545)
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:466)
```
Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1626073312154400
Test Result Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1626073258208400

### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

**Comment by anighanta** [comment]
Issue created to remove the stats related code [here](https://github.com/hashgraph/hedera-services/issues/1800)

**Comment by anighanta** [comment]
Fixed with PR https://github.com/hashgraph/hedera-services/pull/1819
