### ISSUE TITLE
Query-Restart-Performance-6N-6C-10k-31m : DUPLICATE_TRANSACTION 

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1799]
### Description

JRS test `Query-Restart-Performance-6N-6C-10k-31m` fails with `DUPLICATE_TRANSACTION` who trying to get the transaction record of the unique payer cryptoCreate txn. 

**Possible Resolution**

Suppress `DUPLICATE_TRANSACTION` for queries `getTxnRecord` and `getAccountInfo` in `CryptoCreateForSuiteRunner` as we loop over these queries and reRun them until we get the data.

### Steps to reproduce

Run test `Query-Restart-Performance-6N-6C-10k-31m` against `master`. Please be aware that this happens rarely.

### Additional context

```
2021-07-13 06:43:11.452 INFO   143  CryptoCreateForSuiteRunner - -------------- STARTING CryptoCreateForSuiteRunner SUITE --------------
2021-07-13 06:43:11.459 INFO   57   MapPropertySource - Initializing a MapPropertySource from {nodes=34.139.249.227:0.0.3, default.node=0.0.3}
2021-07-13 06:43:12.032 INFO   143  HapiApiClients - Constructed 18 new stubs building clients for HapiApiClients{node0=NodeConnectInfo{host=34.139.249.227, port=50211, tlsPort=50212, account=0.0.3}, default=0.0.3}
2021-07-13 06:43:12.706 INFO   146  FeesAndRatesProvider - The exchange rates are :: [Current hbar/cent equiv 1 <-> 12 expiry @ 4102444800, Next hbar/cent equiv 1 <-> 15 expiry @ 4102444800]
2021-07-13 06:43:12.744 INFO   164  FeesAndRatesProvider - The fee schedule covers 50 ops.
2021-07-13 06:43:12.902 INFO   148  HapiTxnOp - 'CreatePayerAccountForEachClient' -  submitting HapiCryptoCreate{payer=DEFAULT_PAYER, node=0.0.3, account=payerAccount, balance=500000000000000} via body=transactionID { transactionValidStart { seconds: 1626158532 nanos: 497 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 8478339 transactionValidDuration { seconds: 120 } memo: "ITGORKZNRXRVFCNVLYOLAUVCKQTFQPSRKRHGRIDXTGDPGANIVUCLONVCFQVPSSCB" cryptoCreateAccount { key { keyList { keys { ed25519: "\n\250\342\020d\306\036\253\206\342\251\301dV[Nz\232AF\020n\nl\320:\2149Z\021\016\222" } } } initialBalance: 500000000000000 proxyAccountID { } sendRecordThreshold: 5000000000000000000 receiveRecordThreshold: 5000000000000000000 autoRenewPeriod { seconds: 7776000 } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\027\0025{\322l#\241\203j\326s\323\"hQ\227\304\234\023\225\273F\345\316\\\315\204P5\243p\202\210UU\343:n\372il\270\006\t\367SP\232\324\326\214\233\244b\fwxzJ\3179\343\017" }
2021-07-13 06:43:13.486 INFO   235  HapiQueryOp - 'CreatePayerAccountForEachClient' - Paying for COST_ANSWER of HapiGetTxnRecord{node=0.0.3, txn=txn} with body=transactionID { transactionValidStart { seconds: 1626158533 nanos: 501 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84163 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } } accountAmounts { accountID { accountNum: 3 } } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\314J1\315\340x\375\343\271c\246\006\034\017\354+\0036gS\b\016j\312\336D\223\312\370\tM\376\341\246\354\337Sm\347z\356J\017\223`@YHf\270\363W\016\0054\306\264\3513\3241\2741\003" }
2021-07-13 06:43:13.500 INFO   259  HapiQueryOp - 'CreatePayerAccountForEachClient' - --> Node payment for HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn} is 8 tinyBars.
2021-07-13 06:43:13.506 INFO   159  HapiQueryOp - 'CreatePayerAccountForEachClient' - Paying for HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn} with body=transactionID { transactionValidStart { seconds: 1626158533 nanos: 503 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84163 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\006 w\362\211\343j\213\265u\223\023\373\337X\365\262_||\265m\332\005\210;\376\005\234\327\316\237\223\267\377\310#fv#\340B-\252J1\252\321x\006\1779\324Q\004uQ\316\033jr\227\230\016" }
2021-07-13 06:43:13.535 INFO   305  HapiGetTxnRecord - Record (charged $0.0000): 
2021-07-13 06:43:13.536 ERROR  184  HapiQueryOp - Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
2021-07-13 06:43:13.539 WARN   214  HapiSpecOperation - 'CreatePayerAccountForEachClient' - HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn} failed - {}
com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
	at com.hedera.services.bdd.spec.queries.HapiQueryOp.submitOp(HapiQueryOp.java:186) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:36) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:45) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.crypto.CryptoCreateForSuiteRunner.lambda$createAccount$0(CryptoCreateForSuiteRunner.java:102) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.submitOp(CustomSpecAssert.java:61) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:319) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:227) [SuiteRunner.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1799) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
2021-07-13 06:43:13.544 ERROR  38   CustomSpecAssert - Operation 'HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn}' :: Bad answerOnlyPrecheck! expected OK, actual DUPLICATE_TRANSACTION
2021-07-13 06:43:13.550 INFO   235  HapiQueryOp - 'CreatePayerAccountForEachClient' - Paying for COST_ANSWER of HapiGetTxnRecord{node=0.0.3, txn=txn} with body=transactionID { transactionValidStart { seconds: 1626158533 nanos: 505 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84163 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } } accountAmounts { accountID { accountNum: 3 } } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\032}yLV&\275\026\214\341Q\341\036\034wK\251F\377\237\305\343\025\230\372\351\252\345\020q\366\355\027\267\237\304&\247\006\332\tra\311\"r-\202\356\245\344\2105\346\022\326R\272e\266j\342\233\v" }
2021-07-13 06:43:13.557 INFO   259  HapiQueryOp - 'CreatePayerAccountForEachClient' - --> Node payment for HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn} is 8 tinyBars.
2021-07-13 06:43:13.563 INFO   159  HapiQueryOp - 'CreatePayerAccountForEachClient' - Paying for HapiGetTxnRecord{sigs=1, node=0.0.3, txn=txn} with body=transactionID { transactionValidStart { seconds: 1626158533 nanos: 507 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84163 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\342p\276\"\374\216X\315\214\251W\f\347\024\334\304\267\354{\214&\367Jd\205\035q4\371\266\213\356Ju\231\325\251\0006\316\226\247\251\004\211\017\357@\351\003=_[c\347\342\023]<\221\333\375\265\005" }
```

Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1626160510157500
Test Result Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1626160461248000

### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

**Comment by anighanta** [comment]
Fixed by https://github.com/hashgraph/hedera-services/pull/1888
