### ISSUE TITLE
MixedOps-NI-3NReconnect-6k-24m : ReconnectException -> 0 instead of COMM_STATE_ACK or COMM_STATE_NACK

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1803]
### Description

`MixedOps-NI-3NReconnect-6k-24m` fails during reconnect with exception
```
2021-07-13 08:51:12.274 177      ERROR EXCEPTION        <<platform-core: syncCaller-0 13 #0>> SyncCaller: Error while receiving a signed state! {"causeOfFailure":"ERROR"} [com.swirlds.logging.payloads.ReconnectFailurePayload]
com.swirlds.platform.reconnect.ReconnectException: com.swirlds.common.io.BadIOException: COMM_STATE_REQUEST was sent but reply was 0 instead of COMM_STATE_ACK or COMM_STATE_NACK
	at com.swirlds.platform.reconnect.ReconnectReceiver.execute(ReconnectReceiver.java:158) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.receiveStateFromNeighbor(SyncCaller.java:554) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.doReconnect(SyncCaller.java:474) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.callRequestSync(SyncCaller.java:161) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SyncCaller.run(SyncCaller.java:113) [swirlds-platform-core-0.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.io.BadIOException: COMM_STATE_REQUEST was sent but reply was 0 instead of COMM_STATE_ACK or COMM_STATE_NACK
	at com.swirlds.platform.reconnect.ReconnectReceiver.isNodeReadyForReconnect(ReconnectReceiver.java:200) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectReceiver.execute(ReconnectReceiver.java:144) ~[swirlds-platform-core-0.16.0.jar:?]
	... 5 more
```

Reconnect is retried and the node successfully reconnects.

Slack Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1626167879158400
Test Result Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1626166873263100

### Steps to reproduce

Run test `MixedOps-NI-3NReconnect-6k-24m` on `master` or `release/0.16`

### Hedera network

other

### Version

v0.16.0

### Operating system

Other

**Comment by tinker-michaelj** [comment]
Seems a transient failure.
