### ISSUE TITLE
Tests starting with a pre 0.16.0 state Fail with FAIL_FEE NPE 

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1823]
### Description

Tests starting with a pre 0.16.0 state Fail with FAIL_FEE NPE as we don't add subTypes of cryptoTrasnfer to the feeSchedule.

**Solution**

Add untypedPrices for each subType in case of cryptoTransfer [here](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/fees/calculation/AwareFcfsUsagePrices.java#L206)

### Steps to reproduce

For example run test `HTS-Restart-Performance-Hotspot-10k-61m` against `master`

### Additional context
```
2021-07-16 04:44:54.781 WARN   170  FeeCalculator - Unable to calculate fee for op CryptoTransfer, using max fee!
java.lang.NullPointerException: null
	at com.hederahashgraph.fee.FeeBuilder.getFeeObject(FeeBuilder.java:149) ~[SuiteRunner.jar:?]
	at com.hederahashgraph.fee.FeeBuilder.getFeeObject(FeeBuilder.java:169) ~[SuiteRunner.jar:?]
	at com.hederahashgraph.fee.FeeBuilder.getTotalFeeforRequest(FeeBuilder.java:138) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeeCalculator.forOp(FeeCalculator.java:168) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeeCalculator.forActivityBasedOp(FeeCalculator.java:127) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.transactions.crypto.HapiCryptoTransfer.feeFor(HapiCryptoTransfer.java:284) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.finalizedTxn(HapiSpecOperation.java:317) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.finalizedTxn(HapiSpecOperation.java:282) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:145) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:36) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:45) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.ProviderRun.submitOp(ProviderRun.java:109) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:194) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:319) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:227) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:255) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:146) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:139) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:602) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:603) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:577) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:577) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:545) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:466) [SuiteRunner.jar:?]
2021-07-16 04:44:54.787 INFO   148  HapiTxnOp - 'RunTokenTransfers' -  submitting HapiCryptoTransfer{node=0.0.3} via body=transactionID { transactionValidStart { seconds: 1626410634 nanos: 183 } accountID { accountNum: 2102541 } } nodeAccountID { accountNum: 3 } transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { tokenTransfers { token { tokenNum: 2102548 } transfers { accountID { accountNum: 2102547 } amount: -10000 } transfers { accountID { accountNum: 2102549 } amount: 10000 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\217\\\201\003\300\210[R\335YG\264\005\230f\337\334\324L\2540\377m#\214\005 .rl\004:\323\017 5\222\275LA\212t\373\310\277\301\236(T\250\263T\356\025P\021X\032]t\264\177\264\006" } sigPair { pubKeyPrefix: "\026" ed25519: "\'\326\200-G\221Z\320\035\242&p]7o\177kG,\006\v\352\352\2000\027\034\374\214b\243)`\313\363q\233T\033\333+\310#^4\033R\224\253Y\377b\362\371\353=\353\354\031\n>\030\356\004" }
2021-07-16 04:44:54.793 INFO   208  HapiTxnOp - 'RunTokenTransfers' -  HapiCryptoTransfer{sigs=2, node=0.0.3, transfers=[], tokenTransfers=0.0.2102548([0.0.2102547 -> -10000, 0.0.2102549 <- +10000])([])} Wrong actual precheck status FAIL_FEE, expecting OK
2021-07-16 04:44:54.795 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - HapiCryptoTransfer{sigs=2, node=0.0.3, transfers=[], tokenTransfers=0.0.2102548([0.0.2102547 -> -10000, 0.0.2102549 <- +10000])([])} failed Wrong precheck status! Expected OK, actual FAIL_FEE!
```

Summary Link : https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1626418341165500
Test Result Link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1626414307348800
### Hedera network

other

### Version

v0.16.0

### Operating system

Linux

**Comment by abhishek-hedera** [comment]
The test failed again today,
Test Result Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1626759791496800
Test Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1626763813000500

```
---- HAPIClientValidator FAILED validation ----
<<ERROR>>
java.lang.NullPointerException: null
2021-07-20 04:43:02.386 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.3, transfers=[], tokenTransfers=0.0.2102548([0.0.2102547 -> -10000, 0.0.2102549 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:02.386 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
java.lang.NullPointerException: null
2021-07-20 04:43:16.370 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.4, transfers=[], tokenTransfers=0.0.2102560([0.0.2102559 -> -10000, 0.0.2102562 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:16.370 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
java.lang.NullPointerException: null
2021-07-20 04:43:17.013 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.5, transfers=[], tokenTransfers=0.0.2102563([0.0.2102561 -> -10000, 0.0.2102564 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:17.013 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
java.lang.NullPointerException: null
2021-07-20 04:43:13.990 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.6, transfers=[], tokenTransfers=0.0.2102552([0.0.2102550 -> -10000, 0.0.2102554 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:13.990 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
java.lang.NullPointerException: null
2021-07-20 04:43:15.096 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.7, transfers=[], tokenTransfers=0.0.2102557([0.0.2102555 -> -10000, 0.0.2102558 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:15.096 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
java.lang.NullPointerException: null
2021-07-20 04:43:14.484 ERROR  38   CustomSpecAssert - Operation 'HapiCryptoTransfer{sigs=2, node=0.0.8, transfers=[], tokenTransfers=0.0.2102553([0.0.2102551 -> -10000, 0.0.2102556 <- +10000])([])}' :: Wrong precheck status! Expected OK, actual FAIL_FEE
2021-07-20 04:43:14.484 WARN   216  HapiSpecOperation - 'RunTokenTransfers' - ProviderRuncom.hedera.services.bdd.spec.exceptions.HapiTxnPrecheckStateException: Wrong precheck status! Expected OK, actual FAIL_FEE failed {}!
ClientNode - Suite                    Result   Failures
Node 0 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
Node 1 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
Node 2 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
Node 3 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
Node 4 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
Node 5 - TokenTransfersLoadProvider   FAILED   RunTokenTransfers
Exceptions:3
<<INFO>>
ClientNode - Suite                    Result
Node 0 - CryptoCreateForSuiteRunner   PASSED
Node 0 - AdjustFeeSchedule            PASSED
Node 1 - CryptoCreateForSuiteRunner   PASSED
Node 1 - AdjustFeeSchedule            PASSED
Node 2 - CryptoCreateForSuiteRunner   PASSED
Node 2 - AdjustFeeSchedule            PASSED
Node 3 - CryptoCreateForSuiteRunner   PASSED
Node 3 - AdjustFeeSchedule            PASSED
Node 4 - CryptoCreateForSuiteRunner   PASSED
Node 4 - AdjustFeeSchedule            PASSED
Node 5 - CryptoCreateForSuiteRunner   PASSED
Node 5 - AdjustFeeSchedule            PASSED
```

**Comment by anighanta** [comment]
fixed by PR https://github.com/hashgraph/hedera-services/pull/1838
