### ISSUE TITLE
TransactionHistory-NDReconnect-1-16m: failed for SignedStateLoadingException 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1879]
### Description

In last night's regression, this reconnect failed for node 5 (reconnecting node) has the exception when restoring the state.

Seems like platform's recent merging into `develop` has introduced some issue here.

### Steps to reproduce

The slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1627287018233400
and results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210726-073358-GCP-Daily-Reconnect-Correctness-6N-1C/TransactionHistory-NDReconnect-1-16m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

The slack summary link: https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1627298285019300

### Additional context

In node 5's swirlds.log, notice the following error message:

```
2021-07-26 08:00:38.572 23       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Failed to restore postgres sql snapshot: /home/services_nightly_regression/remoteExperiment/data/saved/com.hedera.services.ServicesMain/5/123/2224/SignedState.swh
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:536) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:722) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:974) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0.jar:?]
2021-07-26 08:00:38.579 24       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting

```

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by tinker-michaelj** [comment]
Seems a transient failure with PostgreSQL.
