### ISSUE TITLE
MixedOps-InterruptedReconnect-6k-41m  failed due to server terminated prematurely

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1902]
### Description

The test ended prematurely because of reconnect failure. 

This happens to several other tests as well. 

### Steps to reproduce

Checkout the slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1627550766351000 
and results URL: 

https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210729-083247-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-InterruptedReconnect-6k-41m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In regression.log, it shows the reconnect did go through:
```
NFO  2021-07-29 09:25:34,926  [main] testRunners.MultiReconnectRun (MultiReconnectRun.java:104) - MULTIREC Starting network on: 14
TRACE 2021-07-29 09:25:35,050  [pool-7-thread-14] regression.SSHService (SSHService.java:499) - 'ReviveNetwork' command:
sudo -n iptables -D INPUT -p tcp --dport 10000:65535 -j DROP; sudo -n iptables -D OUTPUT -p tcp --sport 10000:65535 -j DROP;
exit status: 0 :: null
INFO  2021-07-29 09:25:35,050  [main] testRunners.MultiReconnectRun (MultiReconnectRun.java:106) - MULTIREC Waiting for reconnect to start on: 14
ERROR 2021-07-29 09:25:45,050  [main] regression.Experiment (Experiment.java:1124) - Test run had an exception
java.lang.RuntimeException: Exception while running SSH command
	at com.swirlds.regression.ssh.SSHExecutor.runTasks(SSHExecutor.java:133) ~[regression.jar:?]
	at com.swirlds.regression.ssh.SSHExecutor.runCommand(SSHExecutor.java:85) ~[regression.jar:?]
	at com.swirlds.regression.ssh.SSHExecutor.runCommandSingle(SSHExecutor.java:58) ~[regression.jar:?]
	at com.swirlds.regression.testRunners.MultiReconnectRun.reviveAndWait(MultiReconnectRun.java:107) ~[regression.jar:?]
	at com.swirlds.regression.testRunners.MultiReconnectRun.runTest(MultiReconnectRun.java:89) ~[regression.jar:?]
	at com.swirlds.regression.Experiment.runRemoteExperiment(Experiment.java:1113) [regression.jar:?]
	at com.swirlds.regression.RegressionMain.runExperiments(RegressionMain.java:276) [regression.jar:?]
	at com.swirlds.regression.RegressionMain.RunCloudExperiment(RegressionMain.java:148) [regression.jar:?]
	at com.swirlds.regression.RegressionMain.RunRegression(RegressionMain.java:120) [regression.jar:?]
	at com.swirlds.regression.RegressionMain.main(RegressionMain.java:539) [regression.jar:?]
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[?:?]
	at com.swirlds.regression.ssh.SSHExecutor.runTasks(SSHExecutor.java:128) ~[regression.jar:?]
	... 9 more
TRACE 2021-07-29 09:25:45,093  [pool-7-thread-18] regression.SSHService (SSHService.java:499) - 'test if connection broken' command:
echo test
exit status: 0 :: null
TRACE 2021-07-29 09:25:45,093  [pool-7-thread-4] regression.SSHService (SSHService.java:499) - 'test if connection broken' command:


```

In client node 0's hapi-client-combined.log, there is no normal ending summary:
```
2021-07-29 09:24:37.102 INFO   158  FeesAndRatesProvider - The fee schedule covers 56 ops.
2021-07-29 09:24:37.107 INFO   42   CustomSpecAssert - PerfTestLoadSettings{tps=120, totalClients=1, mins=3, tolerance=5, burstSize=5, allowedSecsBelow=60, threads=1, totalTestAccounts=2, totalTestTopics=1, totalTestTokens=1, durationCreateTokenAssociation=60, durationTokenTransfer=60, testActiveTokenAccounts=2, testTreasureStartAccount=1001, submitMessageSize=256, submitMessageSizeVar=64, memoLength=25, totalTokenAssociations=0, totalScheduledTransactions=0, initialBalance=100000000000000, testTopicId=30000, balancesExportPeriodSecs=60, clientToExportBalances=false}
2021-07-29 09:24:37.108 INFO   324  HapiApiSpec - 'RunCreateTopics' finished initial execution of LogMessage{}
2021-07-29 09:24:37.111 INFO   256  RunLoadTest - Thread thread0 ops 1 current TPS Infinity
2021-07-29 09:24:47.112 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1
2021-07-29 09:24:57.114 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1
2021-07-29 09:25:07.115 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1
2021-07-29 09:25:17.115 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1
2021-07-29 09:25:27.116 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.08799
2021-07-29 09:25:37.117 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1
2021-07-29 09:25:47.118 INFO   256  RunLoadTest - Thread thread0 ops 1201 current TPS 120.1

```

In server node 0's hgcaa.log:

```
2021-07-29 09:21:02.934 INFO  147  SignedStateBalancesExporter - Took 2203ms to summarize signed state balances
2021-07-29 09:21:03.482 INFO  164  SignedStateBalancesExporter -  -> Took 547ms to export and sign proto balances file at 2021-07-29T09:21:00.032474Z
2021-07-29 09:22:02.559 INFO  147  SignedStateBalancesExporter - Took 1813ms to summarize signed state balances
2021-07-29 09:22:03.126 INFO  164  SignedStateBalancesExporter -  -> Took 566ms to export and sign proto balances file at 2021-07-29T09:22:00.144456Z
2021-07-29 09:23:02.795 INFO  147  SignedStateBalancesExporter - Took 2070ms to summarize signed state balances
2021-07-29 09:23:03.299 INFO  164  SignedStateBalancesExporter -  -> Took 503ms to export and sign proto balances file at 2021-07-29T09:23:00.141248Z
2021-07-29 09:24:02.666 INFO  147  SignedStateBalancesExporter - Took 1808ms to summarize signed state balances
2021-07-29 09:24:03.166 INFO  164  SignedStateBalancesExporter -  -> Took 499ms to export and sign proto balances file at 2021-07-29T09:24:00.184184Z
2021-07-29 09:25:02.909 INFO  147  SignedStateBalancesExporter - Took 2211ms to summarize signed state balances
2021-07-29 09:25:03.526 INFO  164  SignedStateBalancesExporter -  -> Took 616ms to export and sign proto balances file at 2021-07-29T09:25:00.134196Z
2021-07-29 09:25:45.209 INFO  262  ServicesMain - Terminating Netty on port 50211...

```

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
In today (8/12/2021) regression, this test failed for node1's services not able to bind to IP address:

```
2021-08-12 09:05:35.854 WARN  104  NettyGrpcServerManager - (Attempts=89) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-12 09:05:36.856 WARN  104  NettyGrpcServerManager - (Attempts=90) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-12 09:05:37.858 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#1!
java.lang.IllegalStateException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:84) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:882) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.17.1.jar:?]
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at io.grpc.netty.NettyServer.start(NettyServer.java:328) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:179) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.39.0.jar:1.39.0]
	at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:109) ~[HederaNode.jar:?]
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:77) ~[HederaNode.jar:?]
	... 6 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:455) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:447) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:219) ~[?:?]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:134) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-transport-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.66.Final.jar:4.1.66.Final]
	at java.lang.Thread.run(Thread.java:835) ~[?:?]
2021-08-12 09:05:37.863 INFO  256  ServicesMain - Terminating Netty on port 50211...

```

**Comment by abhishek-hedera** [comment]
In today (8/17/2021) regression, the test failed for node 8 not being able to bind to IP address

```
2021-08-17 09:06:29.285 WARN  104  NettyGrpcServerManager - (Attempts=89) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-17 09:06:30.286 WARN  104  NettyGrpcServerManager - (Attempts=90) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-17 09:06:31.287 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#8!
java.lang.IllegalStateException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:84) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:882) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.17.1.jar:?]
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at io.grpc.netty.NettyServer.start(NettyServer.java:328) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:179) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.39.0.jar:1.39.0]
	at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:109) ~[HederaNode.jar:?]
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:77) ~[HederaNode.jar:?]
	... 6 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2021-08-17 09:06:31.292 INFO  256  ServicesMain - Terminating Netty on port 50211...
```

**Comment by tinker-michaelj** [comment]
This test is generally passing in `master` now.
