### ISSUE TITLE
SignedStateLoadingException : Tests starting from a saved state are failing.

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#1942]
### Description

Test starting from a saved state are failing with : 

```
2021-08-05 04:40:00.907 12       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:529) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:722) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:974) [swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.16.0.jar:?]
Caused by: java.time.DateTimeException: Instant exceeds minimum or maximum instant
	at java.time.Instant.create(Instant.java:411) ~[?:?]
	at java.time.Instant.ofEpochSecond(Instant.java:330) ~[?:?]
	at com.hedera.services.state.submerkle.RichInstant.toJava(RichInstant.java:115) ~[?:?]
	at com.hedera.services.state.merkle.MerkleNetworkContext.readCongestionControlData(MerkleNetworkContext.java:239) ~[?:?]
	at com.hedera.services.state.merkle.MerkleNetworkContext.deserialize(MerkleNetworkContext.java:212) ~[?:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.finishReadingLeaf(MerkleDataInputStream.java:97) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:148) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:202) ~[swirlds-common-0.16.0.jar:?]
	at com.swirlds.platform.SignedStateFileManager.readSavedState(SignedStateFileManager.java:303) ~[swirlds-platform-core-0.16.0.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:501) ~[swirlds-platform-core-0.16.0.jar:?]
	... 3 more

```

### Steps to reproduce

Run any of the tests : 
`HTS-Restart-Performance-Hotspot-10k-61m`
`HTS-Restart-Performance-Random-10k-61m`
`MixedOps-NI-MultiReconnect-6k-39m`
 so on.. 

### Hedera network

other

### Version

v0.17.0-alpha

**Comment by anighanta** [comment]
Revert version checks removed from `MerkleNetworkContext#deserialize`
