### ISSUE TITLE
AutoRenewEntity-NIReconnect-1-20m failed for deserialization running into EOFException when processing sync message

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#1987]
### Description

The error happens to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7)( com.swirlds.common.merkle.synchronization.AckMessage)

The same error happens to many other regression tests as well: 

TokenDeleteValidate-NIReconnect-1-16m
TokenValidate-NIReconnect-1-16m
CongestionPricing-NIReconnect-1-16m
etc.

Seems like this is caused by new 0.17.1 SDK.

### Steps to reproduce

The slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1628681333436300
and the results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210811-073341-GCP-Daily-Reconnect-Correctness-6N-1C/AutoRenewEntity-NIReconnect-1-20m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In node 0,3's swirlds.log:

```
2021-08-11 11:18:35.585 72       ERROR RECONNECT        <<platform-core: syncListener-5 0 #0>> ReconnectSender: Work Group Exception [ groupName = sending-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:156) ~[swirlds-common-0.17.1.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:149) ~[swirlds-common-0.17.1.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:115) [swirlds-common-0.17.1.jar:?]
	at com.swirlds.common.merkle.synchronization.SendingSynchronizer.synchronize(SendingSynchronizer.java:143) [swirlds-common-0.17.1.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.reconnect(ReconnectSender.java:213) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.reconnect.ReconnectSender.execute(ReconnectSender.java:138) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:333) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:174) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:126) [swirlds-platform-core-0.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: com.swirlds.common.merkle.synchronization.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.AckMessage)
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:127) ~[swirlds-common-0.17.1.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:97) ~[swirlds-common-0.17.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readBoolean(DataInputStream.java:249) ~[?:?]
	at com.swirlds.common.merkle.synchronization.AckMessage.deserialize(AckMessage.java:59) ~[swirlds-common-0.17.1.jar:?]
	at com.swirlds.common.merkle.synchronization.AsyncInputStream.run(AsyncInputStream.java:120) ~[swirlds-common-0.17.1.jar:?]
	at com.swirlds.common.threading.StandardWorkGroup.lambda$execute$0(StandardWorkGroup.java:97) ~[swirlds-common-0.17.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
2021-08-11 11:18:35.593 73       ERROR EXCEPTION        <<platform-core: syncListener-5 0 #0>> SyncListener: ! SyncListener.sync Exception (so incrementing interruptedRecSyncsPerSecond) while 0 listening for 5:


```

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
fixed by https://github.com/hashgraph/hedera-services/pull/1997
