### ISSUE TITLE
AllProtectedFilesUpdate-NDReconnect-1-16m failed with Node 5 not binding to IP address

### ISSUE THREAD

**Issue by abhishek-hedera** [hashgraph/hedera-services#2036]
### Description

The test ended prematurely as Node 5 services was unable to bind to IP address.

### Steps to reproduce

Slack Report Link - https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1629185828069900
Summary Link - https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1629198188046500

https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210817-073302-GCP-Daily-Reconnect-Correctness-6N-1C/AllProtectedFilesUpdate-NDReconnect-1-16m;tab=objects?project=hedera-regression&prefix=&forceOnObjectsSortingFiltering=false&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))

### Additional context

Node 5 hgcaa.log

```
2021-08-17 07:36:04.163 WARN  104  NettyGrpcServerManager - (Attempts=89) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-17 07:36:05.164 WARN  104  NettyGrpcServerManager - (Attempts=90) Still trying to start Netty with TLS support on port 50212...Failed to bind to address 0.0.0.0/0.0.0.0:50212
2021-08-17 07:36:06.166 ERROR 100  ServicesMain - Fatal precondition violated in HederaNode#5!
java.lang.IllegalStateException: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:84) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.startNettyIfAppropriate(ServicesMain.java:224) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.contextDrivenInit(ServicesMain.java:168) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:97) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:882) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.17.1.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.17.1.jar:?]
Caused by: java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:50212
	at io.grpc.netty.NettyServer.start(NettyServer.java:328) ~[grpc-netty-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:179) ~[grpc-core-1.39.0.jar:1.39.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90) ~[grpc-core-1.39.0.jar:1.39.0]
	at com.hedera.services.grpc.NettyGrpcServerManager.startOneNettyServer(NettyGrpcServerManager.java:109) ~[HederaNode.jar:?]
	at com.hedera.services.grpc.NettyGrpcServerManager.start(NettyGrpcServerManager.java:77) ~[HederaNode.jar:?]
	... 6 more
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
2021-08-17 07:36:06.171 INFO  256  ServicesMain - Terminating Netty on port 50211...
```

Node 5 swirlds.log

```
2021-08-17 07:34:30.929 1        DEBUG STARTUP          <main> Browser: main() started {} [com.swirlds.logging.payloads.NodeStartPayload]
2021-08-17 07:34:31.004 2        DEBUG STARTUP          <main> Browser: About to run startPlatforms()
2021-08-17 07:34:31.018 3        DEBUG STARTUP          <main> Browser: About do crypto instantiation
2021-08-17 07:34:31.034 4        DEBUG STARTUP          <main> Browser: About start loading keys
2021-08-17 07:34:31.469 5        DEBUG STARTUP          <main> Browser: Done loading keys
2021-08-17 07:34:31.470 6        DEBUG STARTUP          <main> Browser: About to start creating Crypto objects
2021-08-17 07:34:32.632 7        DEBUG STARTUP          <main> Browser: Done creating Crypto objects
2021-08-17 07:34:32.633 8        DEBUG STARTUP          <main> Browser: Done with crypto instantiation
2021-08-17 07:34:32.803 9        DEBUG STARTUP          <main> Browser: Starting platforms
2021-08-17 07:34:32.812 10       DEBUG STARTUP          <main> Browser: Scanning the classpath for RuntimeConstructable classes
2021-08-17 07:34:34.452 11       DEBUG STARTUP          <main> Browser: Done with registerConstructables, time taken 1639ms
2021-08-17 07:34:34.659 12       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Starting
2021-08-17 07:34:34.660 13       DEBUG STARTUP          <main> BinaryObjectStore: Recovering Objects [ objectCount = 0, uniqueObjectCount = 0 ]
2021-08-17 07:34:34.683 14       DEBUG STARTUP          <main> BinaryObjectStore: Recovery Finished
2021-08-17 07:34:34.684 15       INFO  STARTUP          <main> SwirldsPlatform: startUpEventFrozenEndTime: 2021-08-17T07:34:44.683625Z
2021-08-17 07:34:34.685 16       INFO  STARTUP          <main> SwirldsPlatform: initialize eventStreamManager
2021-08-17 07:34:35.348 17       INFO  STARTUP          <main> EventFlow: EventFlow.startAll(), forCons.size: 0, forCurr.size: 0, forNext.size: null, forSigs.size: 0, forWork.size: null
```

hapi-client-combined.log ended prematurely
```
2021-08-17 07:37:00.007 INFO   149  HapiTxnOp - 'runTransfersBeforeReconnect' -  submitting HapiCryptoTransfer{node=0.0.3} via body=transactionID { transactionValidStart { seconds: 1629185760 nanos: 305 } accountID { accountNum: 1001 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 3 } amount: 1 } accountAmounts { accountID { accountNum: 2 } amount: -1 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\027\313\277\3401\321\253\375\nr47v\241\260\317\252\235\330\ft\264j\030\273\276\234@\231\325\340\253V\322\021\261\353\270\021\305\n\356a\345\267Q6c#7\347\302\212\032\021]mG\232\025S0\350\a" }
2021-08-17 07:37:01.022 INFO   149  HapiTxnOp - 'runTransfersBeforeReconnect' -  submitting HapiCryptoTransfer{node=0.0.3} via body=transactionID { transactionValidStart { seconds: 1629185761 nanos: 307 } accountID { accountNum: 1001 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 3 } amount: 1 } accountAmounts { accountID { accountNum: 2 } amount: -1 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\'\372\253D[J\027\276\237nW\223k\b\2520G\266\004tH\202#\031\245jI\314c_\276\347\005\250\3763r\026\242\315r\'\033\337\313\032\376\363X\023K\333D\v\370\343\024\n\271\342\306\366\376\v" }
```

### Hedera network

other

### Version

v0.17.0

### Operating system

Linux

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
