### ISSUE TITLE
Crypto-Recovery-EvSave15sTrunc-300-21m failed for INVALID_EVENT_ERROR 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#2084]
### Description

We didn't see this errors before. Seems like something changed in platform SDK.

### Steps to reproduce

The failure slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1630312548087600

The results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210830-070322-GCP-Daily-Recovery-4N-1C/Crypto-Recovery-EvSave15sTrunc-300-21m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

In node2's swirlds.log, we can observe these error messages:

```
2021-08-30 08:19:29.753 23       INFO  PLATFORM_STATUS  <<platform-core: heartbeat 2 to 0 #0>> SwirldsPlatform: Platform status changed. {"oldStatus":"","newStatus":"ACTIVE"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2021-08-30 08:19:29.753 24       INFO  PLATFORM_STATUS  <<platform-core: heartbeat 2 to 0 #0>> SwirldsPlatform: Platform status changed to: ACTIVE
2021-08-30 08:19:29.865 25       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! otherParent missing (1,5,7fe37c46) sp(1,4,0e84720d) op(3,4,441f4567) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.878 26       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! otherParent missing (1,5,7fe37c46) sp(1,4,0e84720d) op(3,4,441f4567) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.878 27       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,5,a3191449) sp(3,4,441f4567) op(2,3,43261571) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.879 28       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,6,2478b7a9) sp(3,5,a3191449) op(1,1,4f05e8b4) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.879 29       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,7,80099536) sp(3,6,2478b7a9) op(1,4,0e84720d) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.879 30       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,8,7a111d58) sp(3,7,80099536) op(2,5,4141b7d3) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.880 31       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! otherParent missing (3,9,c9a669db) sp(3,8,7a111d58) op(1,5,7fe37c46) min gen:-1 most recent event by missing parent creator:(1,4,0e84720d)
2021-08-30 08:19:29.885 32       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! otherParent missing (1,5,7fe37c46) sp(1,4,0e84720d) op(3,4,441f4567) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.886 33       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,5,a3191449) sp(3,4,441f4567) op(2,3,43261571) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.887 34       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (1,6,786d65f8) sp(1,5,7fe37c46) op(1,-1,null) min gen:-1 most recent event by missing parent creator:(1,4,0e84720d)
2021-08-30 08:19:29.887 35       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,6,2478b7a9) sp(3,5,a3191449) op(1,1,4f05e8b4) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:19:29.887 36       ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 2 #0>> EventValidator: 2 Invalid event! selfParent missing (3,7,80099536) sp(3,6,2478b7a9) op(1,4,0e84720d) min gen:-1 most recent event by missing parent creator:(EventImpl=null)
2021-08-30 08:20:59.873 37       INFO  STATE_TO_DISK    <<platform-core: objectFileManager 2 #0>> SignedStateFileManager: Started writing 'Signed state for round 2' to disk
2021-08-30 08:20:59.888 38       DEBUG SNAPSHOT_MANAGER <<platform-core: objectFileManager 2 #0>> SnapshotManager: SnapshotManager: Successfully queued snapshot request [taskType='BACKUP', applicationName='com.hedera.services.ServicesMain', worldId='123', nodeId=2, roundNumber=2, snapshotId=00000003-000000A3-1, timeStarted=2021-08-30T08:20:59.877335Z, timeCompleted=null, complete=false, error=false ]
2021-08-30 08:26:45.985 73       INFO  EVENT_PARSER     <Thread-11> StreamEventParser: From file 2021-08-30T08_22_30.003230000Z.evts read startRunningHash = 790116bd9eaef919711383ba192e304f4f8bc0973ad78f7937462301714b0071a55fb0e81dda249ab77187d3e50f6a64
2021-08-30 08:26:46.022 74       ERROR EXCEPTION        <Thread-11> SingleStreamIterator: parseStream :: got IOException when readSerializable.  {} [com.swirlds.logging.payloads.StreamParseErrorPayload]
java.io.EOFException: null
	at java.io.DataInputStream.readFully(DataInputStream.java:202) ~[?:?]
	at java.io.DataInputStream.readLong(DataInputStream.java:421) ~[?:?]
	at com.swirlds.common.events.ConsensusData.deserialize(ConsensusData.java:77) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:147) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:115) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.events.ConsensusEvent.deserialize(ConsensusEvent.java:78) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:147) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:94) ~[swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.stream.SingleStreamIterator.next(SingleStreamIterator.java:124) [swirlds-common-0.17.3.jar:?]
	at com.swirlds.common.stream.SingleStreamIterator.next(SingleStreamIterator.java:39) [swirlds-common-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventStreamV5(StreamEventParser.java:280) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventStreamFile(StreamEventParser.java:253) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventFile(StreamEventParser.java:223) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.processEventFile(StreamEventParser.java:193) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventFolder(StreamEventParser.java:150) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.eventPlayback(StreamEventParser.java:110) [swirlds-platform-core-0.17.3.jar:?]
	at com.swirlds.platform.StreamEventParser.run(StreamEventParser.java:368) [swirlds-platform-core-0.17.3.jar:?]

```

### Hedera network

other

### Version

v0.18.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
Closed by: https://github.com/swirlds/swirlds-platform-regression/pull/1525
