### ISSUE TITLE
MixedOps-NDReconnect-1.5k-25m failed for corrupted fee schedules in saved state

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#2089]
### Description

Similar error happened some time before when the test tried to modify fee schedule in middle of sending transactions. 
It's strange the fix is still here, but the error occurs again. 

Need more investigation to find out what's changed again.

### Steps to reproduce

Failed test slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1630397259105000

Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210831-072323-GCP-Daily-Comp-Reconnect-6N-1C/MixedOps-NDReconnect-1.5k-25m;tab=objects?authuser=3&prefix=&forceOnObjectsSortingFiltering=false

### Additional context

The error messages in node 5's hgcaa.log

```
2021-08-31 07:56:58.576 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 4096 bytes...
2021-08-31 07:56:58.577 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:56:58.583 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 4096 bytes...
2021-08-31 07:56:58.583 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:56:59.658 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 8192 bytes...
2021-08-31 07:56:59.658 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:56:59.663 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 8192 bytes...
2021-08-31 07:56:59.664 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:57:00.436 INFO  152  SignedStateBalancesExporter - Took 20ms to summarize signed state balances
2021-08-31 07:57:00.447 INFO  174  SignedStateBalancesExporter -  -> Took 11ms to export and sign proto balances file at 2021-08-31T07:57:00.073021Z
2021-08-31 07:57:00.644 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 12288 bytes...
2021-08-31 07:57:00.644 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:57:00.650 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 12288 bytes...
2021-08-31 07:57:00.650 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:57:01.187 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 16384 bytes...
2021-08-31 07:57:01.188 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:57:01.194 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 16384 bytes...
2021-08-31 07:57:01.194 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
2021-08-31 07:57:01.779 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 17940 bytes...
2021-08-31 07:57:01.779 INFO  98   FeeSchedulesManager - ...successful, new schedules will be applied.
2021-08-31 07:57:01.785 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 17940 bytes...
2021-08-31 07:57:01.786 INFO  98   FeeSchedulesManager - ...successful, new schedules will be applied.
2021-08-31 07:57:12.257 INFO  96   FeeSchedulesManager - Trying to parse fee schedules from 4096 bytes...
2021-08-31 07:57:12.257 INFO  101  FeeSchedulesManager - ...unsuccessful, old schedules will remain active. While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
...

2021-08-31 08:05:02.826 INFO  124  ScreenedSysFileProps - Global/dynamic properties overridden in system file are:
  balances.exportDir.path=data/accountBalances/
  balances.exportPeriodSecs=60
  contracts.defaultLifetime=31536000
  ledger.autoRenewPeriod.maxDuration=1000000000
  ledger.autoRenewPeriod.minDuration=10
  rates.intradayChangeLimitPercent=5
  tokens.nfts.areEnabled=true
2021-08-31 08:05:02.861 ERROR 210  HfsSystemFilesManager - Corrupt fee schedules in saved state (\n\207F\n\232\001\b\033\032\225\001\n-\020\200\200\232\246\352\257\343\001\030\303\205\360\340\020 \371\364\266\003(\360\220\304\374B0\272%8\350\002@\305\366\002P\371\364\266\003X\303\374\n\0221\020\200\200\232\246\352\257\343\001\030\263\330\200\216\214\002 \225\317\3566(\207\216\302\310\257\b0\242\327\0048\371,@\321\350.P\225\317\3566X\261\310\257\001\0321\020\200\200\232\246\352\257\343\001\030\263\330\200\216\214\002 \225\317\3566(\207\216\302\310\257\b0\242\327\0048\371,@\321\350.P\225\317\3566X\261\310\257\001\n\201\001\b!\032}\n%\020\200\200\232\246\352\257\343\001\030\216\270\314\034 \206\355\005(\211\356\245r0@8\005@\377\004P\206\355\005X\335\022\022)\020\200\200\232\246\352\257\343\001\030\331\201\307\311\003 \344\320](\217\341\335\244\0160\377\a8M@\363OP\344\320]X\317\253\002\032)\020\200\200\232\246\352\257\343\001\030\331\201\307\311\003 \344\320](\217\341\335\244\0160\377\a8M@\363OP\344\320]X\317\253\002\n\177\b\002\032{\n%\020\200\200\232\246\352\257\343\001\030\370\250\257\t \266\365\001(\373\260\271%0\0258\002@\321\001P\266\365\001X\221\006\022(\020\200\200\232\246\352\257\343\001\030\202\217\365\225\001 \337\326\036(\266\217\226\327\0040\317\0028\031@\227\032P\337\326\036X\226b\032(\020\200\200\232\246\352\257\343\001\030\202\217\365\225\001 \337\326\036(\266\217\226\327\0040\317\0028\031@\227\032P\337\326\036X\226b\n\252\004\b\001\032g\n\035\020\300\273\001\030\316\247\316\003 \315^(\225\336\267\0160\b8\001@QP\315^X\257\002\022\"\020\240\231\002\030\225\230\236H \212\344\016(\234\333\332\240\0020\241\0018\f@\317\fP\212\344\016X\247/\032\"\020\240\231\002\030\225\230\236H \212\344\016(\234\333\332\240\0020\241\0018\f@\317\fP\212\344\016X\247/\032i\n\035\020\300\273\001\030\237\243\347\003 \333c(\250\302\233\0170\t8\001@UP\333cX\277\002\022\"\020\240\231\002\030\356\300\221L \241\312\017(\252\256\246\260\0020\252\0018\r@\246\rP\241\312\017X\3561\032\"\020\240\231\002\030\356\300\221L \241\312\017(\252\256\246\260\0020\252\0018\r@\246\rP\241\312\017X\3561 \001\032n\n \020\300\273\001\030\275\306\316\a \267\307\001(\316\204\267\0360\0218\001@\252\001P\267\307\001X\376\004\022#\020\240\231\002\030\313\201\243\230\001 \302\224\037(\222\334\314\340\0040\324\0028\032@\314\032P\302\224\037X\333c\032#\020\240\231\002\030\313\201\243\230\001 \302\224\037(\222\334\314\340\0040\324\0028\032@\314\032P\302\224\037X\333c \003\032p\n \020\300\273\001\030\262\325\361\n \230\235\002(\372\221\302+0\0308\002@\363\001P\230\235\002X\221\a\022$\020\240\231\002\030\356\253\341\331\001 \351\307,(\212\347\252\346\0060\347\0038%@\203&P\351\307,X\314\216\001\032$\020\240\231\002\030\356\253\341\331\001 \351\307,(\212\347\252\346\0060\347\0038%@\203&P\351\307,X\314\216\001 \002\032p\n \020\300\273\001\030\336\252\343\025 \261\272\004(\332\243\204W018\004@\347\003P\261\272\004X\241\016\022$\020\240\231\002\030\326\326\302\263\003 \323\217Y(\377\311\325\314\r0\315\a8I@\207LP\323\217YX\230\235\002\032$\020\240\231\002\030\326\326\302\263\003 \323\217Y(\377\311\325\314\r0\315\a8I@\207LP\323\217YX\230\235\002 \004\n\216\001\b\003\032\211\001\n)\020\200\200\232\246\352\257\343\001\030\343\326\345\340\001 \210\200.(\245\234\271\202\a0\366\0038&@\240\'P\210\200.X\232\223\001\022-\020\200\200\232\246\352\257\343\001\030\255\354\332\214\034 \200\201\340\005(\316\304\223\247p0\347>8\333\004@\210\364\004P\200\201\340\005X\235\263\022\032-\020\200\200\232\246\352\257\343\001\030\255\354\332\214\034 \200\201\340\005(\316\304\223\247p0\347>8\333\004@\210\364\004P\200\201\340\005X\235\263\022\n\232\001\b\004\032\225\001\n-\020\200\200\232\246\352\257\343\001\030\252\340\202\334\024 \327\330\236\004(\272\206\274\347R0\250.8\275\003@\215\317\003P\327\330\236\004X\317\310\r\0221\020\200\200\232\246\352\257\343\001\030\237\205\254\300\313\002 \363\212\353C(\233\347\300\367\254\n0\372\344\0058\3117@\310\3619P\363\212\353CX\360\211\331\001\0321\020\200\200\232\246\352\257\343\001\030\237\205\254\300\313\002 \363\212\353C(\233\347\300\367\254\n0\372\344\0058\3117@\310\3619P\363\212\353CX\360\211\331\001\n\216\001\b\005\032\211\001\n)\020\200\200\232\246\352\257\343\001\030\334\346\265\337\001 \211\334-(\233\245\372\374\0060\363\0038%@\202\'P\211\334-X\247\222\001\022-\020\200\200\232\246\352\257\343\001\030\271\353\334\366\033 \224\301\333\005(\251\323\244\317o0\266>8\327\004@\234\360\004P\224\301\333\005X\352\244\022\032-\020\200\200\232\246\352\257\343\001\030\271\353\334\366\033 \224\301\333\005(\251\323\244\317o0\266>8\327\004@\234\360\004P\224\301\333\005X\352\244\022\n_\b\025\032[\n\031\020\200\200\232\246\352\257\343\001\030\256\314\003 ^(\372\257\016@\001P^X\002\022\036\020\200\200\232\246\352\257\343\001\030\346\3059 \343\v(\240\377\345\0010\001@\nP\343\vX&\032\036\020\200\200\232\246\352\257\343\001\030\346\3059 \343\v(\240\377\345\0010\001@\nP\343\vX&\nW\b\016\032S\n\027\020\200\200\232\246\352\257\343\001\030\234\254\001 #(\251\260\005P#X\001\022\033\020\200\200\232\246\352\257\343\001\030\304\303\025 \264\004(\230\205V@\004P\264\004X\016\032\033\020\200\200\232\246\352\257\343\001\030\304\303\025 \264\004(\230\205V@\004P\264\004X\016\n_\b\r\032[\n\031\020\200\200\232\246\352\257\343\001\030\246\231\004 n(\272\343\020@\001PnX\003\022\036\020\200\200\232\246\352\257\343\001\030\345\224C \337\r(\236\267\214\0020\001@\fP\337\rX,\032\036\020\200\200\232\246\352\257\343\001\030\345\224C \337\r(\236\267\214\0020\001@\fP\337\rX,\n_\b\017\032[\n\031\020\200\200\232\246\352\257\343\001\030\366\363\003 f(\210\316\017@\001PfX\003\022\036\020\200\200\232\246\352\257\343\001\030\341\276> \345\f(\206\341\371\0010\001@\vP\345\fX)\032\036\020\200\200\232\246\352\257\343\001\030\341\276> \345\f(\206\341\371\0010\001@\vP\345\fX)\nV\b\026\032R\n\026\020\200\200\232\246\352\257\343\001\030\223w \030(\231\334\003P\030X\001\022\033\020\200\200\232\246\352\257\343\001\030\253\362\016 \206\003(\223\303;@\003P\206\003X\n\032\033\020\200\200\232\246\352\257\343\001\030\253\362\016 \206\003(\223\303;@\003P\206\003X\n\n\220\001\b2\032\213\001\n)\020\200\200\232\246\352\257\343\001\030\226\317\270\267\003 \256\366Y(\234\333\253\334\r0\326\a8J@\336LP\256\366YX\341\237\002\022.\020\200\200\232\246\352\257\343\001\030\334\362\211\3676 
...

2021-08-31 08:05:02.866 ERROR 123  ServicesMain - Fatal precondition violated in HederaNode#5
java.lang.IllegalStateException: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:211) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadProtoWithSupplierFallback(HfsSystemFilesManager.java:250) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFeeSchedules(HfsSystemFilesManager.java:149) ~[HederaNode.jar:?]
	at com.hedera.services.state.initialization.SystemFilesManager.loadObservableSystemFiles(SystemFilesManager.java:50) ~[HederaNode.jar:?]
	at com.hedera.services.state.logic.NetworkCtxManager.loadObservableSysFilesIfNeeded(NetworkCtxManager.java:101) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.initSystemFiles(ServicesMain.java:160) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.doStagedInit(ServicesMain.java:132) ~[HederaNode.jar:?]
	at com.hedera.services.ServicesMain.initApp(ServicesMain.java:121) [HederaNode.jar:?]
	at com.hedera.services.ServicesMain.init(ServicesMain.java:64) [HederaNode.jar:?]
	at com.swirlds.platform.SwirldsPlatform.initializeFirstStep(SwirldsPlatform.java:882) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.17.4.jar:?]
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:107) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.pushLimit(CodedInputStream.java:1199) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readMessage(CodedInputStream.java:890) ~[protobuf-java-3.17.3.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.<init>(CurrentAndNextFeeSchedule.java:60) ~[hedera-protobuf-java-api-0.18.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.<init>(CurrentAndNextFeeSchedule.java:13) ~[hedera-protobuf-java-api-0.18.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule$1.parsePartialFrom(CurrentAndNextFeeSchedule.java:866) ~[hedera-protobuf-java-api-0.18.0-SNAPSHOT.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule$1.parsePartialFrom(CurrentAndNextFeeSchedule.java:860) ~[hedera-protobuf-java-api-0.18.0-SNAPSHOT.jar:?]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.17.3.jar:?]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.17.3.jar:?]
	at com.hederahashgraph.api.proto.java.CurrentAndNextFeeSchedule.parseFrom(CurrentAndNextFeeSchedule.java:289) ~[hedera-protobuf-java-api-0.18.0-SNAPSHOT.jar:?]
	at com.hedera.services.state.initialization.HfsSystemFilesManager.loadFrom(HfsSystemFilesManager.java:208) ~[HederaNode.jar:?]
	... 11 more


```

### Hedera network

other

### Version

v0.18.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
Couldn't be reproduced.
