### ISSUE TITLE
JRS regression tests failed due to changes of JRS's main driver

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#2101]
### Description

Latest JRS framework changed the API of `regression` runner, hence all tests using JRS framework failed.

Needs to modify hedera services' Json test files to follow the new APIs.

### Steps to reproduce

The CircleCi build failure URL: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/21504/workflows/2ad2dca8-2153-4255-bb52-c86ce9c7e12b/jobs/81494

or: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/21492/workflows/1f11b9d6-0bdb-4699-a625-f1ea56915482/jobs/81473/parallel-runs/0/steps/0-112

### Additional context

CircleCi log has the following error message:
```
2021-09-01 06:22:01,402 main DEBUG LoggerContext[name=55054057, org.apache.logging.log4j.core.LoggerContext@45efd90f] started OK.
Unmatched argument at index 1: '/repo'
Usage: jrs-regression [-hV] [-d=<maxTestDuration>]
                      [-r=<hederaRepoPath>]
                      [-w=<workflowEngine>]
                      bootConfigFile
      bootConfigFile   the experiment JSON to be loaded
  -d, --max-test-duration=<maxTestDuration>
                       the maximum duration for which
                         a single test may be
                         configured to execute
                         (default: PT4H)
  -h, --help           Show this help message and exit.
  -r, --hedera-repo=<hederaRepoPath>
                       the path to local Hedera
                         Services repository
  -V, --version        Print version information and
                         exit.
  -w, --workflow-engine=<workflowEngine>
                       the workflow engine to use for
                         local/remote node
                         interactions (default:
                         DOCKER_REMOTE)
2021-09-01 06:22:01,567 pool-1-thread-1 DEBUG Stopping LoggerContext[name=55054057, org.apache.logging.log4j.core.LoggerContext@45efd90f]
```

And/or:
```
02:38:45.277 main Experiment Configuration Import Failure [ file = 'configs/services/suites/daily/GCP-Daily-Services-Recovery-4N-1C.json' ]
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "instanceTemplate" (class com.swirlds.regression.jsonConfigs.CloudConfig), not marked as ignorable (13 known properties: "instanceName", "projectName", "clientTemplate", "login", "instanceKey", "instanceType", "regionList", "keyLocation", "service", "ubuntuRemoteInstanceTemplate", "securityGroup", "addressFileLocation", "dockerRemoteInstanceTemplate"])
 at [Source: (byte[])"{
  // NEVER USE: us-central1-c
  "cloud": {
	"service": "gcp",
	"instanceKey": "***************************",
	"keyLocation":"./keys/services-regression",
	"login": "***************************",
	"projectName" : "*****************",
	"instanceTemplate":"atf-node-instance-template-9",
	"regionList": [
	  {
		"region": "us-east1-b",
		"numberOfNodes": 4
	  }
	]
  },
  "eventFilesWriters": 4,
  "recordFilesWriters" : 4
}
"; line: 9, column: 22] (through reference chain: com.swirlds.regression.jsonConfigs.ExperimentConfig["cloud"]->com.swirlds.regression.jsonConfigs.CloudConfig["instanceTemplate"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.impl.MergingSettableBeanProperty.deserializeAndSet(MergingSettableBeanProperty.java:78) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:257) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2081) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1555) ~[jackson-databind-2.11.2.jar:2.11.2]
	at com.swirlds.regression.config.ConfigUtils.importJson(ConfigUtils.java:97) ~[regression.jar:?]
	at com.swirlds.regression.config.ConfigUtils.importJson(ConfigUtils.java:65) ~[regression.jar:?]
	at com.swirlds.jrs.utils.WorkflowUtils.importExperimentConfig(WorkflowUtils.java:146) ~[regression.jar:?]
	at com.swirlds.jrs.workflow.DockerRemoteRegression.initialize(DockerRemoteRegression.java:138) [regression.jar:?]
	at com.swirlds.jrs.cli.MainCommand.call(MainCommand.java:134) [regression.jar:?]
	at com.swirlds.jrs.cli.MainCommand.call(MainCommand.java:50) [regression.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine.access$1300(CommandLine.java:145) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at picocli.CommandLine.execute(CommandLine.java:2078) [picocli-4.6.1.jar:task ':jar' property 'archiveVersion']
	at com.swirlds.jrs.Main.main(Main.java:32) [regression.jar:?]
02:38:45.286 main Shutdown Initiated By Regression Fatal Exception [ exitCode = 18 ]
02:38:45.286 main Finished Workflow Execution
```

### Hedera network

other

### Version

v0.18.0

### Operating system

Linux

**Comment by ljianghedera** [comment]
Needs more effort and support from platform team to resolve `regression` internal issues that prevent hedera services from running.

Temporary solution is to create a branch off of `develop` with previous commit so hedera services can use old version of `develop` to keep running.
