### ISSUE TITLE
File-Recovery-EvSave15sTrunc-5-21m failed for not finishing recovery

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#2114]
### Description

For unknown reason, all server node terminated in ~8 minutes after initial start. This is much shorted than the duration it should run. But no log files have show any obvious reason why the server ended before it should.

Also, the error is random and not easy to reproduce.

### Steps to reproduce

The failed test slack link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1630572500127100

Results URL: https://console.cloud.google.com/storage/browser/hedera-services-jrs-test-results/hedera-services-automation/master/20210902-070325-GCP-Daily-Recovery-4N-1C/File-Recovery-EvSave15sTrunc-5-21m;tab=objects?prefix=&forceOnObjectsSortingFiltering=false&authuser=3

### Additional context

All 4 node's swirlds.log shows that the services java process finished prematuarely:

```
2021-09-02 08:38:13.347 1        DEBUG STARTUP          <main> Browser: main() started {} [com.swirlds.logging.payloads.NodeStartPayload]
2021-09-02 08:38:13.413 2        DEBUG STARTUP          <main> Browser: About to run startPlatforms()
2021-09-02 08:38:13.425 3        DEBUG STARTUP          <main> Browser: About do crypto instantiation
2021-09-02 08:38:13.433 4        DEBUG STARTUP          <main> Browser: About start loading keys
2021-09-02 08:38:13.770 5        DEBUG STARTUP          <main> Browser: Done loading keys
2021-09-02 08:38:13.771 6        DEBUG STARTUP          <main> Browser: About to start creating Crypto objects
...

7722c4b6792e4ac65f7c0106e7379a5a44167538bbb4f75dc1ee23d4deadea12f3c6e64461fb6eb33853817f8dd1f585
2021-09-02 08:45:33.210 69       ERROR EXCEPTION        <Thread-11> SingleStreamIterator: parseStream :: got IOException when readSerializable.  {} [com.swirlds.logging.payloads.StreamParseErrorPayload]
java.io.EOFException: null
	at java.io.DataInputStream.readFully(DataInputStream.java:202) ~[?:?]
	at java.io.DataInputStream.readFully(DataInputStream.java:170) ~[?:?]
	at com.swirlds.common.io.ExtendedDataInputStream.readByteArray(ExtendedDataInputStream.java:70) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.io.ExtendedDataInputStream.readByteArray(ExtendedDataInputStream.java:86) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.events.BaseEventUnhashedData.deserialize(BaseEventUnhashedData.java:78) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:147) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:115) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.events.ConsensusEvent.deserialize(ConsensusEvent.java:77) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:147) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:94) ~[swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.stream.SingleStreamIterator.next(SingleStreamIterator.java:124) [swirlds-common-0.17.4.jar:?]
	at com.swirlds.common.stream.SingleStreamIterator.next(SingleStreamIterator.java:39) [swirlds-common-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventStreamV5(StreamEventParser.java:280) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventStreamFile(StreamEventParser.java:253) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventFile(StreamEventParser.java:223) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.processEventFile(StreamEventParser.java:193) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.parseEventFolder(StreamEventParser.java:150) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.eventPlayback(StreamEventParser.java:110) [swirlds-platform-core-0.17.4.jar:?]
	at com.swirlds.platform.StreamEventParser.run(StreamEventParser.java:368) [swirlds-platform-core-0.17.4.jar:?]
2021-09-02 08:45:33.219 70       ERROR EXCEPTION        <Thread-11> StreamEventParser: Experienced error during parsing file /home/services_nightly_regression/remoteExperiment/data/eventStream/events_0.0.3/2021-09-02T08_41_40.014825000Z.evts {} [com.swirlds.logging.payloads.StreamParseErrorPayload]
2021-09-02 08:45:33.219 71       INFO  EVENT_PARSER     <Thread-11> StreamEventParser: Finished parsing events
2021-09-02 08:45:33.220 72       INFO  EVENT_PARSER     <Thread-11> StreamEventParser: Recovered 0 event from stream file
2021-09-02 08:45:38.147 73       INFO  FREEZE           <<platform-core: platformRun 0 #0>> DualStateImpl: setFreezeTime: null
2021-09-02 08:45:38.147 74       INFO  FREEZE           <<platform-core: platformRun 0 #0>> DualStateImpl: setLastFrozenTimeToBeCurrentFreezeTime: null
2021-09-02 08:45:38.148 75       INFO  EVENT_PARSER     <<platform-core: platformRun 0 #0>> SwirldsPlatform: Inserted 0 event to forCons queue
2021-09-02 08:45:38.148 76       INFO  EVENT_PARSER     <<platform-core: platformRun 0 #0>> SwirldsPlatform: forConsQueueCount 0
2021-09-02 08:45:38.148 77       INFO  EVENT_PARSER     <<platform-core: platformRun 0 #0>> SwirldsPlatform: lastRecoverRoundWithNewUserTran 2068
2021-09-02 08:45:38.148 78       INFO  EVENT_PARSER     <<platform-core: platformRun 0 #0>> SwirldsPlatform: roundOfLastRecoveredEvent 9223372036854775807
2021-09-02 08:45:38.148 79       INFO  EVENT_PARSER     <<platform-core: platformRun 0 #0>> SwirldsPlatform: No event recovered from event files


```

### Hedera network

other

### Version

v0.18.0

### Operating system

Linux

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
