### ISSUE TITLE
yahcli does not return non-zero exit codes 

### ISSUE THREAD

**Issue by tannerjfco** [hashgraph/hedera-services#2425]
### Description

observed when running a freeze-only transaction with yahcli on a network with insufficient funds, that when yahcli exited unsuccessfully, it does not appear to have exited with a non-zero exit code, as our pipeline was able to continue to the next step despite the failure. I am not sure if the screened-launch.sh in the container is masking the exit code or if yahcli is not providing it. Either way, a non-zero exit code should be returned when a yahcli command is not successful

### Steps to reproduce

We specifically observed this on a freeze-only transaction on a test environment, where the freeze account had run out of sufficient funds to download 0.0.112. This transaction was executed within a pipeline, and the pipeline found this command to be successful and continued to the next step

### Additional context

```
/opt/bin/screened-launch.sh --network integration-docker --config integration-docker.config.yml --payer 58 freeze --start-time 2021-11-03.14:29:00
Targeting integration-docker, paying with 0.0.58
2021-11-03 14:27:42.599 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 194 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\003\232\236\230T\214\320\b?b\022@\231\206|.nz\317J&Y7Ql\2315\314M@g\037\321\203G\036|sE\306R\216t\205\217\035\003\222\377\"\274\344\257\253U\222\236\027\331\355\213\034`\b" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.646 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 195 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\350\306*_\243\255!\304/\2675JX\313\242\f\361\274\242hY\335/\375\002\0329\3539\255\2230\226\367D[\017#\333\037\250\364G\006#\212b\215R\026T\t\326X$\313\312\277\307F\273\311\222\r" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.689 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 196 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\345\366D\373\370ab\350j\323\357p8\275\232hf\256\216\002X\272\2603\"\331Z\267\353\202\035\333Z[\030\234L\220\271{O\245\a\246_LG\034S\344=\232\027\313\252\330\247\361\260\3361\242\t\006" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.732 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 197 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\317\362\260>\206+S}\315S\215\206\220\216Bc\002Y\211n(\373\202<C\272\257G\n@&\272\253\371\230A\3532\0377\b\204\376\346\255\317X\333\211\'\020\244\312c\037\304\217gb\2532\023\253\r" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.775 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 198 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\231\271B\331\252u[\2565.1\a\340\1774.99\306a \\\334\276/\006\020\034\036\035\207#R\301V\375\346\217\231,w\316\265\231\314M\3400m\a\210r\321\213\331G\234\034\204\270\r?\212\016" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.821 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 199 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "xP\032\373\362\356\354\362\343\213\304,h\221\303\301J\305\204\254.\260\2059w\354/H\304\374f/\036XW]\001\346\332\202\331\303W\262\361];>\001\333A\205\361\200\365\351u\'\362,\023n\361\003" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.870 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 200 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "Z\n\206$\f2z\360\035\242\305\367\305\336\030x\2453:\222\366n\245A&\200I\264\004\246:Z\221\202\312=\213\321\030\261\2138b\351JE)\300\217\036N>Xv\031\357(-\'W\227\357|\005" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.917 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 201 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "Mx8\370\244\367\a\267G\330\342\224A\236\340\017\217b\375\004\377\376\361`$\320>\354\031Z\315\355\346\273\364\337\307K\037\267\321\301DMf{\232\022\253\030\354a\300\333\236m<\004\2746|^x\r" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:42.962 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 202 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\006]\247:\232hd\365\'\250z\211\224|\004Xl\231\217\032 n\323A%\356f8ft\301\3373\221\332\025&j\331\222w?\211d\261\216\0324\304\265b5\331^J\350\343>\re\366 \377\006" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:43.005 WARN   183  FeesAndRatesProvider - '0.0.112' download attempt paid with body=transactionID { transactionValidStart { seconds: 1635949602 nanos: 203 } accountID { accountNum: 58 } } nodeAccountID { accountNum: 3 } transactionFee: 100000000 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 58 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n\250\342" ed25519: "\226\a\202k\312\271CG%\"\334Z\032\210\300\310M\023\244\307k\274E\357\255\247@8\033@+\033a\003\265\004\306\a\331\032n\277\211X2\271\366;\206\242o`pw\222\264{4\327P\023\016f\005" } got status INSUFFICIENT_PAYER_BALANCE, retrying...
2021-11-03 14:27:43.007 ERROR  253  HapiApiSpec - Fees failed to initialize! Please check if server is down...
java.lang.IllegalStateException: Could not download '0.0.112' final status INSUFFICIENT_PAYER_BALANCE
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:190) ~[yahcli.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:136) ~[yahcli.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:95) ~[yahcli.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.tryReinitializingFees(HapiApiSpec.java:247) ~[yahcli.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:270) ~[yahcli.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:218) ~[yahcli.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:190) ~[yahcli.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:148) [yahcli.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:135) [yahcli.jar:?]
	at com.hedera.services.yahcli.commands.system.FreezeOnlyCommand.call(FreezeOnlyCommand.java:54) [yahcli.jar:?]
	at com.hedera.services.yahcli.commands.system.FreezeOnlyCommand.call(FreezeOnlyCommand.java:34) [yahcli.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953) [yahcli.jar:?]
	at picocli.CommandLine.access$1300(CommandLine.java:145) [yahcli.jar:?]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352) [yahcli.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346) [yahcli.jar:?]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311) [yahcli.jar:?]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) [yahcli.jar:?]
	at picocli.CommandLine.execute(CommandLine.java:2078) [yahcli.jar:?]
	at com.hedera.services.yahcli.Yahcli.main(Yahcli.java:104) [yahcli.jar:?]
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // container
Post stage
[Pipeline] echo
========Run yahcli freeze executed successfully========
```

### Hedera network

other

### Version

gcr.io/hedera-registry/yahcli:0.1.5

### Operating system

Linux

**Comment by anighanta** [comment]
@tannerjfco pushed a new Yahcli build with tag `0.1.6` with non zero exit codes on failures and also added warn logs on failures.
