### ISSUE TITLE
Crypto-Restart-Performance-Random-10k-61m : ParallelExecutionException caused by NPE and IndexOutOfBoundsException

### ISSUE THREAD

**Issue by anighanta** [hashgraph/hedera-services#2498]
### Description
Need platform team clarification. `NodeSynchronizerInstantiator` is bound to be removed with PR https://github.com/swirlds/swirlds-platform/pull/4037. 

```
2021-11-15 05:12:45.613 61       ERROR EXCEPTION        <<platform-core: syncListener-0 2 #0>> SyncListener: ! SyncListener.sync Exception (so incrementing interruptedRecSyncsPerSecond) while 2 listening for 0:
com.swirlds.common.threading.ParallelExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.sync.SyncInputStream.readByte()" because the return value of "com.swirlds.platform.AbstractNodeSynchronizer.getInputStream()" is null
	at com.swirlds.common.threading.CachedPoolParallelExecutor.doParallel(CachedPoolParallelExecutor.java:81) ~[swirlds-common-0.20.0.jar:?]
	at com.swirlds.platform.NodeSynchronizerImpl.syncStep4(NodeSynchronizerImpl.java:579) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.NodeSynchronizerImpl.synchronize(NodeSynchronizerImpl.java:252) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.NodeSynchronizerInstantiator.synchronize(NodeSynchronizerInstantiator.java:108) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsgOrException(SyncListener.java:305) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.SyncListener.handleOneMsg(SyncListener.java:174) [swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.SyncListener.run(SyncListener.java:126) [swirlds-platform-core-0.20.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.sync.SyncInputStream.readByte()" because the return value of "com.swirlds.platform.AbstractNodeSynchronizer.getInputStream()" is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.threading.CachedPoolParallelExecutor.doParallel(CachedPoolParallelExecutor.java:78) ~[swirlds-common-0.20.0.jar:?]
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.sync.SyncInputStream.readByte()" because the return value of "com.swirlds.platform.AbstractNodeSynchronizer.getInputStream()" is null
	at com.swirlds.platform.AbstractNodeSynchronizer.readByte(AbstractNodeSynchronizer.java:453) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.AbstractNodeSynchronizer.readEvents(AbstractNodeSynchronizer.java:391) ~[swirlds-platform-core-0.20.0.jar:?]
	at com.swirlds.platform.NodeSynchronizerImpl.lambda$syncStep4aReadEvents$6(NodeSynchronizerImpl.java:602) ~[swirlds-platform-core-0.20.0.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more

```

Result link : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1636955959330000

Also occurred in [`GCP-Weekly-Comp-NetDelay-15N-1C.Misc-Basic-14-20m`](https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1636969377334000)

### Steps to reproduce

Run test `Crypto-Restart-Performance-Random-10k-61m`

### Hedera network

other

### Version

v0.20.0

**Comment by anighanta** [comment]
refer https://github.com/swirlds/swirlds-platform/issues/3933

**Comment by anighanta** [comment]
fixed by[ PR in regression repo.](https://github.com/swirlds/swirlds-platform-regression/pull/1769/files) and platform fix https://github.com/swirlds/swirlds-platform/pull/4037.
