### ISSUE TITLE
Many regression panels fail with exception during cleanup

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2543]
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1638421104157200
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1638421676157300
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1638424910157500
https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1638427510157700

```
com.swirlds.regression.exceptions.RegressionFatalException: Exception during cleanup process.
    at com.swirlds.jrs.workflow.TestFlow.cleanupProcess(TestFlow.java:308)
    at com.swirlds.jrs.workflow.TestFlow.handleUnknownExceptionDuringTestFlow(TestFlow.java:291)
    at com.swirlds.jrs.workflow.TestFlow.dispatch(TestFlow.java:221)
    at com.swirlds.jrs.workflow.Regression.testExecution(Regression.java:341)
    at com.swirlds.jrs.workflow.Regression.execute(Regression.java:270)
    at com.swirlds.jrs.cli.MainCommand.call(MainCommand.java:174)
    at com.swirlds.jrs.cli.MainCommand.call(MainCommand.java:51)
    at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
    at picocli.CommandLine.access$1300(CommandLine.java:145)
    at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
    at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
    at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    at picocli.CommandLine.execute(CommandLine.java:2078)
    at com.swirlds.jrs.Main.main(Main.java:32)
Caused by: com.swirlds.jrs.exceptions.CommandExecutionException: net.schmizz.sshj.connection.ConnectionException: Timeout expired
    at com.swirlds.jrs.ssh.RemoteCommand.join(RemoteCommand.java:106)
    at com.swirlds.jrs.node.RemoteNode.exec(RemoteNode.java:107)
    at com.swirlds.jrs.node.NodeManager.lambda$execOn$7(NodeManager.java:882)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: net.schmizz.sshj.connection.ConnectionException: Timeout expired
    at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:32)
    at net.schmizz.sshj.connection.ConnectionException$1.chain(ConnectionException.java:26)
    at net.schmizz.concurrent.Promise.retrieve(Promise.java:139)
    at net.schmizz.concurrent.Event.await(Event.java:105)
    at net.schmizz.sshj.connection.channel.AbstractChannel.join(AbstractChannel.java:280)
    at com.swirlds.jrs.ssh.RemoteCommand.join(RemoteCommand.java:104)
    ... 6 more
Caused by: java.util.concurrent.TimeoutException: Timeout expired
    ... 10 more
```

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
