### ISSUE TITLE
Create a new local saved state for regression tests

### ISSUE THREAD

**Issue by qnswirlds** [hashgraph/hedera-services#2624]
Services just removed some code to load (now unsupported) older state. Therefore the current local saved state cannot be loaded any more.

```
2021-12-15 21:36:14.087 12       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:536) ~[swirlds-platform-core-0.21.0.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:722) [swirlds-platform-core-0.21.0.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:974) [swirlds-platform-core-0.21.0.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:364) [swirlds-platform-core-0.21.0.jar:?]
Caused by: com.swirlds.common.io.InvalidVersionException: Illegal version 6 was read from the stream for class com.hedera.services.ServicesState (class ID -8201042766723040486(0x8E300B0DFDAFBB1A)). Expected version in the range 13 - 14
	at com.swirlds.common.io.SerializableDataInputStream.validateVersion(SerializableDataInputStream.java:123) ~[swirlds-common-0.21.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:145) ~[swirlds-common-0.21.0.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:204) ~[swirlds-common-0.21.0.jar:?]
	at com.swirlds.platform.SignedStateFileManager.readSavedState(SignedStateFileManager.java:308) ~[swirlds-platform-core-0.21.0.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:507) ~[swirlds-platform-core-0.21.0.jar:?]
	... 3 more

```

**Comment by netopyr** [comment]
Closed due to inactivity. Please reopen if you think the issue is still relevant.
