### ISSUE TITLE
Deserialization error while loading state from disk

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#2947]
While loading state from disk the following error occurs . The state is generated by running all suites in CI against `0.24.0-alpha.2`

```
2022-03-04 18:29:07.234 10       ERROR EXCEPTION        <main> Browser: Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
        at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:508) ~[swirlds-platform-core-0.23.1.jar:?]
        at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:677) [swirlds-platform-core-0.23.1.jar:?]
        at com.swirlds.platform.Browser.startPlatforms(Browser.java:792) [swirlds-platform-core-0.23.1.jar:?]
        at com.swirlds.platform.Browser.main(Browser.java:320) [swirlds-platform-core-0.23.1.jar:?]
Caused by: java.lang.IllegalArgumentException: Illegal Capacity: -16711681
        at java.util.ArrayList.<init>(ArrayList.java:160) ~[?:?]
        at com.swirlds.common.io.SerializableDataInputStream.readSerializableList(SerializableDataInputStream.java:263) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.common.io.SerializableDataInputStream.readSerializableList(SerializableDataInputStream.java:189) ~[swirlds-common-0.23.1.jar:?]
        at com.hedera.services.state.submerkle.ExpirableTxnRecord.deserialize(ExpirableTxnRecord.java:391) ~[?:?]
        at com.swirlds.common.io.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:133) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.common.io.SerializableDataInputStream.readSerializableIterableWithSize(SerializableDataInputStream.java:166) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.common.io.SerializableDataInputStream.readSerializableIterableWithSize(SerializableDataInputStream.java:141) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.fcqueue.FCQueue.deserialize(FCQueue.java:869) ~[swirlds-fcqueue-0.23.1.jar:?]
        at com.swirlds.common.merkle.io.MerkleDataInputStream.finishReadingLeaf(MerkleDataInputStream.java:112) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.common.merkle.io.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:180) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.common.merkle.io.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:223) ~[swirlds-common-0.23.1.jar:?]
        at com.swirlds.platform.SignedStateFileManager.readSavedState(SignedStateFileManager.java:331) ~[swirlds-platform-core-0.23.1.jar:?]
        at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:476) ~[swirlds-platform-core-0.23.1.jar:?]
        ... 3 more
```

**Comment by Neeharika-Sompalli** [comment]
Closed by #2940  #2948
