### ISSUE TITLE
SStoreSuite E2EPackageRunner.contractOpcodes tests failing on master

### ISSUE THREAD

**Issue by rjuang** [hashgraph/hedera-services#3522]
### Description

`E2ePackageRunner.contractOpcodes` is failing on master and also failing after a merge sync with a pending PR. A run on master revealed the following error

```
2022-06-10 09:37:58.833 INFO   56   MapPropertySource - Initializing a MapPropertySource from {}
2022-06-10 09:37:58.838 INFO   142  FeesAndRatesProvider - The exchange rates are :: [Current hbar/cent equiv 1 <-> 12 expiry @ 4102444800, Next hbar/cent equiv 1 <-> 15 expiry @ 4102444800]
2022-06-10 09:37:58.841 INFO   160  FeesAndRatesProvider - The fee schedule covers 63 ops.
2022-06-10 09:37:58.842 INFO   260  HapiQueryOp - 'Setup' - Paying for COST_ANSWER of HapiGetFileContents{node=0.0.3, file=APP_PROPERTIES, fileId=null} with body=transactionID { transactionValidStart { seconds: 1654879018 nanos: 734 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } } accountAmounts { accountID { accountNum: 3 } } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\220\265\357\354\310^=G$E\342\003\273\214\355Y\265\351\230r`h\375\373\330Q[\372\003j\006.Wy2t\272\233\237\312A}\366\035\212n2\203\377\2373\225(\367Aq\234q]\343\271\220\001\v" }
2022-06-10 09:37:58.844 INFO   284  HapiQueryOp - 'Setup' - --> Node payment for HapiGetFileContents{sigs=1, node=0.0.3, file=APP_PROPERTIES, fileId=fileNum: 121
} is 8 tinyBars.
2022-06-10 09:37:58.845 INFO   173  HapiQueryOp - 'Setup' - Paying for HapiGetFileContents{sigs=1, node=0.0.3, file=APP_PROPERTIES, fileId=fileNum: 121
} with body=transactionID { transactionValidStart { seconds: 1654879018 nanos: 736 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "*\351\251\253\265#\246\342Ci\002\022\334\364\213\301KY~\272R\311\212\331\266\267H%\345\023\021/\367\274\373\016F^F{\tC\377\037^\352\315Q\376&&\265\377\214/B\276\237\247\355\232 q\006" }
2022-06-10 09:37:58.847 INFO   362  HapiApiSpec - 'Setup' finished initial execution of CustomSpecAssert
2022-06-10 09:37:58.847 INFO   260  HapiQueryOp - 'Setup' - Paying for COST_ANSWER of HapiGetFileContents{payer=GENESIS, node=0.0.3, file=APP_PROPERTIES, fileId=null} with body=transactionID { transactionValidStart { seconds: 1654879018 nanos: 738 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } } accountAmounts { accountID { accountNum: 3 } } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\256\333H\303\266W\211\327\216P\036w\306\r\312\345\310\251\351\314=\327\270\216J\f\247\265\276\335\354\324\277%\214Sa\305&\370\327\327\304\222\207k\022\vi\251\231C\224\343\030X/\240#\004j\004\200\016" }
2022-06-10 09:37:58.848 INFO   284  HapiQueryOp - 'Setup' - --> Node payment for HapiGetFileContents{sigs=1, payer=GENESIS, node=0.0.3, file=APP_PROPERTIES, fileId=fileNum: 121
} is 8 tinyBars.
2022-06-10 09:37:58.849 INFO   173  HapiQueryOp - 'Setup' - Paying for HapiGetFileContents{sigs=1, payer=GENESIS, node=0.0.3, file=APP_PROPERTIES, fileId=fileNum: 121
} with body=transactionID { transactionValidStart { seconds: 1654879018 nanos: 740 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 84010 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { transfers { accountAmounts { accountID { accountNum: 2 } amount: -8 } accountAmounts { accountID { accountNum: 3 } amount: 8 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "z\371\n\305[\324z\236\223\257\240\361\3536j\363\256\030X\f\227\376\024b\r\235\252\254rND,[mU\347*\330\241\341\362\256$L\314\031gm\232\036\260G\256B\304\305\0308F\343%\037\251\f" }
2022-06-10 09:37:58.858 INFO   152  HapiTxnOp - 'Setup' -  submitting HapiFileUpdate{payer=ADDRESS_BOOK_CONTROL, node=0.0.3, fileName=APP_PROPERTIES} via body=transactionID { transactionValidStart { seconds: 1654879018 nanos: 744 } accountID { accountNum: 55 } } nodeAccountID { accountNum: 3 } transactionFee: 33479709 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" fileUpdate { fileID { fileNum: 121 } contents: "\n)\n contracts.throttle.throttleByGas\022\005false\n+\n$contracts.maxRefundPercentOfGasLimit\022\003100\n\034\n\020contracts.maxGas\022\b15000000" }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\\\375\245\000g\365\252b\266\271\243\254>\237vk^2\333/\225\026\275\262)\365\262\026\'\341\210^\272f\310\212\200\006\277\233x\377\322:\256S8\367\326W\361nx>TS\323m\a\345\355f\000\017" }
2022-06-10 09:37:59.368 INFO   278  HapiTxnOp - 'Setup' -  HapiFileUpdate{sigs=1, payer=ADDRESS_BOOK_CONTROL, node=0.0.3, fileName=APP_PROPERTIES} Wrong actual status INVALID_EXPIRATION_TIME, expected SUCCESS
2022-06-10 09:37:59.368 WARN   217  HapiSpecOperation - 'Setup' - HapiFileUpdate{sigs=1, payer=ADDRESS_BOOK_CONTROL, node=0.0.3, fileName=APP_PROPERTIES} failed Wrong status! Expected SUCCESS, was INVALID_EXPIRATION_TIME!
2022-06-10 09:37:59.851 INFO   381  HapiApiSpec - 'Setup' - final status: FAILED!

org.opentest4j.AssertionFailedError: 
			Failure in SUITE {SStoreSuite}, while executing SPEC {Setup} ==> 
Expected :PASSED
Actual   :FAILED
<Click to see difference>


	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
	at E2EPackageRunner.lambda$extractSpecsFromSuite$0(E2EPackageRunner.java:777)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$0(DynamicTestTestDescriptor.java:53)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest(InvocationInterceptor.java:167)
	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptDynamicTest(InvocationInterceptor.java:184)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.lambda$execute$1(DynamicTestTestDescriptor.java:61)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptorCall.lambda$ofVoid$0(InvocationInterceptorChain.java:78)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:60)
	at org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor.execute(DynamicTestTestDescriptor.java:32)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
	at org.junit.jupiter.engine.descriptor.DynamicContainerTestDescriptor.execute(DynamicContainerTestDescriptor.java:67)
	at org.junit.jupiter.engine.descriptor.DynamicContainerTestDescriptor.execute(DynamicContainerTestDescriptor.java:33)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:95)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

### Steps to reproduce

1. Checkout master. 
2. Run ServicesMain
3. Run E2EPackageRunner.contractOpcodes test or create a PR. See SStoreSuite test fail.

### Hedera network

other

### Version

master (as of June 10, 2022, 9:40 am)

### Operating system

macOS

**Comment by rjuang** [comment]
Regression was introduced sometime between Monday this week and today.

**Comment by rjuang** [comment]
based on commit history, it looks like https://github.com/hashgraph/hedera-services/pull/3520 may be the culprit

**Comment by rjuang** [comment]
@JeffreyDallas can you take a look at this issue? your merge is the first PR that shows this test failing in my commit history.

**Comment by rjuang** [comment]
Looks like Michael figured out the cause.

**Comment by JeffreyDallas** [comment]
Yes, there is a pending PR from Michael would fix this.
