### ISSUE TITLE
Multiple reconnect test failed due to NullPointerException from ServicesState

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#3786]
### Description

Multiple reconnect test (almost all) failed due to the merge of new SDK.

The exception happened on learner node after the reconnect session finished.

```
2022-08-13 08:49:20.023 99       ERROR EXCEPTION        <<platform-core: event-intake 5>> TransactionHandler: error invoking SwirldState2.preHandle() [ nodeId = 5 ] with event (1,119907,de03036a) sp(1,119906,d537982e) op(3,119900,fff413c9)
java.lang.NullPointerException: Cannot invoke "com.hedera.services.state.org.StateMetadata.app()" because "this.metadata" is null
	at com.hedera.services.ServicesState.preHandle(ServicesState.java:231) ~[?:?]
	at com.swirlds.platform.state.TransactionHandler.preHandle(TransactionHandler.java:71) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.state.SwirldStateManagerDouble.preHandle(SwirldStateManagerDouble.java:131) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.eventhandling.PreConsensusEventHandler.preConsensusEvent(PreConsensusEventHandler.java:119) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.observers.EventObserverDispatcher.preConsensusEvent(EventObserverDispatcher.java:117) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.components.EventIntake.addEvent(EventIntake.java:126) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.components.EventIntake.addUnlinkedEvent(EventIntake.java:105) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.event.validation.EventValidator.validateEvent(EventValidator.java:68) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.platform.components.EventTaskDispatcher.dispatchTask(EventTaskDispatcher.java:92) ~[swirlds-platform-core-0.29.0.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:234) ~[swirlds-common-0.29.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:573) ~[swirlds-common-0.29.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:204) ~[swirlds-common-0.29.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

[hedera-services-automation_master_results_6N_1C_NDReconnectCorrectness_20220813-083322-GCP-ND-Reconnect-Correctness-6N-1C_AllProtectedFilesUpdate-NDReconnect-1-16m_node0005_swirlds.log](https://github.com/hashgraph/hedera-services/files/9331608/hedera-services-automation_master_results_6N_1C_NDReconnectCorrectness_20220813-083322-GCP-ND-Reconnect-Correctness-6N-1C_AllProtectedFilesUpdate-NDReconnect-1-16m_node0005_swirlds.log)

### Steps to reproduce

Slack report URL

https://swirldslabs.slack.com/archives/C03FD752LKA/p1660385021484049

To reproduce, goto circle ci dashboard
rerun failed nightly test suite

https://app.circleci.com/pipelines/github/hashgraph/hedera-services?branch=master

### Hedera network

mainnet

### Version

latest master branch

### Operating system

Linux

**Comment by Neeharika-Sompalli** [comment]
Will be fixed as per the issue in platform , https://github.com/swirlds/swirlds-platform/issues/5839

**Comment by JeffreyDallas** [comment]
Close obsolete ticket.
