### ISSUE TITLE
In nightly regression, resolvedStatus() got OK, which shouldn't.

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#391]
**Summary of the defect**
ResolveStatus got 'OK', that is not ok.

**How to reproduce (if possible)**
Refer to the test job URL: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/2065/workflows/d0c68d24-b064-48c2-accc-fde596870cac/jobs/24988

**Service logs (if applicable)**
```
...
2020-08-05 22:25:44.026 WARN   152  ProviderRun - Now 1007 ops pending; backing off for 30s!
2020-08-05 22:26:14.043 WARN   152  ProviderRun - Now 1009 ops pending; backing off for 30s!
2020-08-05 22:26:44.044 INFO   125  ProviderRun - 80 minutes left in test - 47685 ops submitted so far (961 pending).
2020-08-05 22:26:44.044 INFO   132  ProviderRun - Precheck txn status counts :: {OK=48191}
2020-08-05 22:26:44.044 INFO   133  ProviderRun - Resolved txn status counts :: {INVALID_SIGNATURE=561, INSUFFICIENT_PAYER_BALANCE=5, UNKNOWN=93, SUCCESS=46395, ACCOUNT_DELETED=165}
2020-08-05 22:26:44.044 INFO   134  ProviderRun - 
------------------------------

2020-08-05 22:26:44.058 WARN   152  ProviderRun - Now 1001 ops pending; backing off for 30s!
2020-08-05 22:27:14.075 WARN   152  ProviderRun - Now 1003 ops pending; backing off for 30s!
2020-08-05 22:27:44.076 INFO   125  ProviderRun - 79 minutes left in test - 47775 ops submitted so far (955 pending).
2020-08-05 22:27:44.076 INFO   132  ProviderRun - Precheck txn status counts :: {OK=48281}
2020-08-05 22:27:44.076 INFO   133  ProviderRun - Resolved txn status counts :: {INVALID_SIGNATURE=561, INSUFFICIENT_PAYER_BALANCE=5, UNKNOWN=189, SUCCESS=46395, ACCOUNT_DELETED=165}
2020-08-05 22:27:44.077 INFO   134  ProviderRun - 
------------------------------

2020-08-05 22:27:44.094 WARN   152  ProviderRun - Now 1005 ops pending; backing off for 30s!
2020-08-05 22:28:14.112 WARN   152  ProviderRun - Now 1007 ops pending; backing off for 30s!
2020-08-05 22:28:40.184 WARN   265  HapiApiSpec - 'UmbrellaRedux' - HapiCryptoTransfer{sigs=2, payer=uniquePayerAccount, node=0.0.4, transfers=[0.0.1971 <- +1, 0.0.2648 -> -1]} failed!
java.lang.AssertionError: Status was OK, not one of [INVALID_SIGNATURE, INSUFFICIENT_PAYER_BALANCE, UNKNOWN, SUCCESS, INSUFFICIENT_ACCOUNT_BALANCE, LIVE_HASH_NOT_FOUND, ACCOUNT_DELETED]!
	at org.junit.Assert.fail(Assert.java:88) ~[junit-4.12.jar:4.12]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.resolveStatus(HapiTxnOp.java:232) ~[classes/:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.finalizeExecFor(HapiTxnOp.java:319) ~[classes/:?]
	at com.hedera.services.bdd.spec.infrastructure.DelegatingOpFinisher.finishFor(DelegatingOpFinisher.java:41) ~[classes/:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.lambda$startFinalizingOps$3(HapiApiSpec.java:263) ~[classes/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2020-08-05 22:28:40.184 WARN   265  HapiApiSpec - 'UmbrellaRedux' - HapiCryptoTransfer{sigs=2, payer=uniquePayerAccount, node=0.0.4, transfers=[0.0.2135 <- +1, 0.0.1884 -> -1]} failed!
java.lang.AssertionError: Status was OK, not one of [INVALID_SIGNATURE, INSUFFICIENT_PAYER_BALANCE, UNKNOWN, SUCCESS, INSUFFICIENT_ACCOUNT_BALANCE, LIVE_HASH_NOT_FOUND, ACCOUNT_DELETED]!
	at org.junit.Assert.fail(Assert.java:88) ~[junit-4.12.jar:4.12]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.resolveStatus(HapiTxnOp.java:232) ~[classes/:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.finalizeExecFor(HapiTxnOp.java:319) ~[classes/:?]
	at com.hedera.services.bdd.spec.infrastructure.DelegatingOpFinisher.finishFor(DelegatingOpFinisher.java:41) ~[classes/:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.lambda$startFinalizingOps$3(HapiApiSpec.java:263) ~[classes/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
2020-08-05 22:28:40.184 WARN   265  HapiApiSpec - 'UmbrellaRedux' - HapiCryptoTransfer{sigs=2, payer=uniquePayerAccount, node=0.0.4, transfers=[0.0.1828 <- +1, 0.0.2609 -> -1]} failed!
java.lang.AssertionError: Status was OK, not one of [INVALID_SIGNATURE, INSUFFICIENT_PAYER_BALANCE, UNKNOWN, SUCCESS, INSUFFICIENT_ACCOUNT_BALANCE, LIVE_HASH_NOT_FOUND, ACCOUNT_DELETED]!
	at org.junit.Assert.fail(Assert.java:88) ~[junit-4.12.jar:4.12]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.resolveStatus(HapiTxnOp.java:232) ~[classes/:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.finalizeExecFor(HapiTxnOp.java:319) ~[classes/:?]
	at com.hedera.services.bdd.spec.infrastructure.DelegatingOpFinisher.finishFor(DelegatingOpFinisher.java:41) ~[classes/:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.lambda$startFinalizingOps$3(HapiApiSpec.java:263) ~[classes/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
...
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by tinker-michaelj** [comment]
The trail is probably cold on this one 🧐
