### ISSUE TITLE
`DeterministicThrottle.lastDecisionTime` is not properly synchronized

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#4248]
### Description

It is possible to read a newer `lastDecisionTime` in `DeterministicThrottle.allow()` which is later than `now`. The following exception ensues:
```
java.lang.IllegalArgumentException: Throttle timeline must advance, but 2022-11-07T16:17:50.650206Z is not after 2022-11-07T16:17:50.650240Z!
        at com.hedera.services.throttles.DeterministicThrottle.elapsedNanosBetween(DeterministicThrottle.java:265) ~[hapi-utils-0.32.0-SNAPSHOT.jar:?]
        at com.hedera.services.throttles.DeterministicThrottle.allow(DeterministicThrottle.java:122) ~[hapi-utils-0.32.0-SNAPSHOT.jar:?]
        at com.hedera.services.throttling.ThrottleReqsManager.allVerboseReqsMetAt(ThrottleReqsManager.java:51) ~[?:?]
        at com.hedera.services.throttling.ThrottleReqsManager.allReqsMetAt(ThrottleReqsManager.java:36) ~[?:?]
        at com.hedera.services.throttling.DeterministicThrottling.shouldThrottleQuery(DeterministicThrottling.java:149) ~[?:?]
        at com.hedera.services.throttling.HapiThrottling.shouldThrottleQuery(HapiThrottling.java:45) ~[?:?]
        at com.hedera.services.queries.answering.StakedAnswerFlow.systemScreen(StakedAnswerFlow.java:189) ~[?:?]
        at com.hedera.services.queries.answering.StakedAnswerFlow.hygieneCheck(StakedAnswerFlow.java:165) ~[?:?]
        at com.hedera.services.queries.answering.StakedAnswerFlow.satisfyUsing(StakedAnswerFlow.java:109) ~[?:?]
        at com.hedera.services.queries.answering.StakeAwareAnswerFlow.satisfyUsing(StakeAwareAnswerFlow.java:42) ~[?:?]
        at com.hedera.services.queries.answering.QueryResponseHelper.respondWithMetrics(QueryResponseHelper.java:75) ~[?:?]
        at com.hedera.services.queries.answering.QueryResponseHelper.answer(QueryResponseHelper.java:54) ~[?:?]
        at com.hedera.services.grpc.controllers.CryptoController.getTransactionReceipts(CryptoController.java:111) ~[?:?]
        at com.hederahashgraph.service.proto.java.CryptoServiceGrpc$MethodHandlers.invoke(CryptoServiceGrpc.java:1579) ~[hedera-protobuf-java-api-0.32.0-SNAPSHOT.jar:?]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.39.0.jar:1.39.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[grpc-core-1.39.0.jar:1.39.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:797) ~[grpc-core-1.39.0.jar:1.39.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.39.0.jar:1.39.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.39.0.jar:1.39.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

The exception was observed when running a benchmark under heavy load.

### Hedera network

other

### Version

v0.32.0

### Operating system

Linux

**Comment by david-bakin-sl** [comment]
See also [swirlds-platform-regression #3389](https://github.com/swirlds/swirlds-platform-regression/issues/3389)

**Comment by netopyr** [comment]
In modular code, `DeterministicThrottle` is wrapped when used in a multi-threading context. The wrapper takes care of synchronization.
