### ISSUE TITLE
No Active Payer on `ContractCallLocal`

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#4676]
While checking the logs, there is a large stack trace that should be fixed on `ContractCallLocal`.
It will be better to fix the stack trace and add a specific exception log

```
2023-01-17 23:50:43.550 WARN  142  ContractCallLocalResourceUsage - Usage estimation unexpectedly failed for contractCallLocal {
  header {
    payment {
      signedTransactionBytes: "\nP\n\031\n\v\b\310\350\234\236\006\020\304\222\272Q\022\b\b\000\020\000\030\200\342<\030\000\022\006\b\000\020\000\030\f\030\200\302\327/\"\002\bxr\"\n \n\017\n\b\b\000\020\000\030\200\342<\020\223\362\351<\n\r\n\006\b\000\020\000\030\f\020\224\362\351<\022f\nd\n s+\3261\026\325\r)xJ\256z\326OP\034\322\rE\304K\223\273Gri}%8\004\302a\032@k\325\357\370\330\t[\321\356\261\036\330\377\235\316\361B\021ON\">Ve\305\321[\023\217d\277)\235\211\274Q\270]\024n\320\030]\020Y\335%\221\177\365\274\367\306\213\006\334_\241\333u\"\371\005\001"
    }
  }
  contractID {
    evm_address: ",\360X\262\340\0206\230\032&o\310]\233T\303\205\347\237\300"
  }
  gas: 400000
  functionParameters: "\030e\305}"
}

java.lang.IllegalStateException: No active payer!
	at com.hedera.services.context.BasicTransactionContext.activePayer(BasicTransactionContext.java:190) ~[?:?]
	at com.hedera.services.contracts.sources.TxnAwareEvmSigsVerifier.hasActiveKeyOrNoReceiverSigReq(TxnAwareEvmSigsVerifier.java:199) ~[?:?]
	at com.hedera.services.contracts.operation.HederaOperationUtil.addressSignatureCheckExecution(HederaOperationUtil.java:117) ~[?:?]
	at com.hedera.services.contracts.operation.HederaStaticCallOperation.execute(HederaStaticCallOperation.java:76) ~[?:?]
	at org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:282) ~[evm-22.10.1.jar:22.10.1]
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:161) ~[evm-22.10.1.jar:22.10.1]
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:173) ~[evm-22.10.1.jar:22.10.1]
	at com.hedera.services.evm.contracts.execution.HederaEvmTxProcessor.process(HederaEvmTxProcessor.java:229) ~[hedera-evm-api-0.33.3.jar:?]
	at com.hedera.services.evm.contracts.execution.HederaEvmTxProcessor.execute(HederaEvmTxProcessor.java:164) ~[hedera-evm-api-0.33.3.jar:?]
	at com.hedera.services.contracts.execution.EvmTxProcessor.execute(EvmTxProcessor.java:145) ~[?:?]
	at com.hedera.services.contracts.execution.CallLocalEvmTxProcessor.execute(CallLocalEvmTxProcessor.java:69) ~[?:?]
	at com.hedera.services.contracts.execution.CallLocalExecutor.execute(CallLocalExecutor.java:91) ~[?:?]
	at com.hedera.services.fees.calculation.contract.queries.ContractCallLocalResourceUsage.usageFor(ContractCallLocalResourceUsage.java:130) ~[?:?]
	at com.hedera.services.fees.calculation.contract.queries.ContractCallLocalResourceUsage.usageGiven(ContractCallLocalResourceUsage.java:102) ~[?:?]
	at com.hedera.services.fees.calculation.UsageBasedFeeCalculator.lambda$computePayment$0(UsageBasedFeeCalculator.java:127) ~[?:?]
	at com.hedera.services.fees.calculation.UsageBasedFeeCalculator.compute(UsageBasedFeeCalculator.java:143) ~[?:?]
	at com.hedera.services.fees.calculation.UsageBasedFeeCalculator.computePayment(UsageBasedFeeCalculator.java:126) ~[?:?]
	at com.hedera.services.queries.answering.StakedAnswerFlow.satisfyUsing(StakedAnswerFlow.java:124) ~[?:?]
	at com.hedera.services.queries.answering.StakeAwareAnswerFlow.satisfyUsing(StakeAwareAnswerFlow.java:42) ~[?:?]
	at com.hedera.services.queries.answering.QueryResponseHelper.respondWithMetrics(QueryResponseHelper.java:75) ~[?:?]
	at com.hedera.services.queries.answering.QueryResponseHelper.answer(QueryResponseHelper.java:54) ~[?:?]
	at com.hedera.services.grpc.controllers.ContractController.contractCallLocalMethod(ContractController.java:95) ~[?:?]
	at com.hederahashgraph.service.proto.java.SmartContractServiceGrpc$MethodHandlers.invoke(SmartContractServiceGrpc.java:1200) ~[hedera-protobuf-java-api-0.33.0.jar:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.45.1-module.jar:1.45.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener.halfClosed(ServerImpl.java:877) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.AbstractServerStream$TransportState.deframerClosed(AbstractServerStream.java:231) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.netty.NettyServerStream$TransportState.deframerClosed(NettyServerStream.java:168) ~[grpc-netty-1.45.1-module.jar:1.45.1]
	at io.grpc.internal.MessageDeframer.close(MessageDeframer.java:233) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.MessageDeframer.closeWhenComplete(MessageDeframer.java:191) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.AbstractStream$TransportState.closeDeframer(AbstractStream.java:200) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:258) ~[grpc-core-1.45.1.jar:1.45.1]
	at io.grpc.netty.NettyServerStream$TransportState.inboundDataReceived(NettyServerStream.java:226) ~[grpc-netty-1.45.1-module.jar:1.45.1]
	at io.grpc.netty.NettyServerHandler.onDataRead(NettyServerHandler.java:508) ~[grpc-netty-1.45.1-module.jar:1.45.1]
	at io.grpc.netty.NettyServerHandler.access$900(NettyServerHandler.java:106) ~[grpc-netty-1.45.1-module.jar:1.45.1]
	at io.grpc.netty.NettyServerHandler$FrameListener.onDataRead(NettyServerHandler.java:840) ~[grpc-netty-1.45.1-module.jar:1.45.1]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) ~[netty-codec-http2-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[netty-transport-native-epoll-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[netty-transport-native-epoll-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[netty-transport-native-epoll-4.1.66.Final.jar:4.1.66.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by nickpoorman** [comment]
We should not be throwing large stack traces when there is no payer in the contract call local. @stoqnkpL

**Comment by Nana-EC** [comment]
Okay to leave in 0.37
