### ISSUE TITLE
Race condition caused by ContractCallLocal bug

### ISSUE THREAD

**Issue by tinker-michaelj** [hashgraph/hedera-services#471]
**Summary of the defect**
The `ContractCallLocal` answer incorrectly uses the persistent `ServicesRepositoryRoot` to look up the ["sender nonce"](https://github.com/hashgraph/hedera-services/blob/master/hedera-node/src/main/java/com/hedera/services/legacy/handler/SmartContractRequestHandler.java#L578). This opens the door to a race condition with the `handleTransaction` thread. 

**How to reproduce (if possible)**
In progress.

**Service logs**
A believed possible symptom is,
```
java.lang.IllegalArgumentException: tried to modify an immutable FCQueue
        at com.swirlds.fcqueue.FCQueue.add(FCQueue.java:254) ~[swirlds-fcqueue-0.7.2.jar:?]
        at com.swirlds.fcqueue.FCQueue.offer(FCQueue.java:427) ~[swirlds-fcqueue-0.7.2.jar:?]
        at com.hedera.services.ledger.HederaLedger.addReturningEarliestExpiry(HederaLedger.java:271) ~[?:?]
        at com.hedera.services.ledger.HederaLedger.addPayerRecord(HederaLedger.java:266) ~[?:?]
        at com.hedera.services.state.expiry.ExpiringCreations.createExpiringRecord(ExpiringCreations.java:111) ~[?:?]
        at com.hedera.services.state.expiry.ExpiringCreations.createExpiringPayerRecord(ExpiringCreations.java:64) ~[?:?]
        at com.hedera.services.records.FeeChargingRecordsHistorian.addNewRecords(FeeChargingRecordsHistorian.java:122) ~[?:?]
        at com.hedera.services.ledger.HederaLedger.commit(HederaLedger.java:121) ~[?:?]
        at com.hedera.services.legacy.services.state.AwareProcessLogic.processInLedgerTxn(AwareProcessLogic.java:149) ~[?:?]
        at com.hedera.services.legacy.services.state.AwareProcessLogic.incorporateConsensusTxn(AwareProcessLogic.java:108) ~[?:?]
        at com.hedera.services.ServicesState.handleTransaction(ServicesState.java:177) ~[?:?]
        at com.swirlds.platform.EventFlow.handleTransaction(EventFlow.java:758) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.EventFlow.takeHandlePut(EventFlow.java:1231) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.EventFlow.doCons(EventFlow.java:821) ~[swirlds-platform-core-0.7.2.jar:?]
        at com.swirlds.platform.StoppableThread$StoppableRunnable.run(StoppableThread.java:132) [swirlds-platform-core-0.7.2.jar:?]
```
Which will cause an ISS isolated to the node which succumbs to the race condition.

**Comment by jsindy** [comment]
Out of curiosity when was this race condition introduced into the code?

**Comment by tinker-michaelj** [comment]
> Out of curiosity when was this race condition introduced into the code?

At least several weeks back, as part of migrating to the new Platform SDK. 

Unfortunately, it doesn't seem easy to reproduce the testnet error above using our standard test clients. 

But it is certainly a bug, and logically _can_ explain the testnet error... 🤔
