### ISSUE TITLE
JRS regression  AWS-Services-Daily-Perf-4N-4C/CryptoTransfer-Perf-2.4k-15m failed at ----Duplicate Transaction error 

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#498]
**Summary of the defect**

The failure is some transaction didn't get UNKNOWN as resolved response code.

**How to reproduce (if possible)**
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1598864672230600

**Service logs (if applicable)**
```
...
---- HAPIClientValidator FAILED validation ----
<<INFO>>
ClientNode - Suite       Result
Node 0 - UmbrellaRedux   PASSED
Node 0 - UmbrellaRedux   PASSED
Node 0 - UmbrellaRedux   PASSED
Node 0 - UmbrellaRedux   PASSED
Node 0 - UmbrellaRedux   PASSED
Node 0 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 1 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 2 - UmbrellaRedux   PASSED
Node 3 - UmbrellaRedux   PASSED
Node 3 - UmbrellaRedux   PASSED
Node 3 - UmbrellaRedux   PASSED
Node 3 - UmbrellaRedux   PASSED
Node 3 - UmbrellaRedux   PASSED
<<ERROR>>
ClientNode - Suite       Result   Failures
Node 3 - UmbrellaRedux   FAILED   UmbrellaRedux
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by anighanta** [comment]
This is occurring very frequently. `DUPLICATE_TRANSACTION` error.

2020-09-01 19:49:03.236 WARN   181  HapiSpecOperation - 'UmbrellaRedux' - ProviderRun{} failed!
java.lang.AssertionError: Operation 'HapiCryptoCreate{sigs=2, node=0.0.4, account=stable-account329-RandomTransfer, balance=100000000000}' :: Wrong precheck status! expected:<OK> but was:<DUPLICATE_TRANSACTION>
	at org.junit.Assert.fail(Assert.java:88) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:40) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:47) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.ProviderRun.submitOp(ProviderRun.java:101) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:165) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:216) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:176) ~[SuiteRunner.jar:?]
