### ISSUE TITLE
Unable to instantiate a working 3 node network in docker by following the instructions.

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#532]
Network does not reach ACTIVE status by following instructions in the [Docker Quickstart](https://github.com/hashgraph/hedera-services/blob/master/docs/docker-quickstart.md)

Tried Ubuntu 20.04 with clean docker installation and WSL2 (Ubumtu 20.04) Docker Windows 10, same behavior in both instances.

Steps to reproduce, from a clean docker environment hosted in Ubuntu 20.04

```sh
~$ git clone https://github.com/hashgraph/hedera-services.git
~$ cd hedera-services
~/hedera-services$ ./compose-build.sh
~/hedera-services$ docker-compose up
```

Result: the database and nodes start, however the network never makes it to ACTIVE status as indicated in the docker reame:

```
node_2      | 2020-04-29 15:05:28.814 INFO  133  ServicesMain - Now current platform status = ACTIVE in HederaNode#2.
node_0      | 2020-04-29 15:05:28.815 INFO  133  ServicesMain - Now current platform status = ACTIVE in HederaNode#0.
node_1      | 2020-04-29 15:05:28.854 INFO  133  ServicesMain - Now current platform status = ACTIVE in HederaNode#1.
```

The above is missing from console out.

Instead, the tail of the main console log shows:

```
node_1      |   deleteLiveHash=
node_1      |   deleteTopic=0-*
node_1      |   freeze=2-58
node_1      |   getAccountInfo=0-*
node_1      |   getAccountRecords=0-*
node_1      |   getBySolidityID=0-*
node_1      |   getContractInfo=0-*
node_1      |   getFastTransactionRecord=
node_1      |   getFileContent=0-*
node_1      |   getFileInfo=0-*
node_1      |   getLiveHash=
node_1      |   getTopicInfo=0-*
node_1      |   getTransactionReceipts=0-*
node_1      |   getTxRecordByContractID=0-*
node_1      |   getTxRecordByTxID=0-*
node_1      |   getVersionInfo=0-*
node_1      |   submitMessage=0-*
node_1      |   systemDelete=2-59
node_1      |   systemUndelete=2-60
node_1      |   updateAccount=0-*
node_1      |   updateContract=0-*
node_1      |   updateFile=0-*
node_1      |   updateTopic=0-*
node_1      | 2020-09-09 23:57:43.001 INFO  64   PropertiesLoader - API Properties Populated with these values :: {deleteTopic=0-*, getContractInfo=0-*, getLiveHash=, cryptoTransfer=0-*, getTxRecordByContractID=0-*, contractCallMethod=0-*, getTopicInfo=0-*, deleteContract=0-*, appendContent=0-*, updateAccount=0-*, createFile=0-*, cryptoGetBalance=0-*, updateTopic=0-*, freeze=2-58, contractCallLocalMethod=0-*, getVersionInfo=0-*, submitMessage=0-*, cryptoDelete=0-*, createContract=0-*, getFileContent=0-*, getTransactionReceipts=0-*, deleteFile=0-*, systemUndelete=2-60, getAccountRecords=0-*, contractGetBytecode=0-*, createTopic=0-*, updateContract=0-*, createAccount=0-*, addLiveHash=, getBySolidityID=0-*, updateFile=0-*, getAccountInfo=0-*, systemDelete=2-59, deleteLiveHash=, getFastTransactionRecord=, getFileInfo=0-*, getTxRecordByTxID=0-*}
node_1      | 2020-09-09 23:57:43.002 INFO  147  ServicesMain - Initialized properties and permissions.
node_1      | 2020-09-09 23:57:43.031 INFO  149  ServicesMain - Record stream started.
node_1      | 2020-09-09 23:57:43.031 INFO  216  ServicesMain - TLS is turned on by default on node 1
node_1      | 2020-09-09 23:57:43.033 INFO  218  ServicesMain - Active profile: PROD
node_1      | 2020-09-09 23:57:43.263 INFO  283  ServicesMain - Starting Netty on port 50211...
node_1      | 2020-09-09 23:57:43.593 INFO  283  ServicesMain - ...done starting Netty on port 50211.
node_1      | 2020-09-09 23:57:43.594 INFO  283  ServicesMain - Starting Netty with TLS support on port 50212...
node_1      | 2020-09-09 23:57:43.596 WARN  70   NettyGrpcServerManager - Could not start Netty with TLS support on port 50212. (hedera.crt or hedera.key could not be found in Services app base folder).
node_1      | 2020-09-09 23:57:43.596 INFO  283  ServicesMain - Could not start Netty with TLS support on port 50212.
node_1      | 2020-09-09 23:57:43.596 INFO  151  ServicesMain - Netty started.
node_1      | 2020-09-09 23:57:43.693 INFO  114  BackedSystemAccountsCreator - Ledger float is 5000000000000000000 tinyBars in 100 accounts.
node_1      | 2020-09-09 23:57:43.695 INFO  153  ServicesMain - System accounts rationalized.
node_1      | 2020-09-09 23:57:43.736 INFO  155  ServicesMain - Ledger state ok.
node_1      | 2020-09-09 23:57:44.111 INFO  157  ServicesMain - System files rationalized.
node_1      | 2020-09-09 23:57:44.170 INFO  159  ServicesMain - Accounts exported.
node_1      | 2020-09-09 23:57:44.187 INFO  161  ServicesMain - Record expiration reviewed.
node_1      | 2020-09-09 23:57:44.197 INFO  163  ServicesMain - Fee schedule loaded.
node_1      | 2020-09-09 23:57:44.198 INFO  165  ServicesMain - Completed initialization of STAKED_NODE #1
node_1      | 2020-09-09 23:57:44.198 INFO  86   ServicesMain - init finished.
node_1      | This computer has an internal IP address:  172.18.0.5
```

**Note** the final portion of the log does not include platform is ACTIVE.

Additionally, the swrlds log is throwing many ssl errors:

```
 tail -f compose-network/node0/output/swirlds.log
```

Yields:

```
...
javax.net.ssl.SSLProtocolException: Received fatal alert: unexpected_message
        at sun.security.ssl.Alert.createSSLException(Alert.java:129) ~[?:?]
        at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285) ~[?:?]
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:180) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:164) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
        at com.swirlds.platform.Crypto.newClientSocketConnect(Crypto.java:362) ~[swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.SyncConnection.connect(SyncConnection.java:227) [swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.SyncClient.getCallerConnOrConnectOnce(SyncClient.java:89) [swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.SyncHeartbeat.run(SyncHeartbeat.java:62) [swirlds-platform-core-0.7.3.jar:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
2020-09-10 00:02:13.545 WARN  344  SyncServer - Listener 0 hearing -1 had SSLException:
javax.net.ssl.SSLException: Read timed out
        at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:320) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:263) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:258) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:137) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:721) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:804) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:763) ~[?:?]
        at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:342) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:594) ~[?:?]
        at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
        at com.swirlds.platform.SyncServer$IncomingConnectionHandler.run(SyncServer.java:318) [swirlds-platform-core-0.7.3.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
...
```

Submitting a create account transaction to the system yields the following response:

```
{
  "nodeTransactionPrecheckCode": "PLATFORM_NOT_ACTIVE"
}
```
This is from a clean pull from master 9/9/20 

```
~/hedera-services$ git describe --tags --always --dirty
v0.7.0-164-g8519b36f-dirty
```

**Removing Nodes 1 & 2** from the docker compose file and **removing nodes 0.0.4 and 0.0.5** from the swrlds config.txt file will at least bring up a single node that reaches ACTIVE STATUS:

```
node_0      | 2020-09-10 00:23:47.269 INFO  159  ServicesMain - Accounts exported.
node_0      | 2020-09-10 00:23:47.292 INFO  161  ServicesMain - Record expiration reviewed.
node_0      | 2020-09-10 00:23:47.302 INFO  163  ServicesMain - Fee schedule loaded.
node_0      | 2020-09-10 00:23:47.302 INFO  165  ServicesMain - Completed initialization of STAKED_NODE #0
node_0      | 2020-09-10 00:23:47.302 INFO  86   ServicesMain - init finished.
node_0      | This computer has an internal IP address:  172.18.0.2
node_0      | 2020-09-10 00:23:47.338 INFO  100  ServicesMain - Now current platform status = STARTING_UP in HederaNode#0.
node_0      | 2020-09-10 00:23:47.341 INFO  108  ServicesMain - Platform 0 status set to : STARTING_UP
node_0      | 2020-09-10 00:23:47.342 INFO  100  ServicesMain - Now current platform status = ACTIVE in HederaNode#0.
```

and apps are able to connect and create new accounts.

**Comment by anighanta** [comment]
Updated the docker registry with the latest release [tag v0.10.0] and verified working 3 node network. check PR https://github.com/hashgraph/hedera-services/pull/880

**Comment by anighanta** [comment]
@bugbytesinc Can you please confirm if the 3 node network creating using docker works.

**Comment by bugbytesinc** [comment]
Unfortunately no, it still does not work out of the box.  A workaround is to turn off TLS on config.txt
