### ISSUE TITLE
ServicesState-MigrationWithRestart-1-5m JRS daily regression fails due to INVALID_SIGNATURE error

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#549]
**Summary of the defect**

Should get OK, but instead, get INVALID_SIGNATURE in precheck.

**How to reproduce (if possible)**

https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1600109242453500

log file: https://s3.console.aws.amazon.com/s3/object/hedera-service-regression-jrs/20200914-1824-AWS-Services-Daily-Migration-4N-1C/ServicesState-MigrationWithRestart-1-5m/node0000-TestClient/hapi-client-combined0.log?region=us-east-2&tab=overview

**Service logs (if applicable)**
```
...
LOCAL_CALL_GAS=260000, port=50211, defaultListeningNodeAccount=0.0.3, payerAccountPEMKeyFile=, NODE_REALM_NUMBER=0}
2020-09-14 18:43:20.191 INFO   731  TestHelper - In Else fileName: src/main/resource/application.properties
2020-09-14 18:43:20.192 INFO   371  HapiApiSpec - CI_PROPERTIES_MAP: tps=10,mins=2,threads=10
2020-09-14 18:43:20.195 INFO   48   MapPropertySource - Initializing a MapPropertySource from {nodes=35.174.209.235:0.0.3:50211, default.node=0.0.3, tls=off, node.selector=random, default.payer=0.0.16, ci.properties.map=tps=10,mins=2,threads=10}
2020-09-14 18:43:20.598 INFO   146  HapiApiClients - Constructed 13 new stubs building clients for HapiApiClients{node0=NodeConnectInfo{host=35.174.209.235, port=50211, tlsPort=50212, account=0.0.3}, default=0.0.3}
2020-09-14 18:43:21.206 WARN   190  HapiApiSpec - 'RunCryptoTransfers' failed to initialize, being skipped!
java.lang.AssertionError: expected:<OK> but was:<INVALID_SIGNATURE>
	at org.junit.Assert.fail(Assert.java:88) ~[SuiteRunner.jar:?]
	at org.junit.Assert.failNotEquals(Assert.java:834) ~[SuiteRunner.jar:?]
	at org.junit.Assert.assertEquals(Assert.java:118) ~[SuiteRunner.jar:?]
	at org.junit.Assert.assertEquals(Assert.java:144) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:159) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:122) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:79) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:187) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:168) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:245) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:137) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:130) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$14(SuiteRunner.java:386) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:387) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:360) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:360) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:329) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:269) [SuiteRunner.jar:?]
2020-09-14 18:43:21.210 INFO   164  CryptoTransferLoadTest - -------------- RESULTS OF CryptoTransferLoadTest SUITE --------------
2020-09-14 18:43:21.211 INFO   166  CryptoTransferLoadTest - Spec{name=RunCryptoTransfers, status=ERROR}
2020-09-14 18:43:21.220 INFO   334  SuiteRunner - ============== sync run results ==============
2020-09-14 18:43:21.220 INFO   337  SuiteRunner - CryptoTransferLoadTest           :: 0/1 suites ran OK
2020-09-14 18:43:21.222 INFO   343  SuiteRunner -   --> Problems in suite 'CryptoTransferLoadTest' :: Spec{name=RunCryptoTransfers, status=ERROR}

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
This seems to have same root cause as #547.

**Comment by ljianghedera** [comment]
Closed by https://github.com/hashgraph/hedera-services/pull/567
