### ISSUE TITLE
Public testnet Migration test failing with INVALID_SIGNATURE

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#550]
JRS regression tests `ServicesState-PubTestNetMigration-100-5m.json`, `ServicesState-PubTestNetMigrationWithRestart-100-3m.json` are failing with `INVALID_SIGNATURE` though the state is the same and key is the same. Need to investigate the reason for the failure.

Error from client logs is as follows:
```java.lang.AssertionError: expected:<OK> but was:<INVALID_SIGNATURE>
	at org.junit.Assert.fail(Assert.java:88) ~[SuiteRunner.jar:?]
	at org.junit.Assert.failNotEquals(Assert.java:834) ~[SuiteRunner.jar:?]
	at org.junit.Assert.assertEquals(Assert.java:118) ~[SuiteRunner.jar:?]
	at org.junit.Assert.assertEquals(Assert.java:144) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:159) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:122) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:79) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:187) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:168) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:245) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:137) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:130) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$14(SuiteRunner.java:386) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:387) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:360) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:360) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:329) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:269) [SuiteRunner.jar:?]

**Comment by ljianghedera** [comment]
This seems to be a duplication of issue #549, hence I am closing it to avoid the redundance.
