### ISSUE TITLE
JRS regression SuiteRunnerSuites-Basic-1-10m has 10 test cases failed

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#560]
**Summary of the defect**
These 10 individual test cases fail consistently.
Please refer to the below error log messages.

**How to reproduce (if possible)**
https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1600177063334400 

**Service logs (if applicable)**
```
...

---- HAPIClientValidator FAILED validation ----
<<INFO>>
ClientNode - Suite                    Result
Node 0 - DeprecatedContractKey        PASSED
Node 0 - FileRecordsSanityCheck       PASSED
Node 0 - TopicGetInfo                 PASSED
Node 0 - SubmitMessage                PASSED
Node 0 - SysDelSysUndelSpec           PASSED
Node 0 - SpecialAccountsAreExempted   PASSED
Node 0 - VersionInfoSpec              PASSED
Node 0 - PermissionSemanticsSpec      PASSED
Node 0 - UmbrellaRedux                PASSED
Node 0 - IssueXXXXSpec                PASSED
Node 0 - CryptoCreate                 PASSED
Node 0 - NewOpInConstructor           PASSED
Node 0 - ChildStorageSpec             PASSED
Node 0 - Chunking                     PASSED
<<ERROR>>
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84)
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
    at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:84)
ClientNode - Suite                    Result   Failures
Node 0 - CryptoRecordsSanityCheck     FAILED   CryptoDeleteRecordSanityChecks
Node 0 - Issue2144Spec                FAILED   MasterIsNeverThrottledOnTransfers, MasterIsNeverThrottledOnMiscTxns, MasterIsNeverThrottledOnHcsTxns, MasterIsNeverThrottledOnMiscQueries, MasterIsNeverThrottledOnHcsQueries
Node 0 - ProtectedFilesUpdate         FAILED   GENESISCanUpdateAPP_PROPERTIES, strong-controlCanUpdateAPP_PROPERTIES, GENESISCanUpdateAPI_PERMISSIONS, strong-controlCanUpdateAPI_PERMISSIONS, GENESISCanUpdateADDRESS_BOOK, strong-controlCanUpdateADDRESS_BOOK, ADDRESS_BOOK_CONTROLCanUpdateADDRESS_BOOK, GENESISCanUpdateNODE_DETAILS, strong-controlCanUpdateNODE_DETAILS, ADDRESS_BOOK_CONTROLCanUpdateNODE_DETAILS, GENESISCanUpdateFEE_SCHEDULE, strong-controlCanUpdateFEE_SCHEDULE, FEE_SCHEDULE_CONTROLCanUpdateFEE_SCHEDULE, GENESISCanUpdateEXCHANGE_RATES, strong-controlCanUpdateEXCHANGE_RATES, EXCHANGE_RATES_CONTROLCanUpdateEXCHANGE_RATES
Node 0 - TopicCreate                  FAILED   SigningRequirementsEnforced
Node 0 - ThresholdRecordCreation      FAILED   OnlyNetAdjustmentIsComparedToThresholdWhenCreating, BothSendAndReceiveThresholdsAreConsidered
Node 0 - FetchSystemFiles             FAILED   
Exceptions:4
Node 0 - TopicDelete                  FAILED   deleteFailedWithWrongKey
Node 0 - TopicUpdate                  FAILED   topicUpdateSigReqsEnforcedAtConsensus
Node 0 - ContractRecordsSanityCheck   FAILED   ContractDeleteRecordSanityChecks
Node 0 - ConsensusThrottles           FAILED   ThrottlesCreateTopicAsExpected, ThrottlesSubmitMessageAsExpected, ThrottlesUpdateTopicAsExpected, ThrottlesDeleteTopicAsExpected, ThrottlesGetTopicInfoAsExpected
```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
They are all failing due to the startup account number issue.

**Comment by Neeharika-Sompalli** [comment]
The issue was resolved
