### ISSUE TITLE
Attempting to Delete a Token with ID (0.0.0) Causes Crash/Hang of Network Node

### ISSUE THREAD

**Issue by bugbytesinc** [hashgraph/hedera-services#565]
**Summary of the defect**
The protobuf accepts a TokenRef which should accept a ~symbol~ __Address__ as an input option, ~however~ when submitting a TokenDeletion message using the TokenRef with ~a Symbol~ __an Address of (0,0,0)__, the gRPC method does not return and exceptions are generated in the logs.

**How to reproduce (if possible)**
Create and submit a TokenDeletion message using a ~Symbol instead of a Token~ Address __of (0,0,0)__

**Service logs (if applicable)**
```
tail -f compose-network/node0/output/swirlds.log

....

2020-09-16 01:50:00.206 INFO  206  SignedStateFileManager - Finished writing 'Signed state for round 238257' to disk
2020-09-16 01:53:28.303 ERROR 1565 Hashgraph - expandSignatures threw an unhandled exception
java.lang.NullPointerException: null
        at com.hedera.services.sigs.metadata.TokenSigningMetadata.from(TokenSigningMetadata.java:56) ~[?:?]
        at com.hedera.services.sigs.metadata.SigMetadataLookup.lambda$static$0(SigMetadataLookup.java:51) ~[?:?]
        at com.hedera.services.sigs.metadata.DelegatingSigMetadataLookup.tokenSigningMetaFor(DelegatingSigMetadataLookup.java:182) ~[?:?]
        at com.hedera.services.sigs.order.HederaSigningOrder.tokenMutates(HederaSigningOrder.java:597) ~[?:?]
        at com.hedera.services.sigs.order.HederaSigningOrder.tokenMutates(HederaSigningOrder.java:586) ~[?:?]
        at com.hedera.services.sigs.order.HederaSigningOrder.forToken(HederaSigningOrder.java:248) ~[?:?]
        at com.hedera.services.sigs.order.HederaSigningOrder.keysForOtherParties(HederaSigningOrder.java:126) ~[?:?]
        at com.hedera.services.sigs.HederaToPlatformSigOps$Expansion.expand(HederaToPlatformSigOps.java:197) ~[?:?]
        at com.hedera.services.sigs.HederaToPlatformSigOps$Expansion.execute(HederaToPlatformSigOps.java:181) ~[?:?]
        at com.hedera.services.sigs.HederaToPlatformSigOps.expandIn(HederaToPlatformSigOps.java:115) ~[?:?]
        at com.hedera.services.ServicesState.expandSignatures(ServicesState.java:200) ~[?:?]
        at com.swirlds.platform.Hashgraph.handleSignatureExpansion(Hashgraph.java:1553) ~[swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.Hashgraph.createNewEvent(Hashgraph.java:1320) ~[swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.Hashgraph.intakeQueueHandler(Hashgraph.java:1342) ~[swirlds-platform-core-0.7.3.jar:?]
        at com.swirlds.platform.StoppableThread$StoppableRunnable.run(StoppableThread.java:132) [swirlds-platform-core-0.7.3.jar:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
...
```
**Environment:**
- WSL2 Docker Ubuntu 20.04]
- Hedera Services Version: 
- HAPI Version: v0.8.0-rc

**Additional Context**
Network remains unresponsive to requests until restart (this is a one node instance)

**Comment by bugbytesinc** [comment]
As embarrassing as it is to admit, I miss-diagnosed the root protobuf pattern that is causing this.  It is NOT using a token ref representing a symbol, instead it is sending a token ref with an **Token ID of (0,0,0)**.  Yes this is only happens if a SDK is malfunctioning (as .net was at the time)...but wow, it still causes the above exception, which freezes the node. 

Apologies for the miss-diagnose for the condition, but when the system hangs on getting a receipt, its darn hard to collect any logs with my test system.
