### ISSUE TITLE
Update-Freeze-1-5m JRS daily regression tests fail to load saved state

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#569]
**Summary of the defect**
The failure is somehow random.  

Please see error message below:

**How to reproduce (if possible)**

CircleCi build page url: https://app.circleci.com/pipelines/github/hashgraph/hedera-services/3460/workflows/46a2a1b1-d6d0-4169-b149-fa5b8fd48f27/jobs/31987

Slack report:
https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1600282535481800

swirlds.log file: https://s3.console.aws.amazon.com/s3/object/hedera-service-regression-jrs/20200916-1831-AWS-Services-Daily-Comp-6_2N-1C/Update-Freeze-1-5m/node0000/swirlds.log?region=us-east-2&tab=overview

Complete artifacts can be found at: https://s3.console.aws.amazon.com/s3/buckets/hedera-service-regression-jrs/20200917-0508-AWS-Services-Daily-Comp-6_2N-1C/Update-Freeze-1-5m/?region=us-east-2&tab=overview

**Service logs (if applicable)**
```
...
020-09-16 18:52:34.558 DEBUG 978  Browser - Done with registerConstructables, time taken 1152ms
2020-09-16 18:52:34.737 INFO  203  Hashgraph - threadPollIntakeQueue is started
2020-09-16 18:52:34.829 ERROR 741  Browser - Saved state not loaded:
com.swirlds.platform.internal.SignedStateLoadingException: Exception while reading signed state!
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:492) ~[swirlds-platform-core-0.7.3.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:739) [swirlds-platform-core-0.7.3.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:982) [swirlds-platform-core-0.7.3.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:380) [swirlds-platform-core-0.7.3.jar:?]
Caused by: com.swirlds.common.io.InvalidVersionException: Illegal version 2 was read from the stream for class com.hedera.services.ServicesState (class ID -8201042766723040486(0x8E300B0DFDAFBB1A)). Expected version in the range 1 - 1
	at com.swirlds.common.io.SerializableDataInputStream.validateVersion(SerializableDataInputStream.java:119) ~[swirlds-common-0.7.3.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:124) ~[swirlds-common-0.7.3.jar:?]
	at com.swirlds.common.merkle.io.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:160) ~[swirlds-common-0.7.3.jar:?]
	at com.swirlds.platform.SignedStateFileManager.readSavedState(SignedStateFileManager.java:295) ~[swirlds-platform-core-0.7.3.jar:?]
	at com.swirlds.platform.SwirldsPlatform.loadSavedStateFromDisk(SwirldsPlatform.java:448) ~[swirlds-platform-core-0.7.3.jar:?]
	... 3 more
2020-09-16 18:52:34.836 DEBUG 206  BinaryObjectStore - Recovery Starting
2020-09-16 18:52:34.836 DEBUG 218  BinaryObjectStore - Recovering Objects [ objectCount = 0, uniqueObjectCount = 0 ]
2020-09-16 18:52:35.225 DEBUG 263  BinaryObjectStore - Recovery Finished
2020-09-16 18:52:35.234 INFO  640  EventFlow - EventFlow.startAll(), forCons.size: 0, forCurr.size: 0, forNext.size: null, forSigs.size: 0, forWork.size: null

```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by Neeharika-Sompalli** [comment]
The issue has been resolved. Test is passing in todays regression https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1602049685393500 .

It will be reopened if the issue is seen again
