### ISSUE TITLE
Traversing a signed state store twice leads to database migration (that never ends ...)

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#5748]
### Description

Rehydrated a signed state file.  Asked for the contract state store with `ServicesState.contractStorage()`.  Did a full traversal with `VirtualMapLike.extractVirtualMapData` - that went fine.  called `VirtualMapLike.release()` on that, then went back to the `ServicesState.contractStorage()` and tried the traversal again. 

It spewed 8 of these (8 was the size of my thread pool):

```
2023-03-21 13:11:04.306 ERROR  353  AbstractThreadConfiguration - exception on thread <virtual-map-migration: reader-8>
java.lang.NullPointerException: Cannot invoke "com.swirlds.virtualmap.datasource.VirtualLeafRecord.getKey()" because "leafRecord" is null
	at com.swirlds.virtualmap.VirtualMapMigration.lambda$extractVirtualMapData$0(VirtualMapMigration.java:96) ~[yahcli.jar:?]
	at com.swirlds.common.threading.framework.internal.AbstractThreadConfiguration.lambda$setInterruptableRunnable$2(AbstractThreadConfiguration.java:618) ~[yahcli.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

then started an infinite spew of 
```
023-03-21 13:08:17.818 INFO   259  HalfDiskHashMap - [fileStore_objectkeytopath] No meed to merge as 7 is less than the minimum 8 files to merge.
2023-03-21 13:08:17.818 INFO   158  MemoryIndexDiskKeyValueStore - [fileStore_pathtohashkeyvalue] No need to merge as 2 is less than the minimum 8 files to merge.
2023-03-21 13:08:18.818 INFO   1356 VirtualDataSourceJasperDB - [fileStore] Starting Small Merge
2023-03-21 13:08:18.818 INFO   158  MemoryIndexDiskKeyValueStore - [fileStore_internalhashes] No need to merge as 2 is less than the minimum 8 files to merge.
2023-03-21 13:08:18.818 INFO   259  HalfDiskHashMap - [fileStore_objectkeytopath] No meed to merge as 7 is less than the minimum 8 files to merge.
2023-03-21 13:08:18.818 INFO   158  MemoryIndexDiskKeyValueStore - [fileStore_pathtohashkeyvalue] No need to merge as 2 is less than the minimum 8 files to merge.
2023-03-21 13:08:19.818 INFO   1356 VirtualDataSourceJasperDB - [fileStore] Starting Small Merge
2023-03-21 13:08:19.818 INFO   158  MemoryIndexDiskKeyValueStore - [fileStore_internalhashes] No need to merge as 2 is less than the minimum 8 files to merge.
2023-03-21 13:08:19.818 INFO   259  HalfDiskHashMap - [fileStore_objectkeytopath] No meed to merge as 7 is less than the minimum 8 files to merge.
```

Should not have done that, instead, it should have done the second traversal just fine without further ado.

### Steps to reproduce

Ran on an intermediate version of `yahcli` I was developing.  You can get a repro from me (I'll have to reproduce the sources).

### Hedera network

other

### Version

develop branch as of 2023-03-21

### Operating system

macOS

**Comment by david-bakin-sl** [comment]
It's been some time.  Need to see if this still repros.

**Comment by david-bakin-sl** [comment]
Not relevant at this time (may be relevant once modular dumpers are created).  Closing.
