### ISSUE TITLE
Config API: ConfigConverter only allow direct implementations and no abstraction

### ISSUE THREAD

**Issue by hendrikebbers** [hashgraph/hedera-services#6106]
To make support of enum types more easy I wanted to introduce the following abstract ConfigConverter:

```
public abstract class AbstractEnumConfigConverter<E extends Enum<E>> implements ConfigConverter<E> {

    @Override
    public E convert(final String value) throws IllegalArgumentException, NullPointerException {
        if (value == null) {
            throw new NullPointerException("null can not be converted");
        }
        final Class<E> enumType = getEnumType();
        Objects.requireNonNull(enumType, "enumType");
        return Enum.valueOf(enumType, value);
    }

    @NonNull
    protected abstract Class<E> getEnumType();
}
```

A simple implementation can look like this:

```
 private static class RetentionPolicyConverter extends AbstractEnumConfigConverter<RetentionPolicy> {

      @Override
      protected Class<RetentionPolicy> getEnumType() {
          return RetentionPolicy.class;
      }
  }
```

Looks like the Config API implementation does not support converters that not directly implement ConfigConverter since adding the converter will throw the given exception:

```
class sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.TypeVariableImpl and java.lang.Class are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.TypeVariableImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.TypeVariableImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at com.swirlds.config.impl.internal.ConverterService.lambda$getConverterType$1(ConverterService.java:115)
	at java.base/java.util.Optional.map(Optional.java:260)
	at com.swirlds.config.impl.internal.ConverterService.getConverterType(ConverterService.java:111)
	at com.swirlds.config.impl.internal.ConverterService.lambda$getConverterType$2(ConverterService.java:116)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.swirlds.config.impl.internal.ConverterService.getConverterType(ConverterService.java:116)
	at com.swirlds.config.impl.internal.ConverterService.addConverter(ConverterService.java:143)
	at com.swirlds.config.impl.internal.ConfigurationBuilderImpl.addConverter(ConfigurationBuilderImpl.java:138)
	at com.swirlds.config.impl.internal.ConfigurationBuilderImpl.withConverter(ConfigurationBuilderImpl.java:123)

```

**Comment by hendrikebbers** [comment]
As a workaround the interface can be added to the concrete implementation for now:

 ```
private static class RetentionPolicyConverter extends AbstractEnumConfigConverter<RetentionPolicy> implements
            ConfigConverter<RetentionPolicy> {

    @Override
    protected Class<RetentionPolicy> getEnumType() {
        return RetentionPolicy.class;
    }
}
```

**Comment by hendrikebbers** [comment]
AbstractEnumConfigConverterTest contains tests that show how enums can be used.
