### ISSUE TITLE
`IllegalArgumentException` when deleting old state

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#6170]
### Description

The following exception is observed in `swirlds.log` when running a single-node benchmark:
```
2023-04-17 23:16:33.889 17412    WARN  STARTUP          <<platform-core: signed-state-file-manager 0>> SavedStateMetadata: Signed state metadata file has invalid value for field SIGNING_NODES:
java.lang.IllegalArgumentException: List is empty
        at com.swirlds.platform.state.signed.SavedStateMetadata.parseLongList(SavedStateMetadata.java:329) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.platform.state.signed.SavedStateMetadata.parse(SavedStateMetadata.java:126) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.platform.state.signed.SavedStateInfo.getMetadata(SavedStateInfo.java:45) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.platform.state.signed.SignedStateFileManager.deleteOldStates(SignedStateFileManager.java:381) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.platform.state.signed.SignedStateFileManager.lambda$saveSignedStateToDisk$1(SignedStateFileManager.java:260) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.platform.state.signed.SignedStateFileManager.lambda$saveSignedStateToDisk$0(SignedStateFileManager.java:231) ~[swirlds-platform-core-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.common.threading.framework.internal.QueueThreadImpl.waitForItem(QueueThreadImpl.java:250) ~[swirlds-common-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:230) ~[swirlds-common-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:622) ~[swirlds-common-0.37.0-adhoc.xc76224af.jar:?]
        at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:217) ~[swirlds-common-0.37.0-adhoc.xc76224af.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

It is possible that a state is saved with 0 signatures due to heavy load when signing gets behind:
```
2023-04-17 23:15:30.993 16704    ERROR EXCEPTION        <<platform-core: state-hash-sign 0>> DefaultStateManagementComponent: state written to disk for round 15015 did not have enough signatures. Collected signatures representing 0/1 stake.
```
When recording such state, SIGNING_NODES is skipped. Throwing an `IllegalArgumentException` when reading `stateMetadata.txt` with omitted SIGNING_NODES indicates an internal error, which it is not.

### Hedera network

other

### Version

v0.37.0

### Operating system

Linux

**Comment by cody-littley** [comment]
A bug, but not a blocker. This is just a nasty-gram in the log, and does not cause any operation to fail. We should not log errors if there are no signatures. Errors should only be logged if the file is mal-formatted, and no signatures is not mal-formatted.
