### ISSUE TITLE
Flaky DataFileReader unit test

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#6423]
I observed the following test flake on one of my branches. Rerunning the panel caused the error to go away.

https://github.com/hashgraph/hedera-services/actions/runs/4861967178/jobs/8667696772?pr=6255

```
    ✘ Test DataFileReader with interrupts (9m 5s)

      java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.io.IOException: Failed to read from file, file channels keep getting closed
          at com.swirlds.merkledb.files.DataFileReaderHammerTest.interruptedReadsHammerTest(DataFileReaderHammerTest.java:117)
      Caused by: java.lang.RuntimeException: java.io.IOException: Failed to read from file, file channels keep getting closed
          at com.swirlds.merkledb.files.DataFileReaderHammerTest.lambda$interruptedReadsHammerTest$0(DataFileReaderHammerTest.java:92)
      Caused by: java.io.IOException: Failed to read from file, file channels keep getting closed
          at com.swirlds.merkledb.files.DataFileReaderHammerTest.lambda$interruptedReadsHammerTest$0(DataFileReaderHammerTest.java:84)
```

**Comment by cody-littley** [comment]
Artem included some changes that made this test more stable in a PR of his.
