### ISSUE TITLE
BDD Suite `ContractPerformanceSuite` doesn't run because no test contract json metadata files are in tree

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-services#6914]
### Description

BDD Suite `ContractPerformanceSuite` fails to run any tests because

1. References a file `performanceContracts.csv` which lists tests to be run but fails to find it - path needs to be `relocatedIfNotPresentInWorkingDir`.  (File does exist in `main/resource`.)

1. Then, once you get past that, all tests look for JSON-formatted Solidity metadata output which doesn't exist in the tree.  See `ContractPerformanceSuite` @L140:
```
            hapiSpecs.add(defaultHapiSpec("Perf_" + test)
                    .given(givenBlock)
                    .when(contractCall(test, "<empty>").gas(35000000).via(via))
```
which calls `TxnVerbs.contractCall` @L381:
```
    public static HapiContractCall contractCall(String contract, String functionName, Object... params) {
        final var abi = getABIFor(FUNCTION, functionName, contract);
``
which calls `bdd.suites.contract.Utils.getABIFor` @L148:
```
    public static String getABIFor(final FunctionType type, final String functionName, final String contractName) {
        try {
            final var path = getResourcePath(contractName, JSON_EXTENSION);
            try (final var input = new FileInputStream(path)) {
                return getFunctionAbiFrom(input, functionName, type);
            }
        } catch (final Exception ignore) {
            return getResourceABIFor(type, functionName, contractName);
```
which tries to find the file with the `.json` extension, can't find it in the file system, so calls `getResourceABIFor` @L161:
```
    public static String getResourceABIFor(
            final FunctionType type, final String functionName, final String contractName) {
        final var resourcePath =
                String.format(UNIQUE_CLASSPATH_RESOURCE_TPL, contractName, contractName + JSON_EXTENSION);
        try (final var input = Utils.class.getClassLoader().getResourceAsStream(resourcePath)) {
            return getFunctionAbiFrom(input, functionName, type);
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
```
which tries to find it as a resource, it isn't there either of course (since it isn't in the file system to be built from), and then
`getClassLoader().getResourceAsStream()` returns `null` which causes a throw of `NullPointerException`.  And then the test suite exits without creating any tests.

In fact it is somewhat worse that as it is looking for a structure
```
- &lt;contract-name>/
  - &lt;contract-name>.bin
  - &lt;contract-name>.json
```
and all that actually exists is
```
- &lt;contract-name>.bin
```

### Steps to reproduce

1.  Go to `ContractPerformanceSuite.java` in IntelliJ
2. Click on the green arrow next to `public class ContractPerformanceSuite ...`
3. Click on the "run" menu item
4. See the following output _instead_ of a successful run:

```
> Task :hedera-node:test-clients:ContractPerformanceSuite.main() FAILED
2023-06-03 15:03:07.336 INFO   232  ContractPerformanceSuite - -------------- STARTING ContractPerformance SUITE --------------
2023-06-03 15:03:07.447 WARN   169  HapiFileCreate - HapiFileCreate{path=src/main/resource/contract/performance/add_small.bin} failed to read bytes from 'src/main/resource/contract/performance/add_small.bin'!
java.io.FileNotFoundException: src/main/resource/contract/performance/add_small.bin (No such file or directory)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(FileInputStream.java:216) ~[?:?]
	at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
	at com.google.common.io.Files$FileByteSource.openStream(Files.java:132) ~[guava-31.1-jre-module.jar:?]
	at com.google.common.io.Files$FileByteSource.read(Files.java:156) ~[guava-31.1-jre-module.jar:?]
	at com.google.common.io.Files.toByteArray(Files.java:238) ~[guava-31.1-jre-module.jar:?]
	at com.hedera.services.bdd.spec.transactions.file.HapiFileCreate.path(HapiFileCreate.java:167) ~[main/:?]
	at com.hedera.services.bdd.suites.perf.contract.ContractPerformanceSuite.getSpecsInSuite(ContractPerformanceSuite.java:136) ~[main/:?]
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:235) ~[main/:?]
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteAsync(HapiSuite.java:218) ~[main/:?]
	at com.hedera.services.bdd.suites.perf.contract.ContractPerformanceSuite.main(ContractPerformanceSuite.java:68) ~[main/:?]
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
	at org.json.JSONTokener.<init>(JSONTokener.java:84)
	at com.hedera.services.bdd.suites.contract.Utils.getFunctionAbiFrom(Utils.java:171)
	at com.hedera.services.bdd.suites.contract.Utils.getResourceABIFor(Utils.java:164)
	at com.hedera.services.bdd.suites.contract.Utils.getABIFor(Utils.java:155)
	at com.hedera.services.bdd.spec.transactions.TxnVerbs.contractCall(TxnVerbs.java:382)
	at com.hedera.services.bdd.suites.perf.contract.ContractPerformanceSuite.getSpecsInSuite(ContractPerformanceSuite.java:142)
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:235)
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteAsync(HapiSuite.java:218)
	at com.hedera.services.bdd.suites.perf.contract.ContractPerformanceSuite.main(ContractPerformanceSuite.java:68)

Execution failed for task ':hedera-node:test-clients:ContractPerformanceSuite.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```


### Additional context

See also #6912 which reports that suites which fail to initialize - e.g., by throwing an exception from `HapiSuite.getSpecsInSuite()` fail _silently_: no message at all to user.

### Hedera network

other

### Version

`develop` on 2023-06-03

### Operating system

macOS

**Comment by Ferparishuertas** [comment]
Seems outdated
