### ISSUE TITLE
MerkleDB Unit Tests Hang

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7046]
Several times in the last week, I have observed the platform unit test suite get stuck and run for many hours. When I observe this, I cancel the test suite. Always, the workflow seem to be in the middle of the JasperDB tests.

Example: https://github.com/hashgraph/hedera-services/actions/runs/5224279727/jobs/9432293344?pr=7022

**Comment by cody-littley** [comment]
Stack trace where we are getting stuck:

```
"Test worker" #1 prio=5 os_prio=0 cpu=35366.39ms elapsed=4571.59s allocated=34029M defined_classes=6810 tid=0x00007f072c027960 nid=0x1ed8 waiting on condition  [0x00007f07315ca000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x0000000710cba600> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.3/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.3/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.3/CountDownLatch.java:230)
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.pausePipelineAndExecute(VirtualPipeline.java:600)
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.detachCopy(VirtualPipeline.java:401)
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.serialize(VirtualRootNode.java:1162)
	at com.swirlds.virtualmap.VirtualMap.serialize(VirtualMap.java:324)
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeSerializableNode(MerkleDataOutputStream.java:64)
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeInternal(MerkleDataOutputStream.java:81)
	at com.swirlds.common.io.streams.MerkleDataOutputStream.lambda$writeMerkleTree$1(MerkleDataOutputStream.java:172)
	at com.swirlds.common.io.streams.MerkleDataOutputStream$$Lambda$1267/0x0000000801175e70.accept(Unknown Source)
	at com.swirlds.common.merkle.iterators.MerkleIterator.forEachRemainingWithIO(MerkleIterator.java:408)
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeMerkleTree(MerkleDataOutputStream.java:166)
	at com.swirlds.merkledb.MerkleDbSnapshotTest.snapshotMultipleTablesTestAsync(MerkleDbSnapshotTest.java:192)

```

[jstack_extended_PR7004.txt](https://github.com/hashgraph/hedera-services/files/11726614/jstack_extended_PR7004.txt)

**Comment by imalygin** [comment]
Cody mentioned that it blocks multiple teams. I'm going to disable this test for now and continue the investigation to unblock everyone.

**Comment by imalygin** [comment]
Apparently, this is a race condition issue. I'm able to reproduce it locally 1 out of 4-5 runs. It's not reproducible if I run the same test multiple times but 
Here are the findings so far:

1. The main thread is blocked in `VirtualPipeline#pausePipelineAndExecute` on `await()` call
```
  try {
            waitForBackgroundThreadToStart.await();
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            throw new RuntimeException("Fatal error: failed to start " + label);
        }
```
<img width="475" alt="image" src="https://github.com/hashgraph/hedera-services/assets/1595361/2a31606f-965b-4494-814d-954d1815b27c">

It waits for the `waitForBackgroundThreadToStart` latch that is supposed to be unlocked by `virtual-pipeline:lifecycle` thread:

```
        final CountDownLatch waitForRunnableToFinish = new CountDownLatch(1);
        executorService.execute(() -> {
            waitForBackgroundThreadToStart.countDown();
```

2. `virtual-pipeline:lifecycle` thread is also blocked on waiting of the `dirtyLeaves` array traversal in method `com.swirlds.virtualmap.internal.cache.VirtualNodeCache#filterMutations`:
```
   try {
            array.parallelTraverse(CLEANING_POOL, action).getAndRethrow();
        } catch (final InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
 ```
 
<img width="557" alt="image" src="https://github.com/hashgraph/hedera-services/assets/1595361/493bbfdb-9920-4452-8335-f93f54ad3988">

That future will never return a result because corresponding `cache-cleaner` thread quietly died:

<img width="353" alt="image" src="https://github.com/hashgraph/hedera-services/assets/1595361/fb11cbfd-5cee-4cb7-9675-c4d35a36dee4">

with this error
```
<virtual-map: cache-cleaner #1> ERROR VirtualNodeCache Failed to purge unneeded key/mutationList pairs
java.lang.NullPointerException: Cannot invoke "com.swirlds.virtualmap.internal.cache.VirtualNodeCache$Mutation.setFiltered()" because "mutation.next" is null
	at com.swirlds.virtualmap.internal.cache.VirtualNodeCache.lambda$filterMutations$15(VirtualNodeCache.java:1322) ~[classes/:?]
	at com.swirlds.virtualmap.internal.cache.ConcurrentArray.lambda$parallelTraverse$0(ConcurrentArray.java:313) ~[classes/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
It was supposed to be rethrown but it didn't happen. 

Here is the code that caused NPE:
```
        final Consumer<Mutation<K, V>> action = mutation -> {
            if (mutation.next != null) {
                mutation.next.setFiltered();
            }
        };
```

There are two quesions:
1. Why did the mutation change? By the moment it's ready to be picked up by the cleaner thread it shouldn't change as it's no longer in use
2. Why did NPE was not re-thrown?

**Comment by imalygin** [comment]
Here is the answer to the second question is in `ConcurrentArray#parallelTraverse` implementation:

```
        for (SubArray<T> cur = head; cur != null && nextIndex < numberOfElements; cur = cur.next) {
            count.incrementAndGet();
            final T[] array = cur.array;
            final int size = cur.size.get();
            executor.execute(() -> {
                for (int i = 0; i < size; ++i) {
                    action.accept(array[i]);
                }
                if (count.decrementAndGet() == 0) {
                    result.complete(null);
                }
            });
            nextIndex += size;
        }
        if (count.decrementAndGet() == 0) {
            result.complete(null);
        }
```

if any call to `action.accept` ends with an exception, the future will never be set. And that is something to be fixed.

**Comment by OlegMazurov** [comment]
This bug was introduced by https://github.com/hashgraph/hedera-services/pull/6741.
