### ISSUE TITLE
`NullPointerException` in `io.helidon` code

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#7173]
### Description

When the server is under heavy load, the following exception is seen in `swirlds.log`:
```
Jun 19, 2023 5:34:59 PM io.grpc.internal.SerializeReentrantCallsDirectExecutor execute
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall@7225ddef
java.lang.IllegalStateException: java.lang.NullPointerException: Cannot invoke "io.helidon.grpc.server.MethodDescriptor.context()" because "methodDescriptor" is null
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:619)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInContext(ServerImpl.java:603)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializeReentrantCallsDirectExecutor.execute(SerializeReentrantCallsDirectExecutor.java:49)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.streamCreatedInternal(ServerImpl.java:644)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.streamCreated(ServerImpl.java:465)
        at io.grpc.netty.NettyServerHandler.onHeadersRead(NettyServerHandler.java:476)
        at io.grpc.netty.NettyServerHandler.access$1000(NettyServerHandler.java:106)
        at io.grpc.netty.NettyServerHandler$FrameListener.onHeadersRead(NettyServerHandler.java:856)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:409)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:65)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader$1.processFragment(DefaultHttp2FrameReader.java:450)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:457)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
        at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
        at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:117)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareThreadFactory.lambda$newThread$0(GrpcServerImpl.java:472)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "io.helidon.grpc.server.MethodDescriptor.context()" because "methodDescriptor" is null
        at io.helidon.grpc.server.ContextSettingServerInterceptor.interceptCall(ContextSettingServerInterceptor.java:74)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.Contexts.interceptCall(Contexts.java:52)
        at io.helidon.grpc.server.GrpcServerImpl$ContextAwareServerInterceptor.interceptCall(GrpcServerImpl.java:453)
        at io.helidon.grpc.server.BindableServiceImpl$InterceptingCallHandler.startCall(BindableServiceImpl.java:204)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:703)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$2200(ServerImpl.java:406)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1HandleServerCall.runInternal(ServerImpl.java:615)
        ... 39 more
```
One case is when `fullMethodName = proto.TokenService/createToken` (no such method in `proto.CryptoService`).
Another case is when `fullMethodName = proto.CryptoService/getTransactionReceipts`. `serviceDescriptor.method(methodName)` evaluates to a valid `methodDescriptor` in debugger, yet the actual value was `null` (looks like a data race issue).

### Steps to reproduce

Running the NFT transfer benchmark with the load generator.

### Hedera network

other

### Version

v.0.40.0-SNAPSHOT

### Operating system

Linux

**Comment by OlegMazurov** [comment]
It appears that the same instance of `ContextSettingServerInterceptor` is used on multiple threads. 
`InterceptingCallHandler.startCall()` calls `setServiceDescriptor(serviceDefinition)` with either `proto.TokenService` (for token creation) or `proto.CryptoService` (for transaction receipt). Doing that from multiple client threads for the same instance inevitably leads to missed `methodDescriptor` and NPE for **both** `createToken` and `getTransactionReceipts` 
 calls.

**Comment by rbair23** [comment]
Looking at this again, I think we could write a replacement for the helidon-grpc module based on PBJ and resolve this and get better performance at the same time. Might be worth a try.
