### ISSUE TITLE
Tests client causes ISS if no payingWith is specified

### ISSUE THREAD

**Issue by cesaragv** [hashgraph/hedera-services#719]
**Summary of the defect**
While running a test client, if no `payingWith` is specified, we get an `IndexOutOfBoundsException` and ISS starts happening.

**How to reproduce (if possible)**
The following test:

```
	private HapiApiSpec updateApiPermissionsDuringReconnect() {
		final String fileInfoRegistry = "apiPermissionsReconnect";
		return defaultHapiSpec("updateApiPermissionsDuringReconnect")
				.given(
						sleepFor(Duration.ofSeconds(60).toMillis()),
						getAccountBalance(GENESIS).setNode("0.0.6").unavailableNode()
				)
				.when(
						fileUpdate(API_PERMISSIONS)
						.overridingProps(Map.of("updateFile", "1-1011"))
						.payingWith(MASTER)
						.logged(),
						getAccountBalance(GENESIS).setNode("0.0.6").unavailableNode()
				)
				.then(

						sleepFor(Duration.ofMinutes(5).toMillis()),
						getFileContents(API_PERMISSIONS)
								.logged()
								.setNode("0.0.3")
								.saveToRegistry(fileInfoRegistry),
						getFileContents(API_PERMISSIONS)
								.logged()
								.setNode("0.0.6")
								.hasContents(fileInfoRegistry)
				);
	}
```

Causes the following exception in the reconnected node:

```
2020-10-27 02:12:08.301 INFO  235  ServicesState - Finish reconnect for HederaNode#3
2020-10-27 02:12:08.301 INFO  235  ServicesState - Finish reconnect for HederaNode#3
2020-10-27 02:12:08.303 INFO  108  ServicesMain - Now current platform status = ACTIVE in HederaNode#3.
2020-10-27 02:14:15.812 WARN  256  AwareProcessLogic - Almost inconceivably, when testing payer sig activation:
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4481) ~[?:?]
	at com.hedera.services.sigs.order.SigningOrderResult.getPayerKey(SigningOrderResult.java:76) ~[?:?]
	at com.hedera.services.keys.HederaKeyActivation.payerSigIsActive(HederaKeyActivation.java:81) ~[?:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.hasActivePayerSig(AwareProcessLogic.java:254) ~[?:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.doProcess(AwareProcessLogic.java:185) ~[?:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.processTxnInCtx(AwareProcessLogic.java:147) ~[?:?]
	at com.hedera.services.state.logic.ServicesTxnManager.process(ServicesTxnManager.java:59) ~[?:?]
	at com.hedera.services.legacy.services.state.AwareProcessLogic.incorporateConsensusTxn(AwareProcessLogic.java:117) ~[?:?]
	at com.hedera.services.ServicesState.handleTransaction(ServicesState.java:257) ~[?:?]
	at com.swirlds.platform.EventFlow.handleTransaction(EventFlow.java:718) ~[swirlds-platform-core-0.7.4-alpha.4.jar:?]
	at com.swirlds.platform.EventFlow.takeHandlePut(EventFlow.java:1206) ~[swirlds-platform-core-0.7.4-alpha.4.jar:?]
	at com.swirlds.platform.EventFlow.doCons(EventFlow.java:785) ~[swirlds-platform-core-0.7.4-alpha.4.jar:?]
	at com.swirlds.platform.StoppableThread.run(StoppableThread.java:191) ~[swirlds-platform-core-0.7.4-alpha.4.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
```

And ISS from which it never recovers.

**Comment by tinker-michaelj** [comment]
Fixed long ago ⏳
