### ISSUE TITLE
Exception running `EventStreamRecoverCommand`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#7287]
Command:
```
pcli event-stream recover data/saved/com.swirlds.demo.hashgraph.HashgraphDemoMain/0/123/2/SignedState.swh ./eventstreams/events_0/ --id=0 --main-name=com.swirlds.demo.hashgraph.HashgraphDemoMain --load ../platform-apps/demos/HashgraphDemo/build/libs/HashgraphDemo-0.40.0-SNAPSHOT.jar
```

Exception:
```
2023-06-27 16:24:24.128 5        INFO  STARTUP          <main> EventRecoveryWorkflow: Initializing application state
java.lang.NullPointerException: Cannot read field "left" because the return value of "com.swirlds.platform.gui.internal.BrowserWindowManager.getInsets()" is null
        at com.swirlds.platform.gui.internal.GuiUtils.winRect(GuiUtils.java:111)
        at com.swirlds.platform.gui.SwirldsGui.createWindow(SwirldsGui.java:89)
        at com.swirlds.demo.hashgraph.HashgraphDemoMain.init(HashgraphDemoMain.java:413)
        at com.swirlds.platform.recovery.EventRecoveryWorkflow.reapplyTransactions(EventRecoveryWorkflow.java:289)
        at com.swirlds.platform.recovery.EventRecoveryWorkflow.recoverState(EventRecoveryWorkflow.java:159)
        at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:120)
        at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.swirlds.cli.PlatformCli.main(PlatformCli.java:218)

```

**Comment by cody-littley** [comment]
Not something we need to worry about for the time being. It's not a high priority to be able to perform recovery using the hashgraph demo app.
