### ISSUE TITLE
EventRecoveryWorkflow `ReferenceCountException`

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#7297]
Running command

```
pcli event-stream recover data/saved/com.swirlds.demo.iss.ISSTestingToolMain/0/123/10254/SignedState.swh ./eventstreams/events_0/ --id=0 --main-name=com.swirlds.demo.iss.ISSTestingToolMain --load ../platform-apps/tests/ISSTestingTool/build/libs/ISSTestingTool-0.40.0-SNAPSHOT.jar
```

Many events are applied, state is written to disk

```
2023-06-28 10:31:20.750 1409     INFO  STATE_TO_DISK    <main> SignedStateFileWriter: Information for state written to disk:
Round = 11653, number of consensus events = 1223432, consensus timestamp = 2023-06-28T14:29:23.673812Z, last timestamp = 2023-06-28T14:29:23.673812Z, consensus Events running hash = dd50f3e24564d0c1a231ca884b48c300fd61854bd8230a10814a1d6f7ab3e7fcb577ad23d6fd696c7b4260ef73b50a85, address book hash = a14cc3f12c6871b50eb6c0bfef471d7293db02f1e86ddc1b224fe0aa63ba5307766cba8f408afe24eb08e77194cfbdfe
(root) State                /       ba07868bc3eda43e4a021fa0b0cbf5ad60daf7868d143f382be64697aed6e3cc554a0e8770ef3c71397dfdb428254f2c    
   0 ISSTestingToolState    /0      aec49aa32f5351bab28d5e1c4adff62aad1488d75cd6b0f148cebbc8039c718f814e7a4772ddc8635894e2dbb3e67053    
   1 PlatformState          /1      f576a54320d4b7008017916244fedbe08920e710a37c858386c40d49ffa1bec24b07a6dcc8b5e076de8112a7d1163f4e    
      0 PlatformData        /1/0    db9b3a77ddbd14cf904ac86e742e32ea997099f22aaef05f0b03fe284136ea982b2110fb5e8b68b4123c3125eb441094    
      1 AddressBook         /1/1    a14cc3f12c6871b50eb6c0bfef471d7293db02f1e86ddc1b224fe0aa63ba5307766cba8f408afe24eb08e77194cfbdfe    
   2 DualStateImpl          /2      83b9860b99739af958f5c5cff39bd6c3882150bc429c923b2eb8d8f9db0ad88c6dce3408445bf6d50ea7225e778a2c43  
```

and then the following exception was thrown:

```
com.swirlds.common.exceptions.ReferenceCountException: This ReservedSignedState has been closed.
        at com.swirlds.platform.state.signed.ReservedSignedState.throwIfClosed(ReservedSignedState.java:192)
        at com.swirlds.platform.state.signed.ReservedSignedState.get(ReservedSignedState.java:128)
        at com.swirlds.platform.recovery.EventRecoveryWorkflow.recoverState(EventRecoveryWorkflow.java:178)
        at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:120)
        at com.swirlds.platform.cli.EventStreamRecoverCommand.call(EventStreamRecoverCommand.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.swirlds.cli.PlatformCli.main(PlatformCli.java:218)
        Suppressed: com.swirlds.common.exceptions.ReferenceCountException: This ReservedSignedState has been closed.
                at com.swirlds.platform.state.signed.ReservedSignedState.throwIfClosed(ReservedSignedState.java:192)
                at com.swirlds.platform.state.signed.ReservedSignedState.close(ReservedSignedState.java:153)
                at com.swirlds.platform.recovery.EventRecoveryWorkflow.recoverState(EventRecoveryWorkflow.java:144)
                ... 11 more

```

**Comment by lpetrovic05** [comment]
This is most likely fixed by my changes to the tool that were made with the consensus changes

**Comment by poulok** [comment]
Closing since it is likely fixed. If it reoccurs, we can open it up again.
