### ISSUE TITLE
Virtual map is unhashed after a reconnect

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7416]
Scenario:

- state contains a virtual map
- node is disconnected for a while and falls behind
- node reconnects and discovers it is behind
- node receives state for round `N`
- node computes hash for round `N` state
- node validates the integrity of round `N` state 
- node attempts to write round `N` state to disk
- exception is thrown by virtual map code saying the map hasn't yet been hashed

http://35.247.76.217:8095/JeffreyDallas/07382-enable-pces/4N/Reconnect/20230705-183047-GCP-Daily-Reconnect-4N/VMerkle-NIReconnect-1k-15m/node0003/swirlds.log

```
java.lang.IllegalStateException: copy must be hashed before it is detached
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.detach(VirtualRootNode.java:1284) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.lambda$detachCopy$2(VirtualPipeline.java:401) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.pausePipelineAndExecute(VirtualPipeline.java:607) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.detachCopy(VirtualPipeline.java:401) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.serialize(VirtualRootNode.java:1162) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.VirtualMap.serialize(VirtualMap.java:324) ~[swirlds-virtualmap-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeSerializableNode(MerkleDataOutputStream.java:64) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeInternal(MerkleDataOutputStream.java:81) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.lambda$writeMerkleTree$1(MerkleDataOutputStream.java:172) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.iterators.MerkleIterator.forEachRemainingWithIO(MerkleIterator.java:408) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeMerkleTree(MerkleDataOutputStream.java:166) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFileToStream(SignedStateFileWriter.java:113) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeStateFile$0(SignedStateFileWriter.java:126) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.utility.FileUtils.writeAndFlush(FileUtils.java:275) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFile(SignedStateFileWriter.java:125) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateFilesToDirectory(SignedStateFileWriter.java:142) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeSignedStateToDisk$1(SignedStateFileWriter.java:193) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:239) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:216) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateToDisk(SignedStateFileWriter.java:192) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileManager.lambda$saveSignedStateToDisk$0(SignedStateFileManager.java:223) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:254) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:622) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:217) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by artemananiev** [comment]
```
node computes hash for round N state
```
How exactly is it done? Where is virtual map (root node) hash obtained from? My only guess is the hash is available (from the teacher), but `hashed` field in VirtualRootNode isn't set to true. If `VirtualRootNode.getHash()` is called, it will make sure `hashed` is set to true. However, if the hash is used directly from the teacher, then the error above may occur.

**Comment by cody-littley** [comment]
> How exactly is it done?

The tree is rehashed in `LearningSynchronizer.hash()`.

```
  /**
   * Hash the tree.
   */
  private void hash() throws InterruptedException {
      logger.info(RECONNECT.getMarker(), "hashing tree");
      final long start = System.currentTimeMillis();

      try {
          MerkleCryptoFactory.getInstance().digestTreeAsync(newRoot).get();
      } catch (ExecutionException e) {
          logger.error(EXCEPTION.getMarker(), "exception while computing hash of reconstructed tree", e);
          return;
      }

      hashTimeMilliseconds = System.currentTimeMillis() - start;
      logger.info(RECONNECT.getMarker(), "hashing complete");
  }
```

**Comment by cody-littley** [comment]
Steps to reproduce locally. Works in `develop`.

In `sdk/config.txt`, comment the hashgraph demo and uncomment the following:

```
 app,		MigrationTestingTool.jar, 4685095852903873060, 5000,	4
```

We need the migration testing tool because it contains a virtual map.

In `sdk/settings.txt`, make following changes:

```
state.saveStatePeriod,                    60                  # causes state to be written every 30 seconds
event.creation.maxCreationRate,           0                  # increase event creation rate, nodes fall behind faster
state.saveReconnectStateToDisk,           true                  # cause a state to be saved after a reconnect
```

Make sure the code is compiled. Run `pcli browse` from the `sdk` directory. Let it run for at least 3 minutes (you want it to save a few states to disk. Ignore the error messages with the `MIGRATION` tag.

Stop the system. 

`rm -r sdk/data/saved/com.swirlds.demo.migration.MigrationTestingToolMain/3`

☝️ This will cause node 3 to need to reconnect when it starts up.

Restart the system with `pcli browse`. You should see the exception within 30 seconds (i.e. as soon as node 3 reconnects).
