### ISSUE TITLE
Discrepancy between VirtualMap indexes and the data of the persisted state

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#7422]
### Description

There is a small discrepancy in the persisted state between index sizes (`pathToDiskLocationInternalNodes` and `pathToDiskLocationLeafNodes`) and the datasource metadata (`validLeafPathRange`) (see `VirtualDataSourceJasperDB` class). 

For example, when `VirtualDataSourceJasperDB` is initialized from the files of `143551637` round, it has `firstLeafPath` equals to 540230 and size of `pathToDiskLocationInternalNodes` equals to 540233. That is, `firstLeafPath = pathToDiskLocationInternalNodes.size()` invariant is violated. 

### Steps to reproduce

1. Download the state for one of the affected round (e.g. `gsutil -m cp -r   "gs://mainnet-1m/hedera-node-01/143859416"   .`)
2. Download the state validation tool (https://storage.googleapis.com/hedera-ci-ephemeral-artifacts/hedera/hedera-state-validator/mainnet-validator.jar)
3. Run following command:
`java -jar mainnet-validator.jar <path_to_state_dir> fast`

You'll see two tests failing: `ValidateInternalIndex` and `ValidateLeafIndex` with an error like the following one:
```
ValidateInternalIndex.validateIndex,[2] smartContractIterableKvStore - FAILED
org.opentest4j.AssertionFailedError: Some read operations failed ==> expected: <0> but was: <3>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:560)
	at com.hedera.statevalidation.validators.jasperdb.ValidateInternalIndex.validateIndex(ValidateInternalIndex.java:86)
```
and
```
ValidateLeafIndex.validateIndex,[2] smartContractIterableKvStore - FAILED
C:\Users\user\IdeaProjects\hedera-state-validator\report.json
org.opentest4j.AssertionFailedError: Some read operations failed ==> expected: <0> but was: <6>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:560)
	at com.hedera.statevalidation.validators.jasperdb.ValidateLeafIndex.validateIndex(ValidateLeafIndex.java:97)
```

### Additional context

1. The issue might have been there for a long time. The validation tool started failing once it got stricter asserts. Namely, it started failing if `pathToDiskLocationLeafNodes` size is different from `firstLeafPath`. Prior to this change, this was just a message in a log. 
2. The `rehash` test is passing, so the data integrity is not violated 
3. Index entries that are beyond the valid key range are not pointing to any existing data. 
4. This issue is not reproducible on version 0.39. That is, testnet is working fine

It needs further investigation but as of now the best explanation is that there is some data race, possibly between snapshot making and flushing.  

### Hedera network

mainnet

### Version

v0.38

### Operating system

None

**Comment by imalygin** [comment]
Further investigation (thank you, @artemananiev)  revealed that this issue is related to JasperDB only. And the root cause is simple - we never remove the elements explicitly once they got to the index. This has been changed with #5210  for MerkleDB in v0.38 but not for JasperDB. The issue cannot be reproduced on the testnet because we use MerkleDB instead of JasperDB there. 

Since we're decommissioning JasperDB anyway, this issue can be resolved as `Won't Fix`

**Comment by imalygin** [comment]
Some adjustments are required for the validation tool. This ticket will address that https://github.com/hashgraph/hedera-services/issues/7431
