### ISSUE TITLE
PTT fast copy bug

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7562]
https://github.com/swirlds/swirlds-platform-regression/issues/3590

http://35.247.76.217:8095/swirlds-automation/develop/10N/MultiNDReconnect/20230714-053619-GCP-Daily-MultiNDReconnect-10N/FCM-MultiNDReconnect-3R-2k-62m-chatter/node0000/swirlds.log
```
com.swirlds.common.merkle.exceptions.IllegalChildTypeException: Invalid class ID -9223372036854775808(0x8000000000000000) at index 2 for parent with class com.swirlds.demo.platform.PlatformTestingToolState
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.throwIfInvalidChild(AbstractMerkleInternal.java:157) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.setChild(AbstractMerkleInternal.java:100) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.interfaces.MerkleParent.setChild(MerkleParent.java:108) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.impl.internal.AbstractMerkleInternal.addDeserializedChildren(AbstractMerkleInternal.java:219) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.impl.PartialNaryMerkleInternal.addDeserializedChildren(PartialNaryMerkleInternal.java:135) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.demo.platform.PlatformTestingToolState.addDeserializedChildren(PlatformTestingToolState.java:482) ~[?:?]
	at com.swirlds.common.io.streams.internal.PartiallyConstructedMerkleInternal.finishConstruction(PartiallyConstructedMerkleInternal.java:51) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.addToParent(MerkleDataInputStream.java:77) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.finishReadingLeaf(MerkleDataInputStream.java:95) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readNextNode(MerkleDataInputStream.java:167) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.MerkleDataInputStream.readMerkleTree(MerkleDataInputStream.java:229) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileReader.lambda$readStateFile$2(SignedStateFileReader.java:148) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.io.streams.StreamDebugUtils.deserializeAndDebugOnFailure(StreamDebugUtils.java:82) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileReader.readStateFile(SignedStateFileReader.java:134) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.SavedStateLoader.readAndRehashState(SavedStateLoader.java:288) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.SavedStateLoader.getRegularSavedStateToLoad(SavedStateLoader.java:271) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.SavedStateLoader.getRegularSavedStateToLoad(SavedStateLoader.java:245) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.SavedStateLoader.getSavedStateToLoad(SavedStateLoader.java:153) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.getUnmodifiedSignedStateFromDisk(Browser.java:869) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.getInitialState(Browser.java:804) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.createLocalPlatforms(Browser.java:661) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:945) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.<init>(Browser.java:311) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:539) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:488) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:969) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
```

Root cause is that PTT state nulls out `nextSeqCons()` in its copy constructor depending on if the platform has been set or not.

**Comment by cody-littley** [comment]
Likely same root cause: https://github.com/swirlds/swirlds-platform-regression/issues/3592
