### ISSUE TITLE
PCES cleanup nullptr

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7611]
http://35.247.76.217:8095/swirlds-automation/develop/4N/FCMFCQ/20230718-053556-GCP-Daily-FCMFCQ-4N/FCMFCQ-Basic-3k-120m/node0002/swirlds.log
```
2023-07-18 07:15:07.256 229569   ERROR EXCEPTION        <<preconsensus: event-writer>> AbstractThreadConfiguration: exception on thread <preconsensus: event-writer>
java.lang.NullPointerException: Cannot invoke "com.swirlds.platform.event.preconsensus.PreconsensusEventFile.getPath()" because "file" is null
	at com.swirlds.platform.event.preconsensus.PreconsensusEventFileManager.pruneOldFiles(PreconsensusEventFileManager.java:574) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.pruneOldFiles(SyncPreconsensusEventWriter.java:299) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.closeFile(SyncPreconsensusEventWriter.java:351) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.prepareOutputStream(SyncPreconsensusEventWriter.java:388) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.SyncPreconsensusEventWriter.writeEvent(SyncPreconsensusEventWriter.java:189) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.event.preconsensus.AsyncPreconsensusEventWriter.addEventHandler(AsyncPreconsensusEventWriter.java:254) ~[swirlds-platform-core-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.MultiQueueThreadImpl.handle(MultiQueueThreadImpl.java:99) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:254) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:615) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:216) ~[swirlds-common-0.40.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by poulok** [comment]
Addressed in https://github.com/hashgraph/hedera-services/pull/7614
