### ISSUE TITLE
Unsafe closing of sockets

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#7762]
The issue seems to be that when we receive a new connection from a peer, we close it while the negotiator is still using it. This needs to be handled more elegantly.

```
2023-07-31 13:19:51.107 131844   ERROR SOCKET_EXCEPTIONS <<sync_server #426>> InboundConnectionManager: 2 got new connection from 1, disconnecting old one
2023-07-31 13:19:52.871 131845   ERROR SOCKET_EXCEPTIONS <<platform-core: SyncProtocolWith0 2 to 0>> NetworkUtils: Connection broken: 2 <- 0 Caused By: {Exception: IOException Message: com.swirlds.common.threading.pool.ParallelExecutionException: Time thrown: 2023-07-31T13:19:52.871700100Z Caused By: {Exception: ParallelExecutionException Message: Time thrown: 2023-07-31T13:19:52.871700100Z Caused By: {Exception: EOFException Message: null }}}
2023-07-31 13:19:52.872 131846   ERROR EXCEPTION        <<platform-core: SyncProtocolWith1 2 to 1>> NetworkUtils: Connection broken: 2 <- 1
javax.net.ssl.SSLException: Cannot read field "processed" because "this.engine" is null
	at sun.security.ssl.Alert.createSSLException(Alert.java:133) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:371) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:314) ~[?:?]
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:309) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1702) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1075) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:263) ~[?:?]
	at com.swirlds.common.io.extendable.extensions.AbstractStreamExtension.read(AbstractStreamExtension.java:75) ~[swirlds-common-0.40.2.jar:?]
	at com.swirlds.common.io.extendable.ExtendableInputStream.read(ExtendableInputStream.java:70) ~[swirlds-common-0.40.2.jar:?]
	at com.swirlds.common.io.extendable.extensions.AbstractStreamExtension.read(AbstractStreamExtension.java:75) ~[swirlds-common-0.40.2.jar:?]
	at com.swirlds.common.io.extendable.ExtendableInputStream.read(ExtendableInputStream.java:70) ~[swirlds-common-0.40.2.jar:?]
	at java.io.FilterInputStream.read(FilterInputStream.java:82) ~[?:?]
	at com.swirlds.common.io.streams.AugmentedDataInputStream.read(AugmentedDataInputStream.java:71) ~[swirlds-common-0.40.2.jar:?]
	at com.swirlds.platform.network.communication.states.SentKeepalive.transition(SentKeepalive.java:59) ~[swirlds-platform-core-0.40.2.jar:?]
	at com.swirlds.platform.network.communication.Negotiator.execute(Negotiator.java:94) ~[swirlds-platform-core-0.40.2.jar:?]
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:74) ~[swirlds-platform-core-0.40.2.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:622) ~[swirlds-common-0.40.2.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:217) ~[swirlds-common-0.40.2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "processed" because "this.engine" is null
	at com.sun.crypto.provider.GaloisCounterMode.checkDataLength(GaloisCounterMode.java:578) ~[?:?]
	at com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1433) ~[?:?]
	at com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:447) ~[?:?]
	at javax.crypto.Cipher.doFinal(Cipher.java:2500) ~[?:?]
	at sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1659) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260) ~[?:?]
	at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181) ~[?:?]
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1503) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1474) ~[?:?]
	at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1059) ~[?:?]
	... 14 more
```

**Comment by edward-swirldslabs** [comment]
The `Negotiator` class has a large body of exceptions that it catches, but NullPointerException is not one of the ones it is expecting to catch.  I'm surprised a NullPointer exception is escaping from the SSL library.  

Proposed solution: The `AugmentedDataInputStream` read method catch and rethrow the NullPointer exception as an IOException which the `Negotiator` is configured to catch.
