### ISSUE TITLE
PCES nullptr bug

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7799]
```
2023-07-28 22:45:32.269 39       ERROR EXCEPTION        <main> Browser: 
java.util.NoSuchElementException: null
	at com.swirlds.common.utility.RandomAccessDeque$1.next(RandomAccessDeque.java:263) ~[swirlds-common-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.common.utility.UnmodifiableIterator.next(UnmodifiableIterator.java:52) ~[swirlds-common-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.event.preconsensus.PreconsensusEventMultiFileIterator.findNext(PreconsensusEventMultiFileIterator.java:68) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.event.preconsensus.PreconsensusEventMultiFileIterator.hasNext(PreconsensusEventMultiFileIterator.java:80) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.event.preconsensus.PreconsensusEventReplayPipeline.replayEvents(PreconsensusEventReplayPipeline.java:139) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.event.preconsensus.PreconsensusEventReplayWorkflow.replayPreconsensusEvents(PreconsensusEventReplayWorkflow.java:103) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.SwirldsPlatform.replayPreconsensusEvents(SwirldsPlatform.java:1057) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.SwirldsPlatform.start(SwirldsPlatform.java:1040) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at com.swirlds.platform.Browser.startPlatforms(Browser.java:952) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.Browser.<init>(Browser.java:313) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:541) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:490) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:971) ~[swirlds-platform-core-0.41.0-adhoc.x2d52beef.jar:?]
```
[integration-node02-swirlds.log](https://github.com/hashgraph/hedera-services/files/12242038/integration-node02-swirlds.log)

**Comment by poulok** [comment]
Re-opening because it still needs to be cherry picked into develop
