### ISSUE TITLE
Exception when running local platform

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#7978]
Off of the most recent `develop` commit, when I run `pcli brose` locally (starting from genesis with default configuration), I observe the following exception.

```
java.lang.IllegalArgumentException: component not found in tabbed pane
	at javax.swing.JTabbedPane.setSelectedComponent(JTabbedPane.java:709) ~[?:?]
	at com.swirlds.platform.gui.internal.WinBrowser.goTab(WinBrowser.java:278) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.gui.internal.BrowserWindowManager.showBrowserWindow(BrowserWindowManager.java:99) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.<init>(Browser.java:318) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:543) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.cli.BrowseCommand.call(BrowseCommand.java:66) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.cli.BrowseCommand.call(BrowseCommand.java:35) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine.access$1300(CommandLine.java:145) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) ~[picocli-4.6.3.jar:4.6.3]
	at picocli.CommandLine.execute(CommandLine.java:2078) ~[picocli-4.6.3.jar:4.6.3]
	at com.swirlds.cli.PlatformCli.main(PlatformCli.java:221) ~[swirlds-cli-0.42.0-SNAPSHOT.jar:?]
```

**Comment by hendrikebbers** [comment]
When starting the gradle run task I can not see the error:
> Task :run
Listening for transport dt_socket at address: 8888
Reading the configuration from the file:   /Users/hendrikebbers/git/hedera-services/platform-sdk/sdk/config.txt
Creating keys, because there are no files in /Users/hendrikebbers/git/hedera-services/platform-sdk/sdk/data/keys
This computer has an internal IP address:  192.168.178.68

**Comment by hendrikebbers** [comment]
ok, can reproduce it.
