### ISSUE TITLE
DataFileCollection: Failed to copy data item 34

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8103]
The following failure was observed in a nightly run of `VMerkleDual-NDReconnect-500-60m`

http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230818-053611-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0003/

```
2023-08-18 06:16:48.118 8885     ERROR EXCEPTION        <<merkledb: Merging #0>> DataFileCollection: Failed to copy data item 34 / 22008224
java.nio.channels.ClosedByInterruptException: null
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199) ~[?:?]
	at sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:168) ~[?:?]
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:820) ~[?:?]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:800) ~[?:?]
	at com.swirlds.merkledb.utilities.MerkleDbFileUtils.completelyRead(MerkleDbFileUtils.java:91) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileReader.read(DataFileReader.java:377) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileReader.readDataItemBytes(DataFileReader.java:201) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.lambda$compactFiles$2(DataFileCollection.java:447) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.collections.AbstractLongList.forEach(AbstractLongList.java:635) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.MemoryIndexDiskKeyValueStore$1.forEach(MemoryIndexDiskKeyValueStore.java:208) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.compactFiles(DataFileCollection.java:426) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.MemoryIndexDiskKeyValueStore.merge(MemoryIndexDiskKeyValueStore.java:212) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.doMerge(MerkleDbDataSource.java:1382) ~[swirlds-jasperdb-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by imalygin** [comment]
This happens when compaction is interrupted by flush. This is expected and, therefore, this particular exception shouldn't be reported as an error.

**Comment by alittley** [comment]
> This is expected and, therefore, this particular exception shouldn't be reported as an error.

@imalygin given this, is it possible for the exception to be caught and logged as an error?
