### ISSUE TITLE
Test Query-Restart-Performance-7N-7C-10k-30m has error INVALID_ACCOUNT_ID

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8132]
### Description

Although test summary report the test passed, but actually there was INVALID_ACCOUNT_ID from client log,
right after client start.
so client did not send any transactions at all.

![image](https://github.com/hashgraph/hedera-services/assets/39912573/c63e2ad8-dd21-408b-b71f-496e55d5e660)

```
2023-08-21 06:45:49.179 ERROR  60   CustomSpecAssert - Operation 'HapiGetAccountInfo{payer=GENESIS, node=0.0.3, account=0.0.237087}' :: Answer-only precheck was INVALID_ACCOUNT_ID, not one of [OK, TRANSACTION_EXPIRED, DUPLICATE_TRANSACTION, PLATFORM_TRANSACTION_NOT_CREATED]!
Exception in thread "thread2" java.lang.IllegalStateException: com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Answer-only precheck was INVALID_ACCOUNT_ID, not one of [OK, TRANSACTION_EXPIRED, DUPLICATE_TRANSACTION, PLATFORM_TRANSACTION_NOT_CREATED]!
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:61)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.executeHederaOps(CustomSpecAssert.java:46)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:40)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.allRunFor(CustomSpecAssert.java:66)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.testRun(RunLoadTest.java:244)
	at com.hedera.services.bdd.spec.utilops.RunLoadTest.lambda$threadMode$22(RunLoadTest.java:210)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.hedera.services.bdd.spec.exceptions.HapiQueryPrecheckStateException: Answer-only precheck was INVALID_ACCOUNT_ID, not one of [OK, TRANSACTION_EXPIRED, DUPLICATE_TRANSACTION, PLATFORM_TRANSACTION_NOT_CREATED]!
	at com.hedera.services.bdd.spec.queries.HapiQueryOp.submitOp(HapiQueryOp.java:190)
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:238)
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.handleExec(CustomSpecAssert.java:58)
	... 6 more

```

The reason that validator did not report the error because test suite did not report error in it's summary

```
2023-08-21 06:45:49.613 INFO   451  HapiSpec - 'runQueryLoadTest' finished initial execution of RunLoadTest{}
2023-08-21 06:45:50.089 INFO   481  HapiSpec - 'runQueryLoadTest' - final status: PASSED!
2023-08-21 06:45:50.096 INFO   638  SuiteRunner - ============== sync run results ==============
2023-08-21 06:45:50.096 INFO   640  SuiteRunner - QueryOnlyLoadTest                :: 1/1 suites ran ok
2023-08-21 06:45:50.096 INFO   651  SuiteRunner - ============== SuiteRunner finished ==============
2023-08-21 06:45:50.097 INFO   293  QueryOnlyLoadTest - -------------- STARTING QueryOnlyLoadTest SUITE --------------
2023-08-21 06:45:50.097 INFO   294  QueryOnlyLoadTest - -------------- RESULTS OF QueryOnlyLoadTest SUITE --------------
2023-08-21 06:45:50.098 INFO   296  QueryOnlyLoadTest - Spec{name=runQueryLoadTest, status=PASSED}
```

---

The client has the error since May 2022

https://swirldslabs.slack.com/archives/C03FD752LKA/p1653375611774489

### Steps to reproduce

Nightly test panel GCP-Weekly-Query-Restart-Perf-7N-7C

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Could be the same root cause as #8152, something related with function
getTestTreasureStartAccount() or `testTreasureStartAccount`

**Comment by JeffreyDallas** [comment]
Closing since no longer need to run performance test
