### ISSUE TITLE
AWS daily reconnect TransactionHistory-Reconnect fails for unexpected precheck status "OK"

### ISSUE THREAD

**Issue by ljianghedera** [hashgraph/hedera-services#815]
**Summary of the defect**
It fails for unexpected precheck status "OK" instead of "DUPLICATE_TRANSACTION". 

**How to reproduce (if possible)**
Slack report link: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1606728919023800

Detailed client log: https://s3.console.aws.amazon.com/s3/object/hedera-service-regression-jrs?region=us-east-2&prefix=4N_1C/Reconnect/20201130-0717-AWS-Daily-Services-Comp-Reconnect-4N-1C/APIPermissionUpdate-Reconnect-1-12m.json/node0000-TestClient/hapi-client-combined.log
 

**Service logs (if applicable)**
```
...
2020-11-30 09:20:38.843 INFO   67   NodeLivenessTimeout - Requiring node 0.0.6 to be available in 180 SECONDS
2020-11-30 09:21:18.845 INFO   86   NodeLivenessTimeout -  --> Node 0.0.6 not available after 10 SECONDS
2020-11-30 09:21:48.848 INFO   86   NodeLivenessTimeout -  --> Node 0.0.6 not available after 20 SECONDS
2020-11-30 09:22:18.852 INFO   86   NodeLivenessTimeout -  --> Node 0.0.6 not available after 30 SECONDS
2020-11-30 09:22:48.854 INFO   86   NodeLivenessTimeout -  --> Node 0.0.6 not available after 40 SECONDS
2020-11-30 09:22:48.928 INFO   77   NodeLivenessTimeout -  --> Node 0.0.6 available after 40 SECONDS
2020-11-30 09:22:48.928 INFO   227  HapiApiSpec - 'validateDuplicateTransactionAfterReconnect' finished initial execution of NodeLivenessTimeout{}
2020-11-30 09:22:48.935 INFO   140  HapiTxnOp - 'validateDuplicateTransactionAfterReconnect' -  submitting HapiCryptoCreate{payer=strong-control, node=0.0.6, account=repeatedTransaction} via body=transactionID { transactionValidStart { seconds: 1606728003 nanos: 356 } accountID { accountNum: 50 } } nodeAccountID { accountNum: 6 } transactionFee: 13299075 transactionValidDuration { seconds: 180 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoCreateAccount { key { ed25519: "U\277W:\300;\364U\214\357\271\357\367\202xX\222\317g\223\030\341\274D]\372\032\261!\376\340^" } initialBalance: 1000000000 proxyAccountID { } sendRecordThreshold: 5000000000000000000 receiveRecordThreshold: 5000000000000000000 autoRenewPeriod { seconds: 7776000 } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "b\355\317\373\376\222\275\257h\026\212D\342\267\336x\300\323\n\262t\021\005\375\033\217\'\236:\017K}*d\271\254\316\275\216\344\357\206L\226\360v)\304\264\232\336\244\202\376\255wC$\257e\272\'\355\b" } sigPair { pubKeyPrefix: "U" ed25519: "\\\257\227\347E\267X\004\"\3012\001*4\320\244\214\r7\300\365\337F~\341!!\312\224\307\202\304\211\346\365\244\035c\346_\365N_0\243\247\273U\216\317\321\231=\005\342\257\t\001\205\000\342\016c\r" }
2020-11-30 09:22:49.067 WARN   199  HapiSpecOperation - 'validateDuplicateTransactionAfterReconnect' - HapiCryptoCreate{sigs=2, payer=strong-control, node=0.0.6, account=repeatedTransaction} failed!
java.lang.AssertionError: Wrong precheck status! expected:<DUPLICATE_TRANSACTION> but was:<OK>
	at org.junit.Assert.fail(Assert.java:88) ~[SuiteRunner.jar:?]
	at org.junit.Assert.failNotEquals(Assert.java:834) ~[SuiteRunner.jar:?]
	at org.junit.Assert.assertEquals(Assert.java:118) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:191) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:179) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.exec(HapiApiSpec.java:222) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:176) ~[SuiteRunner.jar:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSync(HapiApiSuite.java:249) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuite(HapiApiSuite.java:140) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiApiSuite.runSuiteSync(HapiApiSuite.java:133) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$15(SuiteRunner.java:490) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:491) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:465) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) [?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:465) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:434) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:358) [SuiteRunner.jar:?]
2020-11-30 09:22:49.071 INFO   244  HapiApiSpec - 'validateDuplicateTransactionAfterReconnect' - final status: FAILED!
2020-11-30 09:22:49.071 INFO   168  ValidateDuplicateTransactionAfterReconnect - -------------- RESULTS OF ValidateDuplicateTransactionAfterReconnect SUITE --------------
2020-11-30 09:22:49.071 INFO   170  ValidateDuplicateTransactionAfterReconnect - Spec{name=validateDuplicateTransactionAfterReconnect, status=FAILED}
2020-11-30 09:22:49.077 INFO   439  SuiteRunner - ============== sync run results ==============
2020-11-30 09:22:49.077 INFO   442  SuiteRunner - ValidateDuplic...AfterReconnect :: 0/1 suites ran OK
2020-11-30 09:22:49.078 INFO   448  SuiteRunner -   --> Problems in suite 'ValidateDuplicateTransactionAfterReconnect' :: Spec{name=validateDuplicateTransactionAfterReconnect, status=FAILED}



```
**Environment:**
- OS: [e.g. Ubuntu 18.04]
- Java: [e.g. OpenJDK 11.0.4]
- Hedera Services Version: [e.g. 0.0.5]
- HAPI Version: [e.g. 0.0.5]

**Additional Context**
Add any other context about the problem here. Attach any logs here, if applicable.

**Comment by ljianghedera** [comment]
Checked the history of this test. It has been failing from day one when it's merged into 'develop' branch on 11/25/2020.

**Comment by ljianghedera** [comment]
Also notice that the swirlds.log from the server nodes showed there are ISS errors:

https://s3.console.aws.amazon.com/s3/object/hedera-service-regression-jrs?region=us-east-2&prefix=4N_1C/Reconnect/20201127-0717-AWS-Daily-Services-Comp-Reconnect-4N-1C/TransactionHistory-Reconnect-1-12m/node0003/swirlds.log


```
2020-11-29 09:22:14.077 DEBUG 354  ConsensusImpl - ConsensusImpl is initialized. minRound: 2819, maxRound: 2829
2020-11-29 09:22:14.078 INFO  618  Hashgraph - Last known sequence numbers after restart are [15812, 15173, 14865, 2]
2020-11-29 09:22:14.078 INFO  207  Hashgraph - threadPollIntakeQueue is started
2020-11-29 09:22:14.079 INFO  500  EventFlow -  doConsMinGenFamous after startup [(2820,17804), (2821,17811), (2822,17817), (2823,17822), (2824,17828), (2825,17834), (2826,17839), (2827,17844), (2828,17850), (2829,17856), (2830,17861)]
2020-11-29 09:22:14.085 INFO  616  EventFlow - EventFlow.startAll(), forCons.size: 0, forCurr.size: 0, forNext.size: null, forSigs.size: 152, forWork.size: null
2020-11-29 09:22:14.085 INFO  1066 SwirldsPlatform - Platform status changed. {"oldStatus":"BEHIND","newStatus":"ACTIVE"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2020-11-29 09:22:14.086 INFO  1071 SwirldsPlatform - Platform status changed to: ACTIVE
2020-11-29 09:22:21.858 ERROR 992  SignedStateManager - Exception: 3 Received invalid state signature! round:2928 memberId:1 details:
hash: 5c8fa1ba9b86e847d4f693929a7482c358b64872ecefdc8a31024e3329cfc6dd360b221a5a6126574b1bf84e99a794ac
consensusTimestamp: 2020-11-29T09:22:21.555498084Z
numEventsCons: 47409
hashEventsCons: fccba617a769f96778843b115687df1138286bde121b53b192c505ed472f22468f898954a69eb76bdcd837d40edf9205
eventHashXor: 04993f47ecef4039276b5e34bae4ab0256b5c346c39e3c4caa4dc2687950cf1f2913afbbe3ec6fb2e8f0008347fa7017
swirldStateHash: e2dca446bf0360741b4c12ffb27383f386be1ac1182d4d52099f954a7bb70dda04cba6caeae5c7ff3c8c7643c98efced
addressBookHash: e21c3173977c9c797672b32f2837c2cfd275675a3ef66fc74b0e894c825b219193ac0938990bcbb847c4a3f33367e857
ssLeafHash: 53f006c2a66298df42b9d863821a31c54ee623f151714a0135ec3d5627de687b7cccc757215433d51585afbe17441b04
ssLeafConsensusTime: 2020-11-29T09:22:21.555498084Z
ssLeafRound: 2928
ssLeafNumEventsCons: 47409
ssLeafHashEventsCons: fccba617a769f96778843b115687df1138286bde121b53b192c505ed472f22468f898954a69eb76bdcd837d40edf9205
ssLeafMinGenInfo: [(2918,18402), (2919,18407), (2920,18417), (2921,18424), (2922,18431), (2923,18438), (2924,18445), (2925,18451), (2926,18456), (2927,18463), (2928,18470)]
ssLeafAddressBookHash: e21c3173977c9c797672b32f2837c2cfd275675a3ef66fc74b0e894c825b219193ac0938990bcbb847c4a3f33367e857
ssLeafEventCount: 168
ssLeafLastTransactionTimestamp: 2020-11-29T09:22:21.555498084Z
events: 
BaseEventHashedData{creatorId=0, selfParentGen=18401, otherParentGen=18399, selfParentHash=b3a8066281..., otherParentHash=4c2e875c23..., timeCreated=2020-11-29T09:22:20.633804Z, transactions size=0, hash=abd9b1c47a...}
BaseEventUnhashedData{creatorSeq=16267, otherId=2, otherSeq=15315, signature=871e3b2833...}
ConsensusEventData{generation=18402, roundCreated=2918, isWitness=true, isFamous=true, stale=false, consensusTimestamp=2020-11-29T09:22:20.644509Z, roundReceived=2919, consensusOrder=47241, lastInRoundReceived=false}
BaseEventHashedData{creatorId=1, selfParentGen=18400, otherParentGen=18400, selfParentHash=6543ee293a..., otherParentHash=894bcf87dc..., timeCreated=2020-11-29T09:22:20.620167Z, transactions size=0, hash=a4da180dfc...}
BaseEventUnhashedData{creatorSeq=15635, otherId=0, otherSeq=16265, signature=57867dea81...}
ConsensusEventData{generation=18401, roundCreated=2917, isWitness=false, isFamous=false, stale=false, consensusTimestamp=2020-11-29T09:22:20.644509001Z, roundReceived=2919, consensusOrder=47242, lastInRoundReceived=false}
BaseEventHashedData{creatorId=2, selfParentGen=18399, otherParentGen=18401, selfParentHash=4c2e875c23..., otherParentHash=b3a8066281..., timeCreated=2020-11-29T09:22:20.643378Z, transactions size=0, hash=e33ceb96ea...}
BaseEventUnhashedData{creatorSeq=15316, otherId=0, otherSeq=16266, signature=0ea3b25c73...}
ConsensusEventData{generation=18402, roundCreated=2918, isWitness=true, isFamous=true, stale=false, consensusTimestamp=2020-11-29T09:22:20.651662Z, roundReceived=2919, consensusOrder=47243, lastInRoundReceived=false}
BaseEventHashedData{creatorId=0, selfParentGen=18402, otherParentGen=18401, selfParentHash=abd9b1c47a..., otherParentHash=a4da180dfc..., timeCreated=2020-11-29T09:22:20.644509Z, transactions size=0, hash=053d300ad4...}
BaseEventUnhashedData{creatorSeq=16268, otherId=1, otherSeq=15635, signature=5df3f58ad5...}
ConsensusEventData{generation=18403, roundCreated=2918, isWitness=false, isFamous=false, stale=false, consensusTimestamp=2020-11-29T09:22:20.673374Z, roundReceived=2919, consensusOrder=47244, lastInRoundReceived=false}
BaseEventHashedData{creatorId=2, selfParentGen=18402, otherParentGen=18402, selfParentHash=e33ceb96ea..., otherParentHash=abd9b1c47a..., timeCreated=2020-11-29T09:22:20.651662Z, transactions size=0, hash=6f7c812413...}
BaseEventUnhashedData{creatorSeq=15317, otherId=0, otherSeq=16267, signature=1865404448...}
ConsensusEventData{generation=18403, roundCreated=2918, isWitness=false, isFamous=false, stale=false, consensusTimestamp=2020-11-29T09:22:20.680185Z, roundReceived=2919, consensusOrder=47245, lastInRoundReceived=false}
BaseEventHashedData{creatorId=1, selfParentGen=18401, otherParentGen=18402, selfParentHash=a4da180dfc..., otherParentHash=abd9b1c47a..., timeCreated=2020-11-29T09:22:20.639763Z, transactions size=0, hash=15c8da961b...}
BaseEventUnhashedData{creatorSeq=15636, otherId=0, otherSeq=16267, signature=7b71570996...}
ConsensusEventData{generation=18403, roundCreated=2918, isWitness=true, isFamous=true, stale=false, consensusTimestamp=2020-11-29T09:22:20.682564Z, roundReceived=2919, consensusOrder=47246, lastInRoundReceived=false}
BaseEventHashedData{creatorId=0, selfParentGen=18403, otherParentGen=18402, selfParentHash=053d300ad4..., otherParentHash=e33ceb96ea..., timeCreated=2020-11-29T09:22:20.653464Z, transactions size=0, hash=e90cc249d4...}
BaseEventUnhashedData{creatorSeq=16269, otherId=2, otherSeq=15316, signature=55ffb47252...}
ConsensusEventData{generation=18404, roundCreated=2918, isWitness=false, isFamous=false, stale=false, consensusTimestamp=2020-11-29T09:22:20.682564001Z, roundReceived=2919, consensusOrder=47247, lastInRoundReceived=false}
BaseEventHashedData{creatorId=1, selfParentGen=18403, otherParentGen=18402, selfParentHash=15c8da961b..., otherParentHash=e33ceb96ea..., timeCreated=2020-11-29T09:22:20.647879Z, transactions size=0, hash=9d70600a1b...}
BaseEventUnhashedData{creatorSeq=15637, otherId=2, otherSeq=15316, signature=635fc923e7...}
ConsensusEventData{generation=18404, roundCreated=2918, isWitness=false, isFamous=false, stale=false, consensusTimestamp=2020-11-29T09:22:20.682564002Z, roundReceived=2919, consensusOrder=47248, lastInRoundReceived=false}
BaseEventHashedData{creatorId=2, selfParentGen=18403, otherParentGen=18401, selfParentHash=6f7c812413..., otherParentHash=a4da180dfc..., timeCreated=2020-11-29T09:22:20.659836Z, transactions size=0, hash=3407b0332c...}
BaseEventUnhashedData{creatorSeq=15318, otherId=1, otherSeq=15635, signature=740fde5917...}

```

**Comment by cesaragv** [comment]
This is fixed by [689](https://github.com/swirlds/swirlds-platform-regression/pull/689)
