### ISSUE TITLE
Figure out why the record file hash chain is broken

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#8176]

**Comment by mhess-swl** [comment]
These are the only commits merged to `develop` on Aug 15th (see [here](https://github.com/hashgraph/hedera-services/pulls?q=is%3Apr+is%3Aclosed+closed%3A2023-08-15..2023-08-15+-status%3Adraft)), the day the importer started consistently failing:

* #8025 
* #8005 
* #8004 
* #7949 

None of these PRs point to anything obvious (to me) that could’ve broken the hash.

I’ve looked at all the logs in `integration` and `integration-docker`, and have not been able to find any error or warning messages that obviously indicate an issue with the hash. There was a freeze around 8am CST on 8/15, presumably for a deployment; the only error messages are a few `SocketException Message: Connection reset`, which looks like a network hiccup. There were successful node startups at ~8:01:10, as well as a number of messages about starting from a valid hash.

My next avenue of exploration is running a node locally with a single signed state. I want to replay a set of events while swapping out different pieces of code from the above PRs to see if the hash changes in the resulting records produced. Another potential path is to dig around in the record files/sigs  in 2023-08-21T19_33_38.033000246Z, though a quick look at a couple of those records didn’t show anything odd (warn: I might easily miss something odd in the record files).

**Comment by mhess-swl** [comment]
Worthy of note, the first file after an upgrade broke the hash chain today:
```
2023-08-22T16:38:54.040+0000 INFO scheduling-3 c.h.m.i.d.r.RecordFileDownloader No new signature files to download after file: 2023-08-22T16_31_00.029561779Z.rcd.gz. Retrying in 0.5 s 
2023-08-22T16:38:54.588+0000 INFO scheduling-2 c.h.m.i.d.r.RecordFileDownloader No new signature files to download after file: 2023-08-22T16_31_00.029561779Z.rcd.gz. Retrying in 0.5 s 
2023-08-22T16:38:55.214+0000 INFO scheduling-2 c.h.m.i.d.r.RecordFileDownloader Downloaded 6 signatures in 124.4 ms (48/s): {2023-08-22T16_38_38.465367602Z.rcd_sig=6} 
2023-08-22T16:38:55.218+0000 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Verified signature file 2023-08-22T16_38_38.465367602Z.rcd_sig reached consensus but with some errors: {NOT_FOUND=[1]} 
2023-08-22T16:38:55.271+0000 INFO scheduling-2 c.h.m.i.r.r.CompositeRecordFileReader Read 4 items successfully from v6 record file 2023-08-22T16_38_38.465367602Z.rcd.gz in 1.165 ms 
2023-08-22T16:38:55.271+0000 WARN scheduling-2 c.h.m.i.d.r.RecordFileDownloader Failed processing signature from node 5 corresponding to 2023-08-22T16_38_38.465367602Z.rcd_sig. Will retry another node: Running hash mismatch for file 2023-08-22T16_38_38.465367602Z.rcd.gz. Expected = 8c2a77fdceded3ee67a9d5c0517ab43e923ad75c3b9fe916d66f2008e6d97ecd38fd4e79376b2f71ac0304a0082b6c51, Actual = fbc9e4b734dd20971432bb50c98fc20ce8ba98e159672ae98934d00dcb14c2a16c2a80bf79a9df2944d029d5087848af
```

**Comment by mhess-swl** [comment]
I'm getting an exception trying to run the node software locally. This is making progress difficult because I can't replay events and look at the resulting records. 
```
Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class com.swirlds.platform.uptime.UptimeDataImpl, from class com.swirlds.common.constructable.internal.GenericConstructorRegistry (module com.swirlds.common)
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:955) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3686) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3646) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750) ~[?:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.createConstructorLambda(GenericConstructorRegistry.java:170) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.registerConstructables(GenericConstructorRegistry.java:105) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructables(DefaultConstructableRegistry.java:62) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.util.BootstrapUtils.loadSwirldMains(BootstrapUtils.java:537) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:202) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:170) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	... 3 more
```

**Comment by david-bakin-sl** [comment]
Change from milliseconds to nanoseconds at https://github.com/hashgraph/hedera-services/blob/a5f7cfccf4c0173ec4619f1bc2b73a4cbde5dc5b/platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncOutputStream.java#L240 may round differently, thus may change the comparison result - and this is in a file called `.../merkle/SYNCHRONIZATION/STREAMS/...` so even though I don't know the way this may change the running hash ... it might?

**Comment by mhess-swl** [comment]
The following exception has been resolved with ticket #8187 

> I'm getting an exception trying to run the node software locally. This is making progress difficult because I can't replay events and look at the resulting records.
> 
> ```
> Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class com.swirlds.platform.uptime.UptimeDataImpl, from class com.swirlds.common.constructable.internal.GenericConstructorRegistry (module com.swirlds.common)
> 	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:955) ~[?:?]
> 	at java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3686) ~[?:?]
> 	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3646) ~[?:?]
> 	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750) ~[?:?]
> 	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.createConstructorLambda(GenericConstructorRegistry.java:170) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.registerConstructables(GenericConstructorRegistry.java:105) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructables(DefaultConstructableRegistry.java:62) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	at com.swirlds.platform.util.BootstrapUtils.loadSwirldMains(BootstrapUtils.java:537) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:202) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	at com.swirlds.platform.Browser.launch(Browser.java:170) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
> 	... 3 more
> ```

**Comment by mhess-swl** [comment]
After some nontrivial data collection in the integration and integration-docker environments, we determined that the node was not correctly handling blocks during a restart, specifically after a freeze state. Per @tinker-michaelj:

> This can only happen when upgrading from 0.41, because until then there was no pre-consensus event stream
> The scenario is as follows:
> * The network restarts from a freeze state; and,
> * Processes events whose consensus times are still in the last 2-second block B written before freezing.
> In this case, 
> * All post-restart transactions that belonged in block B are omitted from the record stream.

> The fix is for BlockManager to begin a new block if either :one: consensus time has moved out of the 2-second period that contains firstConsTimeInCurrentBlock or :two: this is the first transaction after an init() call that had a non-null dualState.freezeTime().equals(dualState.lastFrozenTime())

**Comment by mhess-swl** [comment]
This code has been merged to the `release/0.42` branch, but still needs to go into `develop`. It can be merged to `develop` as soon as release engineering is done with the unified Gradle build improvements.

**Comment by mhess-swl** [comment]
After looking at `BlockRecordManagerImpl.startUserTransaction(...)`, it looks like we need to apply the same fix to the modular code.

**Comment by mhess-swl** [comment]
This was also found to be a problem in the 0.41 release branch, so the fix was merged there as well. See PR #8444

**Comment by mhess-swl** [comment]
We'll implement the fix in the modularized app in a different ticket. See #8530
