### ISSUE TITLE
AllProtectedFilesUpdate-NIReconnect-1-16m failed with serialization exception 2023-08-23

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#8184]
Node 5 log link: http://35.247.76.217:8095/swirlds-automation/develop/6N_1C/NIReconnectCorrectness/20230823-064004-GCP-NI-Reconnect-Correctness-6N-1C/AllProtectedFilesUpdate-NIReconnect-1-16m/node0005/swirlds.log

exception: 
```
2023-08-23 06:59:25.671 32453    ERROR EXCEPTION        <<platform-core: signed-state-file-manager 5>> SignedStateFileManager: Unable to write signed state to disk for round 599 to /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.hedera.services.ServicesMain/5/123/599.
java.lang.IllegalArgumentException: Cannot snapshot a secondary table, uniqueTokenStore
	at com.swirlds.merkledb.MerkleDb.snapshot(MerkleDb.java:519) ~[swirlds-jasperdb-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSourceBuilder.snapshot(MerkleDbDataSourceBuilder.java:143) ~[swirlds-jasperdb-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.detach(VirtualRootNode.java:1313) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.lambda$detachCopy$2(VirtualPipeline.java:426) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.pausePipelineAndExecute(VirtualPipeline.java:636) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.detachCopy(VirtualPipeline.java:426) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.serialize(VirtualRootNode.java:1167) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.virtualmap.VirtualMap.serialize(VirtualMap.java:324) ~[swirlds-virtualmap-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeSerializableNode(MerkleDataOutputStream.java:64) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeInternal(MerkleDataOutputStream.java:81) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.lambda$writeMerkleTree$1(MerkleDataOutputStream.java:172) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.merkle.iterators.MerkleIterator.forEachRemainingWithIO(MerkleIterator.java:410) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeMerkleTree(MerkleDataOutputStream.java:166) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFileToStream(SignedStateFileWriter.java:114) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeStateFile$0(SignedStateFileWriter.java:127) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.utility.FileUtils.writeAndFlush(FileUtils.java:281) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFile(SignedStateFileWriter.java:126) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateFilesToDirectory(SignedStateFileWriter.java:148) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeSignedStateToDisk$1(SignedStateFileWriter.java:203) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:244) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:220) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateToDisk(SignedStateFileWriter.java:201) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileManager.lambda$saveSignedStateToDisk$0(SignedStateFileManager.java:275) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by poulok** [comment]
This has been fixed in 42 and will not be cherry picked back into 41.
