### ISSUE TITLE
Reconnect test failure: Failed to deserialize `QueryResponse ` object

### ISSUE THREAD

**Issue by alittley** [hashgraph/hedera-services#8185]
The failure occurred in the release 41, test `VMerkleDual-NDReconnect-500-60m`

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/Reconnect/20230823-094025-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

```
2023-08-23 10:17:12.361 438401   ERROR EXCEPTION        <<platform-core: SyncProtocolWith3 1 to 3>> StandardWorkGroup: Work Group Exception [ groupName = teaching-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.lambda$waitForCompletion$2(ConcurrentFuturePool.java:154) ~[swirlds-common-0.41.0.jar:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037) ~[?:?]
	at java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054) ~[?:?]
	at com.swirlds.common.threading.futures.ConcurrentFuturePool.waitForCompletion(ConcurrentFuturePool.java:147) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.waitForTermination(StandardWorkGroup.java:140) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.sendTree(TeachingSynchronizer.java:173) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.TeachingSynchronizer.synchronize(TeachingSynchronizer.java:137) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.reconnect(ReconnectTeacher.java:228) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectTeacher.execute(ReconnectTeacher.java:166) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.teacher(ReconnectProtocol.java:210) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.reconnect.ReconnectProtocol.runProtocol(ReconnectProtocol.java:173) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.network.communication.states.ProtocolNegotiated.transition(ProtocolNegotiated.java:62) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.network.communication.Negotiator.execute(Negotiator.java:94) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:74) ~[swirlds-platform-core-0.41.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:615) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:216) ~[swirlds-common-0.41.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Failed to deserialize object with class ID 8989011001974646263(0x7CBF61E166C6E5F7) (class com.swirlds.common.merkle.synchronization.internal.QueryResponse)
	at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:151) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:126) ~[swirlds-common-0.41.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readBoolean(DataInputStream.java:250) ~[?:?]
	at com.swirlds.common.io.streams.AugmentedDataInputStream.readBoolean(AugmentedDataInputStream.java:139) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.QueryResponse.deserialize(QueryResponse.java:71) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:146) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:126) ~[swirlds-common-0.41.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
```

**Comment by cody-littley** [comment]
The stack trace from the teacher is a symptom, not the cause. The root cause is on the learner I think (node 3):

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.MappedByteBuffer.position()" because "this.writingMmap" is null
	at com.swirlds.merkledb.files.DataFileWriter.computePaddingLength(DataFileWriter.java:319) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.files.DataFileWriter.finishWriting(DataFileWriter.java:291) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.finishCurrentCompactionFile(DataFileCollection.java:511) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.files.DataFileCollection.pauseCompaction(DataFileCollection.java:541) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.files.hashmap.HalfDiskHashMap.pauseMerging(HalfDiskHashMap.java:338) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.pauseMerging(MerkleDbDataSource.java:506) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.MerkleDb.importDataSource(MerkleDb.java:375) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.MerkleDb.copyDataSource(MerkleDb.java:357) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSourceBuilder.copy(MerkleDbDataSourceBuilder.java:125) ~[swirlds-jasperdb-0.41.0.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.setupWithOriginalNode(VirtualRootNode.java:1364) ~[swirlds-virtualmap-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.handleCustomRootInitialLesson(LearnerThread.java:131) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.extractNodeFromLesson(LearnerThread.java:155) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.merkle.synchronization.internal.LearnerThread.run(LearnerThread.java:258) ~[swirlds-common-0.41.0.jar:?]
	at com.swirlds.common.threading.pool.StandardWorkGroup.lambda$execute$1(StandardWorkGroup.java:126) ~[swirlds-common-0.41.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

**Comment by imalygin** [comment]
Thank you for the investigation. There is a good chance that this issue will be resolve with the following PR:
 https://github.com/hashgraph/hedera-services/pull/8142
