### ISSUE TITLE
IllegalAccessException preventing mono local node run

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#8187]
I’m getting an exception trying to run the node software (`MonoServicesMain.main(...)`) locally:
```
Caused by: java.lang.IllegalAccessException: symbolic reference class is not accessible: class com.swirlds.platform.uptime.UptimeDataImpl, from class com.swirlds.common.constructable.internal.GenericConstructorRegistry (module com.swirlds.common)
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:955) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.checkSymbolicClass(MethodHandles.java:3686) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3646) ~[?:?]
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750) ~[?:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.createConstructorLambda(GenericConstructorRegistry.java:170) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.constructable.internal.GenericConstructorRegistry.registerConstructables(GenericConstructorRegistry.java:105) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.common.constructable.internal.DefaultConstructableRegistry.registerConstructables(DefaultConstructableRegistry.java:62) ~[swirlds-common-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.util.BootstrapUtils.loadSwirldMains(BootstrapUtils.java:537) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:202) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:170) ~[swirlds-platform-core-0.42.0-adhoc.xfb77ea8d.jar:?]
	... 3 more
```
Branch: `develop`
Swirlds version: `0.42.0-adhoc.xfb77ea8d.jar`

**Comment by david-bakin-sl** [comment]
When #8093 was merged (with this platform sdk version) it obviously passed all CI/CD checks.  But this failure happened.  There should be a CI/CD check for it - this will be more urgent when the services+platform builds get integrated.

**Comment by nathanklick** [comment]
@david-bakin-sl This is due to the mode of execution in IntelliJ vs. E2E/Integration/Unit tests. Our unit, e2e, and integration tests execute the code as classpath entries and not module path entries. However, in @mhess-swl case he is executing via IntelliJ which is adding them to module path. 

I have previously argued the need for ensuring our unit tests are using the module path (by declaring the unit tests as modules themselves), but was overruled.

**Comment by david-bakin-sl** [comment]
Ah! TY @nathanklick - an interesting ramification of the unit-tests-are-not-in-modules approach which I hadn't realized when we were discussing it (and I was advocating that side of the question).
