### ISSUE TITLE
Cannot run a local node with a saved state from different network

### ISSUE THREAD

**Issue by artemananiev** [hashgraph/hedera-services#8212]
A task (https://github.com/swirlds/infrastructure/issues/4606) is to verify services migration from one version to another. To do that, I downloaded a testnet state for version 0.41 and now trying to run nodes locally with the latest develop. I did it in the past, but now it seems broken. My first attempt failed with the following exception:

```
2023-08-24 13:57:26.264 ERROR 92   MonoServicesMain - Fatal precondition violated in HederaNode#0
java.lang.ArithmeticException: / by zero
	at com.swirlds.gui.GuiUtils.winRect(GuiUtils.java:135) ~[swirlds-platform-gui-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.gui.SwirldsGui.createConsole(SwirldsGui.java:60) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.hedera.node.app.service.mono.state.StateModule.providePrintStream(StateModule.java:230) ~[app-service-mono-0.41.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.service.mono.state.StateModule_ProvidePrintStreamFactory.providePrintStream(StateModule_ProvidePrintStreamFactory.java:46) ~[app-service-mono-0.41.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.service.mono.state.StateModule_ProvidePrintStreamFactory.get(StateModule_ProvidePrintStreamFactory.java:35) ~[app-service-mono-0.41.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.service.mono.state.StateModule_ProvidePrintStreamFactory.get(StateModule_ProvidePrintStreamFactory.java:14) ~[app-service-mono-0.41.0-SNAPSHOT.jar:?]
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) ~[dagger-2.42-module.jar:?]
	at com.hedera.node.app.service.mono.DaggerServicesApp$ServicesAppImpl.consoleOut(DaggerServicesApp.java:3272) ~[app-service-mono-0.41.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.MonoServicesMain.consoleLog(MonoServicesMain.java:159) ~[HederaNode.jar:?]
	at com.hedera.node.app.MonoServicesMain.initApp(MonoServicesMain.java:89) ~[HederaNode.jar:?]
	at com.hedera.node.app.MonoServicesMain.init(MonoServicesMain.java:68) ~[HederaNode.jar:?]
	at com.hedera.node.app.ServicesMain.init(ServicesMain.java:68) ~[HederaNode.jar:?]
	at com.swirlds.platform.Browser.launchUnhandled(Browser.java:268) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.Browser.launch(Browser.java:170) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.Browser.parseCommandLineArgsAndLaunch(Browser.java:145) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.Browser.main(Browser.java:134) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.hedera.node.app.MonoServicesMain.main(MonoServicesMain.java:56) ~[HederaNode.jar:?]
```

Division by zero happens, because the number of windows is 0. This number comes from the number of local addresses in the address book. Since the state is from testnet, none of the addresses are local. OK, let’s try in headless mode using -Djava.awt.headless=true (funny, I had to google how to enabled it and the very first link in google was my own 15-year-old Oracle / Sun blog). This time errors were different:

```
2023-08-24 14:03:39.888 23526    ERROR EXCEPTION        <<platform-core: connectionServer 1>> ConnectionServer: Cannot bind ServerSocket
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:544) ~[?:?]
	at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:388) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:342) ~[?:?]
	at com.swirlds.platform.network.connectivity.SocketFactory.configureAndBind(SocketFactory.java:59) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.network.connectivity.TlsFactory.createServerSocket(TlsFactory.java:101) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.platform.network.connectivity.ConnectionServer.run(ConnectionServer.java:86) ~[swirlds-platform-core-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.42.0-adhoc.xf996440e.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.42.0-adhoc.xf996440e.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Something related to ports. Logs gave me a hint: address book was used from the state, and all nodes there used the same port. OK, I found addressBook.forceUseOfConfigAddressBook config, set it to true, and ran again. Still failed:

```
2023-08-24 14:10:18.927 24392    ERROR INVALID_EVENT_ERROR <<platform-core: event-intake 0>> SignatureValidator: failed the signature check (0,109160502,8b5fd82b) sp(0,109160501,0261c30c) op(2,109160501,1c41f88b)
with sig bcc69e63bb587363f225aba1a667fe92ef8b76733f1f77e1c501599c4e6cee0e902c9f7dfc563172db532f43a1762f366ff0e06eb3c90b2368859c28123a32cef5a3c82af6101a1fd91a23e107dbaf0a7805e615dcce93356686707b347c1478901600eb2ccb8cc050dc5b5b882d3802f31c9e1b20ac6149ae8b479fc23c0bc29568b461d0d811d6e70c2d3896e1383f543e2a0d4096d29df350e72447b92138b93ea3aa0a211e7890a97d208028aca04ff33b492eee1b826edfdf3cf80ee90ac681c6188065a7e7d7bf774959c5357ef3d277c0ecbaeb73f3d230359c7841480de827f3d6d92e33a0851c35855f623a211963264b6967041d702bc16ec5e143d776b94356f6d254a5b5523b99acf13aa436b576e146cc4d24d51ee536a7c9f6c9c326628fedb6ad2961fb940b5a2e341d41b2e5194747ee667eb7913790c09e5e8f9403bde849968247bd5b37a7a92edcbc767d06a364b831672d80a5f878ae77b372ad4651fc668d28e71442284d9a1272057837b4693f54433baecc2ecbc3
and hash 8b5fd82b027225a6300c2740537f0fd2a27366b79276fea3fa908c519fd4564de8a0abfd5ae4fc2a7d4f9df17630b69c
transactions are null: false (if true, this is probably an event from a signed state)
```

All nodes are stuck in CHECKING state.

Attached are logs from the last run, with `-Djava.awt.headless=true` system property and `addressBook.forceUseOfConfigAddressBook` config set to true.

[hgcaa.log](https://github.com/hashgraph/hedera-services/files/12435124/hgcaa.log)
[swirlds.log](https://github.com/hashgraph/hedera-services/files/12435125/swirlds.log)

**Comment by artemananiev** [comment]
When address book from local config is used, the arithmetic exception above is not observed, no need to use the headless mode.

**Comment by artemananiev** [comment]
Testnet states can be downloaded from here: gs://testnet-2023-07-state-backups/testnet-2023-01-node00/<round number>, where the current round number can be found at gs://testnet-2023-07-state-backups/current_round/testnet-2023-01-node00.txt

**Comment by edward-swirldslabs** [comment]
I was able to create the same problem locally by generating a state, then altering the seed for the public keys and restarting the network with the saved state.
