### ISSUE TITLE
VMap: State file not found

### ISSUE THREAD

**Issue by lpetrovic05** [hashgraph/hedera-services#8237]
This appeared in 2 tests:
http://35.247.76.217:8095/swirlds-automation/develop/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/
http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230828-053537-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

```
---- VirtualMerkleLeafValidator FAILED validation ----
<<ERROR>>
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0000/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/0/123/4016/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0001/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/1/123/4016/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/VMerkleLong/20230828-053606-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/node0002/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/2/123/4016/vmapHashes.json
```

**Comment by edward-swirldslabs** [comment]
still failing
http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20230905-053525-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by imalygin** [comment]
`VirtualMerkleLeafHasher` is responsible for creating `vmapHashes.json`. This issue doesn't occur for all the states but it occurs quite often. It fails to create the file because of exceptions like the following one:

```
Exception in thread "main" java.lang.IllegalArgumentException: path (13880980) is not valid; must be in range (24799999,49599998)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:694)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getLeafNode(VirtualInternalNode.java:207)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:154)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getRight(VirtualInternalNode.java:147)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:90)
	at com.swirlds.common.merkle.iterators.MerkleIterator.pushNode(MerkleIterator.java:244)
	at com.swirlds.common.merkle.iterators.internal.BreadthFirstAlgorithm.pushChildren(BreadthFirstAlgorithm.java:77)
	at com.swirlds.common.merkle.iterators.MerkleIterator.findNext(MerkleIterator.java:312)
	at com.swirlds.common.merkle.iterators.MerkleIterator.hasNext(MerkleIterator.java:326)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.validate(VirtualMerkleLeafHasher.java:81)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.main(VirtualMerkleLeafHasher.java:174)
```
It happens because the code incorrectly assumes that a path is for a leaf node:

```
    private VirtualNode getChild(final long childPath) {
        if (childPath < root.getState().getFirstLeafPath()) {
            return getInternalNode(childPath);
        } else {
            return getLeafNode(childPath);
        }
    }

```
`13880980` was supposed to be a path to an internal node. This disconnect likely comes from the fact that the root of this particular node has outdated metadata.

**Comment by imalygin** [comment]
I'll try to rerun this test with `"downloadStateFiles" : true` flag to acquire the state for local debug.

**Comment by edward-swirldslabs** [comment]
Still Failing: http://35.247.76.217:8095/swirlds-automation/release/0.42/4N/VMerkleLong/20230908-100953-GCP-Daily-VMerkleLong-4N/VMerkle-Basic-2.5k-110m/summary.txt
