### ISSUE TITLE
CongestionPricing-NDReconnect-1-16m has error IllegalArgumentException

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8260]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1693299514198389

```
java.lang.IllegalArgumentException: Cannot snapshot a secondary table, uniqueTokenStore
	at com.swirlds.merkledb.MerkleDb.snapshot(MerkleDb.java:519) ~[swirlds-jasperdb-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSourceBuilder.snapshot(MerkleDbDataSourceBuilder.java:143) ~[swirlds-jasperdb-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.detach(VirtualRootNode.java:1313) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.lambda$detachCopy$2(VirtualPipeline.java:426) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.pausePipelineAndExecute(VirtualPipeline.java:636) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.detachCopy(VirtualPipeline.java:426) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.serialize(VirtualRootNode.java:1167) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.virtualmap.VirtualMap.serialize(VirtualMap.java:324) ~[swirlds-virtualmap-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeSerializableNode(MerkleDataOutputStream.java:64) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeInternal(MerkleDataOutputStream.java:81) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.lambda$writeMerkleTree$1(MerkleDataOutputStream.java:172) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.merkle.iterators.MerkleIterator.forEachRemainingWithIO(MerkleIterator.java:410) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.streams.MerkleDataOutputStream.writeMerkleTree(MerkleDataOutputStream.java:166) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFileToStream(SignedStateFileWriter.java:114) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeStateFile$0(SignedStateFileWriter.java:127) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.utility.FileUtils.writeAndFlush(FileUtils.java:281) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeStateFile(SignedStateFileWriter.java:126) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateFilesToDirectory(SignedStateFileWriter.java:148) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.lambda$writeSignedStateToDisk$1(SignedStateFileWriter.java:203) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:244) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.io.utility.FileUtils.executeAndRename(FileUtils.java:220) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileWriter.writeSignedStateToDisk(SignedStateFileWriter.java:201) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.platform.state.signed.SignedStateFileManager.lambda$saveSignedStateToDisk$0(SignedStateFileManager.java:275) ~[swirlds-platform-core-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:260) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.42.0-adhoc.x0e472410.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

Nightly regression panel `GCP-ND-Reconnect-Correctness-6N-1C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Another incident

https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1693986652806449

**Comment by artemananiev** [comment]
Logs from the last failure: http://35.247.76.217:8095/JeffreyDallas/03739-D-six-hour-limit/4N_2C/UpdateReconnect/20230906-041210-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-NI-DisDuringUpdate-RecAftPrepare-1.5k-25m/node0003/swirlds.log

**Comment by artemananiev** [comment]
Here is what's in the logs (node 3):

* A signed state for round 706 is created and scheduled to write to disk, reason = periodic snapshot
* The node is disconnected from network and starts a reconnect
* Eventually, the node is reconnected, round number is 2238
* After reconnect, state for round 2238 is written to disk successfully
* This is where it starts looking weird... The node now tries to save a state for round 706 to disk. The exception happens at this step

**Comment by artemananiev** [comment]
Discussed it with @cody-littley. This seems to be a valid scenario, when an old signed state is written to disk after reconnect. At MerkleDb level, it means there is no need to check if a table is primary or not, when a table snapshot is made.
