### ISSUE TITLE
Release 0.41: IllegalStateException during upgrade test

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8313]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C05MHKR9BJ7/p1693480217038539

```
2023-08-31 10:54:00.115 245660   INFO  STATE_TO_DISK    <<platform-core: signed-state-file-manager 2>> SignedStateFileWriter: Started writing round 10745 state to disk. Reason: periodic snapshot, directory: /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.hedera.services.ServicesMain/2/123/10745
2023-08-31 10:54:00.122 245694   ERROR EXCEPTION        <<virtual-pipeline: lifecycle #0>> VirtualPipeline: exception on virtual pipeline thread
java.lang.IllegalStateException: You can only merge caches that are sealed
	at com.swirlds.virtualmap.internal.cache.VirtualNodeCache.merge(VirtualNodeCache.java:474) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.merge(VirtualRootNode.java:1000) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.merge(VirtualPipeline.java:541) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashFlushMerge(VirtualPipeline.java:563) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.doWork(VirtualPipeline.java:574) ~[swirlds-virtualmap-0.41.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-08-31 10:54:00.133 245708   WARN  EXCEPTION        <<virtual-pipeline: lifecycle #0>> MerkleDbDataSource: [uniqueTokenStore] Interrupted while waiting on executors to shutdown
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1660) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464) ~[?:?]
	at com.swirlds.merkledb.MerkleDbDataSource.shutdownThreadsAndWait(MerkleDbDataSource.java:1157) ~[swirlds-jasperdb-0.41.1.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.close(MerkleDbDataSource.java:794) ~[swirlds-jasperdb-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.onShutdown(VirtualRootNode.java:967) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.fireOnShutdown(VirtualPipeline.java:660) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.shutdown(VirtualPipeline.java:594) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.doWork(VirtualPipeline.java:577) ~[swirlds-virtualmap-0.41.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2023-08-31 10:54:00.137 245720   ERROR EXCEPTION        <<virtual-pipeline: lifecycle #0>> VirtualRootNode: Could not close the dataSource after all copies were destroyed
java.io.IOException: Interrupted while waiting for shutdown to finish.
	at com.swirlds.merkledb.MerkleDbDataSource.shutdownThreadsAndWait(MerkleDbDataSource.java:1166) ~[swirlds-jasperdb-0.41.1.jar:?]
	at com.swirlds.merkledb.MerkleDbDataSource.close(MerkleDbDataSource.java:794) ~[swirlds-jasperdb-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.onShutdown(VirtualRootNode.java:967) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.fireOnShutdown(VirtualPipeline.java:660) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.shutdown(VirtualPipeline.java:594) ~[swirlds-virtualmap-0.41.1.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.doWork(VirtualPipeline.java:577) ~[swirlds-virtualmap-0.41.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1660) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1464) ~[?:?]
	at com.swirlds.merkledb.MerkleDbDataSource.shutdownThreadsAndWait(MerkleDbDataSource.java:1157) ~[swirlds-jasperdb-0.41.1.jar:?]
	... 10 more
```

### Steps to reproduce

Release 0.41, nightly regression test panel `GCP-Daily-Update-Reconnect-4N-2C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Another incident Sep 21

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1695279656898639
