### ISSUE TITLE
ReconnectionCompleteAction with current status of OBSERVING

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#8400]
http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/ISS/20230905-094129-GCP-Daily-ISS-4N/ISS-emergency-recovery-1k-10m/node0002/swirlds.log

This seems to be a state we should never encounter, but we did.   Issue discovered on release 41.  

```
2023-09-05 09:49:43.848 92       ERROR EXCEPTION        <<platform: status-state-machine>> PlatformStatusStateMachine: Received unexpected status action `ReconnectCompleteAction` with current status of `OBSERVING`
com.swirlds.common.system.status.IllegalPlatformStatusException: Received unexpected status action `ReconnectCompleteAction` with current status of `OBSERVING`
	at com.swirlds.common.system.status.logic.ObservingStatusLogic.processReconnectCompleteAction(ObservingStatusLogic.java:135) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.system.status.PlatformStatusStateMachine.getNewLogic(PlatformStatusStateMachine.java:129) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.system.status.PlatformStatusStateMachine.processStatusAction(PlatformStatusStateMachine.java:159) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.system.status.PlatformStatusManager.processStatusAction(PlatformStatusManager.java:121) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:254) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:615) ~[swirlds-common-0.41.1.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:216) ~[swirlds-common-0.41.1.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by edward-swirldslabs** [comment]
found here as well.  

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/ISS/20230905-094129-GCP-Daily-ISS-4N/ISS-emergency-recovery-diff-hash-1k-10m/node0002/swirlds.log

There are other preceding exceptions which might be relevant.

**Comment by edward-swirldslabs** [comment]
found here as well, all 3 ISS tests on release 41.  This one has no preceding exceptions

http://35.247.76.217:8095/swirlds-automation/release/0.41/4N/ISS/20230905-094129-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/node0002/swirlds.log

**Comment by poulok** [comment]
fixed in release 42, not needed in 41
