### ISSUE TITLE
Error from account balance check

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8417]
### Description

Slack test report 

https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1694019756973929

Client log has many lines of error of "was not created successfully"

```
2023-09-06 17:01:05.399 INFO   180  CustomSpecAssert - acct-1 was not created successfully.
2023-09-06 17:01:05.399 INFO   180  CustomSpecAssert - acct-2 was not created successfully.
2023-09-06 17:01:05.399 INFO   180  CustomSpecAssert - acct-3 was not created successfully.
2023-09-06 17:01:05.399 INFO   180  CustomSpecAssert - acct-4 was not created successfully.
2023-09-06 17:01:05.399 INFO   180  CustomSpecAssert - acct-5 was not created successfully.
```

### Steps to reproduce

Run nightly test panel `GCP-Daily-Comp-BalancesValidate-6N-1C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by netopyr** [comment]
@JeffreyDallas  Is the export of balance-files enabled during this test (`balances.exportEnabled=true`)? 

It is disabled by default. This was change recently.

**Comment by JeffreyDallas** [comment]
Yes, `balances.exportEnabled` is set to true.

**Comment by JeffreyDallas** [comment]
Added some more logging,

```
2023-09-06 19:09:41.318 INFO   180  CustomSpecAssert - acct-1 was not created successfully.
com.hedera.services.bdd.spec.infrastructure.RegistryNotFound: Missing AccountID 'acct-1'!
	at com.hedera.services.bdd.spec.infrastructure.HapiSpecRegistry.get(HapiSpecRegistry.java:874) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.infrastructure.HapiSpecRegistry.getAccountID(HapiSpecRegistry.java:665) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.perf.AccountBalancesClientSaveLoadTest.lambda$runAccountBalancesClientSaveLoadTest$19(AccountBalancesClientSaveLoadTest.java:178) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.utilops.CustomSpecAssert.submitOp(CustomSpecAssert.java:82) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:238) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpec.exec(HapiSpec.java:443) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiSpec.run(HapiSpec.java:308) ~[SuiteRunner.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.hedera.services.bdd.suites.HapiSuite.runSequentialSpecs(HapiSuite.java:301) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiSuite.runSuite(HapiSuite.java:258) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.HapiSuite.runSuiteSync(HapiSuite.java:216) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runSuitesSync$17(SuiteRunner.java:697) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runSuitesSync(SuiteRunner.java:698) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.lambda$runTargetCategories$10(SuiteRunner.java:667) ~[SuiteRunner.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?]
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runTargetCategories(SuiteRunner.java:668) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.runCategories(SuiteRunner.java:633) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.suites.SuiteRunner.main(SuiteRunner.java:551) ~[SuiteRunner.jar:?]
```

**Comment by JeffreyDallas** [comment]
Started having the error on Aug 11
https://swirldslabs.slack.com/archives/C03FD752LKA/p1691741814875549

The previous day Aug 10, the test log has no such error
https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1691652949839859
