### ISSUE TITLE
Start testing NftTransferSuite

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#8467]

**Comment by Neeharika-Sompalli** [comment]
It hangs in the middle of the test with GRPC server connection lost. There is no error on node logs. 


```
2023-10-12 15:19:46.067 ERROR 168  HapiTxnOp - body=transactionID { transactionValidStart { seconds: 1697141921 nanos: 56820 } accountID { accountNum: 2 } } nodeAccountID { accountNum: 3 } transactionFee: 992013 transactionValidDuration { seconds: 120 } memo: "\303\203\302\256\303\202\302\267\303\203\302\271tF8\303\202\302\256J\303\203\302\213\303\203\302\220\303\203\302\216" cryptoTransfer { tokenTransfers { token { tokenNum: 1198 } nftTransfers { senderAccountID { accountNum: 1042 } receiverAccountID { accountNum: 1002 } serialNumber: 1 } } }; sigs=sigPair { pubKeyPrefix: "\n" ed25519: "\032X\263k\262f\244K\223\220\b\'\226JA\305\264\324\254\b\215\233U%\276\a\265\030<\211u\331\320\341e\301\340C\252\023\302L\302\365&\276\353\2418y.\021P\005\364\240\326B{\333=\304\000\001" } sigPair { pubKeyPrefix: "\215" ed25519: "\202\314tGf#\216\033%\373N\365\244\237\260\211\221\350\205\355\351\321#&\354S\024P\305\377\206\367R\037V\005A(\262;\352\316v\\\206l@\231\275.O\322\231\345\247\r\240\261\277\334P\021\316\003" } Status resolution failed due to unrecoverable runtime exception, possibly network connection lost.
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc-stub-1.54.1-module.jar:1.54.1]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc-stub-1.54.1-module.jar:1.54.1]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc-stub-1.54.1-module.jar:1.54.1]
	at com.hederahashgraph.service.proto.java.CryptoServiceGrpc$CryptoServiceBlockingStub.cryptoTransfer(CryptoServiceGrpc.java:1130) ~[hapi-0.42.0-SNAPSHOT.jar:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.timedCall(HapiTxnOp.java:258) ~[main/:?]
	at com.hedera.services.bdd.spec.transactions.HapiTxnOp.submitOp(HapiTxnOp.java:158) ~[main/:?]
	at com.hedera.services.bdd.spec.HapiSpecOperation.execFor(HapiSpecOperation.java:238) ~[main/:?]
	at com.hedera.services.bdd.spec.utilops.grouping.ParallelSpecOps.lambda$submitOp$1(ParallelSpecOps.java:54) ~[main/:?]
```


Observation : We always use PROD Netty settings in modular code, while in mono-service we have Dev settings. Not sure if this is the reason. 

When I tried to use Default Netty settings, got a Java heap space issue and ISS

```
023-10-12 16:06:33.543 257      INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 552.0 ms in CHECKING. Now in ACTIVE {"oldStatus":"CHECKING","newStatus":"ACTIVE"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-10-12 16:07:22.330 1394     ERROR EXCEPTION        <grpc-default-executor-69> Log4jSetup: exception on thread grpc-default-executor-69
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:64) ~[?:?]
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:363) ~[?:?]
	at com.hedera.pbj.runtime.io.buffer.BufferedData.allocate(BufferedData.java:104) ~[pbj-runtime-0.7.4.jar:?]
	at com.hedera.node.app.grpc.impl.MethodBase.lambda$static$0(MethodBase.java:67) ~[app-0.42.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.grpc.impl.MethodBase$$Lambda$1460/0x0000000801296738.get(Unknown Source) ~[?:?]
	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305) ~[?:?]
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195) ~[?:?]
	at java.lang.ThreadLocal.get(ThreadLocal.java:172) ~[?:?]
	at com.hedera.node.app.grpc.impl.MethodBase.invoke(MethodBase.java:124) ~[app-0.42.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:252) ~[app-0.42.0-SNAPSHOT.jar:?]
	at com.hedera.node.app.grpc.impl.netty.GrpcServiceBuilder$ListenerImpl.onMessage(GrpcServiceBuilder.java:220) ~[app-0.42.0-SNAPSHOT.jar:?]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333) ~[io.grpc-3.2.1.jar:3.2.1]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316) ~[io.grpc-3.2.1.jar:3.2.1]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835) ~[io.grpc-3.2.1.jar:3.2.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[io.grpc-3.2.1.jar:3.2.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[io.grpc-3.2.1.jar:3.2.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by mhess-swl** [comment]
I just tried enabling this test locally with current `develop` and it passes. Maybe because of the new configs defaulting to mainnet? Not sure

**Comment by Neeharika-Sompalli** [comment]
Will be dealt in this issue instead https://github.com/hashgraph/hedera-services/issues/10637
