### ISSUE TITLE
Failed to find sibling hash

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8471]
Failing test was the migration test on an abbreviated panel.

http://35.247.76.217:8095/cody-littley/06881-eRecovery-lifecycle/4N/Abbrev/20230908-162543-GCP-PRCheck-Abbrev-4N/FCM-Migration-5-2m/

```
---- ErrorValidator FAILED validation ----
(Node 0) Marker EXCEPTION appeared 7 times.
(Node 0) Exception java.util.concurrent.ExecutionException appeared 1 time.
(Node 0) Exception java.lang.IllegalStateException appeared 1 time.
(Node 0) Exception java.lang.InterruptedException appeared 1 time.
(Node 0) Exception java.io.IOException appeared 1 time.
(Node 0) Exception java.lang.RuntimeException appeared 1 time.
(Node 0) Exception java.lang.NullPointerException appeared 1 time.
(Node 1) Marker EXCEPTION appeared 7 times.
(Node 1) Exception java.util.concurrent.ExecutionException appeared 1 time.
(Node 1) Exception java.lang.IllegalStateException appeared 1 time.
(Node 1) Exception java.lang.InterruptedException appeared 1 time.
(Node 1) Exception java.io.IOException appeared 1 time.
(Node 1) Exception java.lang.RuntimeException appeared 1 time.
(Node 1) Exception java.lang.NullPointerException appeared 1 time.
(Node 2) Marker EXCEPTION appeared 7 times.
(Node 2) Exception java.util.concurrent.ExecutionException appeared 1 time.
(Node 2) Exception java.lang.IllegalStateException appeared 1 time.
(Node 2) Exception java.lang.InterruptedException appeared 1 time.
(Node 2) Exception java.io.IOException appeared 1 time.
(Node 2) Exception java.lang.RuntimeException appeared 1 time.
(Node 2) Exception java.lang.NullPointerException appeared 1 time.
(Node 3) Marker EXCEPTION appeared 5 times.
(Node 3) Exception java.util.concurrent.ExecutionException appeared 1 time.
(Node 3) Exception java.lang.InterruptedException appeared 1 time.
(Node 3) Exception java.io.IOException appeared 1 time.
(Node 3) Exception java.lang.RuntimeException appeared 1 time.
```

```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.common.merkle.hash.FutureMerkleHash.rethrowException(FutureMerkleHash.java:83) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:93) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.FutureMerkleHash.get(FutureMerkleHash.java:30) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.state.signed.SignedStateHasher.hashState(SignedStateHasher.java:84) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.platform.components.state.DefaultStateManagementComponent.newSignedStateFromTransactions(DefaultStateManagementComponent.java:359) ~[swirlds-platform-core-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.QueueThreadImpl.doWork(QueueThreadImpl.java:253) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hashSubTree(VirtualHasher.java:708) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:424) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.computeHash(VirtualRootNode.java:1264) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashCopy(VirtualPipeline.java:388) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.getHash(VirtualRootNode.java:1204) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:206) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.lang.IllegalStateException: Failed to find a hash for 66092, which is a sibling of 66091
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.lambda$hashSubTree$2(VirtualHasher.java:667) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
```

**Comment by poulok** [comment]
@Cody Can this be closed?

**Comment by cody** [comment]
Hi, all! I think I’ve been tagged in this thread a couple of times—wanna make sure nothing gets dropped. @cody-littley this one’s for you!

**Comment by artemananiev** [comment]
This exception, failed to find a sibling hash, can be caused by millions different bugs in our code. Without a reliable way to reproduce the problem, I don't know how to proceed with this ticket.
