### ISSUE TITLE
Release 0.42, node stuck with CHECKING for more than 20 minutes, could not reconnect

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#8505]
### Description

Slack report URL

https://swirldslabs.slack.com/archives/C05R1D74CMC/p1694451139476069

Node003 log

http://35.247.76.217:8095/swirlds-automation/release/0.42/4N_2C/UpdateReconnect/20230911-111352-GCP-Daily-Update-Reconnect-4N-2C/Crypto-Update-NI-DisDuringUpdate-RecAftPrepare-1.5k-25m/node0003/swirlds.log

From 15:53 to 16:13, node3 could not become ACTIVE or reconnect with other nodes
```
2023-09-11 15:53:32.623 23050    INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 4.3 m in ACTIVE. Now in CHECKING {"oldStatus":"ACTIVE","newStatus":"CHECKING"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-09-11 16:13:31.868 53026    ERROR EXCEPTION        <<platform: signed-state-sentinel>> SignedStateSentinel: old signed state detected, memory leak probable.
null
2023-09-11 16:16:49.108 57952    INFO  RECONNECT        <<platform-core: SyncProtocolWith2 3 to 2>> ReconnectController: Starting ReconnectController
2023-09-11 16:16:49.109 57953    INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 23.3 m in CHECKING. Now in BEHIND {"oldStatus":"CHECKING","newStatus":"BEHIND"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-09-11 16:16:49.112 57954    WARN  STARTUP          <<reconnect: reconnect-controller>> ReconnectLearnerThrottle: Node has fallen behind, reconnect is disabled outside of time window, will die {"nodeId":3} [com.swirlds.logging.payloads.UnableToReconnectPayload]
2023-09-11 16:16:49.114 57955    INFO  STARTUP          <<reconnect: reconnect-controller>> SystemExitUtils: System exit requested (BEHIND_RECONNECT_DISABLED)
thread requesting exit: <reconnect: reconnect-controller>
com.swirlds.common.system.SystemExitUtils.exitSystem(SystemExitUtils.java:47)
	at com.swirlds.common.system.SystemExitUtils.exitSystem(SystemExitUtils.java:83)
	at com.swirlds.platform.reconnect.ReconnectLearnerThrottle.exitIfReconnectIsDisabled(ReconnectLearnerThrottle.java:114)
	at com.swirlds.platform.reconnect.ReconnectHelper.prepareForReconnect(ReconnectHelper.java:91)
	at com.swirlds.platform.reconnect.ReconnectController.executeReconnect(ReconnectController.java:102)
	at com.swirlds.platform.reconnect.ReconnectController.run(ReconnectController.java:89)
```

### Steps to reproduce

Run release 0.42 nightly test panel `GCP-Daily-Update-Reconnect-4N-2C`

### Hedera network

other

### Version

release 42 test

### Operating system

None

**Comment by JeffreyDallas** [comment]
New incidents

https://swirldslabs.slack.com/archives/C05R1D74CMC/p1695743888190609
https://swirldslabs.slack.com/archives/C05R1D74CMC/p1695916550084739
