### ISSUE TITLE
FCM-Migration-NewNodesFromGenesis-2.5k-8m is failing intermittently 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#8793]
### Description

`FCM-Migration-NewNodesFromGenesis-2.5k-8m` is failing from time to time because the reconnect takes too long. 

Here is a comment from @cody-littley: 

_When investigating this, I’d recommend digging up historical data for this test, and seeing if there has been a significant performance regression in the time it takes to transmit a state for this test. If there has been a performance regression then we need to work on a fix._

_On the other hand, if you determine that this kind of fluctuation is not uncommon, or if you think it makes sense for the reconnect to take as long as it did, the next step will be to relax the constraints in the validator. The maximum limit for reconnect time was chosen because it “seemed right”, not because there was a fundamental reason it had to be at that value. If the chosen consent results in falsely labeling tests as failures, then we should probably relax it until we stop flaking._

Here is [a link ](http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20230918-094736-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/)to the latest failure of the test.

As Cody recommended, I gathered some historic data and here is what I found:

| date | reconnect time 1|  reconnect time 2|  total data amount (Mb) | result |
| --- | --- |--- | --- | --- |
20230904 | 5.24s | 5.82s | 106.76mb | failed  
20230905 | 5.18s | 5.13s | 106.76mb | failed 
20230906 | 20.39s | 20.32s | 647.42mb | failed
20230907 | 6.56s | 6.62s | 148.98mb | passed
20230908 | 7.64s | 6.67s | 148.98mb | passed
20230909 | 6.58s | 9.13s | 148.98mb | passed
20230910 | 6.41s | 6.45s | 148.98mb | passed
20230911 | 6.51s | 6.63s, | 148.98mb | passed
20230912 | 6.36s | 6.36s | 148.98mb | passed
20230913 | 6.12s | 6.53s | 148.98mb | passed
20230914 | 6.55s | 6.62s | 148.97mb | passed
20230915 | 12.14s | 11.88s | 359.81mb | passed
20230916 | 11.97s | 12.21s | 359.81mb | passed
20230917 | 11.92s | 12.79s | 359.81mb | passed
20230918 | 11.86s | 18.00s | 359.81mb | failed
20230919 | 11.96s | 12.03s | 359.82mb | passed

Prior to Sep 6 the test was failing with [a fatal  error:](http://35.247.76.217:8095/swirlds-automation/develop/6N/Migration/20230905-094222-GCP-Daily-Migration-6N/FCM-Migration-NewNodesFromGenesis-2.5k-8m/node0000/swirlds.log) :
```
Caused by: java.lang.RuntimeException: exception encountered while hashing virtual tree
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hashSubTree(VirtualHasher.java:708) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:424) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.computeHash(VirtualRootNode.java:1264) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.pipeline.VirtualPipeline.hashCopy(VirtualPipeline.java:388) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.getHash(VirtualRootNode.java:1204) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.hashSubtree(MerkleHashBuilder.java:206) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at com.swirlds.common.merkle.hash.MerkleHashBuilder.lambda$createHashingRunnable$1(MerkleHashBuilder.java:173) ~[swirlds-common-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	... 1 more
Caused by: java.lang.IllegalStateException: Failed to find a hash for 66096, which is a sibling of 66095
	at com.swirlds.virtualmap.internal.hash.VirtualHasher.lambda$hashSubTree$2(VirtualHasher.java:667) ~[swirlds-virtualmap-0.42.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

This issue was resolved with https://github.com/hashgraph/hedera-services/issues/8236

On Sep 6 the test failed for a reason resolved with https://github.com/hashgraph/hedera-services/issues/8380

On Sep 15, something changed; now the amount of data passed during the reconnect is more than double the initial size.

And, finally, on Sep 18 some fluctuation happened that caused the failure I'm going to investigate 

### Steps to reproduce

The test failure is intermittent. To reproduce it, run `FCM-Migration-NewNodesFromGenesis-2.5k-8m` and hope that this time it fails. 

### Hedera network

other

### Version

v0.43

### Operating system

None

**Comment by imalygin** [comment]
The reason for the increased amount of data is simple - [after this update](https://github.com/swirlds/swirlds-platform-regression/pull/3748)  the size of the state increased. Also, upon further investigation of the logs I found an explanation of why exactly some runs are slower than the others:

`node5`
```
2023-09-18 09:54:41.350 183      INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectHelper: Starting reconnect in role of the receiver. {"receiving":true,"nodeId":5,"otherNodeId":2,"round":-1} [com.swirlds.logging.payloads.ReconnectStartPayload]
2023-09-18 09:54:41.352 184      INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectLearner: Receiving signed state signatures
2023-09-18 09:54:41.353 185      INFO  RECONNECT        <<reconnect: reconnect-controller>> ReconnectLearner: Received signatures from nodes 0, 1, 2, 3
2023-09-18 09:54:41.355 186      INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: synchronizing tree
2023-09-18 09:54:41.356 187      INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.platform.state.State with route []
2023-09-18 09:54:57.008 274      INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 2 -> 1]
2023-09-18 09:54:59.352 341      INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: synchronization complete
```

`node2`:

```
2023-09-18 09:54:24.640 114      INFO  RECONNECT        <<platform-core: SyncProtocolWith4 2 to 4>> ReconnectProtocol: Rejecting reconnect request from node 4 due to lack of a fully signed state
2023-09-18 09:54:25.834 120      INFO  RECONNECT        <<platform-core: SyncProtocolWith5 2 to 5>> ReconnectProtocol: Rejecting reconnect request from node 5 due to lack of a fully signed state
2023-09-18 09:54:31.060 146      INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 10.0 s in OBSERVING. Now in CHECKING {"oldStatus":"OBSERVING","newStatus":"CHECKING"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-09-18 09:54:39.799 192      INFO  PLATFORM_STATUS  <<platform: status-state-machine>> PlatformStatusStateMachine: Platform spent 8.7 s in CHECKING. Now in ACTIVE {"oldStatus":"CHECKING","newStatus":"ACTIVE"} [com.swirlds.logging.payloads.PlatformStatusPayload]
2023-09-18 09:54:39.804 194      INFO  STATE_TO_DISK    <<platform-core: state-hash-sign 2>> SignedStateFileManager: Signed state from round 10329 created, will eventually be written to disk once sufficient signatures are collected, for reason: PERIODIC_SNAPSHOT
2023-09-18 09:54:41.118 201      INFO  STATE_TO_DISK    <<platform-core: signed-state-file-manager 2>> SignedStateFileWriter: Started writing round 10329 state to disk. Reason: PERIODIC_SNAPSHOT, directory: /opt/hgcapp/services-hedera/HapiApp2.0/data/saved/com.swirlds.demo.migration.MigrationTestingToolMain/2/123/10329
2023-09-18 09:54:41.279 209      INFO  RECONNECT        <<platform-core: SyncProtocolWith5 2 to 5>> ReconnectTeacher: Starting reconnect in the role of the sender {"receiving":false,"nodeId":2,"otherNodeId":5,"round":10329} [com.swirlds.logging.payloads.ReconnectStartPayload]
```

So, at the moment `node2` received a reconnect request, it didn't have a signed state it could use for the reconnect. That is, its startup wasn't completed yet. Once it was, the reconnect finished successfully but from the `node5` perspective it just looked like a reconnect that took longer than usual. 

There are two ways of fixing this: 
- make sure that the teacher node is up and running before it receives a reconnect request
- increase a threshold for the reconnect validation

The first option is preferrable. 

```
