### ISSUE TITLE
Can't close socket

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8873]
This test was observed in `ISS-emergency-recovery-reconnect-1k-10m`

http://35.247.76.217:8095/swirlds-automation/release/0.42/4N/ISS/20230924-112635-GCP-Daily-ISS-4N/ISS-emergency-recovery-reconnect-1k-10m/

```
2023-09-24 11:58:28.473 99       ERROR EXCEPTION        <<platform-core: thread-cons 0>> StoppableThreadImpl: stack trace for hanging thread SyncProtocolWith3:
sun.nio.ch.Net.poll(Net.java:-2)
	at sun.nio.ch.NioSocketImpl.park(NioSocketImpl.java:181)
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:548)
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.net.Socket.connect(Socket.java:633)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at com.swirlds.platform.network.connectivity.SocketFactory.configureAndConnect(SocketFactory.java:93)
	at com.swirlds.platform.network.connectivity.TlsFactory.createClientSocket(TlsFactory.java:112)
	at com.swirlds.platform.network.connectivity.OutboundConnectionCreator.createConnection(OutboundConnectionCreator.java:100)
	at com.swirlds.platform.network.OutboundConnectionManager.waitForConnection(OutboundConnectionManager.java:51)
	at com.swirlds.platform.network.communication.NegotiatorThread.run(NegotiatorThread.java:65)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.doWork(StoppableThreadImpl.java:614)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl.run(StoppableThreadImpl.java:215)
	at com.swirlds.common.threading.framework.internal.StoppableThreadImpl$$Lambda$430/0x0000000800fc9558.run(null:-1)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by lpetrovic05** [comment]
I found the original issue https://github.com/swirlds/swirlds-platform/issues/5511
It has a different stack trace, but maybe some implementation details changed in the meantime

**Comment by lpetrovic05** [comment]
outdated
