### ISSUE TITLE
Flake in DataFileCollectionMergeTest

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#8979]
https://github.com/hashgraph/hedera-services/actions/runs/6382175030/job/17320208749?pr=8961

```
  com.swirlds.merkledb.files.DataFileCollectionMergeTest

    Snapshot + update in parallel with compaction

      ? [1] 0
      ? [2] 1
      ? [3] 2
      ? [4] 3

            java.util.concurrent.ExecutionException: org.opentest4j.AssertionFailedError: expected: <10> but was: <11>
                at com.swirlds.merkledb.files.DataFileCollectionMergeTest.testMergeUpdateSnapshotRestore(DataFileCollectionMergeTest.java:516)
            Caused by: org.opentest4j.AssertionFailedError: expected: <10> but was: <11>
                at app//com.swirlds.merkledb.files.DataFileCollectionMergeTest.lambda$testMergeUpdateSnapshotRestore$3(DataFileCollectionMergeTest.java:436)


          Test worker INFO DataFileCollection Loading existing set of [11] data files for DataFileCollection [testMergeSnapshotRestore]
          Test worker INFO DataFileCollection Finished loading existing data files for DataFileCollection [testMergeSnapshotRestore]
```

**Comment by imalygin** [comment]
This issue will be resolved with https://github.com/hashgraph/hedera-services/pull/9060
