### ISSUE TITLE
Fix the 6N-6C regression tests

### ISSUE THREAD

**Issue by Neeharika-Sompalli** [hashgraph/hedera-services#900]
Most of the 6N-6C tests fail to run and show 0 TPS:
HCS : https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1609143637144300
HTS: https://hedera-hashgraph.slack.com/archives/CKWHL8R9A/p1609137037137300

Sometimes they don't show a slack message. https://hedera-hashgraph.slack.com/archives/C018Y4E6ADT/p1609116639166400

Fix the 6N-6C tests, so all performance tests can be moved to 6N and 6C

- [x] Create bucket similar to AWS S3 `services-regression-jrs-files` as GCP can't authenticate S3 while running regression

- [x] Give access to create folders and files while running on GCP, by adding `sudo` to StartBrowser command

**Comment by Neeharika-Sompalli** [comment]
All 6N 6C tests fail with 0 TPS because they receive `INVALID_SIGNATURE` while downloading fees.
```
2020-12-28 19:06:44.598 WARN   204  HapiApiSpec - 'CreatePayerAccountForEachClient' failed to initialize, being skipped!
java.lang.IllegalStateException: Could not download '0.0.112' final status INVALID_SIGNATURE
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadWith(FeesAndRatesProvider.java:185) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.downloadRateSet(FeesAndRatesProvider.java:130) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.fees.FeesAndRatesProvider.init(FeesAndRatesProvider.java:88) ~[SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.init(HapiApiSpec.java:201) [SuiteRunner.jar:?]
	at com.hedera.services.bdd.spec.HapiApiSpec.run(HapiApiSpec.java:182) [SuiteRunner.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1799) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

**Comment by Neeharika-Sompalli** [comment]
When running on GCP the saved state files are not downloaded to the nodes as the path it considers from `gs://` instead of `s3://`

```
14:29:05.701 pool-9-thread-3 Added Building synchronization state... to returnArray
14:29:05.701 pool-9-thread-3 Added Caught non-retryable exception while listing gs://services-regression-jrs-files/StartFromSavedState/11842097-v0.8.0-rc-1-With-Eng-TreasuryKey/11846140/: BucketNotFoundException: 404 gs://services-regression-jrs-files bucket does not exist. to returnArray
14:29:05.701 pool-9-thread-3 Added CommandException: Caught non-retryable exception - aborting rsync to returnArray
14:29:05.701 pool-9-thread-3 Added /snap/google-cloud-sdk/162/lib/third_party/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown. to returnArray
14:29:05.701 pool-9-thread-3 Added   warnings.warn(warning, RequestsDependencyWarning) to returnArray
14:29:05.701 pool-9-thread-3 'Copy 'gs://services-regression-jrs-files/StartFromSavedState/11842097-v0.8.0-rc-1-With-Eng-TreasuryKey/11846140/' from GCP_GS to '34.73.52.249:remoteExperiment/data/saved/com.hedera.services.ServicesMain/2/123/11846140/'' FAILED with error code '{%d}. Output: 1
14:29:05.723 pool-9-thread-4 'list files in 35.231.141.55: remoteExperiment/data/saved/com.hedera.services.ServicesMain/3/123/11846140/' command:
```

**Comment by Neeharika-Sompalli** [comment]
Passed Crypto Restart test : https://hedera-hashgraph.slack.com/archives/C018CBQBTGB/p1609255034339100
