### ISSUE TITLE
StreamDetailValidator exception in `FCMFCQ-RestartEventStream-1k-10m`

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#9163]
### Description

This issue is transferred from regression repo

https://github.com/swirlds/swirlds-platform-regression/issues/3776

The following exception was reported:

```---- StreamDetailValidator failed with an exception:
java.lang.ExceptionInInitializerError
	at com.swirlds.config.api.ConfigurationBuilder.create(ConfigurationBuilder.java:139)
	at com.swirlds.common.config.singleton.ConfigurationHolder.reset(ConfigurationHolder.java:56)
	at com.swirlds.common.config.singleton.ConfigurationHolder.<init>(ConfigurationHolder.java:51)
	at com.swirlds.common.config.singleton.ConfigurationHolder.<clinit>(ConfigurationHolder.java:46)
	at com.swirlds.common.system.events.BaseEventHashedData.deserialize(BaseEventHashedData.java:216)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:108)
	at com.swirlds.common.system.events.DetailedConsensusEvent.deserialize(DetailedConsensusEvent.java:106)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:167)
	at com.swirlds.common.io.streams.SerializableDataInputStream.readSerializable(SerializableDataInputStream.java:88)
	at com.swirlds.common.stream.internal.SingleStreamIterator.next(SingleStreamIterator.java:122)
	at com.swirlds.common.stream.internal.SingleStreamIterator.next(SingleStreamIterator.java:38)
	at com.swirlds.common.stream.internal.StreamFilesIterator.fetchNextInCurrentFileIterator(StreamFilesIterator.java:138)
	at com.swirlds.common.stream.internal.StreamFilesIterator.fetchNext(StreamFilesIterator.java:122)
	at com.swirlds.common.stream.internal.StreamFilesIterator.next(StreamFilesIterator.java:109)
	at com.swirlds.common.stream.internal.StreamFilesIterator.next(StreamFilesIterator.java:42)
	at com.swirlds.common.stream.internal.LinkedObjectStreamValidateUtils.validateIterator(LinkedObjectStreamValidateUtils.java:190)
	at com.swirlds.common.stream.internal.LinkedObjectStreamValidateUtils.validateFileList(LinkedObjectStreamValidateUtils.java:169)
	at com.swirlds.fsts.validator.StreamDetailValidator.validate(StreamDetailValidator.java:220)
	at com.swirlds.fsts.workflow.Test.validate(Test.java:367)
	at com.swirlds.fsts.workflow.Test.validate(Test.java:277)
	at com.swirlds.fsts.workflow.TestFlow.validation(TestFlow.java:509)
	at com.swirlds.fsts.workflow.TestFlow.dispatch(TestFlow.java:193)
	at com.swirlds.fsts.workflow.Regression.testExecution(Regression.java:420)
	at com.swirlds.fsts.workflow.Regression.execute(Regression.java:314)
	at com.swirlds.fsts.cli.MainCommand.executeRegressionFlow(MainCommand.java:297)
	at com.swirlds.fsts.cli.MainCommand.call(MainCommand.java:285)
	at com.swirlds.fsts.cli.MainCommand.call(MainCommand.java:60)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.swirlds.fsts.Main.main(Main.java:31)
Caused by: java.lang.IllegalStateException: No ConfigurationBuilderFactory implementation found!
	at com.swirlds.config.api.intern.ConfigurationProvider.loadImplementation(ConfigurationProvider.java:47)
	at com.swirlds.config.api.intern.ConfigurationProvider.<init>(ConfigurationProvider.java:36)
	at com.swirlds.config.api.intern.ConfigurationProvider.<clinit>(ConfigurationProvider.java:31)
	... 37 more
```

This exception occurred after updating the swirlds version in https://github.com/swirlds/swirlds-platform-regression/pull/3774

Data directory: http://35.247.76.217:8095/swirlds-automation/develop/4N/Restart/20230921-060319-GCP-Daily-Restart-4N/FCMFCQ-RestartEventStream-1k-10m/

### Steps to reproduce

Nightly regression panel `GCP-Daily-Restart-4N`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Test passed after reverted back `0.42.0-adhoc.x16db4279`
https://swirldslabs.slack.com/archives/C05CH6A8AMV/p1695412026308769

so some changes from `0.42.0-adhoc.x16db4279` to `0.42.0-develop.xf3d6e96` broke the test

Platform team need to find out what changes caused the exception.

**Comment by cody-littley** [comment]
We do not plan on fixing this.
