### ISSUE TITLE
Fix Repeated Account Amount Approvals

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#9321]

**Comment by mhess-swl** [comment]
When running `CryptoTransferSuite.allowanceTransfersWorkAsExpected()`, we get the following error:

```
2023-10-17 10:04:21.410 INFO  301  HapiTxnOp - 'AllowanceTransfersWorkAsExpected' -  HapiCryptoTransfer{sigs=1, payer=spender, node=0.0.3, transfers=[0.0.1002 -> -500000000, 0.0.1004 <- +100000000, 0.0.1004 <- +500000000, 0.0.1003 -> -100000000], tokenTransfers=} Wrong actual status ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS, expected SUCCESS
2023-10-17 10:04:21.410 WARN  262  HapiSpecOperation - 'AllowanceTransfersWorkAsExpected' - HapiCryptoTransfer{sigs=1, payer=spender, node=0.0.3, transfers=[0.0.1002 -> -500000000, 0.0.1004 <- +100000000, 0.0.1004 <- +500000000, 0.0.1003 -> -100000000], tokenTransfers=} failed - Wrong status! Expected SUCCESS, was ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS!
```

The error happens close to [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java#L969) (approximately line 969):
```java
cryptoTransfer(
            allowanceTinyBarsFromTo(OWNER, RECEIVER, 5 * ONE_HBAR),
            tinyBarsFromTo(SPENDER, RECEIVER, ONE_HBAR))
    .payingWith(SPENDER)
    .signedBy(SPENDER),
```

Instead of a successful transfer, the modularized code claims there are repeated account amounts. The [modularized code checks](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoTransferValidator.java#L69) for repeated account amounts in `CryptoTransferValidator.pureChecks(...)`, which has the following:
```java
        final var acctAmounts = op.transfersOrElse(TransferList.DEFAULT).accountAmountsOrElse(emptyList());
        final var uniqueAcctIds = new HashSet<AccountID>();
        long netBalance = 0;
        for (final AccountAmount acctAmount : acctAmounts) {
            validateTruePreCheck(acctAmount.hasAccountID(), INVALID_ACCOUNT_ID);
            final var acctId = validateAccountID(acctAmount.accountIDOrThrow());
            uniqueAcctIds.add(acctId);
            netBalance += acctAmount.amount();
        }
        validateTruePreCheck(netBalance == 0, INVALID_ACCOUNT_AMOUNTS);
        validateFalsePreCheck(uniqueAcctIds.size() < acctAmounts.size(), ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS);		// <-- The test fails here
```
The code iterates through the given account amounts, adds each account ID to a set, and then checks that there are no difference in the set size and the original account amounts list size. However, there's no special handling for an account _approval_. If an approval is encountered in the `for` loop, its account ID is added to `uniqueAcctIds` as usual. However, if `acctAmounts` contains a transfer for account X _and_ an approval for account X, it is treated as two separate `AccountAmount` objects. **Therefore, `uniqueAcctIds.add(acctId)` will add account X, but because it is a set, will inherently discard the duplicate account ID if that account ID has already been added prior.** 

We can see this problem in action. Placing a debug statement before this code block and running the test, we get the following output:

```
uniqueAcctIds: [
	AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1002]], 
	AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1003]], 
	AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1004]]		// <-- only one instance of account ID 1004, which is correct behavior for a Set implementation
]
acctAmounts: [
	AccountAmount[accountID=AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1002]], amount=-500000000, isApproval=true], 
	AccountAmount[accountID=AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1003]], amount=-100000000, isApproval=false],
	AccountAmount[accountID=AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1004]], amount=100000000, isApproval=false],        // <-- account ID 1004, isApproval=false
	AccountAmount[accountID=AccountID[shardNum=0, realmNum=0, account=OneOf[kind=ACCOUNT_NUM, value=1004]], amount=500000000, isApproval=true]		// <-- account ID 1004, isApproval=true
]
```
The `acctAmounts` list has two entries for account 1004, one an approval and the other not. The `uniqueAcctIds` set, however, has one less entry, and fails the `validateFalsePreCheck` condition, resulting in the error message above. 

Now, we could tweak this logic – if we filter out all approvals from `acctAmounts` before iterating, and then compare the sizes of the set and the filtered list, the crypto transfer passes. E.g.:
```java
        final var acctAmounts = op.transfersOrElse(TransferList.DEFAULT).accountAmountsOrElse(emptyList())
        	.stream().filter(aa -> !aa.isAllowance()).toList();		// <-- here we filter out all approvals
        final var uniqueAcctIds = new HashSet<AccountID>();
        long netBalance = 0;
        for (final AccountAmount acctAmount : acctAmounts) {
            validateTruePreCheck(acctAmount.hasAccountID(), INVALID_ACCOUNT_ID);
            final var acctId = validateAccountID(acctAmount.accountIDOrThrow());
            uniqueAcctIds.add(acctId);
            netBalance += acctAmount.amount();
        }
        validateTruePreCheck(netBalance == 0, INVALID_ACCOUNT_AMOUNTS);
        validateFalsePreCheck(uniqueAcctIds.size() < acctAmounts.size(), ACCOUNT_REPEATED_IN_ACCOUNT_AMOUNTS);		// <-- Because approvals are ignored, this check no longer fails
```

Problem solved, right? But wait, there's more: filtering out approvals makes `CryptoTransferSuite.allowanceTransfersWorkAsExpected()` happy, but running `CryptoTransferHandlerParityTest` results in a single error for `cryptoTransferAllowanceSpenderScenario()` (code [here](https://github.com/hashgraph/hedera-services/blob/develop/hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java#L406)), suggesting that this tweak diverges from the mono service behavior:

```
PreCheckException{responseCode=INVALID_ACCOUNT_AMOUNTS}
	at com.hedera.node.app.spi.workflows.PreCheckException.validateTruePreCheck(PreCheckException.java:89)
	at com.hedera.node.app.service.token.impl.validators.CryptoTransferValidator.pureChecks(CryptoTransferValidator.java:79)
	at com.hedera.node.app.service.token.impl.handlers.CryptoTransferHandler.pureChecks(CryptoTransferHandler.java:120)
	at com.hedera.node.app.service.token.impl.handlers.CryptoTransferHandler.preHandle(CryptoTransferHandler.java:99)
	at com.hedera.node.app.service.token.impl.test.handlers.CryptoTransferHandlerParityTest.cryptoTransferAllowanceSpenderScenario(CryptoTransferHandlerParityTest.java:409)
	... 
```

How do we appropriately fix this issue?
