### ISSUE TITLE
Fix PrecompileMintThrottlingCheck

### ISSUE THREAD

**Issue by netopyr** [hashgraph/hedera-services#9506]
Ignore this test. Not needed anymore

**Comment by netopyr** [comment]
Currently fails with
```
Caused by: java.lang.IllegalArgumentException: argument "src" is null
	at com.fasterxml.jackson.databind.ObjectMapper._assertNotNull(ObjectMapper.java:4829)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3665)
	at com.hedera.node.app.hapi.utils.sysfiles.serdes.ThrottlesJsonToProtoSerde.loadPojoDefs(ThrottlesJsonToProtoSerde.java:36)
	at com.hedera.node.app.hapi.utils.sysfiles.serdes.ThrottlesJsonToProtoSerde.loadProtoDefs(ThrottlesJsonToProtoSerde.java:30)
	at com.hedera.services.bdd.suites.utils.sysfiles.serdes.ThrottleDefsLoader.protoDefsFromResource(ThrottleDefsLoader.java:28)
	at com.hedera.services.bdd.suites.regression.PrecompileMintThrottlingCheck.precompileNftMintsAreLimitedByConsThrottle(PrecompileMintThrottlingCheck.java:82)
	... 68 more
```
