### ISSUE TITLE
Reconnect test failed due to IndexOutOfBoundsException from fileStoreHashStoreDisk

### ISSUE THREAD

**Issue by JeffreyDallas** [hashgraph/hedera-services#9512]
### Description

https://swirldslabs.slack.com/archives/C03E8SA5UF9/p1698304243316709

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20231026-063724-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-NI-3NReconnect-2k-30m/

```
2023-10-26 07:01:26.880 2341     INFO  RECONNECT        <<reconnect: reconnect-controller>> LearningSynchronizer: receiving tree rooted at com.swirlds.virtualmap.internal.merkle.VirtualRootNode with route [0 -> 3 -> 1]
2023-10-26 07:01:27.793 2393     ERROR EXCEPTION        <<merkledb: Compacting #0>> CompactionTask: [fileStoreHashStoreDisk] Compaction failed
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.swirlds.merkledb.MerkleDbStatistics.setHashesStoreCompactionTimeMs(MerkleDbStatistics.java:447) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbStatisticsUpdater.setHashesStoreCompactionTimeMs(MerkleDbStatisticsUpdater.java:225) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCompactor.compact(DataFileCompactor.java:431) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:257) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:250) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Steps to reproduce

Nightly regression panel `GCP-Daily-Comp-3NReconnect-15N-4C`

### Hedera network

other

### Version

latest

### Operating system

None

**Comment by JeffreyDallas** [comment]
Other incidents of the same error

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20231026-063724-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/


http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/Global3NReconnect/20231026-080914-GCP-Daily-Global-Reconnect-15N-4C/MixedOps-Global-NI-3NReconnect-6k-35m/

http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/Global3NReconnect/20231026-080914-GCP-Daily-Global-Reconnect-15N-4C/MixedOps-Global-ND-3NReconnect-6k-35m/

http://35.247.76.217:8095/swirlds-automation/develop/6N_1C/Reconnect/20231026-063930-GCP-Daily-Comp-Reconnect-6N-1C/MixedOps-NDReconnect-500-25m/

http://35.247.76.217:8095/swirlds-automation/develop/6N_1C/Reconnect/20231026-063930-GCP-Daily-Comp-Reconnect-6N-1C/SmartContractOps-NIReconnect-14-21m/

http://35.247.76.217:8095/swirlds-automation/develop/6N_4C/Reconnect/20231026-084153-GCP-Daily-Reconnect-6K-6N-4C/MixedOps-NIReconnect-2k-28m/

http://35.247.76.217:8095/swirlds-automation/develop/6N_4C/Reconnect/20231026-084153-GCP-Daily-Reconnect-6K-6N-4C/MixedOps-NI-MultiReconnect-2k-32m/
