### ISSUE TITLE
Test in `MerkleDbCompactionCoordinatorTest` may fail non-deterministically 

### ISSUE THREAD

**Issue by imalygin** [hashgraph/hedera-services#9559]
### Description

In some cases tests from `MerkleDbCompactionCoordinatorTest` are failing non-deterministically .

### Steps to reproduce

1. Run any test that calls `MerkleDbCompactionCoordinatorTest#assertCompactable`
2. Observe a failure like the following:
```
org.opentest4j.AssertionFailedError: Unexpected mock state
	at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:42)
	at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:147)
	at app//com.swirlds.common.test.fixtures.AssertionUtils.assertEventuallyTrue(AssertionUtils.java:90)
	at app//com.swirlds.common.test.fixtures.AssertionUtils.assertEventuallyDoesNotThrow(AssertionUtils.java:208)
	at app//com.swirlds.merkledb.MerkleDbCompactionCoordinatorTest.assertCompactable(MerkleDbCompactionCoordinatorTest.java:319)
	at app//com.swirlds.merkledb.MerkleDbCompactionCoordinatorTest.testCompaction(MerkleDbCompactionCoordinatorTest.java:273)
    ...
Caused by: Wanted but not invoked:
hashStoreDisk.compact();
-> at com.swirlds.merkledb.files.DataFileCompactor.compact(DataFileCompactor.java:403)
Actually, there were zero interactions with this mock.

	at app//com.swirlds.merkledb.files.DataFileCompactor.compact(DataFileCompactor.java:403)
	at app//com.swirlds.merkledb.MerkleDbCompactionCoordinatorTest.lambda$assertCompactable$7(MerkleDbCompactionCoordinatorTest.java:323)
	at app//com.swirlds.common.test.fixtures.AssertionUtils.lambda$assertEventuallyDoesNotThrow$3(AssertionUtils.java:211)
	at app//com.swirlds.common.test.fixtures.AssertionUtils.assertEventuallyTrue(AssertionUtils.java:86)
	... 140 more
```

Most likely, it fails due to insufficient timeout (100 ms). Should be increased to 1 second. 

### Hedera network

previewnet

### Version

v0.44

### Operating system

None

**Comment by imalygin** [comment]
PR https://github.com/hashgraph/hedera-services/pull/9560
