### ISSUE TITLE
GCP-Daily-Comp-3NReconnect-15N-4C Compaction failed

### ISSUE THREAD

**Issue by edward-swirldslabs** [hashgraph/hedera-services#9587]
http://35.247.76.217:8095/swirlds-automation/develop/15N_4C/3NReconnect/20231026-063724-GCP-Daily-Comp-3NReconnect-15N-4C/MixedOps-Interrupted-2NReconnect-1k-41m/
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.swirlds.merkledb.MerkleDbStatistics.setHashesStoreCompactionTimeMs(MerkleDbStatistics.java:447) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbStatisticsUpdater.setHashesStoreCompactionTimeMs(MerkleDbStatisticsUpdater.java:225) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.files.DataFileCompactor.compact(DataFileCompactor.java:431) ~[swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:257) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at com.swirlds.merkledb.MerkleDbCompactionCoordinator$CompactionTask.call(MerkleDbCompactionCoordinator.java:250) [swirlds-merkledb-0.44.0-SNAPSHOT.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by edward-swirldslabs** [comment]
Assumed to be fixed by https://github.com/hashgraph/hedera-services/issues/9512
