### ISSUE TITLE
Troubleshoot Hapi tests not running inside Intellij

### ISSUE THREAD

**Issue by mhess-swl** [hashgraph/hedera-services#9634]
Attempting to run any `@HapiTest` inside Intellij currently results in the following error:
```
java.lang.RuntimeException: node 0: Waited 300 seconds, but node did not become active!
	at com.hedera.services.bdd.junit.SubProcessHapiTestNode.waitForActive(SubProcessHapiTestNode.java:119)
	at com.hedera.services.bdd.junit.HapiTestEnv.start(HapiTestEnv.java:85)
	at com.hedera.services.bdd.junit.HapiTestEngine$HapiEngineDescriptor.before(HapiTestEngine.java:161)
	at com.hedera.services.bdd.junit.HapiTestEngine$HapiEngineDescriptor.before(HapiTestEngine.java:144)
``` 

~~We suspect it has something to do with the changes made in PR #9341.~~
EDIT: Reverting the changes from PR #9544 makes the tests run in Intellij

**Comment by mhess-swl** [comment]
@cody-littley fixed this via PR #9642
