### ISSUE TITLE
VirtualMerkleLeafValidator: State File Not Found

### ISSUE THREAD

**Issue by cody-littley** [hashgraph/hedera-services#9708]
```
---- VirtualMerkleLeafValidator FAILED validation ----
<<ERROR>>
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/Reconnect/20231106-053539-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0003/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/3/123/2628/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/Reconnect/20231106-053539-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0003/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/3/123/1701/vmapHashes.json
State file not found: /runner/_work/hedera-services/hedera-services/platform-sdk/regression/assets/results/4N/Reconnect/20231106-053539-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/node0003/data/saved/com.swirlds.demo.platform.PlatformTestingToolMain/3/123/2940/vmapHashes.json
```

This failure occured twice: last night's run and the night before that. Previously this test has been reliably passing.

Last night's run: http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20231106-053539-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/
The night before last night's run: http://35.247.76.217:8095/swirlds-automation/develop/4N/Reconnect/20231105-053524-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by edward-swirldslabs** [comment]
@imalygin Additional Failure: http://35.247.76.217:8095/swirlds-automation/release/0.44/4N/Reconnect/20231108-094320-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by JeffreyDallas** [comment]
There was exception thrown from `VirtualMerkleLeafHasher`

http://35.247.76.217:8095/swirlds-automation/release/0.44/4N/Reconnect/20231108-094320-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/regression-debug.log

```
2023-11-08 11:23:01.322 4002     INFO  POST_PROCESSING  <main> TestFlow: Exception in thread "main" java.lang.IllegalArgumentException: path (3361399) is not valid; must be in range (11272218,22544436)
	at com.swirlds.merkledb.MerkleDbDataSource.loadLeafRecord(MerkleDbDataSource.java:638)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getLeafNode(VirtualInternalNode.java:207)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:154)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getLeft(VirtualInternalNode.java:138)
	at com.swirlds.virtualmap.internal.merkle.VirtualInternalNode.getChild(VirtualInternalNode.java:88)
	at com.swirlds.common.merkle.iterators.MerkleIterator.pushNode(MerkleIterator.java:244)
	at com.swirlds.common.merkle.iterators.internal.BreadthFirstAlgorithm.pushChildren(BreadthFirstAlgorithm.java:77)
	at com.swirlds.common.merkle.iterators.MerkleIterator.findNext(MerkleIterator.java:312)
	at com.swirlds.common.merkle.iterators.MerkleIterator.hasNext(MerkleIterator.java:326)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.validate(VirtualMerkleLeafHasher.java:82)
	at com.swirlds.demo.virtualmerkle.VirtualMerkleLeafHasher.main(VirtualMerkleLeafHasher.java:188)
```

**Comment by alittley** [comment]
Additional failure: http://35.247.76.217:8095/swirlds-automation/release/0.44/4N/Reconnect/20231109-094323-GCP-Daily-Reconnect-4N/VMerkleDual-NDReconnect-500-60m/

**Comment by alittley** [comment]
Not reproducible in `develop`. Precise root cause evades detection, but this appears to just be an infrastructure issue. Will not fix for release 44.
