### ISSUE TITLE
ReconnectNodeRemover.getRecordsToDelete() loops forever

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#9764]
### Description

Reconnect fails as described in #9725. The `vm-node-remover` thread happens to be in `ReconnectNodeRemover.getRecordsToDelete()` and loops forever in
```
        while (handledPath.get() < requiredPath && !exceptionEncountered.get()) {
            tryToSleep(Duration.ofMillis(1));
        }
```
As the thread never exits the reconnect protocol is stuck on the `SyncProtocolWith5 6 to 5` thread. The other node (5) tries to reestablish connection without success filling `swirlds.log` with messages:
```
2023-11-07 10:43:37.639 51889    WARN  SOCKET_EXCEPTIONS <<platform-core: SyncProtocolWith6 5 to 6>> NetworkUtils: Connection broken: 5 -> 6 Caused By: {Exception: SocketTimeoutException Message: Read timed out }
```
The stuck node (6), in turn, logs endless
```
2023-11-07 10:43:42.762 1403     WARN  SOCKET_EXCEPTIONS <<sync_server #4>> InboundConnectionManager: 6 got new connection from 5, disconnecting old one
```
The ever-increasing `platform_conns` metric is a good indicator of the bug.

### Steps to reproduce

The bug was observed in `perf5` performance network.

### Hedera network

other

### Version

v0.44.0-alpha.2

### Operating system

Linux

**Comment by artemananiev** [comment]
Here is a stack trace for a thread running the busy loop from bug description:

```
"<virtualmap: hasher>" #1230 daemon prio=5 os_prio=0 cpu=40552.14ms elapsed=933.08s tid=0x00007efd1b8000a0 nid=0x69d sleeping [0x00007f04004fb000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@17/Native Method)
        at java.lang.Thread.sleep(java.base@17/Thread.java:337)
        at java.util.concurrent.TimeUnit.sleep(java.base@17/TimeUnit.java:446)
        at com.swirlds.common.threading.interrupt.Uninterruptable.lambda$tryToSleep$1(Uninterruptable.java:242)
        at com.swirlds.common.threading.interrupt.Uninterruptable$$Lambda$2358/0x0000000801601b70.run(Unknown Source)
        at com.swirlds.common.threading.interrupt.Uninterruptable.abortIfInterrupted(Uninterruptable.java:115)
        at com.swirlds.common.threading.interrupt.Uninterruptable.tryToSleep(Uninterruptable.java:242)
        at com.swirlds.virtualmap.internal.reconnect.ReconnectNodeRemover.getRecordsToDelete(ReconnectNodeRemover.java:228)
        at com.swirlds.virtualmap.internal.reconnect.ReconnectHashListener.findLeavesToRemove(ReconnectHashListener.java:81)
        at com.swirlds.virtualmap.internal.merkle.AbstractHashListener.onBatchCompleted(AbstractHashListener.java:171)
        at com.swirlds.virtualmap.internal.hash.VirtualHasher.hash(VirtualHasher.java:446)
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.lambda$prepareReconnectHashing$4(VirtualRootNode.java:1460)
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode$$Lambda$2352/0x0000000801600000.run(Unknown Source)
        at java.lang.Thread.run(java.base@17/Thread.java:833)
```

This is not `vm-node-remover` thread, but a hasher thread. It looks like `vm-node-remover` thread has been interrupted successfully by calling `VirtualNodeRemover.close()`, but it didn't break that loop where the hasher is running.

**Comment by artemananiev** [comment]
Another issue is found while working on this ticket. In the main `LearnerThread.run()` loop, node remover is fed all deserialized nodes and then closed in the end, both if the loop is successful or not. Node remover code is asynchronous, it doesn't handle nodes in place, but puts them to a queue, where they are processed in a separate thread (see `VirtualNodeRemover.workQueue`). It means, by the time when `VirtualNodeRemover.stop()` is closed in the end of the learner thread loop, some elements may still be in the queue, and they may not be processed. It would result in a similar endless loop in `getRecordsToDelete()` as described in this ticket.
