### ISSUE TITLE
MerkleSynchronizationException: Timed out waiting to supply a new leaf to the hashing iterator buffer

### ISSUE THREAD

**Issue by OlegMazurov** [hashgraph/hedera-services#9872]
### Description

The following exception may abort reconnect on the learner side:
```
2023-10-29 16:08:26.998 19749    ERROR EXCEPTION        <<reconnect: reconnect-controller>> StandardWorkGroup: Work Group Exception [ groupName = learning-synchronizer ]
java.util.concurrent.ExecutionException: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Timed out waiting to supply a new leaf to the hashing iterator buffer
Caused by: com.swirlds.common.merkle.synchronization.utility.MerkleSynchronizationException: Timed out waiting to supply a new leaf to the hashing iterator buffer
        at com.swirlds.virtualmap.internal.merkle.VirtualRootNode.handleReconnectLeaf(VirtualRootNode.java:1432) ~[swirlds-virtualmap-0.43.1.jar:?]
        at com.swirlds.virtualmap.internal.reconnect.VirtualLearnerTreeView.deserializeLeaf(VirtualLearnerTreeView.java:226) ~[swirlds-virtualmap-0.43.1.jar:?]
        at com.swirlds.virtualmap.internal.reconnect.VirtualLearnerTreeView.deserializeLeaf(VirtualLearnerTreeView.java:54) ~[swirlds-virtualmap-0.43.1.jar:?]
        at com.swirlds.common.merkle.synchronization.internal.LeafDataLesson.deserialize(LeafDataLesson.java:100) ~[swirlds-common-0.43.1.jar:?]
        at com.swirlds.common.merkle.synchronization.internal.Lesson.deserialize(Lesson.java:110) ~[swirlds-common-0.43.1.jar:?]
        at com.swirlds.common.merkle.synchronization.streams.AsyncInputStream.run(AsyncInputStream.java:148) ~[swirlds-common-0.43.1.jar:?]
...
```

### Steps to reproduce

The issue is reproduced in during longevity testing with reconnects in performance networks.
 

### Hedera network

other

### Version

v0.43.1

### Operating system

Linux

**Comment by OlegMazurov** [comment]
During `VirtualMap` synchronization, `VirtualLeafRecords` are deserialized by `VirtualLearnerTreeView.deserializeLeaf()` and then are submitted to two consumers: `ReconnectNodeRemover.newLeafNode()` and `VirtualRootNode.handleReconnectLeaf()`. Both consumers may fall behind and get their input queues full and it's a `LinkedBlockingQueue`in both cases. However, when adding a new element to their queues, the former uses blocking `put()` and the latter uses `offer()` with a timeout. It's that timeout that may get expired.

If the `async-input-stream` gets blocked on any operation it stops reading from the socket and, when all intermediate buffers get full, the writer on the teacher side gets blocked, i.e. back-pressure is adequately propagated.
The second consumer, `VirtualRootNode.handleReconnectLeaf(), provides dirty leaf records to `VirtualRootNode.reconnectIterator` and then to `VirtualHasher.hash()`. When `VirtualHasher.hash()` calls `onBatchCompleted()` all collected data is flushed to the database. That may be a long operation during which `reconnectIterator` may get its queue full for long enough for the timeout to expire.

I don't see a justification for the use of `offer` with timeout by `ConcurrentBlockingIterator.supply()`. I we allow the `async-input-stream` to be blocked by one consumer, why should we abort if the second consumer gets behind.
It is certainly bad from a performance perspective, but that is an orthogonal issue which should be dealt with separately.

**Comment by OlegMazurov** [comment]
Long delays in `ReconnectNodeRemover` are caused by `handleLeaf()` -> `HalfDiskVirtualKeySet.add()` -> `flush()`.
Again, those are tolerated without timeouts and aborts.
